Azure/ResourceModules

- arm/Microsoft.ServiceBus/namespaces/.bicep/nested_rbac.bicep
- arm/Microsoft.ServiceBus/namespaces/.parameters/parameters.json
- arm/Microsoft.ServiceBus/namespacesResources/queues/.parameters/parameters.json
- Restored RBAC Module for Service Bus Namespace
- Changed the name of the test resource for both Service Bus Namespace and Queues.
[![ServiceBus: Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml/badge.svg?branch=quickFix-ServiceBus)](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml)
[![ServiceBus: Namespaces Queues](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.queues.yml/badge.svg?branch=quickFix-ServiceBus)](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.queues.yml)
> Restored Service Bus Namespace RBAC, Changed instance name for Namespace and Queues.

- arm/Microsoft.Network/expressRouteCircuits/deploy.bicep
- arm/Microsoft.Network/expressRouteCircuits/readme.md
Added Local to list of allowed tiers on expressRouteCircuits skuTier parameters. Could not choose Local when testing this module locally ( #357 ). This change adds the possibility for setting Local as a Sku Tier.
Also added some logic on the skuFamily property, because Local setting only allows Unlimited data.
> Updated expressRouteCircuits module with Local tier

- arm/Microsoft.ApiManagement/service/.bicep/nested_rbac.bicep
- arm/Microsoft.ApiManagement/service/deploy.bicep
- arm/Microsoft.ApiManagement/service/readme.md
[![ApiManagement: Service](https://github.com/Azure/ResourceModules/actions/workflows/ms.apimanagement.service.yml/badge.svg?branch=users%2Fmast%2FMS.ApiManagement_RBAC)](https://github.com/Azure/ResourceModules/actions/workflows/ms.apimanagement.service.yml)
> Align RBAC on Microsoft.ApiManagement

- arm/Microsoft.CognitiveServices/accounts/.bicep/nested_rbac.bicep
- arm/Microsoft.CognitiveServices/accounts/deploy.bicep
- arm/Microsoft.CognitiveServices/accounts/readme.md
[![CognitiveServices: Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml/badge.svg?branch=users%2Fmast%2FMS.CognitiveServices_RBAC)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml)
> Align RBAC on Microsoft.CognitiveServices

- arm/Microsoft.DocumentDB/databaseAccounts/.bicep/nested_rbac.bicep
- arm/Microsoft.DocumentDB/databaseAccounts/deploy.bicep
- arm/Microsoft.DocumentDB/databaseAccounts/readme.md
> Align RBAC on Microsoft.DocumentDB

- arm/Microsoft.OperationalInsights/workspaces/.bicep/nested_rbac.bicep
- arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/readme.md
[![OperationalInsights: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.operationalinsights.workspaces.yml/badge.svg?branch=users%2Fmast%2FMS.OperationalInsights_RBAC)](https://github.com/Azure/ResourceModules/actions/workflows/ms.operationalinsights.workspaces.yml)
> Align RBAC on Microsoft.OperationalInsights

- arm/Microsoft.NetApp/netAppAccounts/.bicep/nested_capacityPool.bicep
- arm/Microsoft.NetApp/netAppAccounts/.bicep/nested_capacityPool_rbac.bicep
- arm/Microsoft.NetApp/netAppAccounts/.bicep/nested_capacityPool_volume.bicep
- arm/Microsoft.NetApp/netAppAccounts/.bicep/nested_capacityPool_volume_rbac.bicep
- arm/Microsoft.NetApp/netAppAccounts/.bicep/nested_rbac.bicep
- arm/Microsoft.NetApp/netAppAccounts/deploy.bicep
- arm/Microsoft.NetApp/netAppAccounts/readme.md
> Align RBAC on Microsoft.NetApp

- arm/Microsoft.MachineLearningServices/workspaces/.bicep/nested_rbac.bicep
- arm/Microsoft.MachineLearningServices/workspaces/deploy.bicep
- arm/Microsoft.MachineLearningServices/workspaces/readme.md
> Align RBAC on Microsoft.MachineLearningServices

- arm/Microsoft.Insights/actionGroups/.bicep/nested_rbac.bicep
- arm/Microsoft.Insights/actionGroups/deploy.bicep
- arm/Microsoft.Insights/actionGroups/readme.md
- arm/Microsoft.Insights/activityLogAlerts/.bicep/nested_rbac.bicep
- arm/Microsoft.Insights/activityLogAlerts/deploy.bicep
- arm/Microsoft.Insights/activityLogAlerts/readme.md
- arm/Microsoft.Insights/components/.bicep/nested_rbac.bicep
- arm/Microsoft.Insights/components/deploy.bicep
- arm/Microsoft.Insights/components/readme.md
- arm/Microsoft.Insights/metricAlerts/.bicep/nested_rbac.bicep
- arm/Microsoft.Insights/metricAlerts/deploy.bicep
- arm/Microsoft.Insights/metricAlerts/readme.md
- arm/Microsoft.Insights/privateLinkScopes/.bicep/nested_rbac.bicep
- arm/Microsoft.Insights/privateLinkScopes/deploy.bicep
- arm/Microsoft.Insights/privateLinkScopes/readme.md
- arm/Microsoft.Insights/scheduledQueryRules/.bicep/nested_rbac.bicep
- arm/Microsoft.Insights/scheduledQueryRules/deploy.bicep
- arm/Microsoft.Insights/scheduledQueryRules/readme.md
> Align RBAC on Microsoft.Insights

- .github/workflows/platform.dependencies.yml
- arm/Microsoft.Compute/virtualMachines/.parameters/parameters.json
- arm/Microsoft.Network/applicationGateways/.parameters/parameters.json
Adding `applicationGatewaySslCertificate` certificate to KV dependencies
Updating reference to the newly created certificate in the application gateway module parameters
> Add keyvault certificate to fix app gateway run

- arm/Microsoft.Network/connections/deploy.bicep
- arm/Microsoft.Network/connections/readme.md
Changes the vpnSharedKey to a non-required parameter since its not needed with Express Route Connections
> Change vpnSharedKey param not Required Parameter

- .vscode/settings.json
Adding config in VScode to ignore bare URLs.
https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034---bare-url-used
> Disable MD034 Bare URLs rule + order settings

- arm/Microsoft.Compute/availabilitySets/deploy.bicep
- arm/Microsoft.Compute/availabilitySets/readme.md
- arm/Microsoft.Compute/diskEncryptionSets/deploy.bicep
- arm/Microsoft.Compute/diskEncryptionSets/readme.md
- arm/Microsoft.Compute/images/deploy.bicep
- arm/Microsoft.Compute/images/readme.md
- arm/Microsoft.Compute/proximityPlacementGroups/deploy.bicep
- arm/Microsoft.Compute/proximityPlacementGroups/readme.md
- arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
- arm/Microsoft.Compute/virtualMachineScaleSets/readme.md
- arm/Microsoft.Compute/virtualMachines/.bicep/nested_extension.bicep
- arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep
- arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface_publicIPAddress.bicep
- arm/Microsoft.Compute/virtualMachines/deploy.bicep
- Cleaned up compute modules
- Convert json(null) into null
- Removed excess brackets
- added output descriptions
> Cleaned up compute modules & added output descriptions

- .github/actions/templates/publishModule/action.yml
- .github/actions/templates/validateModuleApis/action.yml
- .github/actions/templates/validateModuleGeneral/action.yml
- .github/workflows/ms.analysisservices.servers.yml
- Removed unsupported default value {{ ... }} from inputs of global validate job
> Removed unsupported default value

- arm/Microsoft.Authorization/policyExemptions/.parameters/parameters.json
- Updated Policy Assignment ID. Previous ID was available on the IACS Sandbox. But now aligning to the ID that gets produced from the 'Policy Assignment' workflow.
- Extended Expiry Date
[![Authorization: policyExemptions](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyexemptions.yml/badge.svg?branch=hotfix%2Fusers%2Fahmad%2FpolicyExemptions)](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyexemptions.yml)
> Hotfix for Azure Policy Exemptions. Updated Policy Assignment ID and extended date

- arm/.global/global.module.tests.ps1
- Changed HTML conversion for a readMe test to the Markdown handling we use for all our ReadMe processing
[![Compute: Virtualmachinescalesets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachinescalesets.yml/badge.svg?branch=users%2Falsehr%2FpesterResilience&event=workflow_dispatch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachinescalesets.yml)
> Refactored pester tests to not fail due to HTML conversion issues

- arm/Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies/deploy.bicep
- Fixed a missing child-structure-update for storage
[![Storage: Storage Account](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Falsehr%2FstorageFollowUp&event=workflow_dispatch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml)
> Fixed a missing child-structure-update for storage

- arm/Microsoft.Insights/scheduledQueryRules/.parameters/parameters.json
- arm/Microsoft.Insights/scheduledQueryRules/deploy.bicep
- arm/Microsoft.Insights/scheduledQueryRules/readme.md
Primary goal was to update the api-version from 2018-04-16 to a newer one.
But since the newer api-versions change the complete structure of the resource, a rewrite was necessary.
Successful sample deployment: https://github.com/Azure/ResourceModules/actions/runs/1482016915
For comparison, the old api documentation...
https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2018-04-16/scheduledqueryrules?tabs=bicep
... and the new one:
https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2021-02-01-preview/scheduledqueryrules?tabs=bicep
FYI: I have used api version 2021-02-01-preview and not 2021-08-01 as the latter one is not yet supported by the bicep linter in vscode.
> Re-write of Microsoft.Insights/schedulequeryrules

- arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
There is a single file that still uses the `<<namePrefix>>` token that we removed. Maybe it came in after the token rollout got merged, or maybe it got missed.
> Note if the pipeline is failing, that is due to the 'removeModule' step
[![Network: Privatednszones](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.privatednszones.yml/badge.svg?branch=users%2Fahmad%2FhotFixDnsZone)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.privatednszones.yml)
> Hotfix - Private DNS Zone Name was using Token

- arm/Microsoft.EventHub/namespaces/eventhubs/.bicep/nested_rbac.bicep
create unique GUID for RBAC for the event hub so it is not colliding with the event hub namespace RBAC
> Fix RBAC deployment for EventHubs

- arm/Microsoft.RecoveryServices/vaults/backupPolicies/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/backupPolicies/readme.md
- arm/Microsoft.RecoveryServices/vaults/backupStorageConfig/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/backupStorageConfig/readme.md
- arm/Microsoft.RecoveryServices/vaults/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/protectionContainers/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/protectionContainers/readme.md
- arm/Microsoft.RecoveryServices/vaults/readme.md
- Refactored RSV to use `existing`
- Minor structural changes
> Note: The nested backupFabric resource cannot exist on its own. Hence we cannot reference the parent
[![RecoveryServices: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml/badge.svg?branch=users%2Falsehr%2F574_rsv_child)](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml)
> Refactored RSV to use `existing`

- arm/Microsoft.KeyVault/vaults/deploy.bicep
- arm/Microsoft.KeyVault/vaults/keys/deploy.bicep
- arm/Microsoft.KeyVault/vaults/keys/readme.md
- arm/Microsoft.KeyVault/vaults/readme.md
- arm/Microsoft.KeyVault/vaults/secrets/deploy.bicep
- arm/Microsoft.KeyVault/vaults/secrets/readme.md
- Implemented `existing` for key vault children
Parameter reference
[![KeyVault: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=users%2Falsehr%2F565_kv_child)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml)
> Implemented `existing` for key vault children

- arm/Microsoft.VirtualMachineImages/imageTemplates/.parameters/parameters.json
- arm/Microsoft.VirtualMachineImages/imageTemplates/deploy.bicep
- arm/Microsoft.VirtualMachineImages/imageTemplates/readme.md
- Update ImageTemplate to use `name` input parameter
- Updated docs
- Updated parameters
[![VirtualMachineImages: Imagetemplates](https://github.com/Azure/ResourceModules/actions/workflows/ms.virtualmachineimages.imagetemplates.yml/badge.svg?branch=users%2Falsehr%2F580_image_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.virtualmachineimages.imagetemplates.yml)
> Update ImageTemplate to use `name` input parameter

- arm/Microsoft.CognitiveServices/accounts/.parameters/parameters.json
- arm/Microsoft.CognitiveServices/accounts/deploy.bicep
- arm/Microsoft.CognitiveServices/accounts/readme.md
- Updated cognitive services to use `name` input parameter
- Updated parameter file
- Updated readme
[![CognitiveServices: Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml/badge.svg?branch=users%2Falsehr%2F551_cog_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml)
> Updated cognitive services to use `name` input parameter

- arm/Microsoft.ContainerInstance/containerGroups/.parameters/parameters.json
- arm/Microsoft.ContainerInstance/containerGroups/deploy.bicep
- arm/Microsoft.ContainerInstance/containerGroups/readme.md
- Update ContainerInstance to use `name` input parameter
- Updated parameter file
- Updated docs
[![ContainerInstance: Containergroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerinstance.containergroups.yml/badge.svg?branch=users%2Falsehr%2F554_container_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerinstance.containergroups.yml)
> Update ContainerInstance to use `name` input parameter

- arm/Microsoft.Databricks/workspaces/.parameters/parameters.json
- arm/Microsoft.Databricks/workspaces/deploy.bicep
- arm/Microsoft.Databricks/workspaces/readme.md
- Updata Databricks to use `name` input param
- Updated parameter file
- Updated docs
[![Databricks: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.databricks.workspaces.yml/badge.svg?branch=users%2Falsehr%2F557_dbricks_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.databricks.workspaces.yml)
> Updata Databricks to use `name` input param

- arm/Microsoft.ContainerService/managedClusters/.parameters/azure.parameters.json
- arm/Microsoft.ContainerService/managedClusters/.parameters/kubenet.parameters.json
- arm/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
- arm/Microsoft.ContainerService/managedClusters/agentPools/readme.md
- arm/Microsoft.ContainerService/managedClusters/deploy.bicep
- arm/Microsoft.ContainerService/managedClusters/readme.md
- Updated child to use `existing`
[![ContainerService: Managedclusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Falsehr%2F556_cs_existing)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml)
> Updated ManagedClusters to use `existing`

- arm/Microsoft.DocumentDB/databaseAccounts/deploy.bicep
- arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections/deploy.bicep
- arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections/readme.md
- arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/deploy.bicep
- arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/readme.md
- arm/Microsoft.DocumentDB/databaseAccounts/readme.md
- arm/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/deploy.bicep
- arm/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/readme.md
- arm/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/deploy.bicep
- arm/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/readme.md
- Updated DocumentDB to use `existing`
- Updated outputs
[![DocumentDB: Database Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml/badge.svg?branch=users%2Falsehr%2F560_cdb_existing)](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml)
> Updated DocumentDB to use `existing`

- arm/Microsoft.DesktopVirtualization/applicationgroups/applications/deploy.bicep
- arm/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
- arm/Microsoft.DesktopVirtualization/applicationgroups/readme.md
- arm/Microsoft.DesktopVirtualization/hostpools/deploy.bicep
- arm/Microsoft.DesktopVirtualization/hostpools/readme.md
- arm/Microsoft.DesktopVirtualization/workspaces/deploy.bicep
- arm/Microsoft.DesktopVirtualization/workspaces/readme.md
- Updated AVD namespace to use `existing`
- Added output descriptions
- Removed Host Pool Key output
Pipeline references
[![DesktopVirtualization: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.desktopvirtualization.applicationgroups.yml/badge.svg?branch=users%2Falsehr%2F559_avd_input)](https://github.com/Azure/ResourceModules/actions/workflows/ms.desktopvirtualization.applicationgroups.yml)
[![DesktopVirtualization: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.desktopvirtualization.hostpools.yml/badge.svg?branch=users%2Falsehr%2F559_avd_input)](https://github.com/Azure/ResourceModules/actions/workflows/ms.desktopvirtualization.hostpools.yml)
[![DesktopVirtualization: …
> Updated AVD namespace to use `existing`

- arm/Microsoft.OperationalInsights/workspaces/.parameters/min.parameters.json
- arm/Microsoft.OperationalInsights/workspaces/.parameters/parameters.json
- arm/Microsoft.OperationalInsights/workspaces/dataSources/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/dataSources/readme.md
- arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/linkedServices/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/linkedServices/readme.md
- arm/Microsoft.OperationalInsights/workspaces/readme.md
- arm/Microsoft.OperationalInsights/workspaces/savedSearches/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/savedSearches/readme.md
- arm/Microsoft.OperationalInsights/workspaces/storageInsightConfigs/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/storageInsightConfigs/readme.md
- utilities/pipelines/dependencies/Microsoft.OperationalInsights/workspaces/parameters/parameters.json
- Updated OMS to use `existing`
- Updated output
[![OperationalInsights: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.operationalinsights.workspaces.yml/badge.svg?branch=users%2Falsehr%2F573_oms__child)](https://github.com/Azure/ResourceModules/actions/workflows/ms.operationalinsights.workspaces.yml)
> Updated OMS to use `existing`

- arm/Microsoft.Authorization/roleDefinitions/.parameters/parameters.json
- utilities/pipelines/resourceRemoval/helper/Remove-Resource.ps1
- Fixed incorrect removal break condition
[![Compute: Availabilitysets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.availabilitysets.yml/badge.svg?branch=users%2Falsehr%2Fhotfix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.availabilitysets.yml)
> Small hotfix for incorrect removal loop

- arm/Microsoft.Automanage/accounts/.parameters/parameters.json
- arm/Microsoft.Automanage/accounts/deploy.bicep
- arm/Microsoft.Automanage/accounts/readme.md
- Update AutoManage to use `name` input parameter
- Updated paramter file
- Updated docs
[![Automanage: Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.automanage.accounts.yml/badge.svg?branch=users%2Falsehr%2F547_automanage_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.automanage.accounts.yml)
> Update AutoManage to use `name` input parameter

- arm/Microsoft.Automanage/accounts/deploy.bicep
- arm/Microsoft.Compute/availabilitySets/.parameters/parameters.json
- arm/Microsoft.Compute/availabilitySets/deploy.bicep
- arm/Microsoft.Compute/availabilitySets/readme.md
- arm/Microsoft.Compute/diskEncryptionSets/.parameters/parameters.json
- arm/Microsoft.Compute/diskEncryptionSets/deploy.bicep
- arm/Microsoft.Compute/diskEncryptionSets/readme.md
- arm/Microsoft.Compute/galleries/.parameters/images.parameters.json
- arm/Microsoft.Compute/galleries/.parameters/parameters.json
- arm/Microsoft.Compute/galleries/deploy.bicep
- arm/Microsoft.Compute/galleries/images/deploy.bicep
- arm/Microsoft.Compute/galleries/images/readme.md
- arm/Microsoft.Compute/galleries/readme.md
- arm/Microsoft.Compute/proximityPlacementGroups/.parameters/parameters.json
- arm/Microsoft.Compute/proximityPlacementGroups/deploy.bicep
- arm/Microsoft.Compute/proximityPlacementGroups/readme.md
- arm/Microsoft.Compute/virtualMachines/extensions/deploy.bicep
- arm/Microsoft.HealthBot/healthBots/.parameters/parameters.json
- arm/Microsoft.HealthBot/healthBots/deploy.bicep
- arm/Microsoft.HealthBot/healthBots/readme.md
- arm/Microsoft.Network/azureFirewalls/deploy.bicep
- arm/Microsoft.Network/bastionHosts/deploy.bicep
- arm/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/deploy.bicep
- arm/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/readme.md
- arm/Microsoft.Network/virtualWans/deploy.bicep
- arm/Microsoft.Network/virtualWans/readme.md
- arm/Microsoft.ServiceBus/namespaces/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/deploy.bicep
- Aligned serveral modules to use `name` parameter
- Smaller improvements/cleanup to additional modules
- Fixed a bug of namespace module parameter passthru
[![Automanage: Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.automanage.accounts.yml/badge.svg?branch=users%2Falsehr%2F330_input_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.automanage.accounts.yml)
[![Compute: Availabilitysets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.availabilitysets.yml/badge.svg?branch=users%2Falsehr%2F330_input_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.availabilitysets.yml)
[![Compute: Diskencryptionsets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.diskencry …
> Aligned serveral modules to use `name` parameter

- arm/Microsoft.Insights/privateLinkScopes/.bicep/nested_privateEndpoint.bicep
- arm/Microsoft.Insights/privateLinkScopes/.parameters/parameters.json
- arm/Microsoft.Insights/privateLinkScopes/deploy.bicep
- arm/Microsoft.Insights/privateLinkScopes/scopedResources/deploy.bicep
- arm/Microsoft.Insights/privateLinkScopes/scopedResources/readme.md
Updated Microsoft.Insights/privateLinkScopes.
scopedResources becomes a child module
[![Insights: Privatelinkscopes](https://github.com/Azure/ResourceModules/actions/workflows/ms.insights.privatelinkscopes.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.insights.privatelinkscopes.yml)
> #443 Update child resources for insights/privateLinkScopes

- arm/Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/blobServices/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/managementPolicies/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/queueServices/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/queueServices/queues/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/tableServices/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/tableServices/tables/deploy.bicep
- Update storage to use `existing` for parent resources
[![Storage: Storage Account](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Falsehr%2F579_storage_existing)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml)
> Update Storage to use `existing`

- utilities/pipelines/resourceRemoval/Remove-DeployedModule.ps1
- utilities/pipelines/resourceRemoval/helper/Get-DependencyResourceNames.ps1
- utilities/pipelines/resourceRemoval/helper/Remove-GeneralModule.ps1
- utilities/pipelines/resourceRemoval/helper/Remove-Resource.ps1
- utilities/pipelines/resourceRemoval/helper/Remove-VirtualMachine.ps1
- To avoid the accidental deletion of dependency resources I implemented an initial version to filter out the resource-group level resources
- It's not perfect as I'm looking for the 'name' parameter in the paramter files and should be improved in the future
- However it will help us for the moment
[![Compute: VirtualMachineScaleSets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachinescalesets.yml/badge.svg?branch=users%2Falsehr%2FremovalImprovment)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachinescalesets.yml)
> Added dependency consideration for removal

- .github/workflows/ms.resources.deploymentscripts.yml
- arm/Microsoft.Resources/deploymentScripts/.parameters/cli.parameters.json
- arm/Microsoft.Resources/deploymentScripts/.parameters/ps.parameters.json
- arm/Microsoft.Resources/deploymentScripts/deploy.bicep
- Updated kind param reference
- Added param file for CLI
[![Resources: DeploymentScripts](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.deploymentscripts.yml/badge.svg?branch=users%2Falsehr%2F184_deplScript_kind)](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.deploymentscripts.yml)
> Updated kind & added param file

- .github/workflows/platform.dependencies.yml
- arm/Microsoft.Authorization/policyAssignments/.parameters/min.parameters.json
- arm/Microsoft.Authorization/policyAssignments/.parameters/parameters.json
- arm/Microsoft.Authorization/policyExemptions/.parameters/min.parameters.json
- arm/Microsoft.Authorization/policyExemptions/.parameters/parameters.json
- docs/wiki/TestingDesign.md
- utilities/pipelines/dependencies/Microsoft.Authorization/policyAssignments/parameters/parameters.json
Closes #666 
- Adding policy assignment to dependency pipeline
- Updating policy assignment and exemptions parameters accordingly
- Updating wiki
> [666] Update dependency pipeline with policy assignment

- arm/Microsoft.Web/connections/deploy.bicep
- arm/Microsoft.Web/hostingEnvironments/deploy.bicep
- arm/Microsoft.Web/serverfarms/deploy.bicep
- arm/Microsoft.Web/sites/deploy.bicep
Aligning deployment names to naming convention for Ms.Web resource provider
> MS.Web deployment names

- arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
Aligning deployment names to naming convention for Microsoft.OperationalInsights resource provider
> Align Microsoft.OperationalInsights deployment names

- arm/Microsoft.Logic/workflows/deploy.bicep
Aligning deployment names to naming convention for Microsoft.Logic resource provider
> Align Microsoft.Logic deployment names

- arm/Microsoft.RecoveryServices/vaults/deploy.bicep
Aligning deployment names to naming convention for Microsoft.RecoveryServices resource provider
> Align Microsoft.RecoveryServices deployment names

- arm/Microsoft.Network/applicationGateways/deploy.bicep
- arm/Microsoft.Network/applicationSecurityGroups/deploy.bicep
- arm/Microsoft.Network/azureFirewalls/deploy.bicep
- arm/Microsoft.Network/bastionHosts/deploy.bicep
- arm/Microsoft.Network/ddosProtectionPlans/deploy.bicep
- arm/Microsoft.Network/expressRouteCircuits/deploy.bicep
- arm/Microsoft.Network/ipGroups/deploy.bicep
- arm/Microsoft.Network/loadBalancers/deploy.bicep
- arm/Microsoft.Network/localNetworkGateways/deploy.bicep
- arm/Microsoft.Network/natGateways/deploy.bicep
- arm/Microsoft.Network/networkSecurityGroups/deploy.bicep
- arm/Microsoft.Network/networkWatchers/deploy.bicep
- arm/Microsoft.Network/privateDnsZones/deploy.bicep
- arm/Microsoft.Network/privateEndpoints/deploy.bicep
- arm/Microsoft.Network/publicIPAddresses/deploy.bicep
- arm/Microsoft.Network/publicIPPrefixes/deploy.bicep
- arm/Microsoft.Network/routeTables/deploy.bicep
- arm/Microsoft.Network/trafficmanagerprofiles/deploy.bicep
- arm/Microsoft.Network/virtualNetworkGateways/deploy.bicep
- arm/Microsoft.Network/virtualNetworks/deploy.bicep
- arm/Microsoft.Network/virtualWans/deploy.bicep
Aligning deployment names to naming convention for Microsoft.Network resource provider
> Align Microsoft.Network deployment names

- arm/Microsoft.KeyVault/vaults/deploy.bicep
- arm/Microsoft.KeyVault/vaults/keys/deploy.bicep
- arm/Microsoft.KeyVault/vaults/readme.md
- arm/Microsoft.KeyVault/vaults/secrets/deploy.bicep
Aligning deployment names to naming convention for Microsoft.KeyVault resource provider
Fixed output to use dotted access instead of reference
> Align Microsoft.KeyVault deployment names

- arm/Microsoft.EventHub/namespaces/deploy.bicep
- arm/Microsoft.EventHub/namespaces/eventhubs/deploy.bicep
Aligning deployment names to naming convention for Microsoft.EventHub resource provider
> Align Microsoft.EventHub deployment names

- arm/Microsoft.DataFactory/factories/deploy.bicep
Aligning deployment names to naming convention for Microsoft.DataFactory resource provider
> Align Microsoft.DataFactory deployment names

- arm/Microsoft.Automanage/accounts/deploy.bicep
Aligning deployment names to naming convention for Microsoft.Automanage resource provider
> Align Microsoft.Automanage deployment names

- arm/Microsoft.Authorization/policyAssignments/deploy.bicep
- arm/Microsoft.Authorization/policyDefinitions/deploy.bicep
- arm/Microsoft.Authorization/policyExemptions/deploy.bicep
- arm/Microsoft.Authorization/policySetDefinitions/deploy.bicep
- arm/Microsoft.Authorization/roleAssignments/deploy.bicep
- arm/Microsoft.Authorization/roleDefinitions/deploy.bicep
Aligning deployment names to naming convention for Microsoft.Authorization resource provider
> Align Microsoft.Authorization deployment names

- arm/Microsoft.ApiManagement/service/.bicep/nested_authorizationServers.bicep
- arm/Microsoft.ApiManagement/service/apis/deploy.bicep
- arm/Microsoft.ApiManagement/service/deploy.bicep
- arm/Microsoft.ApiManagement/service/products/deploy.bicep
Aligning deployment names to naming convention for Microsoft.ApiManagement resource provider
> Align Microsoft.ApiManagement deployment names

- arm/Microsoft.Automation/automationAccounts/deploy.bicep
Aligning deployment names to naming convention for Microsoft.Automation resource provider
> Align Microsoft.Automation deployment names

- arm/Microsoft.Network/virtualNetworks/deploy.bicep
- arm/Microsoft.Network/virtualNetworks/readme.md
In some scenarios, net sec teams are separate from network operations teams.
> Target NSGs in seperate resource group

- docs/wiki/ModulesDesign.md
Adding bicep modules section and deployment names subsection
Minor adjustments
> Modules Design update

- .github/workflows/ms.network.firewallpolicies.yml
> Align fw policy workflow

- arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
- arm/Microsoft.Network/privateDnsZones/deploy.bicep
- arm/Microsoft.Network/privateDnsZones/readme.md
- arm/Microsoft.Network/privateDnsZones/virtualNetworkLinks/deploy.bicep
- arm/Microsoft.Network/privateDnsZones/virtualNetworkLinks/readme.md
- utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
- utilities/pipelines/resourceRemoval/helper/Get-ResourceIdsOfDeployment.ps1
- utilities/pipelines/resourceRemoval/helper/Remove-Deployment.ps1
Closes issue #823 
- Changing default vnetlink name from `<vnetname>` to `<vnetname>-vnetlink` otherwise filtered out from the removal job since having the same name of a dependecy resource
- Updating API to latest
- Improving removal scripts verbosity
> Fixing PrivateDnsZone removal

- docs/wiki/PipelinesDesign.md
- Added ADO artifacts reference to Wiki.
> Added missing ADO artifacts reference in wiki

- arm/Microsoft.Compute/virtualMachines/.parameters/linux.min.parameters.json
- arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
- arm/Microsoft.Compute/virtualMachines/.parameters/windows.min.parameters.json
- arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
- arm/Microsoft.Compute/virtualMachines/deploy.bicep
- arm/Microsoft.Compute/virtualMachines/readme.md
- docs/wiki/KnownIssues.md
- Added 'deleteOption' to virtual machine module's `dataDisk`, `osDisk` & `nicConfiguration`
- Successfully evaluated that e.g. the osDisk & NIC is removed
- Resolves our issue that osDisks are not properly removed
[![Compute: VirtualMachines](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml/badge.svg?branch=users%2Falsehr%2F830_vmDeleteOption)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml)
> Added deleteOption to VM

- .azuredevops/pipelineTemplates/module.jobs.deploy.yml
There was a condition for the ADO deployment pipeline template missing that essentially made it impossible to stop the removal step.
Tested both the cancellation as well as end2end execution in IaCS.
> Added missing removal condition to avoid uncancelable pipeline

- docs/wiki/Home.md
- docs/wiki/UtilitiesConvertToARMTemplate.md
- docs/wiki/UtilitiesGetFormattedRBACRoleList.md
- docs/wiki/UtilitiesRegisterAzureDevOpsPipeline.md
- docs/wiki/UtilitiesSetGitHubReadMeModuleTable.md
- docs/wiki/UtilitiesSetModuleReadMe.md
- docs/wiki/UtilitiesTestModuleLocally.md
- utilities/tools/Test-ModuleLocally.ps1
- Minor cleanup
- Added utilities wiki entry for
- `Set-GitHubReadMeModuleTable.ps1`
- `Test-ModuleLocally.ps1`
> Added utilities wiki entry

- .github/workflows/ms.storage.storageaccounts.yml
- arm/Microsoft.Storage/storageAccounts/deploy.bicep
[![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Fmast%2FMIFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) -> Though this could be lying! :D
Added extra condition on systemAssignedPrincipalId to check if there is principal ID in the identity property of the deployed resource. Currently it seems flaky from the API if this is returned or not. So seems like a backend issue.
> Fix Storage Account MI Issue

- arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
- arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
- docs/wiki/TestingDesign.md
- utilities/pipelines/dependencies/Microsoft.Authorization/roleAssignments/parameters/parameters.json
- utilities/pipelines/dependencies/Microsoft.RecoveryServices/vaults/parameters/parameters.json
- Added an additional note to the wiki to better explain the MSI role assignment which has a serious Chicken-Egg problem.
> Added an additional note to the wiki to better explain the MSI role assignment

- arm/Microsoft.Automation/automationAccounts/.parameters/parameters.json
Error message: The start time of the schedule must be at least 5 minutes after the time you create the schedule.
> Change startTime of "Linux_ZeroDay"

- arm/Microsoft.Storage/storageAccounts/deploy.bicep
- utilities/pipelines/resourceDeployment/New-ModuleDeployment.ps1
Added deployment error fetching based on deployment name if provisioning failed without an exception
Pipeline reference to show that it does not fail:
[![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Falsehr%2F857_provisioningState)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml)
> Added improved error fetching for failed deployments

- .azuredevops/pipelineTemplates/module.jobs.deploy.yml
- .azuredevops/pipelineTemplates/module.jobs.publish.yml
- .azuredevops/pipelineTemplates/module.jobs.validate.yml
- .github/actions/templates/publishModule/action.yml
- .github/actions/templates/validateModuleDeployment/action.yml
- .github/actions/templates/validateModulePester/action.yml
- utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
Closes #873 
GH runners take some time to set up due to an increasing list of PS modules to be installed. 
Most of the modules are required for the removal step. 
This change improves the environment agent setup time by specifying the required set of PS modules to install based on the job type
> e.g. PS modules like 'Az.CognitiveServices','Az.Compute','Az.KeyVault','Az.Monitor','Az.OperationalInsights','Az.RecoveryServices'  are not needed for Pester tests, thus are not installed on the runner executing them
[![CognitiveServices: Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml/badge.svg?branch=users%2Ferikag%2Frunner-module)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml)
[![Automation: …
> Specify set of PS modules for different actions

- arm/Microsoft.Storage/storageAccounts/.parameters/parameters.json
> Replace test storage name

- .azuredevops/modulePipelines/ms.consumption.budgets.yml
- .github/workflows/ms.consumption.budgets.yml
We now can test budgets end2end. Hence we can also enable its removal.
[![Consumption: Budgets](https://github.com/Azure/ResourceModules/actions/workflows/ms.consumption.budgets.yml/badge.svg?branch=users%2Falsehr%2FenableBudgetRemoval)](https://github.com/Azure/ResourceModules/actions/workflows/ms.consumption.budgets.yml)
> Enable budget removal

- .azuredevops/pipelineTemplates/module.jobs.deploy.yml
- .azuredevops/platformPipelines/platform.dependencies.yml
- .github/actions/templates/validateModuleDeployment/action.yml
- .github/workflows/platform.dependencies.yml
- docs/wiki/TestingDesign.md
- utilities/pipelines/dependencies/Microsoft.Authorization/roleAssignments/parameters/parameters.json
- utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/parameters.json
- utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/pe.parameters.json
- utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/sqlmi.parameters.json
- utilities/pipelines/dependencies/Microsoft.RecoveryServices/vaults/parameters/parameters.json
msi principal id is retrieved at runtime as an output of the user assigned identity module and used by the next modules deployed by the dependency pipeline. 
It is not needed to create an msi manually or to deploy the dependency pipeline twice anymore.
Updated validate deploy action and ADO template to accept an additional optional parameter in json format to allow additional custom tokens to be replaced by the token replacement step. That is needed by the dependency pipeline change and transparent for pipelines not needing it.
The change is valid for both GH and ADO
[![.Platform: Dependencies](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml/badge.svg?branch=users%2Ferikag%2Fdep-msi-id-token)](https://github.com/Azure/ResourceModules/actions/workflows/p …
> Dependency pipeline Replace msiPrincipalId at runtime

- arm/Microsoft.OperationalInsights/workspaces/.bicep/nested_solutions.bicep
- arm/Microsoft.OperationalInsights/workspaces/dataSources/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/dataSources/readme.md
- arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/linkedServices/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/linkedServices/readme.md
- arm/Microsoft.OperationalInsights/workspaces/readme.md
- arm/Microsoft.OperationalInsights/workspaces/savedSearches/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/savedSearches/readme.md
- arm/Microsoft.OperationalInsights/workspaces/storageInsightConfigs/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/storageInsightConfigs/readme.md
- arm/Microsoft.RecoveryServices/vaults/backupConfig/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/backupConfig/readme.md
- arm/Microsoft.RecoveryServices/vaults/backupPolicies/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/backupPolicies/readme.md
- arm/Microsoft.RecoveryServices/vaults/backupStorageConfig/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/backupStorageConfig/readme.md
- arm/Microsoft.RecoveryServices/vaults/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/protectionContainers/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/protectionContainers/readme.md
- arm/Microsoft.RecoveryServices/vaults/readme.md
- arm/Microsoft.Resources/deploymentScripts/deploy.bicep
- arm/Microsoft.Resources/deploymentScripts/readme.md
- arm/Microsoft.Resources/resourceGroups/.bicep/nested_lock.bicep
- arm/Microsoft.Resources/resourceGroups/deploy.bicep
- arm/Microsoft.Resources/resourceGroups/readme.md
Updated outputs of
All namespaces starting with [r]
All namespaces starting with [o]
> Updated outputs for namespaces starting with [r], [o]

- arm/Microsoft.Network/virtualNetworks/.parameters/min.parameters.json
- arm/Microsoft.Network/virtualNetworks/deploy.bicep
- arm/Microsoft.Network/virtualNetworks/readme.md
- It's actually not required to deploy a subnet in a VNET (and there are cases were we don't want to deploy one). Hence I removed the requirement 
[![Network: VirtualNetworks](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml/badge.svg?branch=users%2Falsehr%2FvnetDefaultSubnet)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml)
> VNET: Removed requirement for default subnet

- utilities/tools/ConvertTo-ARMTemplate.ps1
- Only clean up `deploy.json` when bicep exists before the conversion.
- Don't attempt to replace workflow or pipeline files if they do not exist. (i.e folders for ado or gh is removed)
> Bug fix for ConvertTo-ARMTemplate

- .azuredevops/modulePipelines/ms.servicefabric.clusters.yml
- .github/workflows/ms.servicefabric.clusters.yml
- Fix incorrect parameter file references in pipeline
[![Service Fabric: Clusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicefabric.clusters.yml/badge.svg?branch=users%2Falsehr%2FserviceFabricPipelineFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicefabric.clusters.yml)
> Service Fabric: Fix incorrect parameter file references in pipeline

- arm/Microsoft.Compute/availabilitySets/deploy.bicep
- arm/Microsoft.Compute/availabilitySets/readme.md
Bugfix availability set when providing the proximityPlacementGroup parameter
> Fix proximityPlacementGroup bug

- utilities/pipelines/resourceRemoval/helper/Get-DependencyResourceNameList.ps1
- Added token replacement to removal
[![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FdependenyToken)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml)
[![Compute: VirtualMachines](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml/badge.svg?branch=users%2Falsehr%2FdependenyToken)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml)
> Added token replacement to removal

- arm/Microsoft.Compute/availabilitySets/deploy.bicep
- arm/Microsoft.Compute/availabilitySets/readme.md
Resource Group name and Availability Set name where exchanged
The description of the Resource Group and Availability Set name outputs where switched.
> Switch description outputs

- .azuredevops/platformPipelines/platform.updateReadMe.yml
- .azuredevops/platformPipelines/platform.wiki-sync.yml
Remove unknown character from run names - this was causing an error when attempting to run the pipelines
> Remove unknown character from run names

- .azuredevops/pipelineTemplates/jobs.publishModule.yml
- .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
- .azuredevops/pipelineTemplates/jobs.validateModulePester.yml
- .github/actions/templates/getWorkflowInput/action.yml
- .github/actions/templates/publishModule/action.yml
- .github/actions/templates/validateModuleDeployment/action.yml
- .github/actions/templates/validateModulePester/action.yml
Use grouping of logs for [ADO](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#formatting-commands) and [GH](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-5)
[![Build Status](https://dev.azure.com/servicescode/infra-as-code-source/_apis/build/status/CARML-Modules/Compute%20-%20Galleries?branchName=users%2Fmast%2FLogGrouping)](https://dev.azure.com/servicescode/infra-as-code-source/_build/latest?definitionId=2170&branchName=users%2Fmast%2FLogGrouping)
[![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Fmast%2FLogGrouping)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analy …
> Introduce grouping of logs

- arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
- arm/Microsoft.Compute/virtualMachineScaleSets/readme.md
- arm/Microsoft.Compute/virtualMachines/deploy.bicep
- arm/Microsoft.Compute/virtualMachines/readme.md
- arm/Microsoft.Network/networkWatchers/.parameters/parameters.json
- utilities/pipelines/dependencies/Microsoft.Compute/virtualMachines/parameters/parameters.json
Adding name token to dependency vm
Fixing incorrect optional description for osType in vm and vmss modules
[![.Platform: Dependencies](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml/badge.svg?branch=users%2Ferikag%2Fvmdepname)](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml)
> vm adp token and description fix

- .azuredevops/platformPipelines/platform.dependencies.yml
- .github/workflows/platform.dependencies.yml
- arm/Microsoft.ContainerService/managedClusters/deploy.bicep
- arm/Microsoft.ContainerService/managedClusters/readme.md
- arm/Microsoft.Network/loadBalancers/.parameters/min.parameters.json
- utilities/pipelines/dependencies/Microsoft.Network/publicIPAddresses/parameters/lb.min.parameters.json
Fixed both Load Balancer & AKS
- Added missing IP to dependency pipeline
- Referenced set IP to not have both LB parameter files use the same IP
- Update AKS API version
[![Network: LoadBalancers](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.loadbalancers.yml/badge.svg?branch=users%2Falsehr%2FpipelineFixes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.loadbalancers.yml)
[![ContainerService: ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Falsehr%2FpipelineFixes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml)
[![.Platform: …
> Fixed both Load Balancer & AKS

- docs/wiki/TestingUsage.md
- utilities/tools/Test-ModuleLocally.ps1
- Quick fix for Local Test Script (imported token map process from pipeline, fixed names for parameters)
- Updated Test documentation to reference hashtable instead of object for the additional tokens.
> Quick fix for Local Test Script and Documentation

- arm/Microsoft.Insights/components/.parameters/parameters.json
- arm/Microsoft.Insights/components/deploy.bicep
- arm/Microsoft.Insights/components/readme.md
- arm/Microsoft.Web/sites/.bicep/nested_components.bicep
- utilities/pipelines/dependencies/Microsoft.Insights/components/parameters/parameters.json
Aligned app insights input parameters to Azure Resource Reference
[![Insights: Components](https://github.com/Azure/ResourceModules/actions/workflows/ms.insights.components.yml/badge.svg?branch=users%2Falsehr%2FappInsightsSimplified)](https://github.com/Azure/ResourceModules/actions/workflows/ms.insights.components.yml)
> Aligned app insights input parameters to Azure Resource Reference

- arm/Microsoft.Authorization/policyAssignments/.bicep/nested_policyAssignments_mg.bicep
- arm/Microsoft.Authorization/policyAssignments/.bicep/nested_policyAssignments_rg.bicep
- arm/Microsoft.Authorization/policyAssignments/.bicep/nested_policyAssignments_sub.bicep
Addresses #981 where policy assignments with Role assignments might fail due to Azure AD replication delay. Suggestion by @azMantas to include a static value to set the principal Type for the role assignment resource to 'ServicePrincipal. That also aligns with the recommendation [documentation - role assignments](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/role-based-access-control/role-assignments-template.md#new-service-principal)
- [] Bug fix (non-breaking change which fixes an issue)
[![Authorization: PolicyAssignments](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyassignments.yml/badge.svg?branch=users%2Fahmad%2FpolicyAssignmentRbac)](https://github.com/Azure/ResourceModules/actions/wor …
> Add static value for 'principalType' for the Policy Assignment with Role Assignment Option

- arm/Microsoft.KeyVault/vaults/.parameters/parameters.json
- arm/Microsoft.KeyVault/vaults/deploy.bicep
- arm/Microsoft.KeyVault/vaults/readme.md
Converting `secrets` parameter to secure object. The array type does not have the `secure` option and will therefore be displayed in plaintext in Azure portal (in deployments or export template). 
(Due to change from array to object)
> Keyvaults - Securing secrets parameter by using object

- arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
- arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
- arm/Microsoft.Compute/virtualMachines/deploy.bicep
- arm/Microsoft.Compute/virtualMachines/readme.md
- utilities/tools/Set-ModuleReadMe.ps1
VM availability set is now changed to only require `availabilityZone` to place the VM in an availability zone. Providing 0 (the default value) disabled the use of availability zones.
[![Compute: VirtualMachines](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml/badge.svg?branch=users%2Fmast%2FVMAvailabilitySet)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml) - Failing due to backup issues with the VM.
The following link is to a test run providing 0 as a hardcoded value to the `zones` property, where you see `0` is not an accepted value.
https://github.com/Azure/ResourceModules/runs/5279888499?check_suite_focus=true#step:4:368
> Simplify VM availability zone parameters

- arm/Microsoft.Automation/automationAccounts/deploy.bicep
- The module throws an error because of the usage of `empty(bool)` which is not supported
- Furthermore, the conditions seem unneccesary complicated
[![Automation: AutomationAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.automation.automationaccounts.yml/badge.svg?branch=users%2Falsehr%2FautoAccountBool)](https://github.com/Azure/ResourceModules/actions/workflows/ms.automation.automationaccounts.yml)
> Fix incorrect parameter handling in Automation Account

- arm/Microsoft.Automation/automationAccounts/.bicep/nested_privateEndpoint.bicep
- arm/Microsoft.Automation/automationAccounts/readme.md
- arm/Microsoft.EventHub/namespaces/.bicep/nested_privateEndpoint.bicep
- arm/Microsoft.EventHub/namespaces/readme.md
- arm/Microsoft.Insights/privateLinkScopes/.bicep/nested_privateEndpoint.bicep
- arm/Microsoft.Insights/privateLinkScopes/readme.md
- arm/Microsoft.Network/privateEndpoints/.bicep/nested_rbac.bicep
- arm/Microsoft.Network/privateEndpoints/deploy.bicep
- arm/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/deploy.bicep
- arm/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/readme.md
- arm/Microsoft.Network/privateEndpoints/readme.md
- arm/Microsoft.Synapse/privateLinkHubs/.bicep/nested_privateEndpoint.bicep
- arm/Microsoft.Synapse/privateLinkHubs/readme.md
- arm/Microsoft.Web/sites/.bicep/nested_privateEndpoint.bicep
- arm/Microsoft.Web/sites/readme.md
- docs/wiki/ModulesDesign.md
- utilities/pipelines/dependencies/Microsoft.Automation/automationAccounts/parameters/law.parameters.json
Update Api version for all `Microsoft.Network/privateEndpoints` and `Microsoft.Network/privateEndpoints/privateDnsZoneGroups` causing failures for modules leveraging them
> Align all nested_privateEndpoint to the same API version

- arm/Microsoft.Storage/storageAccounts/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/readme.md
Added `supportsHttpsTrafficOnly` as an optional parameter, was hardcoded. This should be optional as when you are using NFS file shares, it cannot be enabled.
> Storage Account: Parameterized support for HTTPs

- arm/Microsoft.Network/applicationGateways/.bicep/nested_rbac.bicep
- arm/Microsoft.Network/azureFirewalls/.bicep/nested_rbac.bicep
- arm/Microsoft.Network/firewallPolicies/deploy.bicep
- arm/Microsoft.Network/firewallPolicies/readme.md
- arm/Microsoft.Network/firewallPolicies/ruleCollectionGroups/deploy.bicep
- arm/Microsoft.Network/firewallPolicies/ruleCollectionGroups/readme.md
- arm/Microsoft.Network/firewallPolicies/ruleGroups/deploy.bicep
- arm/Microsoft.Network/networkWatchers/connectionMonitors/deploy.bicep
- arm/Microsoft.Network/networkWatchers/connectionMonitors/readme.md
- arm/Microsoft.Network/networkWatchers/flowLogs/deploy.bicep
- arm/Microsoft.Network/networkWatchers/flowLogs/readme.md
- arm/Microsoft.Network/networkWatchers/readme.md
- arm/Microsoft.Network/virtualNetworks/.bicep/nested_rbac.bicep
- arm/Microsoft.Network/virtualNetworks/deploy.bicep
- arm/Microsoft.Network/virtualNetworks/readme.md
- arm/Microsoft.Network/virtualNetworks/subnets/deploy.bicep
- arm/Microsoft.Network/virtualNetworks/subnets/readme.md
- arm/Microsoft.Network/virtualNetworks/virtualNetworkPeerings/deploy.bicep
- arm/Microsoft.Network/virtualNetworks/virtualNetworkPeerings/readme.md
- utilities/pipelines/dependencies/Microsoft.Automation/automationAccounts/parameters/law.parameters.json
Fixed failing pipelines due to outdated API version
[![Network: VirtualNetworks](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml/badge.svg?branch=users%2Ferikag%2Fapivnet)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml)
[![Network: NetworkWatchers](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkwatchers.yml/badge.svg?branch=users%2Ferikag%2Fapivnet)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkwatchers.yml)
[![Network: FirewallPolicies](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.firewallpolicies.yml/badge.svg?branch=users%2Ferikag%2Fapivnet)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.firew …
> Update networking API versions

- docs/wiki/Home.md
- docs/wiki/Known issues.md
- utilities/pipelines/dependencies/Microsoft.Automation/automationAccounts/parameters/law.parameters.json
> Wiki restructuring - known issues

- arm/Microsoft.Compute/virtualMachines/readme.md
- utilities/pipelines/dependencies/Microsoft.Compute/virtualMachines/parameters/parameters.json
Dependency-VM: Disable `accelerated networking` to support small size
[![.Platform: Dependencies](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml/badge.svg?branch=users%2Falsehr%2FdependencyVM)](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml)
> Dependency-VM: Disable `accelerated networking` to support small size

- arm/Microsoft.Network/bastionHosts/.parameters/parameters.json
- arm/Microsoft.Network/bastionHosts/deploy.bicep
- arm/Microsoft.Network/bastionHosts/readme.md
Updated Azure Bastion module to add SKU and Scale Unit capabilities
[![Network: BastionHosts](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.bastionhosts.yml/badge.svg?branch=users%2Fsenavar%2F1009-extend-azure-bastion-host)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.bastionhosts.yml)
> Extend Bastion Host Module 

- arm/Microsoft.Sql/managedInstances/.parameters/parameters.json
- arm/Microsoft.Sql/managedInstances/deploy.bicep
- arm/Microsoft.Sql/managedInstances/encryptionProtector/readme.md
- arm/Microsoft.Sql/managedInstances/readme.md
- arm/Microsoft.Sql/managedInstances/securityAlertPolicies/readme.md
- arm/Microsoft.Sql/managedInstances/vulnerabilityAssessments/readme.md
Updated the SQL MI Module to document the requirements/configuration of NSG + Route Table for SQL MI
Updated code + readme to deploy service principal for Azure AD Authentication 
Added ability to configure Zone Redundancy and Backup Storage Redundancy
The pipeline is red because it timed out, the SQL MI successfully deployed and removed when reviewing pipeline logs.
[![Sql: ManagedInstances](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml/badge.svg?branch=users%2Fsenavar%2FsqlMIUpdate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml)
> SQL MI Update

- arm/Microsoft.Network/virtualNetworks/deploy.bicep
- Removed subnet property from main deployment (as its not required an can cause issues)
[![Network: VirtualNetworks](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml/badge.svg?branch=users%2Falsehr%2Fvnet)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml)
> VNET: Removed subnet property from main deployment

- .azuredevops/modulePipelines/ms.storage.storageaccounts.yml
- .github/workflows/ms.storage.storageaccounts.yml
- arm/Microsoft.Storage/storageAccounts/.parameters/nfs.parameters.json
- arm/Microsoft.Storage/storageAccounts/blobServices/readme.md
- arm/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/fileServices/readme.md
- arm/Microsoft.Storage/storageAccounts/fileServices/shares/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/fileServices/shares/readme.md
- arm/Microsoft.Storage/storageAccounts/queueServices/readme.md
Adding support for NFS 4.1 file shares
[![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Fmast%2FSA_NFS)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml)
> Enabling NFS 4.1 Fileshares

- .azuredevops/modulePipelines/ms.network.virtualwans.yml
- .github/workflows/ms.network.virtualwans.yml
- arm/Microsoft.Network/virtualHubs/deploy.bicep
- arm/Microsoft.Network/virtualHubs/readme.md
- arm/Microsoft.Network/virtualWans/.bicep/nested_rbac.bicep
- arm/Microsoft.Network/virtualWans/.parameters/min.parameters.json
- arm/Microsoft.Network/virtualWans/.parameters/parameters.json
- arm/Microsoft.Network/virtualWans/deploy.bicep
- arm/Microsoft.Network/virtualWans/readme.md
- arm/Microsoft.Network/vpnGateways/deploy.bicep
- arm/Microsoft.Network/vpnGateways/readme.md
- Moved resources to corresponding modules and removed duplicates (incl. RBAC)
- Added new vWAN parameters
- Added new vWAN parameter file
[![Network: VirtualWans](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualwans.yml/badge.svg?branch=users%2Falsehr%2F982_vWANCleanup)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualwans.yml)
> vWAN: Moved resources to corresponding modules and removed duplicates

- .azuredevops/platformPipelines/platform.dependencies.yml
Bug fix. ADO Dependency pipeline update to include policy module changes
Post change:
> Bug fix: Update ADO Dependency Pipeline to support new policy assignment parameter file names, point to the root template instead of child

- arm/Microsoft.Sql/servers/.parameters/parameters.json
- arm/Microsoft.Sql/servers/deploy.bicep
- arm/Microsoft.Sql/servers/readme.md
Add the configuration to use AAD as sql server admin authentication. 
SQL admin credentials were previously required parameters, this is changed to conditional as they are no longer necessary if AAD is configured to be only authentication method.
> add Azure Active Directory as sql server admin authentication

- .azuredevops/modulePipelines/ms.sql.servers.yml
- .github/workflows/ms.sql.servers.yml
- arm/Microsoft.Sql/servers/.parameters/admin.parameters.json
- arm/Microsoft.Sql/servers/.parameters/parameters.json
- arm/Microsoft.Sql/servers/deploy.bicep
- arm/Microsoft.Sql/servers/readme.md
cc: @mvbugge
[![Sql: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Falsehr%2FforkSQLTest)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml)
> Added additional test case for SQL Server 

- arm/Microsoft.Insights/scheduledQueryRules/deploy.bicep
Changing parameters to optional and check if value is not empty
> Make some parameters optional

- arm/Microsoft.Sql/servers/.parameters/parameters.json
- arm/Microsoft.Sql/servers/databases/deploy.bicep
- arm/Microsoft.Sql/servers/databases/readme.md
- arm/Microsoft.Sql/servers/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/.parameters/parameters.json
- Fixed diagnostic references on storage & SQL
[![Sql: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Falsehr%2FsqldatabaseDiag)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml)
[![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Falsehr%2FsqldatabaseDiag)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml)
> Fixed diagnostic references on storage & SQL

- arm/Microsoft.Network/virtualNetworkGateways/deploy.bicep
bgpsettings were trying to still apply the object even when set to false.
This caused an issue when trying to use the module to deploy a 'Basic' type vpn gateway, as bgp isnt supported.
The fix checks the variable enableBgp_var instead of type expressroute before trying to apply settings
> Bugfix for bgpsettings trying to apply even when disabled

- .azuredevops/platformPipelines/platform.dependencies.yml
Fixes #1134 where the ADO pipeline does not have the PPG dependency needed for the availability set module:
**Before**:
**After**:
> Added proximity placement groups in the ADO dependency pipeline

- arm/Microsoft.Network/virtualNetworks/deploy.bicep
Updated dependency of peering resource as the current dependency would break once somebody removes the subnet child resource.
[![Network: VirtualNetworks](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml/badge.svg?branch=users%2Falsehr%2F1198_vnet)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml)
> VNET: Updated peering dependency

- arm/Microsoft.Compute/virtualMachines/.parameters/linux.min.parameters.json
- arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
- arm/Microsoft.Compute/virtualMachines/.parameters/windows.min.parameters.json
- arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
- arm/Microsoft.Compute/virtualMachines/deploy.bicep
Added some smart defaults to `osDisk` and `dataDisks` for VM
[![Compute: VirtualMachines](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml/badge.svg?branch=users%2Fmast%2FVMDiskDefaults)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml)
> Added some defaults to osDisk and dataDisks for VM

- arm/Microsoft.Compute/availabilitySets/deploy.bicep
- arm/Microsoft.Compute/availabilitySets/readme.md
- arm/Microsoft.Insights/components/readme.md
- arm/Microsoft.KeyVault/vaults/readme.md
- arm/Microsoft.KubernetesConfiguration/extensions/readme.md
- arm/Microsoft.KubernetesConfiguration/fluxConfigurations/readme.md
- arm/Microsoft.NetApp/netAppAccounts/capacityPools/readme.md
- arm/Microsoft.Network/firewallPolicies/deploy.bicep
- utilities/tools/Set-ModuleReadMe.ps1
- Added support for multi-line metadata (both parameters & outputs)
- Tested it with an availability set example
Parameter reference
[![Compute: AvailabilitySets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.availabilitysets.yml/badge.svg?branch=users%2Falsehr%2FmarkdownTest)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.availabilitysets.yml)
> Added support for multi-line metadata

- .github/actions/templates/getParameterFiles/action.yml
- arm/Microsoft.Web/sites/.parameters/fa.parameters.json
- The compression used for passing the parameter files from one job to another auto-converted arrays into single strings that broke the consumption via the matrix. This is now fixed.
[![DesktopVirtualization: HostPools](https://github.com/Azure/ResourceModules/actions/workflows/ms.desktopvirtualization.hostpools.yml/badge.svg?branch=users%2Falsehr%2FsingleParameterFileFetch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.desktopvirtualization.hostpools.yml)
Re-test with multi-param example
[![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FsingleParameterFileFetch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.y …
> Fixed GitHub parameter fetch

- .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
- .github/actions/templates/validateModuleDeployment/action.yml
- docs/wiki/Contribution guide - Validate module locally.md
- docs/wiki/TestingDesign.md
- docs/wiki/UtilitiesTestModuleLocally.md
- utilities/pipelines/resourceDeployment/New-TemplateDeployment.ps1
- utilities/pipelines/resourceDeployment/Test-TemplateDeployment.ps1
- utilities/tools/Test-ModuleLocally.ps1
- Enabled template deployment without parameter file
- Also renamed the functions to reflact this change
[![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FdeploymentScriptUpdate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml)
[link](https://dev.azure.com/servicescode/infra-as-code-source/_build/results?buildId=266810&view=results)
> Enabled template deployment without parameter file

- .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
- .github/actions/templates/validateModuleDeployment/action.yml
Passing resourceGroupName as an additional deployment parameter does not work for resources deployed to a scope different than resourcegroup. 
Something to rethink for the dependencies restructuring PoC.
Tested at both sub and rg level
[![Insights: DiagnosticSettings](https://github.com/Azure/ResourceModules/actions/workflows/ms.insights.diagnosticsettings.yml/badge.svg?branch=users%2Ferikag%2Ffix-sub-level)](https://github.com/Azure/ResourceModules/actions/workflows/ms.insights.diagnosticsettings.yml)
[![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Ferikag%2Ffix-sub-level)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml)
Please delete options that are …
> Fix deployment validation at scope different than rg

- arm/Microsoft.Network/virtualNetworks/deploy.bicep
- Retested VNET without @batch and it works (i.e. I don't see a reason to keep it)
[![Network: VirtualNetworks](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml/badge.svg?branch=users%2Falsehr%2FvnetBatchTest&event=workflow_dispatch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml)
> [VNET] Remove `batch` for subnets 

- arm/Microsoft.NetApp/netAppAccounts/deploy.bicep
- Removed `batch` processing as it seems not to be needed (anymore)
| Pipeline reference |
| - |
| [![NetApp: NetAppAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.netapp.netappaccounts.yml/badge.svg?branch=users%2Falsehr%2FbatchTestNetApp&event=workflow_dispatch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.netapp.netappaccounts.yml) |
> [Netapp] Removed `batch` for Capacity Pools

- arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
- Removed the `batch` as it seems not needed (anymore)
[![OperationalInsights: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.operationalinsights.workspaces.yml/badge.svg?branch=users%2Falsehr%2FbatchTestLAW)](https://github.com/Azure/ResourceModules/actions/workflows/ms.operationalinsights.workspaces.yml)
> [OperationalInsights] Removed `batch` for solutions deployment

- arm/Microsoft.Network/firewallPolicies/deploy.bicep
- Test showed the `batch` seems not needed (anymore)
[![Network: FirewallPolicies](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.firewallpolicies.yml/badge.svg?branch=users%2Falsehr%2FbatchTestFirewallPolicies&event=workflow_dispatch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.firewallpolicies.yml)
> [FirewallPolicies] Removed `batch` for ruleCollectionGroups

- arm/.global/global.module.tests.ps1
- utilities/tools/Set-ModuleReadMe.ps1
- [Pester] Added test to make sure the `Set-ModuleReadMe` script was applied
- Note: This test may fail for quite a few modules as we did not have this test before
- Optimized runtime by avoiding to compile the template 3 times
A failed test would look like
[![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2F1241_readmetest&event=workflow_dispatch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml)
[![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Falsehr%2FruntimeOpt)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storag …
> [Pester] Added test to make sure the `Set-ModuleReadMe` script was applied

- arm/.global/global.module.tests.ps1
- Updated the caching to work with duplicated resource type names
| Pipeline |
| - |
| [![ServiceBus: Namespaces](https://github.com/Azure/ResourceModules/workflows/ServiceBus:%20Namespaces/badge.svg?branch=users%2Falsehr%2FruntimeFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml) |
| [![EventHub: Namespaces](https://github.com/Azure/ResourceModules/workflows/EventHub:%20Namespaces/badge.svg?branch=users%2Falsehr%2FruntimeFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml) |
| [![ApiManagement: Service](https://github.com/Azure/ResourceModules/workflows/ApiManagement:%20Service/badge.svg?branch=users%2Falsehr%2 …
> [Pester] Fixed an issue with the runtime optimization

- arm/Microsoft.Network/firewallPolicies/deploy.bicep
When a FW policy uses a base policy and have more rule collection groups, they need to be deployed sequentially, otherwise the deployment would fail because of concurrent access to the base policy. This fix deploys forces ARM to deploy them one after the other.
| Pipeline |
| - |
| [![Network: FirewallPolicies](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.firewallpolicies.yml/badge.svg?branch=Azure-main)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.firewallpolicies.yml)|
> fixing deployment of rule collection groups

- arm/Microsoft.EventHub/namespaces/.parameters/parameters.json
- arm/Microsoft.EventHub/namespaces/deploy.bicep
- arm/Microsoft.EventHub/namespaces/readme.md
- arm/Microsoft.KeyVault/vaults/.parameters/parameters.json
- arm/Microsoft.KeyVault/vaults/deploy.bicep
- arm/Microsoft.KeyVault/vaults/readme.md
- arm/Microsoft.Storage/storageAccounts/.parameters/parameters.json
- arm/Microsoft.Storage/storageAccounts/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/readme.md
Discussed here:  #1287 
This PR changes the networkACL sections, so that a resource id is required instead of just a name.
| Pipeline |
| - |
| |
> changed virtualnetworkrules to use resourceid instead of name

- .azuredevops/pipelineTemplates/jobs.validateModulePester.yml
- .github/actions/templates/validateModulePester/action.yml
- utilities/tools/Test-ModuleLocally.ps1
- Fixed incorrect token reference in local test script
- Made test pipeline more robust for cases where e.g. a managementGroupId was not set in the secrets. Otherwise, tests will fail with misleading error messages
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FlocalTestsFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml)|
> Fixed local tests ref

- utilities/pipelines/resourceDeployment/New-TemplateDeployment.ps1
- Updated the update of the login context to plain subscription ID
- The rational is that the current `Get-AzContext` only returns a maximum of 25 context objects. If an SP has access to more subscriptions, the login won't work and you may end up deploying into a subscription you did not intent to.
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/workflows/AnalysisServices:%20Servers/badge.svg?branch=users%2Falsehr%2Fcontext)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
| [![Resources: ResourceGroups](https://github.com/Azure/ResourceModules/workflows/Resources:%20ResourceGroups/badge.svg?branch=users%2 …
> Updated the update of the login context to plain subscription ID

- utilities/pipelines/resourceDeployment/Test-TemplateDeployment.ps1
- Updated login in Test-Script to align with Deploy-Script
- Ref #1331
- The rational is that the current Get-AzContext only returns a maximum of 25 context objects. If an SP has access to more subscriptions, the login won't work and you may end up deploying into a subscription you did not intent to.
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/workflows/AnalysisServices:%20Servers/badge.svg?branch=users%2Falsehr%2FtestscriptUpdate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
| [![Resources: ResourceGroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.resourcegroups.yml/b …
> Updated login in Test-Script to align with Deploy-Script

- .azuredevops/modulePipelines/ms.apimanagement.service.yml
- .azuredevops/modulePipelines/ms.cognitiveservices.accounts.yml
- .azuredevops/modulePipelines/ms.insights.diagnosticsettings.yml
- .azuredevops/modulePipelines/ms.keyvault.vaults.yml
- .azuredevops/modulePipelines/ms.kubernetesconfiguration.extensions.yml
- .azuredevops/modulePipelines/ms.kubernetesconfiguration.fluxconfigurations.yml
- .azuredevops/modulePipelines/ms.network.networkwatchers.yml
Update `removeDeployment` default parameter for ADO pipelines still disabling removal for modules with soft deletion.
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/servicescode/infra-as-code-source/_apis/build/status/CARML-Modules/KeyVault%20-%20Vaults?branchName=users%2Ferikag%2Falign-ado-removal)](https://dev.azure.com/servicescode/infra-as-code-source/_build/latest?definitionId=2195&branchName=users%2Ferikag%2Falign-ado-removal) |
> Align ADO removeDeployment default input parameter 

- .azuredevops/pipelineTemplates/jobs.publishModule.yml
- README.md
related
#1341 
| Pipeline |
| - |
|[![Build Status](https://dev.azure.com/seseichtMSFT/CARLM-SeSeicht/_apis/build/status/Resources%20-%20ResourceGroups?branchName=main)](https://dev.azure.com/seseichtMSFT/CARLM-SeSeicht/_build/latest?definitionId=308&branchName=main)|
> Change Task Type for ADO in the publishing to bicep registry 

- .azuredevops/modulePipelines/ms.batch.batchaccounts.yml
- arm/Microsoft.Batch/batchAccounts/.parameters/min.parameters.json
- arm/Microsoft.Batch/batchAccounts/.parameters/parameters.json
- arm/Microsoft.Batch/batchAccounts/deploy.bicep
- arm/Microsoft.Batch/batchAccounts/readme.md
The current batchaccounts module does not support any detailed configurations towards the Azure resource.
The one @JPEasier and myself added, supports the full range of options currently available from the API directly.
Developed with pair-programming.
[![Batch: BatchAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.batch.batchaccounts.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.batch.batchaccounts.yml)
> Added configuration options to Microsoft.Batch/batchAccounts

- utilities/pipelines/resourceRemoval/helper/Invoke-ResourceRemoval.ps1
- Added role assignment removal to removal logic
| Pipeline |
| - |
| [![KeyVault: Vaults](https://github.com/Azure/ResourceModules/workflows/KeyVault:%20Vaults/badge.svg?branch=users%2Falsehr%2F803_rbacRemoval)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml) |
| [![Resources: ResourceGroups](https://github.com/Azure/ResourceModules/workflows/Resources:%20ResourceGroups/badge.svg?branch=users%2Falsehr%2F803_rbacRemoval)](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.resourcegroups.yml) |
> Added role assignment removal to removal logic

- .azuredevops/modulePipelines/ms.machinelearningservices.workspaces.yml
- arm/Microsoft.MachineLearningServices/workspaces/.parameters/min.parameters.json
- arm/Microsoft.MachineLearningServices/workspaces/.parameters/parameters.json
- arm/Microsoft.MachineLearningServices/workspaces/deploy.bicep
- arm/Microsoft.MachineLearningServices/workspaces/readme.md
- arm/Microsoft.Sql/managedInstances/deploy.bicep
- arm/Microsoft.Sql/managedInstances/readme.md
- Update ML workspace to latest api
- Added additional features
- Added min test
| Pipeline |
| - |
| [![MachineLearningServices: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml/badge.svg?branch=users%2Falsehr%2FmlwAPI)](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml)|
> Update ML Workspace to latest API

- arm/Microsoft.Authorization/policyAssignments/.parameters/mg.parameters.json
- arm/Microsoft.Authorization/policyAssignments/.parameters/rg.min.parameters.json
- arm/Microsoft.Authorization/policyAssignments/.parameters/rg.parameters.json
- arm/Microsoft.Authorization/policyAssignments/.parameters/sub.parameters.json
- arm/Microsoft.Authorization/policyAssignments/deploy.bicep
- arm/Microsoft.Authorization/policyAssignments/managementGroup/deploy.bicep
- arm/Microsoft.Authorization/policyAssignments/managementGroup/readme.md
- arm/Microsoft.Authorization/policyAssignments/readme.md
- arm/Microsoft.Authorization/policyAssignments/resourceGroup/deploy.bicep
- arm/Microsoft.Authorization/policyAssignments/resourceGroup/readme.md
- arm/Microsoft.Authorization/policyAssignments/subscription/deploy.bicep
- arm/Microsoft.Authorization/policyAssignments/subscription/readme.md
Closes #1360 
Enables User assigned identity support for a policy assignment.
Note: This will not trigger the 'role assignment' resource creation object as it is assumed that a user identity will have the permissions required to modify resources. Hence the role assignment will only run if the policy is using a system assigned identity.
| Pipeline | Run |
| - | - |
| policy assignment |[![Authorization: PolicyAssignments](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyassignments.yml/badge.svg?branch=users%2Fahmad%2FpolicyAssignment_UMI)](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyassignments.yml) |
Please delete options …
> allowed User assigned identity deployments

- utilities/tools/Set-ModuleReadMe.ps1
When Set-ModuleReadMe was called inside the same directory as the bicep file, there was an error and the readme could not be created.
This PR will fix this by resolving relative paths to full paths.
> Fix Set-ModuleReadMe when called w/ relative path

- arm/Microsoft.Compute/virtualMachines/deploy.bicep
- arm/Microsoft.Compute/virtualMachines/readme.md
- constructs/Microsoft.Compute/virtualMachinesMultiple/.parameters/linux.prefix.parameter.json
- constructs/Microsoft.Compute/virtualMachinesMultiple/.parameters/linux.vmnames.parameter.json
- constructs/Microsoft.Compute/virtualMachinesMultiple/deploy.bicep
- constructs/Microsoft.Compute/virtualMachinesMultiple/readme.md
- utilities/tools/Set-ModuleReadMe.ps1
- Added a sample/construct to show how to deploy multiple VMs using our module in combination with a name generator
- Tested both conditional `vmNames` and `vmInitialNumber` + `vmNamePrefix` + `vmNumberOfInstances`
```PowerShell
DeploymentName          : vmNamesTest
ResourceGroupName       : validation-rg
ProvisioningState       : Succeeded
Timestamp               : 06.05.2022 20:03:21
Mode                    : Incremental
TemplateLink            : 
Parameters              : 
Name                                     Type                       Value
=======================================  =========================  ==========
vmNames                                  Array …
```
> [Modules] Added multiple vm deployment example

- .azuredevops/modulePipelines/ms.aad.domainservices.yml
- .azuredevops/modulePipelines/ms.desktopvirtualization.scalingplans.yml
- .azuredevops/modulePipelines/ms.kubernetesconfiguration.extensions.yml
- .azuredevops/modulePipelines/ms.kubernetesconfiguration.fluxconfigurations.yml
- .azuredevops/modulePipelines/ms.network.frontdoors.yml
- .github/workflows/ms.network.vpnsites.yml
- docs/wiki/The CI environment - Publishing.md
Fixed some missing parts to pipelines and a mistake in wiki
> Fixed some missing parts to pipelines and a mistake in wiki

- docs/wiki/Solution creation.md
picture isn't showing at https://github.com/Azure/ResourceModules/wiki/Solution%20creation#repo-structure
Could be potentially integrated into #1375 
> [Docs] picture fix: changing to <img>

- arm/Microsoft.Network/applicationGateways/deploy.bicep
Minor bug fix. If 0 was set as min for autoscale, the autoscale settings were not applied
| Pipeline |
| - |
| |
> [Modules] allow 0 as min capacity

- .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
- utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
If the used ServiceConnection in ADO has access to more than one subscription. It can use the wrong as default and doesn't find the deployments to remove. Therefore the Context will be set accordingly to the subscription.
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/seseichtMSFT/CARLM-SeSeicht/_apis/build/status/SeSeicht.ResourceModules?branchName=fix%2FRemovalContext)](https://dev.azure.com/seseichtMSFT/CARLM-SeSeicht/_build/latest?definitionId=310&branchName=fix%2FRemovalContext) |
> [CI environment] Set Az Context in Removal Stage in ADO

- arm/Microsoft.EventHub/namespaces/.bicep/nested_rbac.bicep
- arm/Microsoft.EventHub/namespaces/.parameters/parameters.json
- arm/Microsoft.EventHub/namespaces/authorizationRules/deploy.bicep
- arm/Microsoft.EventHub/namespaces/authorizationRules/readme.md
- arm/Microsoft.EventHub/namespaces/deploy.bicep
- arm/Microsoft.EventHub/namespaces/disasterRecoveryConfigs/deploy.bicep
- arm/Microsoft.EventHub/namespaces/disasterRecoveryConfigs/readme.md
- arm/Microsoft.EventHub/namespaces/eventhubs/.bicep/nested_rbac.bicep
- arm/Microsoft.EventHub/namespaces/eventhubs/authorizationRules/deploy.bicep
- arm/Microsoft.EventHub/namespaces/eventhubs/authorizationRules/readme.md
- arm/Microsoft.EventHub/namespaces/eventhubs/consumergroups/deploy.bicep
- arm/Microsoft.EventHub/namespaces/eventhubs/consumergroups/readme.md
- arm/Microsoft.EventHub/namespaces/eventhubs/deploy.bicep
- arm/Microsoft.EventHub/namespaces/eventhubs/readme.md
- arm/Microsoft.EventHub/namespaces/networkRuleSets/deploy.bicep
- arm/Microsoft.EventHub/namespaces/networkRuleSets/readme.md
- arm/Microsoft.EventHub/namespaces/networkRuleSets/version.json
- arm/Microsoft.EventHub/namespaces/readme.md
Closes #1356 
- Created the child resources for Network Rule Sets and replaced the existing 'network ACLs' property.
- Updated module to use the latest APIs
| Pipeline |
| - |
| [![EventHub: Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml/badge.svg?branch=users%2Fahmad%2FeventHubUpdates)](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml)|
> [Modules] Update Eventhub Network Rules + latest APIs

- arm/Microsoft.Network/connections/deploy.bicep
The case of the condition was wrong, causing the deployment to fail for IPsec connections as the local gateway ID was never included.
Bug #1402
> Update casing for IPsec connections

- arm/Microsoft.Resources/tags/deploy.bicep
- arm/Microsoft.Resources/tags/readme.md
- arm/Microsoft.Resources/tags/resourceGroups/deploy.bicep
- arm/Microsoft.Resources/tags/resourceGroups/readme.md
- arm/Microsoft.Resources/tags/subscriptions/deploy.bicep
- arm/Microsoft.Resources/tags/subscriptions/readme.md
- Added missing output to tags module
For example
```
Outputs                 : 
Name             Type                       Value
===============  =========================  ==========
name             String                     "default"
tags             Object                     {"Test":"Yes","TestToo":"No"}
resourceId       String                     "/subscriptions/a7439831-1cd9-435d-a091-4aa863c96556/providers/Microsoft.Resources/tags/default"
```
| Pipeline |
| - |
| [![Resources: Tags](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.tags.yml/badge.svg?branch=users%2Falsehr%2FtagsFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.tags.y …
> [Bugfix] Added missing output to tags module

- arm/Microsoft.Compute/virtualMachines/deploy.bicep
NSG parameter is not updated asper the standard, so updated the currect parameter "networkSecurityGroupId" and also conducted the test against the same
> [Module] Fixed Inconsistent naming of NSGs IDs #1323

- .github/PULL_REQUEST_TEMPLATE.md
- arm/Microsoft.AAD/DomainServices/deploy.bicep
- arm/Microsoft.AAD/DomainServices/readme.md
- docs/wiki/The library - Module design.md
- settings.json
- Added telemetry to AAD module & description to docs
> Added telemetry to AAD module & description to docs

- .github/PULL_REQUEST_TEMPLATE.md
- arm/Microsoft.AAD/DomainServices/deploy.bicep
- arm/Microsoft.AAD/DomainServices/readme.md
- arm/Microsoft.Compute/virtualMachines/deploy.bicep
- arm/Microsoft.Network/azureFirewalls/deploy.bicep
- arm/Microsoft.Network/azureFirewalls/readme.md
- docs/wiki/The library - Module design.md
- settings.json
> FW Proposal PR (not main)

- arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/savedSearches/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/savedSearches/readme.md
Without etag parameter savedsearches cannot be overwritten. Set it to `*` to override the existing etag
| Pipeline |
| - |
|[![Build Status](https://dev.azure.com/seseichtMSFT/CARLM-SeSeicht/_apis/build/status/OperationalInsights%20-%20Workspaces?branchName=users%2Fseseicht%2FoperationalInsightFix)](https://dev.azure.com/seseichtMSFT/CARLM-SeSeicht/_build/latest?definitionId=313&branchName=users%2Fseseicht%2FoperationalInsightFix) |
> [Modules] OperationalInsights add etag parameter to SavedSearches

- arm/Microsoft.AppConfiguration/configurationStores/.bicep/nested_privateEndpoint.bicep
- arm/Microsoft.AppConfiguration/configurationStores/.parameters/parameters.json
- arm/Microsoft.AppConfiguration/configurationStores/deploy.bicep
- arm/Microsoft.AppConfiguration/configurationStores/readme.md
- Added private endpoint deployment
| Pipeline |
| - |
|[![AppConfiguration: ConfigurationStores](https://github.com/Azure/ResourceModules/actions/workflows/ms.appconfiguration.configurationstores.yml/badge.svg?branch=users%2Falsehr%2FappConfRecover)](https://github.com/Azure/ResourceModules/actions/workflows/ms.appconfiguration.configurationstores.yml) |
> [Modules] [AppConfig] Added private endpoint

- arm/Microsoft.Automation/automationAccounts/.parameters/parameters.json
- arm/Microsoft.Automation/automationAccounts/deploy.bicep
- arm/Microsoft.Automation/automationAccounts/readme.md
- Renamed parameter to more meaningful name
- `linkedWorkspaceId` to `linkedWorkspaceResourceId`  
| Pipeline |
| - |
| [![OperationalInsights: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.operationalinsights.workspaces.yml/badge.svg?branch=users%2Falsehr%2FrenameAutoAccountParam)](https://github.com/Azure/ResourceModules/actions/workflows/ms.operationalinsights.workspaces.yml)|
> [Module] Renamed parameter to more meaningful name

- .azuredevops/platformPipelines/platform.dependencies.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ms.network.azurefirewalls.yml
- .github/workflows/platform.dependencies.yml
- arm/Microsoft.Network/azureFirewalls/.bicep/nested_publicIPAddress.bicep
- arm/Microsoft.Network/azureFirewalls/.bicep/nested_publicIPAddress_rbac.bicep
- arm/Microsoft.Network/azureFirewalls/.parameters/addpip.parameters.json
- arm/Microsoft.Network/azureFirewalls/.parameters/custompip.parameters.json
- arm/Microsoft.Network/azureFirewalls/.parameters/min.parameters.json
- arm/Microsoft.Network/azureFirewalls/.parameters/parameters.json
- arm/Microsoft.Network/azureFirewalls/deploy.bicep
- arm/Microsoft.Network/azureFirewalls/readme.md
- docs/wiki/The library - Module design.md
- utilities/pipelines/dependencies/Microsoft.Network/publicIPAddresses/parameters/fw.additional.parameters.json
- utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/10.azfw.parameters.json
- utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/11.azfw.parameters.json
- utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/9.azfw.parameters.json
The work completes a portion of #1154 in which I added logic to create a public ip if one is not provided for Azure Firewall. Based on feedback from the team from reviewing #1328, the older PR of this work, I also added functionality to allow the user to revoke creating a default public ip through a boolean parameter. I copied a portion of the logic from arm\Microsoft.Network\bastionHosts\deploy.bicep. 
I also introduced a min.parameters.json file for just azurefirewall - which is a portion of this task #401 
> This is a breaking change because I deleted the ipconfigurations parameter and separated it out into vnetId parameter, publicIpAddressId, and/or publicIPAddressObject
Checking this box after checking #401 has not been started
> [Modules] 1154 Add Public IP to Azure Firewall

- docs/wiki/Solution creation.md
- Updated solution examples in Wiki
- Added 'details' blocks
- Added 'How to start' block
Depends on #1362  
> [Docs]: Updated solution examples in Wiki

- arm/.global/global.module.tests.ps1
Closes #1461 
Fixing a typo in the global pester test file.
| Pipeline |
| - |
| Coming! |
> Fix typo in global test

- arm/Microsoft.Authorization/policySetDefinitions/deploy.bicep
- arm/Microsoft.Authorization/policySetDefinitions/managementGroup/deploy.bicep
- arm/Microsoft.Authorization/policySetDefinitions/managementGroup/readme.md
- arm/Microsoft.Authorization/policySetDefinitions/readme.md
There is no limit of 24 for the PolicySet Definitions. This limit is only for the assignments. It's documented wrong in the official docs. Currently working on getting this fixed also.
https://github.com/MicrosoftDocs/azure-docs/pull/93870
CARML should not prevent the creation of names longer than 24 and shorter than 64
| Pipeline |
| - |
| |
> [Modules] Update PolicySet Definition Name limit to 64

- arm/Microsoft.Network/applicationGateways/.parameters/parameters.json
- arm/Microsoft.Network/applicationGateways/readme.md
I could only find the **applicationGatewaySslCertificate** in the platform deployment so I am assuming that the **applicationGatewaySslCertificate02** reference for the appgateway deployment is wrong (or maybe manually/locally created).   
Also suggesting to remove the version numbering as this will make it more generic? Or is this needed for some reason maybe? The deployment pipeline works fine for me after this change (with the standard platform dependencies deployment).
| Pipeline |
| - |
| |
> Fixed ApplicationGateway pipeline deployment by updating the keyvault reference.

- utilities/tools/AzureDevOps/Register-AzureDevOpsPipeline.ps1
Fixed pipeline name parsing in Register-AzureDevOpsPipeline.ps1, previous version was not working in windows. It always returned an empty string.
N/A
- [ X ] I'm sure there are no other open Pull Requests for the same update/change
- [ X ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [ X ] My code follows the style guidelines of this project
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ X ] I have made corresponding changes to the documentation (readme)
- [ X ] I did format my code
> Fixed pipeline name parsing in Register-AzureDevOpsPipeline.ps1

- arm/Microsoft.Compute/galleries/.bicep/nested_roleAssignments.bicep
- arm/Microsoft.Compute/galleries/deploy.bicep
- arm/Microsoft.Compute/galleries/images/.bicep/nested_roleAssignments.bicep
- arm/Microsoft.Compute/galleries/images/deploy.bicep
- arm/Microsoft.Compute/galleries/images/readme.md
- arm/Microsoft.Compute/galleries/readme.md
Updating Compute Gallery API version to the latest documented in ARR
| Pipeline |
| - |
| [![Compute: Galleries](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.galleries.yml/badge.svg?branch=users%2Ferikag%2Ffix-gallery)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.galleries.yml) |
> [Modules] Compute Galleries API version update

- docs/wiki/The CI environment - Pipeline design.md
Updating wiki pipeline design with latest resources added to the dependencies pipeline
| Pipeline |
| - |
| |
> [Wiki] Update wiki dependencies with latest added resources

- arm/Microsoft.Insights/components/deploy.bicep
- arm/Microsoft.Insights/components/readme.md
- Added the `instrumentationKey` output variable to Microsoft.Insights/components for usage in other services.
- Updated docs
> [Modules]  Added instrumentationKey output variable

- arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections/deploy.bicep
- arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/deploy.bicep
Replaced `thoughput` parameter with `null`, if the database capabilities contain `EnableServerless`.
> [Modules] MongoDB: Removed throughput if database is deployed serverless

- .azuredevops/modulePipelines/ms.servicefabric.clusters.yml
Fixed trigger for ServiceFabric/Clusters in ADO pipelines.
| Pipeline |
| - |
| Only works in main |
> [Module] ServiceFabric/Clusters - Added correct CI trigger for ADO

- .github/actions/templates/getWorkflowInput/action.yml
- docs/wiki/Contribution guide - Validate module locally.md
- docs/wiki/Contribution guide - Validate module on scale.md
- docs/wiki/Contribution guide.md
- utilities/pipelines/sharedScripts/Get-GitHubWorkflowDefaultInput.ps1
- utilities/tools/Invoke-PipelinesForBranch.ps1
- Moved the GitHub-Workflow Inputs script to `sharedScripts` in order to leverage it also in the new function
- The function allows you to filter which pipelines you want to run
- It optionally returns also the pipeline badges for all runs
> [Utilities] Added utility to bulk-run pipelines for a given branch

- arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections/deploy.bicep
- arm/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/deploy.bicep
Based on PR #1571 by @itpropro 
- Replaced `thoughput` parameter with `null`, if the database capabilities contain `EnableServerless`.
| Pipeline |
| - |
| [![DocumentDB: DatabaseAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml/badge.svg?branch=users%2Fitpropro%2FfixMongo)](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml) |
> [Modules] MongoDB: Removed throughput if database is deployed serverless #1571

- arm/Microsoft.Compute/diskEncryptionSets/.parameters/parameters.json
- arm/Microsoft.Compute/diskEncryptionSets/deploy.bicep
- arm/Microsoft.Compute/diskEncryptionSets/readme.md
- Optimized implementation by making the key version an optional parameter
| Pipeline |
| - |
| [![Compute: DiskEncryptionSets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.diskencryptionsets.yml/badge.svg?branch=users%2Falsehr%2FdiskEncrOptimization)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.diskencryptionsets.yml) |
> Updated implementation

- .github/actions/templates/getWorkflowInput/action.yml
- Fix incorrect function reference for GitHub action
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FGhPathFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
> [Fixes] Fix incorrect function reference for GitHub action

- modules/Microsoft.Sql/servers/.parameters/parameters.json
- modules/Microsoft.Sql/servers/deploy.bicep
- modules/Microsoft.Sql/servers/readme.md
- settings.json
Adding parameter for minimum TLS version for the SQL server resource type. 
This PR closes https://github.com/Azure/ResourceModules/issues/1513. 
| Pipeline |
| - |
[![Sql: Servers](https://github.com/ArielRam99/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=arrami%2FsqlServerMinimumTlsVersion)](https://github.com/ArielRam99/ResourceModules/actions/workflows/ms.sql.servers.yml)
> [Modules] Minimum TLS version for SQL server

- modules/.global/global.module.tests.ps1
- Fixed incorrect param file ref
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status/Modules/AnalysisServices%20-%20Servers?branchName=users%2Falsehr%2FpesterTypoFix)](https://dev.azure.com/carml/CARML/_build/latest?definitionId=2&branchName=users%2Falsehr%2FpesterTypoFix) |
> [Fixes] Fixed incorrect param file ref

- utilities/tools/AzureDevOps/Register-AzureDevOpsPipeline.ps1
> [Utilities] Updated DevOps Registration

- docs/wiki/The CI environment - Deployment validation.md
- docs/wiki/The CI environment - Management Group Deployment removal utility.md
- utilities/tools/Clear-ManagementGroupDeployment.ps1
- utilities/tools/helper/Split-Array.ps1
- Created a utility to remove any non-running deployment from a given Management-Group scope
- Uses batch processing, which let's you remove the deployments within a few seconds.
- This utility can later be used in issue #1320 , but until we automate it, it's useful to have around for manual execution
> [Utilities] Added ManagementGroup-Deployment removal script

- modules/Microsoft.ServiceBus/namespaces/networkRuleSets/readme.md
- modules/Microsoft.ServiceBus/namespaces/readme.md
Small fix to Service bus readme files, regenerated to comply with static validation
| Pipeline |
| - |
| [![ServiceBus: Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml/badge.svg?branch=users%2Ferikag%2Fsmall-readme-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml) |
> [Fixes] ServiceBus regenerate readme

- modules/Microsoft.Batch/batchAccounts/.test/encr.parameters.json
- modules/Microsoft.Batch/batchAccounts/.test/parameters.json
- modules/Microsoft.Batch/batchAccounts/deploy.bicep
- modules/Microsoft.Batch/batchAccounts/readme.md
- settings.json
Add private endpoint support with updated parameters file to Batch account module.
Part of the fix for #890 
| Pipeline |
| - | 
| [![Batch: BatchAccounts](https://github.com/ishita-malik1/ResourceModules/actions/workflows/ms.batch.batchaccounts.yml/badge.svg?branch=ismalik%2Fbatch_privateendpoint)](https://github.com/ishita-malik1/ResourceModules/actions/workflows/ms.batch.batchaccounts.yml) |
> [Modules] Batch accounts: Add private endpoint support with updated parameters file.

- modules/Microsoft.DocumentDB/databaseAccounts/gremlinDatabases/deploy.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections/deploy.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/deploy.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/deploy.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/deploy.bicep
When CosmosDB is deployed serverless, it is not supported to provide `throughput`.
Therefore a filter was introduced in the options to conditionally provide the property.
```bicep
...
options: contains(databaseAccount.properties.capabilities, { name: 'EnableServerless' }) ? null : {
throughput: throughput
}
...
```
-
> [Modules] Leave out not supported throughput field in Cosmos

- modules/Microsoft.Sql/servers/.test/parameters.json
- modules/Microsoft.Sql/servers/readme.md
- Changed login away from secret as user name is not defined as secure()
| Pipeline |
| - |
| [![Sql: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Falsehr%2F1652_sqlLogin)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml) |
> [Fixes] SQL - Changed login away from secret as user name is not defined as secure()

- modules/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep
- modules/Microsoft.Compute/virtualMachines/readme.md
- modules/Microsoft.Network/networkInterfaces/deploy.bicep
Fixes #1676 
The `ipConfiguration.vmIPAddress` property within the Virtual Machine module is sent via a nested bicep resource to the Network Interfaces module using `privateIPAddress`, instead of `vmIPAddress`
I would assume we cannot update the Network Intefaces modules to align to the `privateIPAddress` property (as that would be a break public interface, so I guess the fix is to map the Virtual Machine nested bicep to use `vmIPAddress` throughout.
1st nested layer:
https://github.com/Azure/ResourceModules/blob/be7074418e312a8c6790b2879e2e669cb4e36aad/modules/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep#L68
2nd nested layer:
https://github.com/Azure/ResourceModules/blob/be7074418e312a8c6790b2879e2e669cb4e36aad/modules/Microsoft.Network/networkInterfaces/deploy.b …
> [Fixes] VM - Update NIC IP Address handover

- modules/Microsoft.Automation/automationAccounts/.test/encr.parameters.json
- modules/Microsoft.Automation/automationAccounts/.test/parameters.json
- modules/Microsoft.Automation/automationAccounts/deploy.bicep
- modules/Microsoft.Automation/automationAccounts/readme.md
- Adding private DNS zone group id to associate the private endpoint with a private DNS zone.
- Added publicNetworkAccess parameter to be disabled automatically when pe is set. Allowed input values are aligned with other resources and converted to the ones expected by the resource.
| Pipeline |
| - |
| [![Automation: AutomationAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.automation.automationaccounts.yml/badge.svg?branch=users%2Ferikag%2F1692-autoaccount-pe)](https://github.com/Azure/ResourceModules/actions/workflows/ms.automation.automationaccounts.yml) |
> [Modules] Configure privateDnsZoneGroups on automation account

- utilities/pipelines/staticValidation/module.tests.ps1
- utilities/tools/Set-ModuleReadMe.ps1
- Now that CLI version 2.38.0 was release to the MS-hosted agents, the bug that was introduced with 2.37.0 is resolved. As a result we can remove the temporal workaround we introduced in the past
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2F1477_removeWorkaround)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
> [CI Environment] Removed temporal no-restore flag following the CLI fix

- modules/Microsoft.SignalRService/webPubSub/.test/parameters.json
- modules/Microsoft.SignalRService/webPubSub/.test/pe.parameters.json
- modules/Microsoft.SignalRService/webPubSub/deploy.bicep
- modules/Microsoft.SignalRService/webPubSub/readme.md
- modules/Microsoft.SignalRService/webPubSub/version.json
Closes #1695 
- Adding private DNS zone group id to associate the private endpoint with a private DNS zone.
- Updating publicNetworkAccess implementation to be disabled by default only if:
- no explicit value is passed
- private endpoint parameter is not empty
- network acls parameter is empty
This is needed to allow both private endpoint and firewall rules to be applied on the same resource (i.e. set network access to selected networks only)
- Updating main test to deploy both pe and network acls (to test that public network access stays enabled).
- Adding pe test to deploy pe alone (to test that public network access gets disabled).
- Updating parameter description and deployment name typos …
> [Modules] Configure privateDnsZoneGroups on Web PubSub Service

- utilities/pipelines/staticValidation/module.tests.ps1
- Added a test to ensure no non-required parameter (no default) has a description that starts with 'Required'.
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2F1034_optionalTest)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
> [CI Environment] Added test case for parameter description

- modules/Microsoft.Compute/virtualMachines/readme.md
- modules/Microsoft.Network/ddosProtectionPlans/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Network/ddosProtectionPlans/deploy.bicep
- modules/Microsoft.Network/ddosProtectionPlans/readme.md
- modules/Microsoft.Network/natGateways/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Network/natGateways/deploy.bicep
- modules/Microsoft.Network/natGateways/readme.md
- modules/Microsoft.Network/networkWatchers/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Network/networkWatchers/connectionMonitors/deploy.bicep
- modules/Microsoft.Network/networkWatchers/connectionMonitors/readme.md
- modules/Microsoft.Network/networkWatchers/deploy.bicep
- modules/Microsoft.Network/networkWatchers/flowLogs/deploy.bicep
- modules/Microsoft.Network/networkWatchers/flowLogs/readme.md
- modules/Microsoft.Network/networkWatchers/readme.md
- modules/Microsoft.Network/virtualNetworkGateways/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Network/virtualNetworkGateways/deploy.bicep
- modules/Microsoft.Network/virtualNetworkGateways/readme.md
- modules/Microsoft.Network/vpnGateways/connections/deploy.bicep
- modules/Microsoft.Network/vpnGateways/connections/readme.md
- modules/Microsoft.Network/vpnGateways/deploy.bicep
- modules/Microsoft.Network/vpnGateways/natRules/deploy.bicep
- modules/Microsoft.Network/vpnGateways/natRules/readme.md
- modules/Microsoft.Network/vpnGateways/readme.md
- modules/Microsoft.Synapse/workspaces/readme.md
- Regenerating readmes
- Updating API versions
- Updating PIP dependencies
| Pipeline |
| - |
| [![Synapse: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml/badge.svg?branch=users%2Ferikag%2Ffix-readmes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml) |
| [![Network: NetworkWatchers](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkwatchers.yml/badge.svg?branch=users%2Ferikag%2Ffix-readmes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkwatchers.yml) |
| [![Network: DdosProtectionPlans](https://github.com/Azure/ResourceModules/actions/workflows/ms.net …
> [Fixes] Further fixes for static validation failures

- modules/Microsoft.Network/virtualNetworks/deploy.bicep
Replace json('null') -> null
same as: #464
> [Fixes] VNet Replace json('null') -> null

- modules/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
- modules/Microsoft.Compute/virtualMachineScaleSets/readme.md
- modules/Microsoft.Compute/virtualMachines/deploy.bicep
- modules/Microsoft.Compute/virtualMachines/readme.md
Readme PR per request by Rainer Halanek PR related to bug I submitted (https://github.com/Azure/ResourceModules/issues/1595). Updated the domain join settings to the correct ones to domain join correctly. The previous ones in the readme do not work and would attempt to join a blank workgroup. Reference: https://docs.microsoft.com/en-us/azure/active-directory-domain-services/join-windows-vm-template
| Pipeline |
| - |
| |
> [Fixes] Update VM domainJoin parameter usage

- modules/Microsoft.ContainerInstance/containerGroups/deploy.bicep
Changes default param value to prevent deployment issues when using the default set.
This was already correct in the .test example param file
> fixed param example for ContainerGroup

- utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
- To resolve an issue for agents that don't have Az-Modules pre-installed (and hence no $profile is setup) we should always create the profile file if not existing. This eases later case handling.
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FprofileFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
> [Fixes] Ensure $profile is always available

- .vscode/settings.json
Setting default json tab size to 4 spaces
| Pipeline |
| - |
| |
> [Fixes] Extend vscode settings with json specific

- utilities/pipelines/staticValidation/helper/helper.psm1
The pester script was not able to use the new 'cross reference' script as it was not defined in the helper. This fixes the issue
| Pipeline |
| - |
|[![Network: ApplicationSecurityGroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationsecuritygroups.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationsecuritygroups.yml) |
> [Bug Fix] Updated helper to reference the new script for cross reference

- modules/Microsoft.Web/serverfarms/deploy.bicep
- modules/Microsoft.Web/serverfarms/readme.md
Adds `zoneRedundant` property to **Microsoft.Web/serverfarms** module.
Partially fixes #1105.
> [Modules] Adds zoneRedundant property to serverfarms module

- .azuredevops/platformPipelines/platform.dependencies.yml
Adding Set-AzContext support the use of Management Group Scope Service Connections in Azure DevOps. linked to #1708 
| Pipeline |
| - |
| TBC |
> [CI environment] Added subscription context for supporting MG scope service connections

- .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
- .github/actions/templates/validateModuleDeployment/action.yml
Closes #1781 
Add support for token replacement for the dependency resources during the token replacement step in the deployment. The reason is that the removal step relies on dependency resources parameter files tokens to be replaced, and given that we do not have a value for the `localToken_namePrefix`, it will be replaced by empty thus impacting dependency resources risk being removed. Replacing the tokens for dependency files before the removal step kicks in guarantees that there are no tokens that need to be swapped
Future feature suggestion:
- Add support in the 'Test-ModuleLocally' script to allow for resource removal. 
| Pipeline |
| - |
| [![RecoveryServices: …
> [Fixes] Resource removal stage attempts to remove dependency resources

- utilities/pipelines/staticValidation/module.tests.ps1
- utilities/tools/Get-CrossReferencedModuleList.ps1
- utilities/tools/Set-ModuleReadMe.ps1
- utilities/tools/Test-ModuleLocally.ps1
- Added diverse properties that are required when running CARML on Linux (e.g. `-Force`)
- Improved robustness by adding additional checks for e.g. empty files/arrays
- Added support for Test-Local script to support execution without any parameter files
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FreadMeLinuxFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
> [Fixes] Improved compatibility with Linux & improved robustness

- modules/Microsoft.Network/bastionHosts/.test/parameters.json
- modules/Microsoft.Network/bastionHosts/deploy.bicep
- modules/Microsoft.Network/bastionHosts/readme.md
Addition of standard SKU options to support tunnelling, native client and enable/disable features.
| Pipeline |
| - |
| [![Network: BastionHosts](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.bastionhosts.yml/badge.svg?branch=users%2Fcsidebotham%2Fbastion-standard-sku-options)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.bastionhosts.yml) |
> [Modules] Adding Standard SKU Options to bastionHosts

- .azuredevops/platformPipelines/platform.dependencies.yml
- .github/workflows/platform.dependencies.yml
- modules/Microsoft.Network/privateLinkServices/.test/min.parameters.json
- modules/Microsoft.Network/privateLinkServices/.test/parameters.json
- modules/Microsoft.Network/privateLinkServices/readme.md
- utilities/pipelines/dependencies/Microsoft.Network/loadBalancers/parameters/pls.parameters.json
- utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/parameters.json
closes #1803 
Private Link services rely on dependences that don't allow it to be successfully deployed. Two issues:
- The Azure Load Balancer frontend cannot be referenced from the existing 'internal' dependency load balancer due to NAT rules. Hence created a new PLS load balancer with 2 separate frontends as we cannot create additional frontends with the existing one.
- The subnets do require private link network policies to be disabled. Hence created new subnets for it.
| Pipeline |
| - |
| [![Network: PrivateLinkServices](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.privatelinkservices.yml/badge.svg?branch=users%2Fahmad%2FbugFix_PLS_dependency)](https://github.com/A …
> Added new dependencies and updated pls resources references

- modules/Microsoft.Network/networkInterfaces/.test/parameters.json
- modules/Microsoft.Network/networkInterfaces/deploy.bicep
- modules/Microsoft.Network/networkInterfaces/readme.md
#1278 
Added a default value for the Ip configuration of network interfaces. Now if no value is provided for the IP configuration, the IP configuration is named 'ipconfig-{currentIndex}'. 
Whilst there are other IP configuration name values across the modules (e.g., Azure Firewall), only the Virtual Machine is updated. The rationale being the name for an AZ Firewall IP configuration is more significant than that within a network interface. 
| Pipeline |
| - |
| [![Network: NetworkInterfaces](https://github.com/milescattini/Bicep-ResourceModules/actions/workflows/ms.network.networkinterfaces.yml/badge.svg)](https://github.com/milescattini/Bicep-ResourceModules/actions/workflows/ms.network.networkinterfaces.yml)|
> [Modules] Default value for IpConfiguration name

- modules/Microsoft.KeyVault/vaults/.test/min.parameters.json
- modules/Microsoft.KeyVault/vaults/readme.md
- Updated KV Min Test Name to resolve conflict
| Pipeline |
| - |
| [![KeyVault: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=users%2Falsehr%2FkvName)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml) |
> [Fixes] Updated KeyVault min test name to resolve conflict

- modules/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/agentPools/readme.md
- modules/Microsoft.ContainerService/managedClusters/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/readme.md
- modules/Microsoft.KubernetesConfiguration/extensions/deploy.bicep
- modules/Microsoft.KubernetesConfiguration/fluxConfigurations/deploy.bicep
- Upgraded AKS API version to latest non-review
| Pipeline |
| - |
| [![ContainerService: ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Falsehr%2Faks_api_fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml) |
> [Modules] Upgraded AKS API version to latest non-review

- modules/Microsoft.ContainerService/managedClusters/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/readme.md
> To make sure every Authentication and Authorization method can be selected, I created a new parameter `enableRBAC` to 
> enable or disable RBAC regardless of AzureRBAC configuration so you can choose between local accounts or Azure AD for 
> authentication and Azure RBAC or Kubernetes RBAC for your authorization needs.
[![ContainerService: ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml)
> [Modules] Update ContainerService/managedClusters add enableRBAC parameter for multiple authentication options

- modules/Microsoft.Sql/managedInstances/.test/min.parameters.json
- modules/Microsoft.Sql/managedInstances/.test/parameters.json
- modules/Microsoft.Sql/managedInstances/administrators/deploy.bicep
- modules/Microsoft.Sql/managedInstances/administrators/readme.md
- modules/Microsoft.Sql/managedInstances/deploy.bicep
- modules/Microsoft.Sql/managedInstances/encryptionProtector/deploy.bicep
- modules/Microsoft.Sql/managedInstances/encryptionProtector/readme.md
- modules/Microsoft.Sql/managedInstances/keys/deploy.bicep
- modules/Microsoft.Sql/managedInstances/keys/readme.md
- modules/Microsoft.Sql/managedInstances/readme.md
Closes #1858
- Added min test to sqlmi
- Fixed child condition causing min test to fail
- Updated children output description
| Pipeline |
| - |
| [![Sql: ManagedInstances](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml/badge.svg?branch=users%2Ferikag%2Fsqlmidep)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml) |
> [Modules] SQLMI Added min param

- modules/Microsoft.ServiceBus/namespaces/deploy.bicep
- modules/Microsoft.ServiceBus/namespaces/readme.md
- modules/Microsoft.Storage/storageAccounts/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/readme.md
Clean up not used `baseTime` parameter
| Pipeline |
| - |
| [![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Ferikag%2F1965-baseTime)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) |
| [![ServiceBus: Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml/badge.svg?branch=users%2Ferikag%2F1965-baseTime)](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml) |
> [Modules] Clean up not used baseTime parameter

- .azuredevops/modulePipelines/ms.powerbidedicated.capacities.yml
- .github/workflows/ms.powerbidedicated.capacities.yml
- modules/Microsoft.PowerBIDedicated/capacities/.bicep/nested_rbac.bicep
- modules/Microsoft.PowerBIDedicated/capacities/.test/min.parameters.json
- modules/Microsoft.PowerBIDedicated/capacities/deploy.bicep
- modules/Microsoft.PowerBIDedicated/capacities/readme.md
- modules/Microsoft.PowerBIDedicated/capacities/version.json
New CARML Module for Microsoft.PowerBIDedicated/capacities resource used to deploy PowerBi Embedded in Azure.
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status/Modules/PowerBiDedicated.Capacities?branchName=1976-feature-request-module-for-powerbidedicatedcapacities)](https://dev.azure.com/carml/CARML/_build/latest?definitionId=106&branchName=1976-feature-request-module-for-powerbidedicatedcapacities) |
> [Modules] Microsoft.PowerBIDedicated/capacities module

- modules/Microsoft.Batch/batchAccounts/.test/encr.parameters.json
- modules/Microsoft.Batch/batchAccounts/.test/parameters.json
- modules/Microsoft.Batch/batchAccounts/deploy.bicep
- modules/Microsoft.Batch/batchAccounts/readme.md
- modules/Microsoft.Batch/batchAccounts/version.json
Updating networking. In particular
- add option to specify network profile (Selected networks). Required API version update.
- public network access is set to disabled if private endpoints are set and if network profile is not set
- add privateDnsZoneGroups on batchAccount tests using private endpoints
Version update
| Pipeline |
| - |
| [![Batch: BatchAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.batch.batchaccounts.yml/badge.svg?branch=users%2Ferikag%2F1975-batch-dns)](https://github.com/Azure/ResourceModules/actions/workflows/ms.batch.batchaccounts.yml) |
> [Modules] Configure privateDnsZoneGroups on batchAccount

- modules/Microsoft.EventGrid/topics/.test/min.parameters.json
- modules/Microsoft.EventGrid/topics/.test/parameters.json
- modules/Microsoft.EventGrid/topics/.test/pe.parameters.json
- modules/Microsoft.EventGrid/topics/deploy.bicep
- modules/Microsoft.EventGrid/topics/readme.md
- modules/Microsoft.EventGrid/topics/version.json
Updating networking. In particular
- public network access is set to disabled if private endpoints are set and if inboundIpRules are not set
- add privateDnsZoneGroups to tests using private endpoints
- update common test to use both private endpoints and inboundIpRules (public network access is not disabled)
- add test using private endpoints only (public network access gets automatically disabled)
- add min test
Minor updates to input and output parameter descriptions
Version update
| Pipeline |
| - |
| [![EventGrid: Topics](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventgrid.topics.yml/badge.svg?branch=users%2Ferikag%2F2000-eventgrid-dns)](https://github.com/Azure/Resourc …
> [Modules] Configure privateDnsZoneGroups on eventgrid

- modules/Microsoft.ContainerRegistry/registries/.test/parameters.json
- modules/Microsoft.ContainerRegistry/registries/.test/pe.parameters.json
- modules/Microsoft.ContainerRegistry/registries/deploy.bicep
- modules/Microsoft.ContainerRegistry/registries/readme.md
- modules/Microsoft.ContainerRegistry/registries/version.json
Updating networking. In particular
- public network access is set to disabled if private endpoints are set and if networkRuleSetIpRules are not set
- add privateDnsZoneGroups on tests using private endpoints
- update common test to use both private endpoints and networkRuleSetIpRules (public network access is not disabled but set to selected networks)
- add test using private endpoints only (public network access gets automatically disabled)
- add note in networking parameter descriptions that the Premium sku is required
Version update
| Pipeline |
| - |
| [![ContainerRegistry: Registries](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml/badge.svg?b …
> [Modules] Configure privateDnsZoneGroups on ACR

- utilities/tools/Get-FormattedGitHubRelease.ps1
Update script to generate custom release notes. Include contributor names, count of PRs, count of new contributors and count of all contributors.
| Pipeline |
| - |
| |
> [Utilities] Update script to generate custom release notes

- .github/workflows/ms.keyvault.vaults.yml
- ps-rule.yaml
> [Hackaton] First test for PSRule exclusions on KeyVault

- .github/workflows/ms.network.virtualnetworks.yml
- modules/Microsoft.Network/virtualNetworks/.test/vnet-ps-rule.yaml
- ps-rule.yaml
[Hackathon] PSRule output in markdown and added to github step summary
| Pipeline |
| - |
| |
- [ X] New feature (non-breaking change which adds functionality)
> [Hackathon] PSRule output in markdown 

- .github/workflows/ms.keyvault.vaults.yml
- ps-rule.yaml
> [Hackaton] csv output on Keyvault module

- utilities/pipelines/staticValidation/module.tests.ps1
- Increased flexibility on parameter table search (i.e., search for the start of the table instead of assuming it's 'just' in the next line)
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FreadMeTestFollowUp)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
> [Utilities] Increased flexibility on parameter table search

- modules/Microsoft.Network/connections/.test/vnet2vnet/dependencies.bicep
- Fixed incorrect depenency variable reference
| Pipeline |
| - |
| [![Network: Connections](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.connections.yml/badge.svg?branch=users%2Falsehr%2FconNameFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.connections.yml) |
> [Fixes] Fixed incorrect depenency variable reference

- utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
- utilities/pipelines/resourceRemoval/helper/Get-DeploymentTargetResourceList.ps1
Prerequisite for PR #2136 and #2019. 
In the new dependencies approach for compute images, a deployment at subscription scope (roleAssignment) is nested in a deployment at resource group scope (rg dependencies). The current removal logic does not cover this scenario and the nested deployment is not fetched when having a higher scope than the parent. Hence the roleAssignment is not removed, and a subsequent validation of the module fails.
- Improving fetching of deployments and resources to delete to support the above scenario.
- Adding roleAssignment removal priority 
| Pipeline |
| - |
| [![Consumption: Budgets](https://github.com/Azure/ResourceModules/actions/workflows/ms.consumption.budgets. …
> [CI environment] Extend and optimize resource removal of nested deployments with higher scope than the parent

- .azuredevops/pipelineTemplates/jobs.publishModule.yml
- .azuredevops/pipelineTemplates/jobs.validateModulePester.yml
- Removed Multi-Repo leftovers from Pester validation & publish
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status/Modules/Cache%20-%20Redis?branchName=users%2Falsehr%2F2109_pipelineCleanup)](https://dev.azure.com/carml/CARML/_build/latest?definitionId=103&branchName=users%2Falsehr%2F2109_pipelineCleanup) |
> [Pipelines] Removed checkout repository leftovers

- modules/Microsoft.Web/staticSites/customDomains/readme.md
- modules/Microsoft.Web/staticSites/linkedBackends/readme.md
Readme update needed
| Pipeline |
| - |
| [![Web: StaticSites](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.staticsites.yml/badge.svg?branch=users%2Ferikag%2F2166-fix-web-staticsites)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.staticsites.yml) |
> [Fixes] Fix Web StaticSites readme

- modules/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
- modules/Microsoft.Compute/virtualMachineScaleSets/readme.md
Received the following error during recent deployment:
```json
{
"code": "DeploymentFailed",
"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
"details": [{
"code": "MinimumApiVersionNotSpecifiedToSetTheProperty",
"message": "Specified api-version 2021-04-01 does not meet the minimum required api-version 2022-03-01 to set this property skuOnPublicIPAddressConfiguration."
}]
}
```
> [Modules] Update VMSS API version

- modules/Microsoft.KeyVault/vaults/.test/common/deploy.test.bicep
- modules/Microsoft.KeyVault/vaults/deploy.bicep
- modules/Microsoft.KeyVault/vaults/readme.md
- Remove outdated `vNetId` parameter usage
- Update `networkAcls` parameter usage
- Removed parameter value from common test. `action: 'Allow'` is added by default.
- Cleaned up variable `networkAcls_var` from the module
| Pipeline |
| - |
| |
> [Fixes] Key Vault - Fix parameter usage section

- modules/Microsoft.NetApp/netAppAccounts/.test/nfs41/deploy.test.bicep
- modules/Microsoft.NetApp/netAppAccounts/readme.md
Missing RBAC principalType for NetApp nfs41 test caused deployment validation to fail
| Pipeline |
| - |
| [![NetApp: NetAppAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.netapp.netappaccounts.yml/badge.svg?branch=users%2Ferikag%2F2209-fix-anf)](https://github.com/Azure/ResourceModules/actions/workflows/ms.netapp.netappaccounts.yml) |
> [Modules] NetApp nfs41 adding principalType to RBAC

- modules/Microsoft.Resources/deploymentScripts/.test/cli/deploy.test.bicep
- modules/Microsoft.Resources/deploymentScripts/readme.md
Latest az cli version is 2.41.0, but not yet supported by Deployment Scripts and causing deployment validation to fail on cli test.
Reverting to current runner up 2.40.0
| Pipeline |
| - |
| [![Resources: DeploymentScripts](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.deploymentscripts.yml/badge.svg?branch=users%2Ferikag%2F2221-fix-ds)](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.deploymentscripts.yml) |
> [Fixes] Update latest az cli version for Deployment Scripts cli test

- modules/Microsoft.Web/sites/.test/FunctionAppCommon/deploy.test.bicep
- modules/Microsoft.Web/sites/deploy.bicep
- modules/Microsoft.Web/sites/readme.md
This PR will introduce the ability to define a specific identity to be used by the app service when authenticating to a keyvault.
Previously this missing property could lead to issues when using a system- and a user-assigned identity at the same time.
| Pipeline |
| [![Web: Sites](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml/badge.svg?branch=users%2Ff_blix%2Fsites-kvrefidentity)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml) |
| |
> [Modules] Extend Web Sites with kvrefidentity

- modules/Microsoft.DBforPostgreSQL/flexibleServers/.test/private/dependencies.bicep
It appears this is a special case for this resource provider. When comparing the [parameter files](https://github.com/Azure/ResourceModules/blob/main/utilities/pipelines/dependencies/Microsoft.Network/privateDnsZones/parameters/postgres.parameters.json) it becomes relatively apparant ...
| Pipeline |
| - |
| [![DbForPostgreSQL: FlexibleServers](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml/badge.svg?branch=users%2Falsehr%2F2234_dbfp)](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml) |
> [Fixes] Fixed test DNS name

- modules/Microsoft.MachineLearningServices/workspaces/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.MachineLearningServices/workspaces/.test/encr/dependencies.bicep
- modules/Microsoft.MachineLearningServices/workspaces/.test/encr/deploy.test.bicep
- modules/Microsoft.MachineLearningServices/workspaces/computes/deploy.bicep
- modules/Microsoft.MachineLearningServices/workspaces/computes/readme.md
- modules/Microsoft.MachineLearningServices/workspaces/deploy.bicep
- modules/Microsoft.MachineLearningServices/workspaces/readme.md
- Updated API version(s)
- Added 2 additional parameters 
- Added 2 additinoal allowed values for property
| Pipeline |
| - |
| [![MachineLearningServices: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml/badge.svg?branch=users%2Falsehr%2F2233_mlAPI)](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml) |
> [Modules] Updated & extended ML Workspaces API version

- modules/Microsoft.Sql/managedInstances/deploy.bicep
- modules/Microsoft.Sql/managedInstances/readme.md
Implements SQL Managed Instances to have Minimum TLS version. This PR fixes #2261.
| Pipeline |
| - |
| |
> Managed instance support TLS setting (Fixes #2261)

- modules/Microsoft.Network/virtualHubs/deploy.bicep
- modules/Microsoft.Network/virtualHubs/hubRouteTables/deploy.bicep
- modules/Microsoft.Network/virtualHubs/hubRouteTables/readme.md
- modules/Microsoft.Network/virtualHubs/hubVirtualNetworkConnections/deploy.bicep
- modules/Microsoft.Network/virtualHubs/hubVirtualNetworkConnections/readme.md
- modules/Microsoft.Network/virtualHubs/readme.md
Based on #2253 
---
change the API version from 2021-08-01 to 2022-05-01 because when we want add the virtualRouterAsn we are getting the following error:
```
"CustomAsnNotSupportedByVirtualHub\\\",\\r\\n    \\\"message\\\": \\\"To modify router ASN in virtual hub, please use API version 2022-01-01 and beyond
```
| Pipeline |
| - |
| [![Network: VirtualHubs](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualhubs.yml/badge.svg?branch=users%2Faavdberg%2F2253_apiUpdate)](https:/ …
> [Modules] Update the API version for Virtual Hubs to latest version

- modules/Microsoft.ManagedServices/registrationDefinitions/.test/common/deploy.test.bicep
- modules/Microsoft.ManagedServices/registrationDefinitions/.test/rg/deploy.test.bicep
- modules/Microsoft.ManagedServices/registrationDefinitions/readme.md
Due to some group cleanup in the target tenant, recreating groups for testing and validation purposes.
| Pipeline |
| - |
| [![ManagedServices: RegistrationDefinitions](https://github.com/Azure/ResourceModules/actions/workflows/ms.managedservices.registrationdefinitions.yml/badge.svg?branch=users%2Fmast%2F2279)](https://github.com/Azure/ResourceModules/actions/workflows/ms.managedservices.registrationdefinitions.yml) |
> [Module] Lighthouse - fix group object IDs

- utilities/pipelines/resourceDeployment/New-TemplateDeployment.ps1
- Adjusted the deployment name logic to regenerate it each time a retry takes place (added with a `t#` in the end)
- Also incorporated the module's name in case the template's file path allows it
Examples
- Analysis Servies
- Key Vault
```
VERBOSE: Deploying with deployment name [KeyVault-vaults-min-20221104T2011351293Z-t1]
VERBOSE: Deploying with deployment name [KeyVault-vaults-min-20221104T2011411996Z-t2]
VERBOSE: Deploying with deployment name [KeyVault-vaults-min-20221104T2011437597Z-t3]
```
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2F2276_deploymentName&event …
> [Utilities] Updated the deployment name generation to be more detailed

- .github/actions/templates/getModuleTestFiles/action.yml
- .github/actions/templates/getWorkflowInput/action.yml
- .github/actions/templates/validateModuleDeployment/action.yml
- .github/actions/templates/validateModulePester/action.yml
Following examples [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#patching-your-actions-and-workflows) and specifically [here](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions?tool=powershell#setting-an-output-parameter) for PowerShell workflow commands
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Ferikag%2F2211-env-files)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
| [![DesktopVirtualization: …
> [CI environment] Replace `set-output` commands with GH environment file `$env:GITHUB_OUTPUT`

- .lycheeignore
- modules/Microsoft.Web/sites/config-appsettings/deploy.bicep
- modules/Microsoft.Web/sites/config-appsettings/readme.md
- modules/Microsoft.Web/sites/config-authsettingsv2/deploy.bicep
- modules/Microsoft.Web/sites/config-authsettingsv2/readme.md
- modules/Microsoft.Web/sites/deploy.bicep
- modules/Microsoft.Web/sites/readme.md
- Updated the kind property of the Microsoft.Web/sites module to also include options to deploy a logic app.
- Fixed broken link checker by adding the sts.microsoft.com URL as an exception as its part of the code and not to be checked by the linter.
[![Web: Sites](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml/badge.svg?branch=users%2Ffblix%2F2304-missing-kind-property-for-microsoft-web-site-module)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml)
> [Fixes] missing kind property for microsoft web site module

- modules/Microsoft.Web/connections/readme.md
- modules/Microsoft.Web/sites/readme.md
- utilities/tools/helper/ConvertTo-OrderedHashtable.ps1
- Updated `Set-ModuleReadMe` script to work with latest PowerShell version
- In a new version, `ConvertFrom-Json` returns now an 'OrderedHashtable' instead of a default Hashtable which can cause issues
- Also, re-ran the script on all modules
| Pipeline |
| - |
| |
> [Utiltities] Updated `Set-ModuleReadMe` script to work with latest PowerShell version

- modules/Microsoft.ContainerService/managedClusters/.test/azure/dependencies.bicep
- modules/Microsoft.ContainerService/managedClusters/.test/azure/deploy.test.bicep
- modules/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/agentPools/readme.md
- modules/Microsoft.ContainerService/managedClusters/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/readme.md
When the AKS is deployed with a default or spezific Version and then redeploy with a newer Version,
the module updates only the Kubernetes control plane not the node pools.
As a best practice, you should upgrade all node pools in an AKS cluster to the same Kubernetes version.
The Operational version will be set to the Kubernetes version if it's set in parameters.
- Update API version
| Pipeline |
| - |
| [![ContainerService: ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Fjpeasier%2FFixUpdateKubernetesVersionOnNodePool)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml) |
> [Modules] Update AKS Orchestrator version when upgrade.

- utilities/pipelines/resourceDeployment/Test-TemplateDeployment.ps1
- Aligned deployment name generation of `Test-TemplateDeployment` & `New-TemplateDeployment`
- For example: `c-g-common-20221111T1211149371Z`
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FtestTemplateDeploymentName)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
> [Utilities] Aligned deployment name generation of `Test-TemplateDeployment` & `New-TemplateDeployment`

- README.md
Use GH workflow badges in home readme for linter and broken links
| Pipeline |
| - |
| |
> [Fixes] Update home readme status badges

- utilities/pipelines/resourceDeployment/Test-TemplateDeployment.ps1
- The name is only supported for non-resource-group-scoped deployments
| Pipeline |
| - |
| [![Synapse: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml/badge.svg?branch=users%2Falsehr%2FfixedDeploymentNameRef)](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml) <= unrelated, expected error |
> [Fixes] Fixed usage of deployment name in Test-Deployment script

- modules/Microsoft.VirtualMachineImages/imageTemplates/deploy.bicep
- Adjusted a 'split' in the template to be more robust
| Pipeline |
| - |
| [![VirtualMachineImages: ImageTemplates](https://github.com/Azure/ResourceModules/actions/workflows/ms.virtualmachineimages.imagetemplates.yml/badge.svg?branch=users%2Falsehr%2FImageTemplateRef)](https://github.com/Azure/ResourceModules/actions/workflows/ms.virtualmachineimages.imagetemplates.yml) |
> [Modules] Update reference usage in template

- docs/wiki/The CI environment - Deployment history cleanup.md
> [Wiki] Re-apply suggested changes

- docs/wiki/Contribution guide - Generate module readme.md
- docs/wiki/Interoperability - Bicep to ARM conversion.md
- utilities/tools/ConvertTo-ARMTemplate.ps1
- utilities/tools/tests/ConvertTo-ARMTemplate.Tests.ps1
- Updated compatability of `ConvertTo-ARMTemplate` utility to new dependencies approach
- Updated test cases
- Enabled multi-threading & invocation
| Pipeline |
| - |
| [![.Platform: Test - ConvertTo-ARMTemplate.ps1](https://github.com/Azure/ResourceModules/actions/workflows/platform.convertToArmTemplate.tests.yml/badge.svg?branch=users%2Falsehr%2FconverttoARMUpdate)](https://github.com/Azure/ResourceModules/actions/workflows/platform.convertToArmTemplate.tests.yml) |
> [Utilties] Updated compatability of `ConvertTo-ARMTemplate` utility to new dependencies approach

- modules/Microsoft.DBforPostgreSQL/flexibleServers/deploy.bicep
After creating the databases, firewall rules are created. These must be deployed before configurations can be created, otherwise a deployment error may occur. [Failed Pipeline](https://github.com/Azure/ResourceModules/actions/runs/3577153479)
See also: https://learn.microsoft.com/en-us/answers/questions/1078895/deploying-postgresql-flexible-server-with-azureext.html
Add dependsOn to the sub resources
| Pipeline |
| - |
| [![DbForPostgreSQL: FlexibleServers](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml/badge.svg?branch=users%2Fjpeasier%2FfixDeploymentErrorWithFlexibleServerConfigurations)](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml) |
> [Fixes] Fix deployment error with flexible server configurations

- .github/workflows/ms.maintenance.maintenanceconfigurations.yml
GH workflow missing removal. Aligned to use `workflowInput` output from initialize pipeline action
| Pipeline |
| - |
| [![Maintenance: MaintenanceConfigurations](https://github.com/Azure/ResourceModules/actions/workflows/ms.maintenance.maintenanceconfigurations.yml/badge.svg?branch=users%2Ferikag%2Fmaintenance-removal)](https://github.com/Azure/ResourceModules/actions/workflows/ms.maintenance.maintenanceconfigurations.yml) |
> [Fixes] Fix removal of maintenance config 

- modules/Microsoft.ContainerRegistry/registries/deploy.bicep
- modules/Microsoft.ContainerRegistry/registries/readme.md
- Added property `anonymousPullEnabled`
| Pipeline |
| - |
| [![ContainerRegistry: Registries](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml/badge.svg?branch=users%2Falsehr%2F2036_acr2)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml) |
> [Modules] Added property `anonymousPullEnabled`

- docs/wiki/The library - Module design.md
Language update for new telemetry content: https://github.com/Azure/ResourceModules/wiki/The%20library%20-%20Module%20design#telemetry
| Pipeline |
| - |
| |
> [Fixes] Telemetry language update

- modules/Microsoft.Sql/servers/.test/common/dependencies.bicep
- modules/Microsoft.Sql/servers/.test/common/deploy.test.bicep
- modules/Microsoft.Sql/servers/deploy.bicep
- modules/Microsoft.Sql/servers/keys/deploy.bicep
- modules/Microsoft.Sql/servers/keys/readme.md
- modules/Microsoft.Sql/servers/keys/version.json
- modules/Microsoft.Sql/servers/readme.md
Updated API versions
Added Key Module to SQL Server
| Pipeline |
| - |
|[![Sql: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Ffabmas_2190_sql)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml) |
> [Modules] Added Key Module to SQL Server

- modules/Microsoft.Network/frontDoors/readme.md
Fixing the readme file as per requirements to pass static validation 
| Pipeline |
| - |
|[![Network: Frontdoors](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.frontdoors.yml/badge.svg?branch=users%2Fcsidebotham%2Ffront-door-static-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.frontdoors.yml)  |
> [Modules]: Microsoft.Network/frontdoors - Fix for Static Validation

- utilities/pipelines/resourceRemoval/helper/Invoke-ResourcePostRemoval.ps1
- utilities/pipelines/resourceRemoval/helper/Invoke-ResourceRemoval.ps1
Closes #2486 
| Pipeline |
| - |
| [![Automation: AutomationAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.automation.automationaccounts.yml/badge.svg?branch=users%2Ferikag%2Flaw-purge)](https://github.com/Azure/ResourceModules/actions/workflows/ms.automation.automationaccounts.yml) |
| [![AppConfiguration: ConfigurationStores](https://github.com/Azure/ResourceModules/actions/workflows/ms.appconfiguration.configurationstores.yml/badge.svg?branch=users%2Ferikag%2Flaw-purge)](https://github.com/Azure/ResourceModules/actions/workflows/ms.appconfiguration.configurationstores.yml) |
> [Fixes] Update LAW force delete

- .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
- .github/actions/templates/validateModuleDeployment/action.yml
- utilities/pipelines/staticValidation/module.tests.ps1
- utilities/src/apiSpecsList.json
- utilities/tools/ConvertTo-ARMTemplate.ps1
- utilities/tools/Set-ModuleReadMe.ps1
- We're experiencing increasingly many problems with rate limits like:  `ERROR: Error while attempting to retrieve the latest Bicep version: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Azure/bicep/releases/latest.`
- As per [this](https://github.com/Azure/bicep/issues/3689) Bicep issue it seems to be an issue with the Azure CLI which it is suggested to work around by using the native Bicep CLI
- This PR perfoms that change for the entire repository. Functionality-wise it should work the exact same way
| Pipeline |
| - |
| [![ContainerRegistry: Registries](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml/badge.svg?bran …
> [Fixes] Switch from `az bicep build` to `bicep build` to avoid rate limits

- modules/Microsoft.AppConfiguration/configurationStores/readme.md
- modules/Microsoft.Automation/automationAccounts/readme.md
- modules/Microsoft.Batch/batchAccounts/readme.md
- modules/Microsoft.Cache/redis/readme.md
- modules/Microsoft.CognitiveServices/accounts/readme.md
- modules/Microsoft.ContainerInstance/containerGroups/readme.md
- modules/Microsoft.ContainerRegistry/registries/readme.md
- modules/Microsoft.DataFactory/factories/readme.md
- modules/Microsoft.EventGrid/topics/readme.md
- modules/Microsoft.EventHub/namespaces/readme.md
- modules/Microsoft.Insights/privateLinkScopes/readme.md
- modules/Microsoft.KeyVault/vaults/readme.md
- modules/Microsoft.RecoveryServices/vaults/readme.md
- modules/Microsoft.ServiceBus/namespaces/readme.md
- modules/Microsoft.SignalRService/webPubSub/readme.md
- modules/Microsoft.Sql/servers/readme.md
- modules/Microsoft.Storage/storageAccounts/readme.md
- modules/Microsoft.Synapse/privateLinkHubs/readme.md
- modules/Microsoft.Synapse/workspaces/readme.md
- modules/Microsoft.Web/sites/readme.md
- utilities/src/apiSpecsList.json
Updating readme's to fix whitespace error from generator 
| Pipeline | 
| - |
| [![Batch: BatchAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.batch.batchaccounts.yml/badge.svg?branch=users%2Fcsidebotham%2Freadmeupdates-for-static-validation)](https://github.com/Azure/ResourceModules/actions/workflows/ms.batch.batchaccounts.yml) |
| [![CognitiveServices: Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml/badge.svg?branch=users%2Fcsidebotham%2Freadmeupdates-for-static-validation)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml) | 
| [![Storage: …
> [Modules]: Updating readme's from generator - whitespace errors fix

- modules/Microsoft.Authorization/policyDefinitions/deploy.bicep
- modules/Microsoft.Authorization/policyDefinitions/managementGroup/deploy.bicep
- modules/Microsoft.Authorization/policyDefinitions/managementGroup/readme.md
- modules/Microsoft.Authorization/policyDefinitions/readme.md
- modules/Microsoft.Authorization/policyDefinitions/subscription/deploy.bicep
- modules/Microsoft.Authorization/policyDefinitions/subscription/readme.md
Added the new mode type `Microsoft.Network.Data` used for Azure Virtual Network Manager - Network Groups that use dynamic memberships.
See [Policy Definitions Mode Type](https://learn.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#resource-provider-modes) and [Configuring Virtual Network Manager Network Groups using Azure Policy](https://learn.microsoft.com/en-us/azure/virtual-network-manager/concept-azure-policy-integration#policy-definition) for more details.
| Pipeline |
| - |
| [![Authorization: PolicyDefinitions](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policydefinitions.yml/badge.svg?branch=users%2Fahmad%2FpolicyDefModeUpdate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policydefinitions.ym …
> [Modules] Updated Azure Policy Definitions - mode to support 'Microsoft.Network.Data'

- modules/Microsoft.Authorization/policyAssignments/.test/mg.common/deploy.test.bicep
- modules/Microsoft.Authorization/policyAssignments/.test/rg.common/deploy.test.bicep
- modules/Microsoft.Authorization/policyAssignments/.test/sub.common/deploy.test.bicep
- modules/Microsoft.Authorization/policyAssignments/deploy.bicep
- modules/Microsoft.Authorization/policyAssignments/managementGroup/deploy.bicep
- modules/Microsoft.Authorization/policyAssignments/managementGroup/readme.md
- modules/Microsoft.Authorization/policyAssignments/readme.md
- modules/Microsoft.Authorization/policyAssignments/resourceGroup/deploy.bicep
- modules/Microsoft.Authorization/policyAssignments/resourceGroup/readme.md
- modules/Microsoft.Authorization/policyAssignments/subscription/deploy.bicep
- modules/Microsoft.Authorization/policyAssignments/subscription/readme.md
Closes #2524 
Update the Policy Assignments module API version to support Resource Selectors and Overrides.
- Updated API version to 2022-06-01
- Change the policy definition to an initiative to support the override parameter
| Pipeline |
| - |
|[![Authorization: PolicyAssignments](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyassignments.yml/badge.svg?branch=users%2Fahmad%2F2524_policyAssignmentUpdate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyassignments.yml) |
> [Modules] Update Azure Policy Assignment Module API to '2022-06-01', enabling the Resource Selectors and Overrides

- modules/Microsoft.Network/azureFirewalls/.test/hub/dependencies.bicep
- modules/Microsoft.Network/azureFirewalls/deploy.bicep
- modules/Microsoft.Network/azureFirewalls/readme.md
- Several smaller follow up updates to the Azure Firewall module
- Conditions
- Naming
- Metadata
- Readme 
| Pipeline |
| - |
| [![Network: AzureFirewalls](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.azurefirewalls.yml/badge.svg?branch=users%2Falsehr%2F2395_followUp)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.azurefirewalls.yml) |
> [Modules] Several smaller follow up updates to the Azure Firewall module

- .azuredevops/modulePipelines/ms.eventgrid.domains.yml
- .github/workflows/ms.eventgrid.domains.yml
- modules/Microsoft.EventGrid/domains/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.EventGrid/domains/.test/common/dependencies.bicep
- modules/Microsoft.EventGrid/domains/.test/common/deploy.test.bicep
- modules/Microsoft.EventGrid/domains/.test/min/deploy.test.bicep
- modules/Microsoft.EventGrid/domains/.test/pe/dependencies.bicep
- modules/Microsoft.EventGrid/domains/.test/pe/deploy.test.bicep
- modules/Microsoft.EventGrid/domains/deploy.bicep
- modules/Microsoft.EventGrid/domains/readme.md
- modules/Microsoft.EventGrid/domains/version.json
- settings.yml
I have added new module for Microsoft.EventGrid domains: https://learn.microsoft.com/en-us/azure/templates/microsoft.eventgrid/domains?pivots=deployment-language-bicep
This module is under Microsoft.EventGrid and manage large number of Event Grid topics related to the same application. It allows an event publisher to publish events to thousands of topics at the same time. Domains also give you authentication and authorization control over each topic so you can partition your tenants.
|  Pipeline  |
[![EventGrid: Domains](https://github.com/shaban-khan/ResourceModules/actions/workflows/ms.eventgrid.domains.yml/badge.svg?branch=main)](https://github.com/shaban-khan/ResourceModules/actions/workflo …
> [Modules] : New module Microsoft.EventGrid domains

- modules/Microsoft.CDN/profiles/.test/common/deploy.test.bicep
- modules/Microsoft.CDN/profiles/endpoints/origins/deploy.bicep
- modules/Microsoft.CDN/profiles/endpoints/origins/readme.md
- modules/Microsoft.CDN/profiles/readme.md
Fix for Conditional parameter description
| Pipeline |
| - |
| [![CDN: Profiles](https://github.com/Azure/ResourceModules/actions/workflows/ms.cdn.profiles.yml/badge.svg?branch=users%2Fcsidebotham%2Fcdn-readme-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cdn.profiles.yml) |
> [Modules] Microsoft.Cdn - Fixing Descriptions for Pipeline Validation

- docs/wiki/The library - Module design.md
- Expanded on the recommendations for `deploy.test.bicep` & `dependencies.bicep` files
> [Wiki] Updated docs recommendations & structure

- docs/wiki/The library - Module design.md
- modules/Microsoft.SignalRService/signalR/.test/common/deploy.test.bicep
- modules/Microsoft.Web/sites/.test/webAppCommon/deploy.test.bicep
Replace resourceGroupResources leftovers with nestedDependencies
Fixes Web Sites static validation
| Pipeline |
| - |
| [![Web: Sites](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml/badge.svg?branch=users%2Ferikag%2Fsites-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml) |
| [![SignalR Service: SignalR](https://github.com/Azure/ResourceModules/actions/workflows/ms.signalrservice.signalr.yml/badge.svg?branch=users%2Ferikag%2Fsites-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.signalrservice.signalr.yml) |
> [Fixes] `resourceGroupResources` leftover

- modules/Microsoft.Storage/storageAccounts/.test/common/deploy.test.bicep
- modules/Microsoft.Storage/storageAccounts/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/fileServices/shares/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/fileServices/shares/readme.md
- modules/Microsoft.Storage/storageAccounts/fileServices/shares/version.json
- modules/Microsoft.Storage/storageAccounts/fileServices/version.json
- modules/Microsoft.Storage/storageAccounts/readme.md
- modules/Microsoft.Storage/storageAccounts/version.json
Adding option to enable Large File Shares only on Standard LRS and ZRS storage skus, where the option is supported
Fixing typo for quota parameter name on file shares child module
Updating common test to use the new parameter
Version update for storage, fileservices and shares due to input parameter renaming
| Pipeline |
| - |
| [![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Ferikag%2F2570-largeshare)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) |
> [Modules] Storage account - Enable LargeFileShares feature

- modules/Microsoft.Network/applicationGateways/deploy.bicep
When you deploy the Application Gateway with the SKU of 'VpnGwAZ' then this means the Application Gateway doesn't support WAF. 
With the current implementation, when no WAF setting are provided to the module the parameter is still added to the resources but with a 'null' value. When you try to deploy the module in this way, you will get an error that WAF is not supported in the SKU, even if the property is 'null'.
Solved this by not including the WAF config tag to the service when the module parameter is empty. This way you can deploy the Application Gateway with SKU of 'VpnGwV2' not including any WAF.
No dependencies required for this change.  
No pipeline changes
> [Fixes] Solve issue with WAF config in Application Gateway

- .github/workflows/platform.ManageIssueForFailingPipelines.yml
- utilities/pipelines/manageIssueForFailingPipelines/New-IssuesForFailingPipelines.ps1
- utilities/pipelines/manageIssueForFailingPipelines/Set-IssueForWorkflow.ps1
Adding a new pipeline that will run once a day and create issues for failing pipelines. If the issue is already in place, then a comment will be added, if it is a newer failed run. If the pipeline succeeds and an issue is open, it will be closed. See #2287 
| Pipeline |
| - |
| [![create/update/close issues for failing pipelines in main](https://github.com/Azure/ResourceModules/actions/workflows/platform.ManageIssueForFailingPipelines.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/platform.ManageIssueForFailingPipelines.yml) |
> [CI Environment] Create/Comment/Close issues for failing pipelines

- docs/wiki/The CI environment - Publishing.md
- settings.yml
- utilities/pipelines/resourcePublish/Get-TemplateSpecsName.ps1
- utilities/pipelines/resourcePublish/Get-UniversalArtifactsName.ps1
- Implemented name shortening for TemplateSpecs artifacts
- Extended docs
- Removed some old code from the ADO Artifacts generation that would, for example, cut their name at 255 characters
Successfull RSV publishing with shortened name:
| Pipeline |
| - |
| [![KeyVault: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=users%2Falsehr%2F1172_publish)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml) |
| [![RecoveryServices: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml/badge.svg?branch=users%2Falsehr%2F1172_publish)](https://github.com/Azure/ResourceModu …
> [CI Environment] Implemented name shortening for TemplateSpecs artifacts & extended docs

- utilities/pipelines/resourcePublish/Get-TemplateSpecsName.ps1
- Update the TemplateSpec name generation to bypass the ProviderNamespace as it caused issues for some resource types
- Added some documentation
<details>
<summary>Test run</summary>
- ms.aad.domainservices
- ms.analysisservices.servers
- ms.apimanagement.service
- ms.apimanagement.service.apis
- ms.apimanagement.service.apis.policies
- ms.apimanagement.service.apiversionsets
- ms.apimanagement.service.authorizationservers
- ms.apimanagement.service.backends
- ms.apimanagement.service.caches
- ms.apimanagement.service.identityproviders
- ms.apimanagement.service.namedvalues
- ms.apimanagement.service.policies
- ms.apimanagement.service.portalsettings
- ms.apimanagement.service.products
- ms.apimanagement.service.products.apis
- ms.apimanagement.service.products.groups
- …
> [Fixes] Fixed template spec name gen & added documentation

- docs/wiki/Known issues.md
- modules/Microsoft.Network/networkManagers/deploy.bicep
- modules/Microsoft.Network/networkManagers/readme.md
Upon feedback from PG. Usage of the management scope for AVNM requires the 'Microsoft.Network' resource provider to be registered at the MG before creating the AVNM resource. This is done automatically via the Portal but needs to be done before running an AVNM code implementation. This PR updates documentation for usage guidance in both the wiki and the module.
Closes #2551 
| Pipeline |
| - |
|[![Network: Network Managers](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkmanagers.yml/badge.svg?branch=users%2Fahmad%2F2551_update_AVNM_Doc)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkmanagers.yml) |
Please delete options that are not …
> [Documentation] Update Network Manager documentation and Wiki known issues.

- modules/Microsoft.Storage/storageAccounts/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/readme.md
- Bumped version of Storage Account to most recent (2022-09-01)
- Added a couple of extra parameters:
- allowCrossTenantReplication
- allowedCopyScope
- allowSharedKeyAccess
- customDomainName
- customDomainUseSubDomainName
- defaultToOAuthAuthentication
- dnsEndpointType
- isLocalUserEnabled
| Pipeline |
| - |
| [![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Fmast%2FsaBump)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) |
> [Modules] Bump StorageAccount and add params

- modules/Microsoft.Compute/diskEncryptionSets/.test/common/dependencies.bicep
- modules/Microsoft.Compute/diskEncryptionSets/.test/common/deploy.test.bicep
- modules/Microsoft.Compute/diskEncryptionSets/deploy.bicep
- modules/Microsoft.Compute/diskEncryptionSets/readme.md
Closes #2632 
Updated the DES module to the latest API version to fix failing pipeline: 
Added support for:
- federatedClientId: Multi-tenant application client id to access key vault in a different tenant. 
- User Assigned Managed Identity support. Set the system assigned to default to true.
| Pipeline |
| - |
|[![Compute: DiskEncryptionSets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.diskencryptionsets.yml/badge.svg?branch=users%2Fahmad%2FpipelineFixes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.diskencryptionsets.yml) |
> [Modules] Updated Disk Encryption Set to latest published API version (2022-07-02)

- modules/Microsoft.Resources/resourceGroups/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Resources/resourceGroups/version.json
- utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
From: [Create Azure RBAC resources by using Bicep](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/scenarios-rbac#name)
_A role assignment's resource name must be a globally unique identifier (GUID).
It's a good practice to create a GUID that uses the scope, principal ID, and role ID together_
This PR is about using the resource ID instead of the resource name as the scope when calculating the RG role assignment name (GUID). This is also consistent with what done by nested_roleAssignment templates at resource scope for other modules.
This also fixes an error thrown by the Bicep compiler once upgrading Bicep to release 0.14.6
`Argument of type "null | string" is not assignable to parameter of type "string".bicep(BCP070)`
> For module/pipeline changes, please create and …
> [Fixes] Update rg roleAssignments name (guid) to use rg resourceID instead of rg name

- modules/Microsoft.CDN/profiles/endpoints/deploy.bicep
- modules/Microsoft.Network/bastionHosts/deploy.bicep
- modules/Microsoft.Network/virtualNetworkGateways/deploy.bicep
- modules/Microsoft.RecoveryServices/vaults/protectionContainers/deploy.bicep
Add `enableReferencedModulesTelemetry `variable and usage to disable by default telemetry on cross referenced resources
| Pipeline |
| - |
| [![CDN: Profiles](https://github.com/Azure/ResourceModules/actions/workflows/ms.cdn.profiles.yml/badge.svg?branch=users%2Ferikag%2Ftelemetry-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cdn.profiles.yml) |
> [Fixes] Disable referenced modules telemetry for a few modules missing the functionality

- modules/Microsoft.Network/bastionHosts/.test/custompip/deploy.test.bicep
- modules/Microsoft.Network/bastionHosts/readme.md
- modules/Microsoft.Sql/servers/.test/pe/deploy.test.bicep
Fixing naming, removing old `adp` ref
| Pipeline |
| - |
| [![Network: BastionHosts](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.bastionhosts.yml/badge.svg?branch=users%2Ferikag%2Fadp-cleanup)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.bastionhosts.yml) |
> [Fixes] Replace 'adp' naming prefix across modules

- modules/Microsoft.ContainerService/managedClusters/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/readme.md
Included the OIDC issuer url as output from the module. This is typically consumed by other services.
This solves #2608 
| Pipeline |
| - |
| |
> [Modules] Included OIDC issuer URL as output to the AKS module

- modules/Microsoft.Compute/galleries/.test/common/deploy.test.bicep
- modules/Microsoft.Compute/galleries/images/deploy.bicep
- modules/Microsoft.Compute/galleries/images/readme.md
- modules/Microsoft.Compute/galleries/readme.md
This change is to enable two additional features (Hibernation and Accelerated Networking) on Azure Compute Gallery Image Definitions. 
[![Compute: Galleries](https://github.com/shawntmeyer/CARML/actions/workflows/ms.compute.galleries.yml/badge.svg)](https://github.com/shawntmeyer/CARML/actions/workflows/ms.compute.galleries.yml)
> [Modules] Compute gallery image definition update

- modules/Microsoft.AAD/DomainServices/readme.md
- modules/Microsoft.ApiManagement/service/authorizationServers/readme.md
- modules/Microsoft.ApiManagement/service/identityProviders/readme.md
- modules/Microsoft.Compute/virtualMachineScaleSets/readme.md
- modules/Microsoft.Compute/virtualMachines/readme.md
- modules/Microsoft.DBforPostgreSQL/flexibleServers/readme.md
- modules/Microsoft.DevTestLab/labs/artifactSources/readme.md
- modules/Microsoft.KeyVault/vaults/secrets/readme.md
- modules/Microsoft.NetApp/netAppAccounts/readme.md
- modules/Microsoft.Network/localNetworkGateways/readme.md
- modules/Microsoft.Sql/managedInstances/readme.md
- modules/Microsoft.Sql/servers/readme.md
- modules/Microsoft.Sql/servers/securityAlertPolicies/readme.md
- modules/Microsoft.Web/staticSites/readme.md
- Regenerated all docs to account for new Bicep update
| Pipeline |
| - |
| [![Web: StaticSites](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.staticsites.yml/badge.svg?branch=users%2Falsehr%2Fsecurestring)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.staticsites.yml) |
> [Modules] Regenerated all docs to account for new Bicep update

- modules/Microsoft.Network/virtualNetworkGateways/.test/expressRoute/deploy.test.bicep
- modules/Microsoft.Network/virtualNetworkGateways/.test/vpn/dependencies.bicep
- modules/Microsoft.Network/virtualNetworkGateways/.test/vpn/deploy.test.bicep
- modules/Microsoft.Network/virtualNetworkGateways/deploy.bicep
- modules/Microsoft.Network/virtualNetworkGateways/natRules/deploy.bicep
- modules/Microsoft.Network/virtualNetworkGateways/natRules/readme.md
- modules/Microsoft.Network/virtualNetworkGateways/natRules/version.json
- modules/Microsoft.Network/virtualNetworkGateways/readme.md
closes #2669 
Updated virtual network gateway module to the latest API version. And added new properties and natRules child module, and updated test cases to leverage new properties
| Pipeline |
| - |
| [![Network: VirtualNetworkGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworkgateways.yml/badge.svg?branch=users%2Fahmad%2F2669_vnetGwApi)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworkgateways.yml)|
> [Modules] Updated Virtual Network Gateway Module API Version (2022-07-01)

- modules/Microsoft.Compute/diskEncryptionSets/.bicep/nested_keyVaultPermissions.bicep
- modules/Microsoft.Compute/diskEncryptionSets/.bicep/nested_managedIdentityReference.bicep
- modules/Microsoft.Compute/diskEncryptionSets/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Compute/diskEncryptionSets/.test/accessPolicies/dependencies.bicep
- modules/Microsoft.Compute/diskEncryptionSets/.test/accessPolicies/deploy.test.bicep
- modules/Microsoft.Compute/diskEncryptionSets/.test/common/dependencies.bicep
- modules/Microsoft.Compute/diskEncryptionSets/deploy.bicep
- modules/Microsoft.Compute/diskEncryptionSets/readme.md
- Enabled RBAC authorization of the Key used in the Disk Encryption Set. Before it was limited to RBAC.
> NOTE: The solution works with User-Assigned Identities only. The reason is that the System-Assigned identity is not yet available when the role assignment would need to happen
| Pipeline |
| - |
| [![Compute: DiskEncryptionSets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.diskencryptionsets.yml/badge.svg?branch=users%2Falsehr%2F2683_rbac)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.diskencryptionsets.yml) |
> Enabled RBAC role assignment for disk encrpytion set key

- bicepconfig.json
- modules/Microsoft.Authorization/policyAssignments/managementGroup/deploy.bicep
- modules/Microsoft.Compute/virtualMachines/readme.md
- modules/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
- modules/Microsoft.Network/localNetworkGateways/readme.md
- modules/Microsoft.RecoveryServices/vaults/backupConfig/readme.md
- modules/Microsoft.RecoveryServices/vaults/backupPolicies/readme.md
- modules/Microsoft.RecoveryServices/vaults/backupStorageConfig/readme.md
- modules/Microsoft.RecoveryServices/vaults/protectionContainers/protectedItems/readme.md
- modules/Microsoft.RecoveryServices/vaults/protectionContainers/readme.md
- modules/Microsoft.RecoveryServices/vaults/readme.md
- modules/Microsoft.RecoveryServices/vaults/replicationAlertSettings/readme.md
- modules/Microsoft.RecoveryServices/vaults/replicationFabrics/readme.md
- modules/Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/readme.md
- modules/Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectionContainerMappings/readme.md
- modules/Microsoft.RecoveryServices/vaults/replicationPolicies/readme.md
- modules/Microsoft.Storage/storageAccounts/readme.md
Replace missing occurrences of docs.microsoft.com links, causing static validation to fail for two modules
Regenerate readme files
| Pipeline |
| - |
| |
> [Fixes] Replace missing occurrences of docs.microsoft.com links and regenerated readmes

- modules/Microsoft.Network/applicationGateways/deploy.bicep
- modules/Microsoft.Network/applicationGateways/readme.md
Co-authored-by: Jayachandran Chandran Pillai @jayanchpd #2724
Did not update to 2022-09-01 as the Azure Resource reference is not updated with this info. Sorry for implementing this before you had the time @ahmadabdalla, but we needed it for a solution.
- Added 2 options for `sslPolicyMinProtocolVersion` parameter
- Added 2 options for `sslPolicyName` parameter
- Added 1 option for `sslPolicyType` parameter
- Updated API version
- Solves #2699
Added functionality with no code change is the following property as a result of the version bump.
```bicep
sslProfiles: [
{
properties: {
clientAuthConfiguration: {
verifyClientRevocation: 'string'
}
}
}
]
```
| Pipeline |
| - |
| [![Network - ApplicationGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationgatew …
> [Modules] Updated Application Gateway module to the latest API Version (2022-07-01)

- modules/Microsoft.Insights/dataCollectionRules/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Insights/dataCollectionRules/.test/linux/deploy.test.bicep
- modules/Microsoft.Insights/dataCollectionRules/.test/min/deploy.test.bicep
- modules/Microsoft.Insights/dataCollectionRules/.test/windows/deploy.test.bicep
- modules/Microsoft.Insights/dataCollectionRules/readme.md
This PR resolves #2776 and fixes the module pipeline failing due to a wrong sampling frequency.
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status/Modules/Insights%20-%20DataCollectionRules?branchName=users%2Fkrbar%2F2776-fixing-datacollectionrules)](https://dev.azure.com/carml/CARML/_build/latest?definitionId=131&branchName=users%2Fkrbar%2F2776-fixing-datacollectionrules) |
> [Modules] Fixing failing dataCollectionRules pipeline

- modules/Microsoft.Sql/servers/.test/common/deploy.test.bicep
- modules/Microsoft.Sql/servers/databases/backupLongTermRetentionPolicies/deploy.bicep
- modules/Microsoft.Sql/servers/databases/backupLongTermRetentionPolicies/readme.md
- modules/Microsoft.Sql/servers/databases/backupLongTermRetentionPolicies/version.json
- modules/Microsoft.Sql/servers/databases/backupShortTermRetentionPolicies/deploy.bicep
- modules/Microsoft.Sql/servers/databases/backupShortTermRetentionPolicies/readme.md
- modules/Microsoft.Sql/servers/databases/backupShortTermRetentionPolicies/version.json
- modules/Microsoft.Sql/servers/databases/deploy.bicep
- modules/Microsoft.Sql/servers/databases/readme.md
- modules/Microsoft.Sql/servers/deploy.bicep
- modules/Microsoft.Sql/servers/readme.md
The change adds support for configuring short and long term backup retention policies for Azure SQL Databases.
Default values are fetched from a deployment through portal without defining any policy.
retentionDays: 7
diffBackupIntervalInHours: 24
| Pipeline |
| - |
| |
> [Modules] Support for configuring backup retention policies for Azure SQL Database

- modules/Microsoft.Compute/images/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Compute/images/.test/common/dependencies.bicep
- modules/Microsoft.Compute/images/.test/common/deploy.test.bicep
- modules/Microsoft.Compute/images/deploy.bicep
- modules/Microsoft.Compute/images/readme.md
This PR resolves #2828  and introduces following improvements:
- replaced a non-existing source image sku for the "Common" test case (causing the workflow to fail): 
- old: `Windows-10` - `19h2-evd`
- new: `Windows-11` - `win11-21h2-avd`
- updated API versions in the test deployments
- updated API versions of the `image` resource
| Pipeline |
| - |
| [![Compute - Images](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.images.yml/badge.svg?branch=users%2Fkrbar%2F2828-compute-images-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.images.yml) |
> [Modules] Updated  Microsoft.Compute/images: API versions, image sku

- modules/Microsoft.Compute/disks/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Compute/disks/.test/common/deploy.test.bicep
- modules/Microsoft.Compute/disks/.test/image/deploy.test.bicep
- modules/Microsoft.Compute/disks/.test/import/dependencies.bicep
- modules/Microsoft.Compute/disks/.test/import/deploy.test.bicep
- modules/Microsoft.Compute/disks/.test/min/deploy.test.bicep
- modules/Microsoft.Compute/disks/deploy.bicep
- modules/Microsoft.Compute/disks/readme.md
This PR resolves #2827 and introduces following improvements:
- replaced a non-existing source image sku for the "Import" test case: 
- old: `Windows-10` - `19h2-evd`
- new: `Windows-11` - `win11-21h2-avd`
- updated API versions of the test deployments
- updated API versions of the `disk` resource and related improvements
- added new disk sku: `PremiumV2_LRS`
- added new, non-breaking parameters:
- `architecture`
- `optimizedForFrequentAttach`
> Note: two additional parameters included in the api version [2022-07-02](https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/2022-07-02/disks?pivots=deployment-language-bicep) were not included in the module update as they appear to be in preview and/or are not supported in the test subscription and could not be tested: …
> [Modules] Updated  Microsoft.Compute/disks: API versions, image sku, new properties

- modules/Microsoft.KeyVault/vaults/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.KeyVault/vaults/.test/common/deploy.test.bicep
- modules/Microsoft.KeyVault/vaults/deploy.bicep
- modules/Microsoft.KeyVault/vaults/keys/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.KeyVault/vaults/keys/deploy.bicep
- modules/Microsoft.KeyVault/vaults/keys/readme.md
- modules/Microsoft.KeyVault/vaults/readme.md
- modules/Microsoft.KeyVault/vaults/secrets/.bicep/nested_roleAssignments.bicep
This PR resolves #2824 and adds rotation policy for the keys.
| Pipeline |
| - |
| [![KeyVault - Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=users%2Fkrbar%2F2824-kv-key-rotation-policy)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml) |
> [Modules] Key Vault - Added support for key key auto-rotation

- modules/Microsoft.DataFactory/factories/.test/common/deploy.test.bicep
- modules/Microsoft.DataFactory/factories/deploy.bicep
- modules/Microsoft.DataFactory/factories/readme.md
Add support for ADF GlobalParameter property
| Pipeline |
| - |
|[![DataFactory - Factories](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.datafactory.factories.yml/badge.svg?branch=feature%2Fadf-globalparameters)](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.datafactory.factories.yml)|
> Add support for ADF GlobalParameter

- modules/Microsoft.KeyVault/vaults/version.json
- utilities/pipelines/resourcePublish/Publish-ModuleToUniversalArtifactsFeed.ps1
- Updated the reference to the module's deploy file to its parent folder
Downloaded artifact
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status/Modules/KeyVault%20-%20Vaults?branchName=users%2Falsehr%2F2829_publish)](https://dev.azure.com/carml/CARML/_build/latest?definitionId=46&branchName=users%2Falsehr%2F2829_publish) |
> [Fixes] Fix target-path reference for Universal Package Publish

- modules/Microsoft.Sql/servers/.test/common/deploy.test.bicep
- modules/Microsoft.Sql/servers/deploy.bicep
- modules/Microsoft.Sql/servers/readme.md
Adds the restrictOutboundNetworkAccess parameter to Microsoft.Sql/servers - https://learn.microsoft.com/en-us/azure/templates/microsoft.sql/servers?pivots=deployment-language-bicep
> [Modules] Added restrictOutboundNetworkAccess to Microsoft.Sql/servers

- modules/Microsoft.Resources/tags/.test/min/deploy.test.bicep
- modules/Microsoft.Resources/tags/.test/sub/deploy.test.bicep
- modules/Microsoft.Resources/tags/readme.md
- modules/Microsoft.Synapse/workspaces/.test/common/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwsai/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwuai/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/managedvnet/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/min/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/readme.md
This PR resolves #2810 and adds the parameter `enableDefaultTelemetry` wherever it's missing in the test files. Two modules and 7 test files are affected:
- Microsoft.Resources/tags
- Microsoft.Synapse/workspaces
| Pipeline |
| - |
| [![Resources - Tags](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.tags.yml/badge.svg?branch=users%2Fkrbar%2Ftelemetry-fixes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.tags.yml) |
| [![Synapse - Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml/badge.svg?branch=users%2Fkrbar%2Ftelemetry-fixes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml) |
> [Modules] Added missing 'enableDefaultTelemetry' param in test files

- modules/Microsoft.Resources/resourceGroups/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Resources/resourceGroups/deploy.bicep
Simplify the inputs required for RG RBAC. As the resource ID is already provided in the scope of the deployment, the default is to get the current resourceGroup id.
| Pipeline |
| - |
| [![Resources - ResourceGroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.resourcegroups.yml/badge.svg?branch=mast%2Ffeat%2Frg_rbac_cleanup)](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.resourcegroups.yml) |
> [Modules] Simplify roleAssignment implementation for Resource Group

- utilities/tools/Set-ModuleReadMe.ps1
- utilities/tools/helper/ConvertTo-OrderedHashtable.ps1
- To avoid further issues of peers that want to use the script but have issues as they're using e.g. PowerShell version 7.2.7, this change enforces 7.3 (which contains the breaking change for the `ConvertFrom-Json -AsHashTable` invocation)
- Tested locally, no changes to the result
> [Utilities] Enforce PS7.3 where required

- modules/Microsoft.MachineLearningServices/workspaces/.test/encr/dependencies.bicep
- modules/Microsoft.MachineLearningServices/workspaces/deploy.bicep
- Reduced the permissions of the Encryption Test of the ML workspace from the original `Key Vault Administrator` to `Key Vault Crypto User` with scope `key` as it does not require any more permissions. This is also closer aligned to similar tests for other modules.
- Added a comment to one of the properties that turned out to be NOT idempotent (and pretty weird too)
| Pipeline |
| - |
| [![MachineLearningServices - Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml/badge.svg?branch=users%2Falsehr%2FmlSharedPeTest)](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml) |
Please delete …
> [Modules] Reduced permissions of ML encr test

- modules/Microsoft.ContainerService/managedClusters/deploy.bicep
When deploying the current version of managedCluster and you enable some of the addons, and later remove them using the module, you get an error for reconfiguring addonProfiles as the format is incorrectly formatted. This PR fixes this where its sets the expected value of `null` on config for the profiles which are disabled.
| Pipeline |
| - |
| [![ContainerService - ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Fmast%2FmanagedClusterFixAddonProfiles)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml) |
> [Modules] managedClusters - Fix a bug for addonprofiles

- modules/Microsoft.ContainerService/managedClusters/.test/azure/deploy.test.bicep
- modules/Microsoft.ContainerService/managedClusters/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/readme.md
- Add support for enabling Open Service Mesh
- Updated the Azure test to include enabling the open service mesh addon.
| Pipeline |
| - |
| [![ContainerService - ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Fmast%2FAKSosm)](https://github.com/Azure/ResourceModules/actions/runs/4372001076) |
> [Modules] managedCluster - Add support for enabling Open Service Mesh

- modules/Microsoft.Compute/diskEncryptionSets/.test/accessPolicies/deploy.test.bicep
- modules/Microsoft.Compute/diskEncryptionSets/.test/common/deploy.test.bicep
- modules/Microsoft.Compute/diskEncryptionSets/readme.md
- modules/Microsoft.EventGrid/eventSubscriptions/.test/common/deploy.test.bicep
- modules/Microsoft.EventGrid/eventSubscriptions/readme.md
Closes #2910 
Closes #2900
| Pipeline |
| - |
| [![EventGrid - Event Subscriptions](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventgrid.eventsubscriptions.yml/badge.svg?branch=users%2Ferikag%2Fpsrule-fix-readmes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventgrid.eventsubscriptions.yml) |
| [![Compute - DiskEncryptionSets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.diskencryptionsets.yml/badge.svg?branch=users%2Ferikag%2Fpsrule-fix-readmes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.diskencryptionsets.yml) |
> [Fixes] Diskencryptionsets and Eventgridsubscriptions tags update

- modules/Microsoft.Automation/automationAccounts/.test/common/deploy.test.bicep
- modules/Microsoft.Automation/automationAccounts/readme.md
Automation account schedule frequency update as previous setting started causing pipeline failure
Closes #2899 
| Pipeline |
| - |
| [![Automation - AutomationAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.automation.automationaccounts.yml/badge.svg?branch=users%2Ferikag%2Fautoacc-freq)](https://github.com/Azure/ResourceModules/actions/workflows/ms.automation.automationaccounts.yml) |
> [Fixes] Automation account schedule frequency update

- modules/Microsoft.Storage/storageAccounts/deploy.bicep
The parameter is not passed on as expected, but seems to be a copy/paste error.
In effect I cannot enable the authorizedKeys for the local user.
need to come back after it has run
| Pipeline |
| - |
| |
> [Fixes] Storage Account Local User : Pass on correct parameter

- utilities/tools/Invoke-PipelinesForBranch.ps1
- Fixed a minor utility issue due to a parameter type change
> [Fixes] Fixed a minor utility issue due to a parameter type change

- modules/Microsoft.App/managedEnvironments/.test/common/deploy.test.bicep
- modules/Microsoft.App/managedEnvironments/readme.md
Closes #3018 
Changed our test case to use the 'Consumption SKU' instead of the 'Premium' as the premium seems to have some support issues. Although the premium SKU is still mentioned in the Template Doc: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2022-10-01/managedenvironments?pivots=deployment-language-bicep#environmentskuproperties
| Pipeline |
| - |
| [![App - Managed Environments](https://github.com/Azure/ResourceModules/actions/workflows/ms.app.managedenvironments.yml/badge.svg?branch=users%2Fahmad%2F3018_capp)](https://github.com/Azure/ResourceModules/actions/workflows/ms.app.managedenvironments.yml)|
> [Modules] Updated SKU for the Managed Environment Test

- docs/wiki/Getting started - Scenario 1 Consume library.md
Added a PowerShell script example for mass loading modules to a Bicep registry
> [Wiki] Added a PowerShell script example to frontload all supported publish locations with all modules

- modules/Microsoft.Storage/storageAccounts/.test/common/deploy.test.bicep
- modules/Microsoft.Storage/storageAccounts/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/readme.md
Added support for SAS Policy Parameters. Fix for Issue #2997 with the help of @sdah0414.
[![Storage - StorageAccounts](https://github.com/shawntmeyer/CARML/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=StorageAccounts-sasPolicySupport)](https://github.com/shawntmeyer/CARML/actions/workflows/ms.storage.storageaccounts.yml)
> [Modules] StorageAccounts - new feature - sasPolicy

- .github/CODEOWNERS
As the names of the teams have been renamed, the auto assignment on reviewers in PRs is not working. This attempts to fix that so that reviewers are again auto assigned.
| Pipeline |
| - |
| N/A |
> [CI Environment] CODEOWNERS - Fix codeowners based on team rename

- modules/Microsoft.Sql/servers/.test/common/deploy.test.bicep
- modules/Microsoft.Sql/servers/deploy.bicep
- modules/Microsoft.Sql/servers/encryptionProtector/deploy.bicep
- modules/Microsoft.Sql/servers/encryptionProtector/readme.md
- modules/Microsoft.Sql/servers/encryptionProtector/version.json
- modules/Microsoft.Sql/servers/readme.md
- settings.yml
I added the missing encryption protector for SQL Server. #1980 
This should enable to apply TDE on Databases with a custom key. 
However this is my first contribution, in case I missed anything please raise your voice. 
| Pipeline |
| - |
| [![Sql - Servers](https://github.com/jhueppauff/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg)](https://github.com/jhueppauff/ResourceModules/actions/workflows/ms.sql.servers.yml)|
> [Modules] Added SQL Protector for SQL Server

- .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
- .azuredevops/pipelineTemplates/jobs.validateModulePester.yml
- .github/actions/templates/validateModuleDeployment/action.yml
- .github/actions/templates/validateModulePester/action.yml
- docs/wiki/The CI environment - Deployment validation.md
- docs/wiki/The CI environment - Token replacement.md
- modules/Microsoft.Network/azureFirewalls/readme.md
- modules/Microsoft.Network/bastionHosts/readme.md
- utilities/pipelines/tokensReplacement/Convert-TokensInFileList.ps1
- utilities/tools/Test-ModuleLocally.ps1
- utilities/tools/Test-NamePrefixAvailability.ps1
Closes #3081 
| Pipeline |
| - |
| [![Compute - ProximityPlacementGroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.proximityplacementgroups.yml/badge.svg?branch=users%2Ferikag%2Fdeploymentspid)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.proximityplacementgroups.yml) |
> [CI Environment] Remove implementation retrieving deploymentSpId

- modules/Microsoft.Compute/availabilitySets/.test/common/deploy.test.bicep
- modules/Microsoft.Compute/availabilitySets/deploy.bicep
- modules/Microsoft.Compute/availabilitySets/readme.md
- modules/Microsoft.ContainerService/managedClusters/.test/azure/dependencies.bicep
- modules/Microsoft.ContainerService/managedClusters/.test/azure/deploy.test.bicep
- modules/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/agentPools/readme.md
- modules/Microsoft.ContainerService/managedClusters/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/readme.md
- Updated more parameters
- Added test case
| Pipeline |
| - |
| [![ContainerService - ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Falsehr%2FparamReduction)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml) |
| [![Compute - AvailabilitySets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.availabilitysets.yml/badge.svg?branch=users%2Falsehr%2FparamReduction)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.availabilitysets.yml) |
> [Modules] Updated more parameters & added test case

- modules/Microsoft.Synapse/workspaces/.test/common/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/common/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwsai/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwsai/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwuai/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwuai/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/managedvnet/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/managedvnet/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/min/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/min/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/deploy.bicep
- modules/Microsoft.Synapse/workspaces/readme.md
- The field `resourceId` was added in the API which wasn't updated in the module. When the module is used, it is showing errors as it couldn't find the `resourceId` which is expected by the API.
| Pipeline |
| - |
| |
> [Modules] Synapse workspaces Added support for `resourceId` #2613

- modules/Microsoft.Synapse/workspaces/.test/common/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/common/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwsai/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwsai/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwuai/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwuai/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/managedvnet/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/managedvnet/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/min/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/min/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/deploy.bicep
- modules/Microsoft.Synapse/workspaces/readme.md
The field `resourceId` was added in the API which wasn't updated in the module. When the module is used, it is showing errors as it couldn't find the `resourceId` which is expected by the API.
Based on PR #2825 with addressed comments
| Pipeline |
| - |
| [![Synapse - Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml/badge.svg?branch=users%2Falsehr%2F2825_merge)](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml) |
> [Modules] Synapse workspaces Added support for resourceId

- modules/Network/applicationGateways/main.bicep
Per https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules#microsoftnetwork, it's 80 characters.
> [Modules] Correct max length of Application Gateway name

- modules/CognitiveServices/accounts/.bicep/nested_roleAssignments.bicep
- modules/CognitiveServices/accounts/.test/common/main.test.bicep
- modules/CognitiveServices/accounts/.test/encr/main.test.bicep
- modules/CognitiveServices/accounts/.test/min/main.test.bicep
- modules/CognitiveServices/accounts/.test/speech/main.test.bicep
- modules/CognitiveServices/accounts/README.md
- modules/CognitiveServices/accounts/main.bicep
PR resolves #3097 by:
- setting `restrictOutboundNetworkAccess=false` for the Customer Managed Keys test case. Otherwise the key cannot be accessed
- update of the API versions
| Pipeline |
| - |
| [![CognitiveServices - Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml/badge.svg?branch=users%2Fkrbar%2F3097-cognitiveservices-accounts)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml) |
> [Modules] Cognitive Services accounts - CMK fix + API update

- modules/db-for-postgre-sql/flexible-servers/.test/public/main.test.bicep
- modules/db-for-postgre-sql/flexible-servers/README.md
- modules/db-for-postgre-sql/flexible-servers/main.bicep
Add missing diagnostic logs for PostgreSQL Flexible servers.
[![DbForPostgreSQL - FlexibleServers](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml/badge.svg?branch=fix%2Fpostgresql-diag)](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml)
> Update Diagnostic Settings for PostgreSql Flexible Servers diag

- modules/insights/components/.test/common/dependencies.bicep
- modules/insights/components/.test/common/main.test.bicep
- modules/insights/components/README.md
- modules/insights/components/main.bicep
add AppInsights Diagnostic Settings. Diagnostic settings for App Insights is supported for the new Workspace-based AppInsights (which is the only flavour that the CARML module supports).
[![Insights - Components](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.insights.components.yml/badge.svg?branch=feature%2FappInsights-diag)](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.insights.components.yml)
> [Modules] Add AppInsights Diagnostic Settings

- modules/storage/storage-accounts/main.bicep
This will fix https://github.com/Azure/ResourceModules/issues/3106
only send the nfsv3 when enabled
cannot be changed or added with a value of False if the storage account wasn't creating with it.
this is fixing an breaking change
| Pipeline |
| - |
|[![Storage - StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Fahmad%2F3290_storage)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) |
> [Modules] storage account module : conditional nfsv3 parameter 

- modules/purview/accounts/.test/common/main.test.bicep
- modules/sql/servers/.test/secondary/main.test.bicep
- modules/sql/servers/README.md
Closes #3311 
Closes #3310
| Pipeline |
| - |
| [![Purview - Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.purview.accounts.yml/badge.svg?branch=users%2Ferikag%2Ftemplate_fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.purview.accounts.yml) |
| [![Sql - Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Ferikag%2Ftemplate_fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml) |
> [Fixes] Fix sql and purview tests

- modules/health-bot/health-bots/.bicep/nested_roleAssignments.bicep
- modules/health-bot/health-bots/.test/common/dependencies.bicep
- modules/health-bot/health-bots/.test/common/main.test.bicep
- modules/health-bot/health-bots/.test/min/main.test.bicep
- modules/health-bot/health-bots/README.md
- modules/health-bot/health-bots/main.bicep
Closes #3341 
Updated to latest API version and added support for user identities
| Pipeline |
| - |
| [![HealthBot - HealthBots](https://github.com/Azure/ResourceModules/actions/workflows/ms.healthbot.healthbots.yml/badge.svg?branch=users%2Fahmad%2F3341_healthBot)](https://github.com/Azure/ResourceModules/actions/workflows/ms.healthbot.healthbots.yml)|
> [Modules] Updated Healthbot Module to latest API version and added support for user identities

- modules/operational-insights/workspaces/README.md
- modules/operational-insights/workspaces/main.bicep
Closes #3332 
Updated SKU Name to align with the public documentation.
Added support for capacity reservation SKU and options
**NOTE**: Although tested in isolation and it is successful. I am not adding test cases for these parameters just in case if it causes charges on Azure subscriptions
| Pipeline |
| - |
|[![OperationalInsights - Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.operationalinsights.workspaces.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.operationalinsights.workspaces.yml) |
> [Modules] Added support for Capacity Reservation for the Log Analytics Workspace Module

- modules/document-db/database-accounts/README.md
Closes #3342 
In the recent merge of the documentation updates, the document DB readme was set to empty. This PR restores it again.
**NOTE**: For some reason my Bicep build process locally did not work and set this module Readme to empty. I ran the readme generator on my Linux Codespace, which worked.
| Pipeline |
| - |
| [![DocumentDB - DatabaseAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml/badge.svg?branch=users%2Fahmad%2FcosmosDB_docremediate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml)|
> [Modules] Restored Document DB Readme after recent wider Readme updates

- modules/sql/servers/main.bicep
WhatIf deploymens of microsoft.sql/servers/ does not show output for databases if "server.location" is used. Changing it to "location" (which server.location is built from) solves the issue. (Perhaps related to https://github.com/Azure/arm-template-whatif/issues/157 ?)
That being said it could be hard-coded to `location: location` instead of `location: contains(database, 'location') ? database.location : location` as it is not possible to deploy a database in a different location than the server, so it is a confusing parameter to have.
| Pipeline |
| - |
| |
> [Fixes] Fixed WhatIf output on databases when nested deploying using server module

- modules/api-management/service/apis/README.md
- modules/api-management/service/apis/main.bicep
- Update apim api type allowed values to include graphql and websocket.
[![ApiManagement - Service](https://github.com/clarked-msft/ResourceModules/actions/workflows/ms.apimanagement.service.yml/badge.svg)](https://github.com/clarked-msft/ResourceModules/actions/workflows/ms.apimanagement.service.yml)
| Pipeline |
| - |
| |
- [x ] Bugfix (non-breaking change which fixes an issue)
- [x ] Update to documentation
> [Modules] API Management allowed values update

- modules/event-grid/system-topics/main.bicep
The code is not checking the property on the item being looped over
systemtopic subs
| Pipeline |
| - |
| |
> [Modules] Update Event Grid Module - Fix typo, not checking on loop-item

- modules/network/nat-gateways/main.bicep
…atGatewayPublicIpAddress=true"
Error Encountered: PublicIPAddress Not Found- In the main.bicep file, if we set the parameter value of natGatewayPublicIpAddress to true, the module throws an error indicating that the publicipaddress cannot be found.
The module in main.bicep throws an error stating that the publicipaddress is not found when we set the parameter value of natGatewayPublicIpAddress to true. To resolve this issue, it is necessary to include a dependency condition in the natgateway resource, ensuring it depends on the publicipaddress module.
| Pipeline |
| - |
| |
> [Fixes] Updated a "depends on" condtion on natgateway for pip address

- utilities/pipelines/resourcePublish/Publish-ModuleToPrivateBicepRegistry.ps1
Re-Enabled PBR overwrite
```PowerShell
PS C:\dev\ip\Azure-ResourceModules\ResourceModules> . 'C:\dev\ip\Azure-ResourceModules\ResourceModules\utilities\pipelines\resourcePublish\Publish-ModuleToPrivateBicepRegistry.ps1'
VERBOSE: Performing the operation "Publish" on target "Private bicep registry entry [bicep/modules/aad.domain-services] version [0.1] to registry [adpsxxazacrx001]".
The module "br:adpsxxazacrx001.azurecr.io/bicep/modules/aad.domain-services:0.1" already exists in registry. Use --force to overwrite the existing module.
VERBOSE: Publish complete
PS C:\dev\ip\Azure-ResourceModules\ResourceModules> . 'C:\dev\ip\Azure-ResourceModules\ResourceModules\utilities\pipelines\resourcePubli …
```
> [CI Environment] Re-Enabled PBR overwrite

- modules/data-factory/factories/README.md
- modules/data-factory/factories/main.bicep
- modules/data-factory/factories/main.json
Closes #3419 
Connecting ADF to GitHub Enterprise Server requires an additional `hostName` argument to the `repoConfiguration`.
| Pipeline |
| - |
| |
> [Modules] Azure Data Factory: Support for GitHub Enterprise Server

- modules/data-factory/factories/README.md
- modules/data-factory/factories/main.bicep
- modules/data-factory/factories/main.json
This PR resolves #3436 and adds the `disablePublish` property to the Repo Configuration of the Data Factory.
| Pipeline |
| - |
| [![DataFactory - Factories](https://github.com/Azure/ResourceModules/actions/workflows/ms.datafactory.factories.yml/badge.svg?branch=users%2Fkrbar%2F3436-adf-disablepublish)](https://github.com/Azure/ResourceModules/actions/workflows/ms.datafactory.factories.yml) |
> [Modules] Data Factory: Added gitDisablePublish parameter

- modules/network/network-managers/.bicep/nested_roleAssignments.bicep
- modules/network/network-managers/.test/common/dependencies.bicep
- modules/network/network-managers/.test/common/main.test.bicep
- modules/network/network-managers/README.md
- modules/network/network-managers/connectivity-configurations/README.md
- modules/network/network-managers/connectivity-configurations/main.bicep
- modules/network/network-managers/connectivity-configurations/main.json
- modules/network/network-managers/main.bicep
- modules/network/network-managers/main.json
- modules/network/network-managers/network-groups/README.md
- modules/network/network-managers/network-groups/main.bicep
- modules/network/network-managers/network-groups/main.json
- modules/network/network-managers/network-groups/static-members/README.md
- modules/network/network-managers/network-groups/static-members/main.bicep
- modules/network/network-managers/network-groups/static-members/main.json
- modules/network/network-managers/scope-connections/README.md
- modules/network/network-managers/scope-connections/main.bicep
- modules/network/network-managers/scope-connections/main.json
- modules/network/network-managers/security-admin-configurations/README.md
- modules/network/network-managers/security-admin-configurations/main.bicep
- modules/network/network-managers/security-admin-configurations/main.json
- modules/network/network-managers/security-admin-configurations/rule-collections/README.md
- modules/network/network-managers/security-admin-configurations/rule-collections/main.bicep
- modules/network/network-managers/security-admin-configurations/rule-collections/main.json
- modules/network/network-managers/security-admin-configurations/rule-collections/rules/README.md
- modules/network/network-managers/security-admin-configurations/rule-collections/rules/main.bicep
- modules/network/network-managers/security-admin-configurations/rule-collections/rules/main.json
This PR resolves #3272 (failed workflow runs) and updates the NetworkManager module (and child modules) to the newest API versions.
| Pipeline |
| - |
| [![Network - Network Managers](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkmanagers.yml/badge.svg?branch=users%2Fkrbar%2F3272-network-managers-api)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkmanagers.yml) |
> [Modules] Updated the NetworkManager module to the newest API

- modules/event-hub/namespaces/.test/common/main.test.bicep
- modules/event-hub/namespaces/README.md
- modules/event-hub/namespaces/eventhubs/.bicep/nested_roleAssignments.bicep
- modules/event-hub/namespaces/eventhubs/main.json
- modules/event-hub/namespaces/main.json
This PR resolves #3439 by generating role assignment names, which are unique within an EventHub workspace.
| Pipeline |
| - |
| [![EventHub - Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml/badge.svg?branch=users%2Fkrbar%2F3439-eventhub-role-assignments-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml) |
> [Modules] Fixed EventHub role assignment naming issues

- utilities/pipelines/staticValidation/helper/helper.psm1
- utilities/pipelines/staticValidation/module.tests.ps1
- utilities/tools/helper/Get-PipelineFileName.ps1
Closes #3476
Update pester tests checking ADO, GH and cross references pipeline existence.
Leveraging apispecs to get correct naming for yml files
Works with both singular and plural module folder names, hence can be merged to main
| Pipeline |
| - |
| [![Storage - StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Favm%2Fpester_pipelines)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) |
| [![ContainerRegistry - Registries](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml/badge.svg?branch=users%2Favm%2Fpester_pipelines)](https …
> [CI environment] Get yml pipeline name based on specs resourcetype

- utilities/pipelines/resourceDeployment/New-TemplateDeployment.ps1
- utilities/pipelines/resourceDeployment/Test-TemplateDeployment.ps1
- utilities/pipelines/resourcePublish/Get-ModulesMissingFromPrivateBicepRegistry.ps1
- utilities/pipelines/resourcePublish/Get-ModulesMissingFromTemplateSpecsRG.ps1
- utilities/pipelines/resourcePublish/Get-ModulesMissingFromUniversalArtifactsFeed.ps1
- utilities/pipelines/resourcePublish/Get-ModulesToPublish.ps1
- utilities/pipelines/resourcePublish/Get-PrivateRegistryRepositoryName.ps1
- utilities/pipelines/resourcePublish/Get-TemplateSpecsName.ps1
- utilities/pipelines/resourcePublish/Get-UniversalArtifactsName.ps1
- utilities/pipelines/resourcePublish/Publish-ModuleToPrivateBicepRegistry.ps1
- utilities/pipelines/resourcePublish/Publish-ModuleToTemplateSpecsRG.ps1
- utilities/pipelines/resourcePublish/Publish-ModuleToUniversalArtifactsFeed.ps1
- utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
- utilities/pipelines/sharedScripts/Get-ModuleTestFileList.ps1
- utilities/pipelines/sharedScripts/Get-NestedResourceList.ps1
- utilities/pipelines/staticValidation/Set-PesterGitHubOutput.ps1
- utilities/tools/ConvertTo-ARMTemplate.ps1
- utilities/tools/Get-CrossReferencedModuleList.ps1
- utilities/tools/Set-ModuleReadMe.ps1
- utilities/tools/Test-ModuleLocally.ps1
- utilities/tools/Update-RoleAssignmentList.ps1
- utilities/tools/helper/Get-ModulesAsMarkdownTable.ps1
- Updated utility references to new naming scheme
> [Utilities] Updated utility references to new naming scheme

- docs/wiki/The library - Module design.md
- docs/wiki/The library - Module usage.md
- Updated 'Module Library' section to latest
> [Wiki] Updated 'Module Library' section to latest

- modules/authorization/policy-assignment/.test/mg.common/main.test.bicep
- modules/authorization/policy-assignment/.test/mg.min/main.test.bicep
- modules/authorization/policy-assignment/.test/rg.common/main.test.bicep
- modules/authorization/policy-assignment/.test/rg.min/main.test.bicep
- modules/authorization/policy-assignment/.test/sub.common/main.test.bicep
- modules/authorization/policy-assignment/.test/sub.min/main.test.bicep
- modules/authorization/policy-assignment/README.md
Policy assignment test updates for PSRule requirements:
- Add assignedby metadata on existing metadata blocks
- Setname, description and metablock with assigned identity in min files
closes #2667 
| Pipeline |
| - |
| [![Authorization - PolicyAssignments](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyassignments.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyassignments.yml)|
> [PSRule] Fix Rule Azure.Policy.AssignmentAssignedBy #2667

- utilities/pipelines/resourceRemoval/helper/Get-DeploymentTargetResourceList.ps1
- utilities/pipelines/resourceRemoval/helper/Remove-Deployment.ps1
- Updated deployment search to not prematurely throw an exception if a deployment name does not yield deployed resources
- Currently, the logic searches the deployment name until the timeout is reached and throws an exception if no deployments are found (which is an issue if runnning, for example, retries)
- Instead it should then continue with the next name and only throw an exception if no deployment is found after checking all names
| Pipeline |
| - |
| [![Network - NetworkInterfaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkinterfaces.yml/badge.svg?branch=users%2Falsehr%2FadjustDeplSearchLogic)](https://github.com/Azure/ResourceModules/actions/workflows/m …
> [Fixes] Update deployment search to not prematurely throw an exception

- .azuredevops/modulePipelines/ms.network.frontdoorwebapplicationfirewallpolicies.yml
- .github/workflows/ms.network.frontdoorwebapplicationfirewallpolicies.yml
- modules/network/front-door-web-application-firewall-policy/.bicep/nested_roleAssignments.bicep
- modules/network/front-door-web-application-firewall-policy/.test/common/main.test.bicep
- modules/network/front-door-web-application-firewall-policy/.test/main.test.bicep
- modules/network/front-door-web-application-firewall-policy/README.md
- modules/network/front-door-web-application-firewall-policy/main.bicep
- modules/network/front-door-web-application-firewall-policy/main.json
- modules/network/front-door-web-application-firewall-policy/version.json
New module added to create WAF Policy for Front Door related to https://github.com/Azure/ResourceModules/issues/3714
| Pipeline |
| - |
| |
> Bicep module to create Front Door WAF Policy

- .azuredevops/modulePipelines/ms.network.frontdoorwebapplicationfirewallpolicies.yml
- .github/workflows/ms.network.frontdoorwebapplicationfirewallpolicies.yml
- modules/network/front-door-web-application-firewall-policy/.bicep/nested_roleAssignments.bicep
- modules/network/front-door-web-application-firewall-policy/.test/common/dependencies.bicep
- modules/network/front-door-web-application-firewall-policy/.test/common/main.test.bicep
- modules/network/front-door-web-application-firewall-policy/.test/main.test.bicep
- modules/network/front-door-web-application-firewall-policy/.test/min/main.test.bicep
- modules/network/front-door-web-application-firewall-policy/README.md
- modules/network/front-door-web-application-firewall-policy/main.bicep
- modules/network/front-door-web-application-firewall-policy/main.json
- modules/network/front-door-web-application-firewall-policy/version.json
- Based on PR #3718 
- New module added to create WAF Policy for Front Door related to https://github.com/Azure/ResourceModules/issues/3714
cc: @rajeshkaremane 
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status%2FModules%2FNetwork%20-%20FrontDoorWebApplicationFirewallPolicies?branchName=users%2Falsehr%2F228005_DeployFrontDoorWAFRules_rajeshkaremane)](https://dev.azure.com/carml/CARML/_build/latest?definitionId=137&branchName=users%2Falsehr%2F228005_DeployFrontDoorWAFRules_rajeshkaremane) |
> [Modules] Bicep module to create Front Door WAF Policy (#3718)

- .ps-rule/min-suppress.Rule.yaml
- modules/authorization/policy-assignment/.test/mg.min/main.test.bicep
- modules/authorization/policy-assignment/.test/rg.min/main.test.bicep
- modules/authorization/policy-assignment/.test/sub.min/main.test.bicep
- modules/authorization/policy-assignment/README.md
Configured min-suppress.Rule-yaml to exclude evaluation of rule Azure.Policy.AssignmentDescriptors for min files:
ResourceModules/modules/Microsoft.Authorization/policyAssignments/.test/sub.min/deploy.test.bicep 
ResourceModules/modules/Microsoft.Authorization/policyAssignments/.test/rg.min/deploy.test.bicep 
ResourceModules/modules/Microsoft.Authorization/policyAssignments/.test/mg.min/deploy.test.bicep 
closes #2668 
| Pipeline |
| - |
|[![Authorization - PolicyAssignments](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyassignments.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyassignments.yml) |
Please …
> [PSRule] Fix Rule Azure.Policy.AssignmentDescriptors #2668

- .ps-rule/min-suppress.Rule.yaml
Added exclusion for AZR-000142: ***apdmgmin001 failed Azure.Policy.Descriptors. Policy and initiative definitions should use a display name, description, and category for min test files.
closes #3894 
| Pipeline |
| - |
|[![Authorization - PolicyDefinitions](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policydefinitions.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policydefinitions.yml) |
> Fix Rule Azure.Policy.Descriptors

- .ps-rule/min-suppress.Rule.yaml
Fixed AZR-000145: ***apergmin001 failed Azure.Policy.ExemptionDescriptors. Policy exemptions should use a display name and description for min files. Added exclusion on min-suppress.yaml
| Pipeline |
| - |
|[![Authorization - PolicyExemptions](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyexemptions.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.policyexemptions.yml) |
> [PSRule] Fix Rule Azure.Policy.ExemptionDescriptors

- .github/actions/templates/validateModuleDeployment/action.yml
Fixes #3590
Replaces: #3591
Aligning GH resource removal condition with ADO.
| Pipeline  | Expected behavior | Actual result | 
| - | - | - |
| [Regular deploy](https://github.com/MariusStorhaug/ResourceModules/actions/runs/6051481775) | Success | ✅ |
| [Deploy with failure](https://github.com/MariusStorhaug/ResourceModules/actions/runs/6052501714/job/16426102603) | Fail deployment, resources removed | ✅ |
| [Deploy with cancel](https://github.com/MariusStorhaug/ResourceModules/actions/runs/6052763057/job/16426990507) | Deploy some resources, cancel whole workflow | ✅ |
> [Fixes] Align GH removal with ADO

- utilities/tools/Set-ModuleReadMe.ps1
add `#requires -Modules powershell-yaml` to `Set-ModuleReadMe.ps1` so the script will not run when `powershell-yaml` module is not installed
> [Utilities] Added  'required module'  to `Set-ModuleReadMe.ps1` script

- .azuredevops/pipelineTemplates/stages.module.yml
- Update ADO pipeline conditions to make it impossible to continue on canceled job
- Based on #3579
Tested pipeline cases
| Runtime Static | Runtime Deployment | Runtime Pre-Release | Manual Action | Result |
| - | - | - | - | - |
| ✅ | ✅ | ✅ | - | Runs all |
| ✅ | ✅ | ✅ | Cancel during static | Skipps deployment & publishing |
| ✅ | ✅ | ✅ | Cancel during deployment | Skipps publishing |
| :x: | ✅ | ✅ | - | Skipps publishing |
| ✅  | :x: | ✅ | - | Skipps publishing |
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status%2FModules%2FResources%20-%20ResourceGroups?branchName=users%2Falsehr%2FadoCond)](https://dev.azure.com/carml/CARML/_build/latest?definitionI …
> [Fixes] Update ADO pipeline conditions to make it impossible to continue on canceled job

- modules/network/express-route-gateway/.bicep/nested_roleAssignments.bicep
- modules/network/express-route-gateway/.test/common/main.test.bicep
- modules/network/express-route-gateway/.test/main.test.bicep
- modules/network/express-route-gateway/.test/min/dependencies.bicep
- modules/network/express-route-gateway/.test/min/main.test.bicep
- modules/network/express-route-gateway/README.md
- modules/network/express-route-gateway/main.bicep
- modules/network/express-route-gateway/main.json
Updated RBAC handling & added min test
| Pipeline |
| - |
| [![Network - ExpressRouteGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.expressroutegateways.yml/badge.svg?branch=users%2Falsehr%2F3668_rbacFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.expressroutegateways.yml) |
> [Fixes] Express-route-gateway: Updated RBAC handling & added min test

- .github/workflows/platform.convertToArmTemplate.tests.yml
- utilities/tools/tests/ConvertTo-ARMTemplate.Tests.ps1
Fixed `ConvertTo-ARMTemplate` test case by aligning it with the latest interface
| Pipeline |
| - |
| [![.Platform: Test - ConvertTo-ARMTemplate.ps1](https://github.com/Azure/ResourceModules/actions/workflows/platform.convertToArmTemplate.tests.yml/badge.svg?branch=users%2Falsehr%2F3531_convertFix)](https://github.com/Azure/ResourceModules/actions/workflows/platform.convertToArmTemplate.tests.yml) |
> [Fixes] Fixed `ConvertTo-ARMTemplate` test case 

- modules/network/network-watcher/.test/main.test.bicep
- modules/network/network-watcher/.test/min/main.test.bicep
- Removed unused input param for min test
> [Fixes] NetworkWatcher: Removed unused input param for min test

- modules/resources/tags/.test/main.test.bicep
- modules/resources/tags/.test/min/main.test.bicep
- modules/resources/tags/.test/rg/main.test.bicep
- modules/resources/tags/.test/sub/main.test.bicep
- Tags: Removed unused param
| Pipeline |
| - |
| [![Resources - Tags](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.tags.yml/badge.svg?branch=users%2Falsehr%2FtagsUnusedParam)](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.tags.yml) |
> [Fixes] Tags: Removed unused param

- .github/workflows/platform.convertToArmTemplate.tests.yml
- utilities/tools/tests/ConvertTo-ARMTemplate.Tests.ps1
Follow-up to #3931
| Pipeline |
| - |
| [![.Platform: Test - ConvertTo-ARMTemplate.ps1](https://github.com/Azure/ResourceModules/actions/workflows/platform.convertToArmTemplate.tests.yml/badge.svg?branch=users%2Falsehr%2F3531_convertFix)](https://github.com/Azure/ResourceModules/actions/workflows/platform.convertToArmTemplate.tests.yml) |
> [Fixes] Fixed ConvertTo-ARMTemplate test case

- modules/cache/redis/main.bicep
- modules/cache/redis/main.json
Name syntax error for the RBAC submodule.
| Pipeline |
| - |
|[![Cache - Redis](https://github.com/Azure/ResourceModules/actions/workflows/ms.cache.redis.yml/badge.svg?branch=users%2Fahmad%2FredisUpdate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cache.redis.yml) |
> [Modules] Updated Redis RBAC nested module naming

- modules/managed-identity/user-assigned-identity/.test/common/main.test.bicep
- modules/managed-identity/user-assigned-identity/.test/min/main.test.bicep
- modules/managed-identity/user-assigned-identity/README.md
- modules/managed-identity/user-assigned-identity/federated-identity-credential/README.md
- modules/managed-identity/user-assigned-identity/federated-identity-credential/main.bicep
- modules/managed-identity/user-assigned-identity/federated-identity-credential/main.json
- modules/managed-identity/user-assigned-identity/federated-identity-credential/version.json
- modules/managed-identity/user-assigned-identity/main.bicep
- modules/managed-identity/user-assigned-identity/main.json
- Updated the API version for the User Assigned Identity module to the latest published version.
- Added support for `Federated Identity credential` child module. Used for workload identity scenarios with AKS.
- Added `min` test case
| Pipeline |
| - |
|[![ManagedIdentity - UserAssignedIdentities](https://github.com/Azure/ResourceModules/actions/workflows/ms.managedidentity.userassignedidentities.yml/badge.svg?branch=users%2Fahmad%2FUAMIupdate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.managedidentity.userassignedidentities.yml) |
> [Modules] Updated Managed Identity API Version and Added Federated Identity Credential

- modules/document-db/database-account/.test/gremlindb/dependencies.bicep
- modules/document-db/database-account/.test/gremlindb/main.test.bicep
- modules/document-db/database-account/.test/mongodb/dependencies.bicep
- modules/document-db/database-account/.test/mongodb/main.test.bicep
- modules/document-db/database-account/.test/plain/dependencies.bicep
- modules/document-db/database-account/.test/plain/main.test.bicep
- modules/document-db/database-account/.test/sqldb/dependencies.bicep
- modules/document-db/database-account/.test/sqldb/main.test.bicep
- modules/document-db/database-account/README.md
Updated Cosmos DB to support dynamic location for primary and secondary regions in test file. Used the deployment script pattern we applied for other modules.
| Pipeline |
| - |
| [![DocumentDB - DatabaseAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml/badge.svg?branch=users%2Fahmad%2FcosmosUpdate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml)|
> [Modules] Updated Cosmos DB Module tests to support dynamic primary and secondary region locations

- modules/db-for-postgre-sql/flexible-server/README.md
- modules/db-for-postgre-sql/flexible-server/main.bicep
- modules/db-for-postgre-sql/flexible-server/main.json
Updated the version parameter in the main.bicep file to allow version 15, and set the default version to 15. 
#3950 
| Pipeline |
| - |
| |
> [Modules] Update allowed version values

- modules/db-for-postgre-sql/flexible-server/.test/public/dependencies.bicep
- modules/db-for-postgre-sql/flexible-server/.test/public/main.test.bicep
- modules/db-for-postgre-sql/flexible-server/README.md
- modules/db-for-postgre-sql/flexible-server/administrator/README.md
- modules/db-for-postgre-sql/flexible-server/administrator/main.bicep
- modules/db-for-postgre-sql/flexible-server/administrator/main.json
- modules/db-for-postgre-sql/flexible-server/administrator/version.json
- modules/db-for-postgre-sql/flexible-server/main.bicep
- modules/db-for-postgre-sql/flexible-server/main.json
Changes to enable AAD authentication and set AAD admins to the PostgreSQL flexibleServers. Changed the administratorLogin and administratorLoginPassword parameters to optional to set AAD authentication only
Based on #3952
| Pipeline |
| - |
| [![DbForPostgreSQL - FlexibleServers](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml/badge.svg?branch=users%2Falsehr%2Fppotturi%2Fpostgresql-add-auth)](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml) |
> [Modules] Enable AAD authentication (#3952)

- .azuredevops/pipelineTemplates/jobs.publishModule.yml
- .github/actions/templates/publishModule/action.yml
Fixed an ordering for the publish stage in ADO - Bicep Registry as the order is not right. This is a copy/paste error when #3906 was implemented. The reason it didn't appear in that PR is that it was tested correctly initially, but when standardizing the code block across Artifacts, Template Specs, and Bicep Registry, the code block was copied to the incorrect space. This causes the following error for only ADO - BR - Feature branch publishing:
```powershell
VERBOSE: Looking for modified files under: [managed-identity/user-assigned-identity]
VERBOSE: Modified modules found: [1]
VERBOSE:  - [managed-identity/user-assigned-identity]
VERBOSE: Publish the following modules:
VERBOSE:  - [managed-identity/user-assigned-identity] [0.11.2251-prerelease] 
VERBOSE: Invoke …
```
> [CI Platform] Fixed ADO Publish Job for Bicep Registry ordering for prerelease and feature branch publishing

- modules/cache/redis/README.md
- modules/insights/private-link-scope/README.md
- utilities/tools/Set-ModuleReadMe.ps1
- utilities/tools/helper/Get-PipelineFileName.ps1
- utilities/tools/helper/Get-SpecsAlignedResourceName.ps1
- Implement fixes to correctly identify resource type & pipeline
| Pipeline |
| - |
| [![AAD - DomainServices](https://github.com/Azure/ResourceModules/actions/workflows/ms.aad.domainservices.yml/badge.svg?branch=users%2Falsehr%2FutilitiesFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.aad.domainservices.yml) |
| [![AnalysisServices - Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FutilitiesFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
| [![ApiManagement - Service](https://github.com/Azure/ResourceModules/actions/workflows/ms.apimanagement.service.yml/badge.svg?branch=users%2Falsehr%2FutilitiesFix)](https://github.com/Azure/Resource …
> [Fixes] Implement fixes to correctly identify resource type & pipeline

- modules/storage/storage-account/main.bicep
- modules/storage/storage-account/main.json
- Changed `else` case to `any('')` which is accepted by the provider and works idempotently.
| Pipeline |
| - |
| [![Storage - StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Falsehr%2Fntfsv3Fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) |
> [Fixes] Adjusted case-handling for NFSv3 to improve idempotency

- modules/db-for-my-sql/flexible-server/.test/private/dependencies.bicep
- modules/db-for-my-sql/flexible-server/.test/private/main.test.bicep
- modules/db-for-my-sql/flexible-server/README.md
- modules/db-for-my-sql/flexible-server/administrator/README.md
- modules/db-for-my-sql/flexible-server/administrator/main.bicep
- modules/db-for-my-sql/flexible-server/administrator/main.json
- modules/db-for-my-sql/flexible-server/administrator/version.json
- modules/db-for-my-sql/flexible-server/main.bicep
- modules/db-for-my-sql/flexible-server/main.json
Closes #3948 
Added child module `administrator` to support Azure AD Auth. 
| Pipeline |
| - |
| [![DbForMySQL - FlexibleServers](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbformysql.flexibleservers.yml/badge.svg?branch=users%2Fahmad%2Fmysql)](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbformysql.flexibleservers.yml)|
> [Modules] Added support for Azure AD Authentication for MySQL Flexible Server

- utilities/pipelines/staticValidation/module.tests.ps1
the Pester test [Bicep test deployment files should invoke test like [`module testDeployment '../.*main.bicep'](https://github.com/Azure/ResourceModules/blob/main/utilities/pipelines/staticValidation/module.tests.ps1#L1320C34-L1320C127) does not support for loop in the regex.
Fix #4018 
[![Authorization - PolicyDefinitions](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.authorization.policydefinitions.yml/badge.svg?branch=fix%2Fbicep-test-deployment-pester)](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.authorization.policydefinitions.yml)
> Fix Pester test Bicep test deployment files should invoke test like [`module testDeployment '../.*main.bicep' does not support for loop

- modules/network/connection/README.md
- modules/network/connection/main.bicep
- modules/network/connection/main.json
- modules/network/vpn-gateway/main.json
- modules/network/vpn-gateway/vpn-connection/README.md
- modules/network/vpn-gateway/vpn-connection/main.bicep
- modules/network/vpn-gateway/vpn-connection/main.json
In this PR I have added securestring and secure() to the sharedKey parameter for VPN connection to hide the value of the secret during deployments.
> Added securestring and secure() to several arm templates and biceps

- utilities/tools/Set-ModuleReadMe.ps1
- Enabled `Set-ModuleReadMe` to find looped test cases
- Follow up to #4019
> [Utilities] Enabled `Set-ModuleReadMe` to find looped test cases

- modules/event-hub/namespace/authorization-rule/main.json
- modules/event-hub/namespace/disaster-recovery-config/main.json
- modules/event-hub/namespace/eventhub/authorization-rule/main.json
- modules/event-hub/namespace/eventhub/consumergroup/main.json
- modules/event-hub/namespace/eventhub/main.json
- modules/event-hub/namespace/main.json
- modules/event-hub/namespace/network-rule-set/main.json
> [Modules] Updated Event Hub - Recompiled JSON files

- README.md
- modules/compute/ssh-public-key/MOVED-TO-AVM.md
- modules/key-vault/vault/MOVED-TO-AVM.md
- modules/kubernetes-configuration/extension/MOVED-TO-AVM.md
- modules/kubernetes-configuration/flux-configuration/MOVED-TO-AVM.md
- modules/network/private-endpoint/MOVED-TO-AVM.md
- modules/network/public-ip-address/MOVED-TO-AVM.md
- Updated banner
- Added `MOVED-TO-AVM.md` files
> [Modules] Updated banner & added `MOVED-TO-AVM.md` files

- modules/app-configuration/configuration-store/.bicep/nested_roleAssignments.bicep
- modules/app-configuration/configuration-store/.test/common/dependencies.bicep
- modules/app-configuration/configuration-store/.test/common/main.test.bicep
- modules/app-configuration/configuration-store/.test/encr/dependencies.bicep
- modules/app-configuration/configuration-store/.test/encr/main.test.bicep
- modules/app-configuration/configuration-store/README.md
- modules/app-configuration/configuration-store/key-value/.bicep/nested_roleAssignments.bicep
- modules/app-configuration/configuration-store/key-value/README.md
- modules/app-configuration/configuration-store/key-value/main.bicep
- modules/app-configuration/configuration-store/key-value/main.json
- modules/app-configuration/configuration-store/main.bicep
- modules/app-configuration/configuration-store/main.json
Updated to the latest API version. Added support for CMK and test case for encryption.
| Pipeline |
| - |
| [![AppConfiguration - ConfigurationStores](https://github.com/Azure/ResourceModules/actions/workflows/ms.appconfiguration.configurationstores.yml/badge.svg?branch=users%2Fahmad%2FAppConfigUpdates)](https://github.com/Azure/ResourceModules/actions/workflows/ms.appconfiguration.configurationstores.yml)|
> [Modules] Updated App Configuration Module to use the latest APIs and added support for CMK

- modules/cache/redis-enterprise/README.md
- modules/cache/redis-enterprise/main.bicep
- modules/cache/redis-enterprise/main.json
> [Modules] Updated Redis Cache Enterprise Logging

- modules/web/site/README.md
- modules/web/site/basic-publishing-credentials-policy/README.md
- modules/web/site/basic-publishing-credentials-policy/main.bicep
- modules/web/site/basic-publishing-credentials-policy/main.json
- modules/web/site/main.json
- modules/web/site/tests/e2e/functionAppCommon/main.test.bicep
- modules/web/site/tests/e2e/webAppCommon/main.test.bicep
Web Site Basic Publishing Credentials Policy does not expose allow property
Fixes #4201 
| Pipeline |
| - |
| [![Web - Sites](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.web.sites.yml/badge.svg?branch=fix%2Fwebsite-publishing-cred-policy)](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.web.sites.yml)|
> Fix website publishing cred policy 

- modules/operational-insights/workspace/MOVED-TO-AVM.md
- modules/operational-insights/workspace/README.md
Added `MOVED-TO-AVM.md` files for `operational-insights/workspace` module as it has been merged into AVM, see https://github.com/Azure/bicep-registry-modules/pull/612
This PR resolves #4060
> Added MOVED-TO-AVM.md  for `operational-insights/workspace` module

- modules/web/serverfarm/README.md
- modules/web/serverfarm/main.bicep
- modules/web/serverfarm/main.json
The `kind` parameter for `web/serverfarm` (app service plan) is obsolete according to this article [Overview of the ‘kind’ property for App Service](https://azure.github.io/AppService/2021/08/31/Kind-property-overview.html)
The RP sets the value based on the `sku`, regardless what you have specified. To repro, assign a value to the `kind` parameter:
after the resource is created, the `GET` request shows a different value that aligned with the `sku`:
I have tried to make it conditional such as `kind: !empty(kind) ? kind : null`, but it didn't work (error as shown below):
The only option is removing it completely and let RP to set it at creation time.
| Pipeline |
| - |
| [![Web - Serverfarms](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.web.serverfarms.yml/badge.svg …
> [Bug Fix] Remove kind parameter from App Service Plan `web/serverfarm` module

- modules/container-service/managed-cluster/README.md
- modules/container-service/managed-cluster/agent-pool/main.json
- modules/container-service/managed-cluster/main.bicep
- modules/container-service/managed-cluster/main.json
- modules/container-service/managed-cluster/tests/e2e/azure/dependencies.bicep
- modules/container-service/managed-cluster/tests/e2e/azure/main.test.bicep
- modules/container-service/managed-cluster/tests/e2e/priv/dependencies.bicep
- modules/container-service/managed-cluster/tests/e2e/priv/main.test.bicep
- utilities/pipelines/staticValidation/module.tests.ps1
- Added Azure Key Vault key management service settings to Security profile
- Update azure/main.test.bicep and example in readme to test enabling Key Management Service changes.
- Switched API error to API warning as per AVM changes
This change will allow enabling the Key Management Service by adding the settings required to the Security Profile as per the 'Microsoft.ContainerService/managedClusters' documentation.  See link below:
https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/2023-07-02-preview/managedclusters?pivots=deployment-language-bicep#azurekeyvaultkms
| Pipeline |
| - | 
| [![ContainerService - ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Faadev1%2FazureKey …
> [Modules] Follow-Up-To: Added Azure Key Vault key management service settings to Security profile

- modules/storage/storage-account/blob-service/README.md
- modules/storage/storage-account/blob-service/container/immutability-policy/main.json
- modules/storage/storage-account/blob-service/container/main.json
- modules/storage/storage-account/blob-service/main.bicep
- modules/storage/storage-account/blob-service/main.json
- modules/storage/storage-account/file-service/main.json
- modules/storage/storage-account/file-service/share/main.json
- modules/storage/storage-account/local-user/main.json
- modules/storage/storage-account/main.bicep
- modules/storage/storage-account/main.json
- modules/storage/storage-account/management-policy/main.json
- modules/storage/storage-account/queue-service/main.json
- modules/storage/storage-account/queue-service/queue/main.json
- modules/storage/storage-account/table-service/main.json
- modules/storage/storage-account/table-service/table/main.json
- Addressed Bicep warning about allowed values
- Regenerated all docs & templates
| Pipeline |
| - |
| [![Storage - StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Falsehr%2F4250_linter&event=workflow_dispatch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) |
> [Fixes] Address BlobServices linter warning

- modules/insights/component/MOVED-TO-AVM.md
- modules/insights/component/README.md
Added `MOVED-TO-AVM.md` files for `insights/component` module as it has been merged into AVM, see https://github.com/Azure/bicep-registry-modules/pull/635
This PR resolves #4268
> Added MOVED-TO-AVM.md for `insights/component` module

- modules/sql/server/MOVED-TO-AVM.md
- modules/sql/server/README.md
Added `MOVED-TO-AVM.md` files for `sql/server` module as it has been merged into AVM, see https://github.com/Azure/bicep-registry-modules/pull/637
This PR resolves #4270
> Added MOVED-TO-AVM.md for `sql/server` module

- modules/web/serverfarm/tests/e2e/max/main.test.bicep
- utilities/pipelines/resourceDeployment/Get-TemplateDeploymenWhatIf.ps1
- utilities/tools/Test-ModuleLocally.ps1
Extend `Test-ModuleLocally.ps1` script, added capability to perform Azure What-If deployment validation
When `-WhatIfTest` switch parameter is specified, it performs ARM What-If test and display the result like the following:
> [New Feature] Add WhatIf feature to Test module locally script

- utilities/pipelines/resourceDeployment/New-TemplateDeployment.ps1
- utilities/pipelines/resourceDeployment/Test-TemplateDeployment.ps1
- utilities/tools/Test-ModuleLocally.ps1
- utilities/tools/helper/Get-TemplateDeploymentWhatIf.ps1
- Updated WhatIf feature to AVM changes
- Removed `parameter.json` support
- Fixed diverse smaller bugs (e.g. file names, folder names, etc.)
| Pipeline |
| - |
| [![AnalysisServices - Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FwhatIfFixes&event=workflow_dispatch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
> [Utilities] Updated WhatIf feature to AVM changes

- modules/document-db/database-account/MOVED-TO-AVM.md
- modules/document-db/database-account/README.md
Added `MOVED-TO-AVM.md` files for  `document-db/database-account` module as it has been merged into AVM, see https://github.com/Azure/bicep-registry-modules/pull/667
This PR resolves #4321
> Added MOVED-TO-AVM.md for `document-db/database-account` module

- modules/service-bus/namespace/MOVED-TO-AVM.md
- modules/service-bus/namespace/README.md
- modules/service-bus/namespace/authorization-rule/main.json
- modules/service-bus/namespace/disaster-recovery-config/main.json
- modules/service-bus/namespace/migration-configuration/main.json
- modules/service-bus/namespace/network-rule-set/main.json
- modules/service-bus/namespace/queue/authorization-rule/main.json
- modules/service-bus/namespace/topic/authorization-rule/main.json
| Pipeline |
| - |
| [![ServiceBus - Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml/badge.svg?branch=users%2Fcsidebotham%2Fservicebus-avm)](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml)|
> Adding MOVED-TO-AVM to `serviceBus/capacity`

- modules/insights/data-collection-endpoint/MOVED-TO-AVM.md
- modules/insights/data-collection-endpoint/README.md
Added `MOVED-TO-AVM.md` files for  `insights/data-collection-endpoint` module as it has been merged into AVM, see https://github.com/Azure/bicep-registry-modules/pull/695
This PR resolves #4332
> Added MOVED-TO-AVM.md for `insights/data-collection-endpoint` module

- modules/network/public-ip-prefix/MOVED-TO-AVM.md
- modules/network/public-ip-prefix/README.md
Added `MOVED-TO-AVM.md` files for  `network/public-ip-prefix` module as it has been merged into AVM, see https://github.com/Azure/bicep-registry-modules/pull/690
This PR resolves #4323
> Added MOVED-TO-AVM.md for `network/public-ip-prefix` module

- modules/container-service/managed-cluster/README.md
- modules/container-service/managed-cluster/main.bicep
- modules/container-service/managed-cluster/main.json
- modules/container-service/managed-cluster/tests/e2e/azure/main.test.bicep
Based on #4329 
cc: @aadev1, @JPEasier
AVM ref: https://github.com/Azure/bicep-registry-modules/pull/665
Added azureMonitorProfile to allow us to enable the Prometheus collector and kube state metrics for prometheus addon profile for the container service cluster
Update azure/main.test.bicep and example in readme to test enabling Prometheus collector
This change will allow enabling the Prometheus collector and kube state metrics for prometheus addon profile for the container service cluster by adding the settings required to theazureMonitorProfile as per the 'Microsoft.ContainerService/managedClusters' documentation. See link below:
https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/2023-07-02-preview/managedclusters?pivots=deployment-language-bicep#managedcluster …
> [Modules] Added azureMonitorProfile to allow us to enable the Prometheus collector

- modules/app/managed-environment/README.md
- modules/app/managed-environment/main.bicep
- modules/app/managed-environment/main.json
- modules/app/managed-environment/tests/e2e/max/dependencies.bicep
- modules/app/managed-environment/tests/e2e/max/main.test.bicep
- modules/app/managed-environment/tests/e2e/waf-aligned/dependencies.bicep
- modules/app/managed-environment/tests/e2e/waf-aligned/main.test.bicep
> Container Apps Env Upgrade to latest version 2023-05-01

- modules/insights/data-collection-rule/MOVED-TO-AVM.md
- modules/insights/data-collection-rule/README.md
Added `MOVED-TO-AVM.md` files for  `insights/data-collection-endpoint` module as it has been merged into AVM, see https://github.com/Azure/bicep-registry-modules/pull/697
This PR resolves #4333
> Added MOVED-TO-AVM.md for `insights/data-collection-rule` module

- modules/insights/activity-log-alert/MOVED-TO-AVM.md
- modules/insights/activity-log-alert/README.md
- modules/insights/metric-alert/MOVED-TO-AVM.md
- modules/insights/metric-alert/README.md
- modules/insights/scheduled-query-rule/MOVED-TO-AVM.md
- modules/insights/scheduled-query-rule/README.md
Added `MOVED-TO-AVM.md` files for  three modules:
- `insights/activity-log-alert`
- PR: https://github.com/Azure/bicep-registry-modules/pull/708
- resolves #4344 
- `insights/metric-alert`
- PR: https://github.com/Azure/bicep-registry-modules/pull/711
- resolves #4343 
- `insights/scheduled-query-rule`
- PR: https://github.com/Azure/bicep-registry-modules/pull/712
- resolves #4345
> Added MOVED-TO-AVM.md for three modules

- modules/automation/automation-account/MOVED-TO-AVM.md
- modules/automation/automation-account/README.md
- modules/automation/automation-account/job-schedule/main.json
- modules/automation/automation-account/module/main.json
- modules/automation/automation-account/runbook/main.json
- modules/automation/automation-account/schedule/main.json
- modules/automation/automation-account/software-update-configuration/main.json
- modules/automation/automation-account/variable/main.json
Adding Moved to AVM file and readme update for automation account module
> Migrated module automation/automation-account

- modules/api-management/service/MOVED-TO-AVM.md
- modules/api-management/service/README.md
- modules/data-factory/factory/MOVED-TO-AVM.md
- modules/data-factory/factory/README.md
- modules/insights/webtest/MOVED-TO-AVM.md
- modules/insights/webtest/README.md
- modules/maintenance/maintenance-configuration/MOVED-TO-AVM.md
- modules/maintenance/maintenance-configuration/README.md
- `api-management/service`
- PR: https://github.com/Azure/bicep-registry-modules/pull/713
- resolves #4355 
- `data-factory/factory`
- PR: https://github.com/Azure/bicep-registry-modules/pull/730
- resolves #4376 
- `insights/webtest`
- PR: https://github.com/Azure/bicep-registry-modules/pull/728
- resolves #4377
- `maintenance/maintenance-configuration`
- PR: https://github.com/Azure/bicep-registry-modules/pull/729
- resolves #4378
> Added MOVED-TO-AVM.md for the recently migrated modules

- modules/storage/storage-account/README.md
- modules/storage/storage-account/blob-service/container/immutability-policy/main.json
- modules/storage/storage-account/blob-service/container/main.json
- modules/storage/storage-account/blob-service/main.json
- modules/storage/storage-account/file-service/README.md
- modules/storage/storage-account/file-service/main.json
- modules/storage/storage-account/file-service/share/README.md
- modules/storage/storage-account/file-service/share/main.bicep
- modules/storage/storage-account/file-service/share/main.json
- modules/storage/storage-account/file-service/share/modules/nested_inner_roleAssignment.json
- modules/storage/storage-account/file-service/share/modules/nested_roleAssignment.bicep
- modules/storage/storage-account/local-user/main.json
- modules/storage/storage-account/main.json
- modules/storage/storage-account/management-policy/main.json
- modules/storage/storage-account/queue-service/main.json
- modules/storage/storage-account/queue-service/queue/main.json
- modules/storage/storage-account/table-service/main.json
- modules/storage/storage-account/table-service/table/main.json
- utilities/pipelines/sharedScripts/Get-NestedResourceList.ps1
- utilities/pipelines/staticValidation/helper/helper.psm1
- Implemented workaround for fileShare role assignment.
- Added workaround to 2 scripts working with nested resource detection to not fail on loaded ARM template.
> **Note:** It cannot detect the roleAssignment resource type in a nested ARM template
Ref: https://github.com/Azure/bicep-types-az/issues/1532
Proof that the role assignment worked:
| Pipeline |
| - |
| [![Storage - StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Falsehr%2F4346_shareRbac&event=workflow_dispatch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) |
> [Module] Implemented workaround for fileShare role assignment

- modules/virtual-machine-images/image-template/main.json
- modules/virtual-machine-images/image-template/tests/e2e/max/dependencies.bicep
- modules/virtual-machine-images/image-template/tests/e2e/max/main.test.bicep
- modules/virtual-machine-images/image-template/tests/e2e/waf-aligned/dependencies.bicep
- modules/virtual-machine-images/image-template/tests/e2e/waf-aligned/main.test.bicep
- utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
Ensure that VirtualMachineImages are removed before MSIs are removed as there's otherwise a high chance for a lock. -> The resource cannot be removed anymore until an MSI is re-assigned.
| Pipeline |
| - |
| [![VirtualMachineImages - ImageTemplates](https://github.com/Azure/ResourceModules/actions/workflows/ms.virtualmachineimages.imagetemplates.yml/badge.svg?branch=users%2Falsehr%2FimageRemovalFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.virtualmachineimages.imagetemplates.yml) |
> [Fixes] Ensure that VirtualMachineImages are removed before MSIs are removed as there's otherwise a high chance for a lock

- modules/container-service/managed-cluster/MOVED-TO-AVM.md
- modules/container-service/managed-cluster/README.md
- modules/container-service/managed-cluster/main.json
Issue: #4194
PR on bicep regestry: https://github.com/Azure/bicep-registry-modules/pull/665
This module has already been migrated to [AVM](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res). Only the AVM version is expected to receive updates / new features. Please do not work on improving this module in [CARML](https://aka.ms/carml).
> Migrate container-service/managed-cluster to AVM specs

- modules/analysis-services/server/README.md
- modules/cache/redis/README.md
- modules/compute/disk/README.md
- modules/compute/image/README.md
- modules/consumption/budget/README.md
- modules/data-protection/backup-vault/README.md
- modules/databricks/access-connector/README.md
- modules/databricks/workspace/README.md
- modules/db-for-my-sql/flexible-server/README.md
- modules/health-bot/health-bot/README.md
- modules/net-app/net-app-account/README.md
- utilities/tools/Get-CrossReferencedModuleList.ps1
- Ported updated reference resolution from AVM: Fixed resolution of local file references ignoring files not named `main.bicep`
- Updated READMEs 
> **Note:** Led to no direct updates as the issue did not occur in CARML through local references. However, some readme's got fixed
Original PR: https://github.com/Azure/bicep-registry-modules/pull/766
> [Utilities] Ported updated reference resolution from AVM

- modules/event-hub/namespace/README.md
- modules/event-hub/namespace/authorization-rule/main.json
- modules/event-hub/namespace/disaster-recovery-config/main.json
- modules/event-hub/namespace/eventhub/authorization-rule/main.json
- modules/event-hub/namespace/eventhub/consumergroup/main.json
- modules/event-hub/namespace/eventhub/main.json
- modules/event-hub/namespace/main.bicep
- modules/event-hub/namespace/main.json
- modules/event-hub/namespace/network-rule-set/README.md
- modules/event-hub/namespace/network-rule-set/main.bicep
- modules/event-hub/namespace/network-rule-set/main.json
- modules/event-hub/namespace/tests/e2e/max/main.test.bicep
- As per linked issue, updated behavior of NetworkRuleSet
- Instead of making any assumptions on behalf of the user, the value now simply defaults to true (which is the expected behavior (unless explicitely specified differently)
| Pipeline |
| - |
| [![EventHub - Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml/badge.svg?branch=users%2Falsehr%2F4452_networkRuleSet&event=workflow_dispatch)](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml) |
> [Fixes] Event Hub Namespace : Updated behavior of NetworkRuleSet

- modules/insights/private-link-scope/README.md
- utilities/pipelines/sharedScripts/Set-ModuleReadMe.ps1
- Fixed issue with multi-line parameter descriptions
- Regenerated all docs
| Pipeline |
| - |
| [![Insights - PrivateLinkScopes](https://github.com/Azure/ResourceModules/actions/workflows/ms.insights.privatelinkscopes.yml/badge.svg?branch=users%2Falsehr%2FreadmeDescriptionMultilineFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.insights.privatelinkscopes.yml) |
> [Fixes] Fixed issue with multi-line parameter descriptions

- modules/compute/availability-set/MOVED-TO-AVM.md
- modules/compute/availability-set/README.md
- modules/compute/availability-set/main.json
- modules/insights/private-link-scope/MOVED-TO-AVM.md
- modules/insights/private-link-scope/README.md
- modules/insights/private-link-scope/main.json
- modules/insights/private-link-scope/scoped-resource/main.json
- modules/network/ip-group/MOVED-TO-AVM.md
- modules/network/ip-group/README.md
- modules/network/ip-group/main.json
- modules/network/private-link-service/MOVED-TO-AVM.md
- modules/network/private-link-service/README.md
- modules/network/private-link-service/main.json
Reference:
#4411 
#4416 
#4414 
#4413 
| Pipeline |
| - |
| |
> [Modules] Added Moved to AVM for availability sets, private link scope, ip groups and private link service

- modules/management/management-group/MOVED-TO-AVM.md
- modules/management/management-group/README.md
- `management/management-group`
- PR: https://github.com/Azure/bicep-registry-modules/pull/1002
- resolves #4496
> Added MOVED-TO-AVM for `management/management-group`

- utilities/pipelines/sharedScripts/Set-ModuleReadMe.ps1
- Based on found issue by a colleague where the script failed if 'modules' also appeared in other parts of the path
- The `/modules/` instead of `modules/` is in alignment with all other places where we split
- Tested & validated
> [Fixes] Added missing slash to module path split

- modules/cdn/profile/MOVED-TO-AVM.md
- modules/cdn/profile/README.md
- `cdn/profile`
- PR: https://github.com/Azure/bicep-registry-modules/pull/1106
- resolves #4510
> Added MOVED-TO-AVM.md for the CDN Profile module

- modules/app-configuration/configuration-store/MOVED-TO-AVM.md
- modules/app-configuration/configuration-store/README.md
- `app-configuration/configuration-store`
- PR: https://github.com/Azure/bicep-registry-modules/pull/1072
- resolves #4504
> Added MOVED-TO-AVM.md for the App Configuration Store

- modules/signal-r-service/signal-r/MOVED-TO-AVM.md
- modules/signal-r-service/signal-r/README.md
- modules/signal-r-service/web-pub-sub/MOVED-TO-AVM.md
- modules/signal-r-service/web-pub-sub/README.md
- `signal-r-service/signal-r`
- PR: https://github.com/Azure/bicep-registry-modules/pull/1109
- resolves #4511 
- `signal-r-service/web-pub-sub`
- PR: https://github.com/Azure/bicep-registry-modules/pull/1219
- resolves #4514
> Added MOVED-TO-AVM.md for the Signal-R modules
