Azure/ResourceModules

- .github/CODEOWNERS
> codeowners updated

- arm/Microsoft.Web/hostingEnvironments/parameters/parameters.json
- arm/Microsoft.Web/sites/parameters/function.parameters.json
> Fixed resource ref

- arm/Microsoft.Compute/galleries/deploy.bicep
- arm/Microsoft.Compute/galleries/deploy.json
- arm/Microsoft.Compute/galleries/readme.md
- arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
- arm/Microsoft.Compute/virtualMachineScaleSets/deploy.json
- arm/Microsoft.Compute/virtualMachineScaleSets/parameters/linux.parameters.json
- arm/Microsoft.Compute/virtualMachineScaleSets/parameters/windows.parameters.json
- arm/Microsoft.Compute/virtualMachineScaleSets/readme.md
- arm/Microsoft.Compute/virtualMachines/deploy.json
- arm/Microsoft.Compute/virtualMachines/readme.md
> fixing some pipelines/modules

- arm/Microsoft.Consumption/budgets/deploy.bicep
Updated so all variable names are camelCased.
> fix budgets

- .github/workflows/ms.insights.actiongroups.yml
- .github/workflows/ms.insights.diagnosticsettings.yml
- arm/Microsoft.Insights/actionGroups/deploy.bicep
Missed updating the workflows to use the deploy.bicep files in #82 and #84.
Fixed reference on rbac module for actionGroup
> Fix workflow for actiongroup and activityLog(diagnosticSettings)

- .github/workflows/ms.servicebus.namespaces.yml
- arm/Microsoft.ServiceBus/namespaces/.bicep/nested_privateEndpoints.bicep
- arm/Microsoft.ServiceBus/namespaces/.bicep/nested_rbac.bicep
- arm/Microsoft.ServiceBus/namespaces/deploy.bicep
- arm/Microsoft.ServiceBus/namespaces/deploy.json
> Create namespace bicep

- .github/workflows/ms.network.virtualnetworks.virtualnetworkpeerings.yml
> remove tags

- .github/workflows/linter.yml
Put the linter into stand-by to not having us distracting during development.
> VALIDATE_YAML: false

- arm/Microsoft.OperationalInsights/workspaces/parameters/parameters.json
> Fixed param file

- .github/workflows/ms.apimanagement.service.apis.yml
- .github/workflows/ms.apimanagement.service.authorizationservers.yml
- .github/workflows/ms.apimanagement.service.backends.yml
- .github/workflows/ms.apimanagement.service.caches.yml
- .github/workflows/ms.apimanagement.service.namedvalues.yml
- .github/workflows/ms.apimanagement.service.products.yml
- .github/workflows/ms.apimanagement.service.subscriptions.yml
- .github/workflows/ms.apimanagement.service.yml
- .github/workflows/ms.authorization.policyassignments.yml
- .github/workflows/ms.authorization.policydefinitions.yml
- .github/workflows/ms.authorization.policyexemptions.yml
- .github/workflows/ms.authorization.policysetdefinitions.yml
- .github/workflows/ms.authorization.roleassignments.yml
- .github/workflows/ms.authorization.roledefinitions.yml
- .github/workflows/ms.automanage.accounts.yml
- .github/workflows/ms.automation.automationaccounts.softwareupdateconfigurations.yml
- .github/workflows/ms.cognitiveservices.accounts.yml
- .github/workflows/ms.consumption.budgets.yml
- .github/workflows/ms.eventhub.namespaces.eventhubs.yml
- .github/workflows/ms.insights.diagnosticsettings.yml
- .github/workflows/ms.keyvault.vaults.yml
- .github/workflows/ms.managedservices.registrationdefinitions.yml
- .github/workflows/ms.management.managementgroups.yml
- .github/workflows/ms.network.networkwatchers.yml
- .github/workflows/ms.network.virtualnetworks.virtualnetworkpeerings.yml
- .github/workflows/ms.security.azuresecuritycenter.yml
- .github/workflows/ms.servicebus.namespaces.queues.yml
- arm/Microsoft.Automanage/accounts/.parameters/parameters.json
- arm/Microsoft.ServiceBus/namespaces/.bicep/nested_rbac.bicep
- arm/Microsoft.ServiceBus/namespacesResources/queues/readme.md
- Additional Comments Added, as per pending fix for #313 
- Reset service bus role assignment guid (swapping two inputs) to generate a new guid that is not a conflicting one. Addresses current Service Bus deployment issue
[![ServiceBus: Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml/badge.svg?branch=users%2Fahmad%2Fbug-automanage)](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml)
[![Automanage: Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.automanage.accounts.yml/badge.svg?branch=users%2Fahmad%2Fbug-automanage)](https://github.com/Azure/ResourceModules/actions/workflows/ms.automanage.accounts.yml)
*** This is acceptable as the virtual machine does not exist *** the auto …
> Bug Fixes - Automanage & Registrations Definitions

- docs/wiki/ModulesUsage.md
- Added template-spec example to module usage
> Added template-spec example to module usage

- arm/Microsoft.Management/managementGroups/.parameters/parameters.json
- Updated MgmtGroupID to new tenant mgmtGroup (Common Resource Library)
> Updated MgmtGroupID

- arm/Microsoft.AnalysisServices/servers/.bicep/nested_rbac.bicep
- arm/Microsoft.AnalysisServices/servers/deploy.bicep
- arm/Microsoft.AnalysisServices/servers/readme.md
[![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Fmast%2FMS.AnalysisServices_RBAC)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml)
> Align RBAC on Microsoft.AnalysisServices

- arm/Microsoft.Automation/automationAccounts/.bicep/nested_rbac.bicep
- arm/Microsoft.Automation/automationAccounts/deploy.bicep
- arm/Microsoft.Automation/automationAccounts/readme.md
[![Automation: Automationaccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.automation.automationaccounts.yml/badge.svg?branch=users%2Fmast%2FMS.Automation_RBAC)](https://github.com/Azure/ResourceModules/actions/workflows/ms.automation.automationaccounts.yml)
> Align RBAC on Microsoft.Automation

- arm/Microsoft.ContainerService/managedClusters/.bicep/nested_rbac.bicep
- arm/Microsoft.ContainerService/managedClusters/deploy.bicep
- arm/Microsoft.ContainerService/managedClusters/readme.md
> Align RBAC on Microsoft.ContainerService

- arm/Microsoft.ContainerRegistry/registries/.bicep/nested_rbac.bicep
- arm/Microsoft.ContainerRegistry/registries/deploy.bicep
- arm/Microsoft.ContainerRegistry/registries/readme.md
> Align RBAC on Microsoft.ContainerRegistry

- arm/Microsoft.Databricks/workspaces/.bicep/nested_rbac.bicep
- arm/Microsoft.Databricks/workspaces/deploy.bicep
- arm/Microsoft.Databricks/workspaces/readme.md
> Align RBAC on Microsoft.Databricks

- arm/Microsoft.EventGrid/topics/.bicep/nested_rbac.bicep
- arm/Microsoft.EventGrid/topics/deploy.bicep
- arm/Microsoft.EventGrid/topics/readme.md
> Align RBAC on Microsoft.EventGrid

- arm/Microsoft.DesktopVirtualization/applicationgroups/.bicep/nested_rbac.bicep
- arm/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
- arm/Microsoft.DesktopVirtualization/applicationgroups/readme.md
- arm/Microsoft.DesktopVirtualization/hostpools/.bicep/nested_rbac.bicep
- arm/Microsoft.DesktopVirtualization/hostpools/deploy.bicep
- arm/Microsoft.DesktopVirtualization/hostpools/readme.md
- arm/Microsoft.DesktopVirtualization/workspaces/.bicep/nested_rbac.bicep
- arm/Microsoft.DesktopVirtualization/workspaces/deploy.bicep
- arm/Microsoft.DesktopVirtualization/workspaces/readme.md
> Align RBAC on Microsoft.DesktopVirtualization

- arm/Microsoft.DataFactory/factories/.bicep/nested_rbac.bicep
- arm/Microsoft.DataFactory/factories/deploy.bicep
- arm/Microsoft.DataFactory/factories/readme.md
> Align RBAC on Microsoft.DataFactory

- arm/Microsoft.Web/connections/.bicep/nested_rbac.bicep
- arm/Microsoft.Web/connections/deploy.bicep
- arm/Microsoft.Web/connections/readme.md
- arm/Microsoft.Web/hostingEnvironments/.bicep/nested_rbac.bicep
- arm/Microsoft.Web/hostingEnvironments/deploy.bicep
- arm/Microsoft.Web/hostingEnvironments/readme.md
- arm/Microsoft.Web/serverfarms/.bicep/nested_rbac.bicep
- arm/Microsoft.Web/serverfarms/deploy.bicep
- arm/Microsoft.Web/serverfarms/readme.md
- arm/Microsoft.Web/sites/.bicep/nested_rbac.bicep
- arm/Microsoft.Web/sites/deploy.bicep
- arm/Microsoft.Web/sites/readme.md
> Align RBAC on Microsoft.Web

- arm/Microsoft.VirtualMachineImages/imageTemplates/.bicep/nested_rbac.bicep
- arm/Microsoft.VirtualMachineImages/imageTemplates/deploy.bicep
- arm/Microsoft.VirtualMachineImages/imageTemplates/readme.md
> Align RBAC on Microsoft.VirtualMachineImages

- arm/Microsoft.Storage/storageAccounts/.bicep/nested_rbac.bicep
- arm/Microsoft.Storage/storageAccounts/blobServices/containers/.bicep/nested_rbac.bicep
- arm/Microsoft.Storage/storageAccounts/blobServices/containers/readme.md
- arm/Microsoft.Storage/storageAccounts/blobServices/readme.md
- arm/Microsoft.Storage/storageAccounts/fileServices/readme.md
- arm/Microsoft.Storage/storageAccounts/fileServices/shares/.bicep/nested_rbac.bicep
- arm/Microsoft.Storage/storageAccounts/fileServices/shares/readme.md
- arm/Microsoft.Storage/storageAccounts/queueServices/queues/.bicep/nested_rbac.bicep
- arm/Microsoft.Storage/storageAccounts/queueServices/queues/readme.md
- arm/Microsoft.Storage/storageAccounts/queueServices/readme.md
- arm/Microsoft.Storage/storageAccounts/readme.md
> Align RBAC on Microsoft.Storage

- arm/Microsoft.Sql/managedInstances/.bicep/nested_rbac.bicep
- arm/Microsoft.Sql/managedInstances/deploy.bicep
- arm/Microsoft.Sql/managedInstances/readme.md
- arm/Microsoft.Sql/servers/.bicep/nested_rbac.bicep
- arm/Microsoft.Sql/servers/deploy.bicep
- arm/Microsoft.Sql/servers/readme.md
> Align RBAC on Microsoft.Sql

- arm/Microsoft.ServiceBus/namespaces/.bicep/nested_rbac.bicep
- arm/Microsoft.ServiceBus/namespaces/authorizationRules/readme.md
- arm/Microsoft.ServiceBus/namespaces/deploy.bicep
- arm/Microsoft.ServiceBus/namespaces/queues/.bicep/nested_rbac.bicep
- arm/Microsoft.ServiceBus/namespaces/queues/deploy.bicep
- arm/Microsoft.ServiceBus/namespaces/queues/readme.md
- arm/Microsoft.ServiceBus/namespaces/readme.md
> Align RBAC on Microsoft.ServiceBus

- arm/Microsoft.RecoveryServices/vaults/.bicep/nested_rbac.bicep
- arm/Microsoft.RecoveryServices/vaults/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/readme.md
[![RecoveryServices: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml/badge.svg?branch=users%2Fmast%2FMS.RecoveryServices_RBAC)](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml)
> Align RBAC on Microsoft.RecoveryServices

- arm/Microsoft.ManagedIdentity/userAssignedIdentities/.bicep/nested_rbac.bicep
- arm/Microsoft.ManagedIdentity/userAssignedIdentities/deploy.bicep
- arm/Microsoft.ManagedIdentity/userAssignedIdentities/readme.md
> Align RBAC on Microsoft.ManagedIdentity

- arm/Microsoft.Logic/workflows/.bicep/nested_rbac.bicep
- arm/Microsoft.Logic/workflows/deploy.bicep
- arm/Microsoft.Logic/workflows/readme.md
> Align RBAC on Microsoft.Logic

- arm/Microsoft.KeyVault/vaults/.bicep/nested_rbac.bicep
- arm/Microsoft.KeyVault/vaults/deploy.bicep
- arm/Microsoft.KeyVault/vaults/readme.md
> Align RBAC on Microsoft.KeyVault

- arm/Microsoft.HealthBot/healthBots/.bicep/nested_rbac.bicep
- arm/Microsoft.HealthBot/healthBots/deploy.bicep
> Align RBAC on Microsoft.HealthBot

- arm/Microsoft.EventHub/namespaces/.bicep/nested_rbac.bicep
- arm/Microsoft.EventHub/namespaces/deploy.bicep
- arm/Microsoft.EventHub/namespaces/readme.md
- arm/Microsoft.EventHub/namespacesResources/eventhubs/.bicep/nested_rbac.bicep
- arm/Microsoft.EventHub/namespacesResources/eventhubs/deploy.bicep
- arm/Microsoft.EventHub/namespacesResources/eventhubs/readme.md
> Align RBAC on Microsoft.EventHub

- .github/workflows/platform.dependencies.yml
- docs/wiki/TestingDesign.md
- utilities/dependencies/Microsoft.Network/privateDnsZones/parameters/parameters.json
- Adding PrivateDnsZone resource to the dependency pipeline to fix the PrivateEndpoint module pipeline
- Updating dependency pipeline documentation
> Fix privateEndpoint module

- arm/Microsoft.Network/virtualNetworkGateways/.parameters/expressRoute.parameters.json
- arm/Microsoft.Network/virtualNetworkGateways/.parameters/vpn.parameters.json
Update vnet gateway parameter with new dependency
[![Network: Virtualnetworkgateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworkgateways.yml/badge.svg?branch=users%2Ferikag%2Ffix-vnetgateway)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworkgateways.yml)
> Fix Virtual Network Gateway Dependencies

- arm/Microsoft.ServiceBus/namespaces/.bicep/nested_privateEndpoints.bicep
- arm/Microsoft.ServiceBus/namespaces/.bicep/nested_rbac.bicep
- arm/Microsoft.ServiceBus/namespaces/deploy.bicep
- arm/Microsoft.ServiceBus/namespaces/queues/.bicep/nested_rbac.bicep
- arm/Microsoft.ServiceBus/namespaces/queues/deploy.bicep
- Cleaned up service bus module
- Convert json(null) into null
- Removed excess brackets
- added output descriptions
> Cleaned up service bus module & added output descriptions

- arm/Microsoft.ApiManagement/service/deploy.bicep
- arm/Microsoft.ApiManagement/service/readme.md
- arm/Microsoft.ApiManagement/serviceResources/apis/deploy.bicep
- arm/Microsoft.ApiManagement/serviceResources/apis/readme.md
- arm/Microsoft.ApiManagement/serviceResources/authorizationServers/deploy.bicep
- arm/Microsoft.ApiManagement/serviceResources/authorizationServers/readme.md
- arm/Microsoft.ApiManagement/serviceResources/backends/deploy.bicep
- arm/Microsoft.ApiManagement/serviceResources/backends/readme.md
- arm/Microsoft.ApiManagement/serviceResources/caches/deploy.bicep
- arm/Microsoft.ApiManagement/serviceResources/caches/readme.md
- arm/Microsoft.ApiManagement/serviceResources/namedValues/deploy.bicep
- arm/Microsoft.ApiManagement/serviceResources/namedValues/readme.md
- arm/Microsoft.ApiManagement/serviceResources/products/deploy.bicep
- arm/Microsoft.ApiManagement/serviceResources/products/readme.md
- arm/Microsoft.ApiManagement/serviceResources/subscriptions/deploy.bicep
- arm/Microsoft.ApiManagement/serviceResources/subscriptions/readme.md
- Cleaned up api management modules
- Convert json(null) into null
- Removed excess brackets
- added output descriptions
> Cleaned up api management modules & added output descriptions

- arm/Microsoft.Web/connections/deploy.bicep
- arm/Microsoft.Web/connections/readme.md
- arm/Microsoft.Web/hostingEnvironments/deploy.bicep
- arm/Microsoft.Web/hostingEnvironments/readme.md
- arm/Microsoft.Web/serverfarms/deploy.bicep
- arm/Microsoft.Web/serverfarms/readme.md
- arm/Microsoft.Web/sites/.bicep/nested_privateEndpoint.bicep
- arm/Microsoft.Web/sites/deploy.bicep
- arm/Microsoft.Web/sites/readme.md
- Cleaned up network modules
- Convert json(null) into null
- Removed excess brackets
- added output descriptions
> Cleaned up web modules & added output descriptions

- .github/actions/templates/removeModule/scripts/Remove-DeployedModule.ps1
> #435 remove child resources first

- .github/workflows/ms.network.privateendpoints.yml
- arm/Microsoft.Network/privateEndpoints/.bicep/nested_rbac.bicep
- arm/Microsoft.Network/privateEndpoints/.parameters/min.parameters.json
- arm/Microsoft.Network/privateEndpoints/.parameters/parameters.json
- arm/Microsoft.Network/privateEndpoints/deploy.bicep
- arm/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/deploy.bicep
- arm/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/readme.md
- arm/Microsoft.Network/privateEndpoints/readme.md
[![Network: Privateendpoints](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.privateendpoints.yml/badge.svg?branch=users%2Fmast%2FMS.Network%2FprivateEndpoints_child)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.privateendpoints.yml)
- Updated Private EndPoints resource and child-resources to new child resource structure
> Update PrivateEndpoints to new child-resource structure

- .github/workflows/platform.dependencies.yml
- arm/Microsoft.Compute/virtualMachines/deploy.bicep
- utilities/dependencies/Microsoft.EventHub/namespaces/parameters/parameters.json
- utilities/dependencies/Microsoft.KeyVault/vaults/parameters/parameters.json
- utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/2.vnetpeer01.parameters.json
- utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/3.vnetpeer02.parameters.json
- utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/4.azfw.parameters.json
- utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/5.aks.parameters.json
- utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/6.sqlmi.parameters.json
- utilities/dependencies/Microsoft.Network/virtualNetworks/parameters/parameters.json
- Removed Network Watcher from dependencies since NSGFlowLogs are now part of the same module due to Network watcher child restructure
- Merged Eventhub namespace and event hub into a single job due to eventhub child restructure
- Update parameter names to latest version
- Fix bug in VM module identity
- Update Backup Management Service objectId after tenant move
> Update Dependency pipeline after child restructure

- constructs/Microsoft.Network/virtualNetwork/virtualNetworkPeerings-multiRemoteVnets/deploy.bicep
> Update reference to peering resource module

- arm/Microsoft.DesktopVirtualization/applicationgroups/.parameters/min.parameters.json
- arm/Microsoft.DesktopVirtualization/applicationgroups/.parameters/parameters.json
- arm/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
- arm/Microsoft.DesktopVirtualization/applicationgroups/readme.md
Replace `type `with `applicationGroupType `to reflect official reference https://docs.microsoft.com/en-us/azure/templates/microsoft.desktopvirtualization/applicationgroups?tabs=bicep
> Minor fix for avd appgroup param name

- arm/Microsoft.Network/localNetworkGateways/.parameters/parameters.json
Pipeline fails, as a wrong set of parameters is set => removed one parameter
- [ x] I did format my code
> Fix local network gatway pipeline

- arm/Microsoft.ServiceBus/namespaces/deploy.bicep
- arm/Microsoft.ServiceBus/namespaces/readme.md
Pipeline didn't run because of a failed test -> one parameter was malformed in the description
> add missing keyword Optional

- docs/wiki/ParameterFileTokens.md
- utilities/tools/Test-ModuleLocally.ps1
Closes #487 
- Changed Script Import Path for the Validate and Deploy Scripts after the recent folder restructuring (from .github\actions --> utilities\pipelines)
- Updated link in the wiki + removed an unnecessary link (as it was provided in the line before).
> Closes: #487 - Fixed Test-ModuleLocally Script Post Folder Restructures + Updated Links in Wiki

- .github/workflows/platform.dependencies.yml
- arm/Microsoft.Network/privateEndpoints/.parameters/min.parameters.json
- arm/Microsoft.Network/privateEndpoints/.parameters/parameters.json
- docs/wiki/TestingDesign.md
- utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/parameters.json
- utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/pe.parameters.json
- utilities/pipelines/dependencies/Microsoft.KeyVault/vaults/parameters/sqlmi.parameters.json
[![.Platform: Dependencies](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml/badge.svg?branch=users%2Ferikag%2Fghdependencies-09)](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml)
- Decoupling sqlmi dependencies from those of other modules, adding a choice input parameter to enable sqlmi dependencies to the workflow 
- Adding specific kv to test pe module. That is to avoid the kv being locked on private endpoint while the PE module is running or in case testing resources are not removed correctly
- Leveraging tenantId and spn id tokens in dependency parameters 
- Updating docs
> Dependency pipeline update for sqlmi and pe

- arm/Microsoft.DataFactory/factories/integrationRuntime/deploy.bicep
- arm/Microsoft.DataFactory/factories/readme.md
- Fixed a minor complaint by bicep (Self-Hosted vs SelfHosted)
- Re-generated readme via file (we should check why it's not working for you)
> Minor fix + ReadMe generation

- arm/Microsoft.ManagedIdentity/userAssignedIdentities/.parameters/parameters.json
- arm/Microsoft.ManagedIdentity/userAssignedIdentities/deploy.bicep
- arm/Microsoft.ManagedIdentity/userAssignedIdentities/readme.md
- utilities/pipelines/dependencies/Microsoft.ManagedIdentity/userAssignedIdentities/parameters/parameters.json
Updated 
- inputs
- outputs
- readme
[![ManagedIdentity: Userassignedidentities](https://github.com/Azure/ResourceModules/actions/workflows/ms.managedidentity.userassignedidentities.yml/badge.svg?branch=users%2Falsehr%2FmsiInput)](https://github.com/Azure/ResourceModules/actions/workflows/ms.managedidentity.userassignedidentities.yml)
> Updated inputs, outputs & readme

- arm/Microsoft.Management/managementGroups/.bicep/nested_rbac.bicep
- arm/Microsoft.Management/managementGroups/.parameters/parameters.json
- arm/Microsoft.Management/managementGroups/deploy.bicep
- arm/Microsoft.Management/managementGroups/readme.md
Update 
- inputs
- outputs 
- readme
> Update inputs, outputs & readme

- arm/Microsoft.Resources/deploymentScripts/.parameters/parameters.json
- arm/Microsoft.Resources/deploymentScripts/deploy.bicep
- arm/Microsoft.Resources/deploymentScripts/readme.md
- arm/Microsoft.Resources/resourceGroups/.parameters/parameters.json
- arm/Microsoft.Resources/resourceGroups/deploy.bicep
- arm/Microsoft.Resources/resourceGroups/readme.md
- utilities/pipelines/dependencies/Microsoft.Resources/resourceGroups/parameters/artifacts.parameters.json
- utilities/pipelines/dependencies/Microsoft.Resources/resourceGroups/parameters/platform-core.parameters.json
- utilities/pipelines/dependencies/Microsoft.Resources/resourceGroups/parameters/validation.parameters.json
- Replaced input name with 'name'
- Added outputs where necessary
- Other small things
Pipeline references
[![Resources: Deploymentscripts](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.deploymentscripts.yml/badge.svg?branch=users%2Falsehr%2FrgParam)](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.deploymentscripts.yml)
[![Resources: Resourcegroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.resourcegroups.yml/badge.svg?branch=users%2Falsehr%2FrgParam)](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.resourcegroups.yml)
> Updated resources namespace to naming pattern

- arm/Microsoft.ServiceBus/namespaces/queues/.bicep/nested_rbac.bicep
- arm/Microsoft.Storage/storageAccounts/blobServices/containers/.bicep/nested_rbac.bicep
- arm/Microsoft.Storage/storageAccounts/fileServices/shares/.bicep/nested_rbac.bicep
- arm/Microsoft.Storage/storageAccounts/queueServices/queues/.bicep/nested_rbac.bicep
fix wrong split parameters for name
> fix wrong split parameters for name

- arm/Microsoft.ManagedServices/registrationDefinitions/.parameters/parameters.json
- arm/Microsoft.ManagedServices/registrationDefinitions/.parameters/rg.parameters.json
- arm/Microsoft.ManagedServices/registrationDefinitions/deploy.bicep
- arm/Microsoft.ManagedServices/registrationDefinitions/readme.md
Updated
- Inputs
- Outputs
- Docs
[![ManagedServices: Registrationdefinitions](https://github.com/Azure/ResourceModules/actions/workflows/ms.managedservices.registrationdefinitions.yml/badge.svg?branch=users%2Falsehr%2FmanagedServiceInput)](https://github.com/Azure/ResourceModules/actions/workflows/ms.managedservices.registrationdefinitions.yml)
> Update the inputs, outputs und docs

- arm/Microsoft.ApiManagement/service/apiVersionSets/deploy.bicep
- arm/Microsoft.ApiManagement/service/apiVersionSets/readme.md
- arm/Microsoft.ApiManagement/service/apis/deploy.bicep
- arm/Microsoft.ApiManagement/service/apis/policies/deploy.bicep
- arm/Microsoft.ApiManagement/service/apis/policies/readme.md
- arm/Microsoft.ApiManagement/service/apis/readme.md
- arm/Microsoft.ApiManagement/service/authorizationServers/deploy.bicep
- arm/Microsoft.ApiManagement/service/authorizationServers/readme.md
- arm/Microsoft.ApiManagement/service/backends/deploy.bicep
- arm/Microsoft.ApiManagement/service/backends/readme.md
- arm/Microsoft.ApiManagement/service/caches/deploy.bicep
- arm/Microsoft.ApiManagement/service/caches/readme.md
- arm/Microsoft.ApiManagement/service/identityProviders/deploy.bicep
- arm/Microsoft.ApiManagement/service/identityProviders/readme.md
- arm/Microsoft.ApiManagement/service/namedValues/deploy.bicep
- arm/Microsoft.ApiManagement/service/namedValues/readme.md
- arm/Microsoft.ApiManagement/service/policies/deploy.bicep
- arm/Microsoft.ApiManagement/service/policies/readme.md
- arm/Microsoft.ApiManagement/service/portalsettings/deploy.bicep
- arm/Microsoft.ApiManagement/service/portalsettings/readme.md
- arm/Microsoft.ApiManagement/service/products/apis/deploy.bicep
- arm/Microsoft.ApiManagement/service/products/apis/readme.md
- arm/Microsoft.ApiManagement/service/products/deploy.bicep
- arm/Microsoft.ApiManagement/service/products/groups/deploy.bicep
- arm/Microsoft.ApiManagement/service/products/groups/readme.md
- arm/Microsoft.ApiManagement/service/products/readme.md
- arm/Microsoft.ApiManagement/service/readme.md
- arm/Microsoft.ApiManagement/service/subscriptions/deploy.bicep
- arm/Microsoft.ApiManagement/service/subscriptions/readme.md
- Update API with `existing`
- Updated docs
- Cleanup
[![ApiManagement: Service](https://github.com/Azure/ResourceModules/actions/workflows/ms.apimanagement.service.yml/badge.svg?branch=users%2Falsehr%2F545_api_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.apimanagement.service.yml)
> Update API with `existing`

- arm/Microsoft.AnalysisServices/servers/.parameters/min.parameters.json
- arm/Microsoft.AnalysisServices/servers/.parameters/parameters.json
- arm/Microsoft.AnalysisServices/servers/deploy.bicep
- arm/Microsoft.AnalysisServices/servers/readme.md
- Updated Analysis Services to use `name` input parameter
- Updated parameter files
- Updated docs
[![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2F543_analysis_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml)
> Updated Analysis Services to use `name` input parameter

- arm/Microsoft.Batch/batchAccounts/.parameters/parameters.json
- arm/Microsoft.Batch/batchAccounts/deploy.bicep
- arm/Microsoft.Batch/batchAccounts/readme.md
- Updated batch to use `name` input parameter
- Update dparameter file
- Updated docs
[![Batch: Batchaccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.batch.batchaccounts.yml/badge.svg?branch=users%2Falsehr%2F550_batch_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.batch.batchaccounts.yml)
> Updated batch to use `name` input parameter

- arm/Microsoft.Consumption/budgets/deploy.bicep
- arm/Microsoft.Consumption/budgets/readme.md
- Update budget to use `name` input parameter
- Updated docs
- Updated parameter file
> Update budget to use `name` input parameter

- arm/Microsoft.DataFactory/factories/integrationRuntime/deploy.bicep
- arm/Microsoft.DataFactory/factories/integrationRuntime/readme.md
- arm/Microsoft.DataFactory/factories/managedVirtualNetwork/deploy.bicep
- arm/Microsoft.DataFactory/factories/managedVirtualNetwork/readme.md
- arm/Microsoft.DataFactory/factories/readme.md
- Updated Data Factory to use existing
[![DataFactory: Factories](https://github.com/Azure/ResourceModules/actions/workflows/ms.datafactory.factories.yml/badge.svg?branch=users%2Falsehr%2F558_df_existing)](https://github.com/Azure/ResourceModules/actions/workflows/ms.datafactory.factories.yml)
> Updated DataFactory to use `existing`

- arm/Microsoft.EventGrid/topics/.parameters/parameters.json
- arm/Microsoft.EventGrid/topics/deploy.bicep
- arm/Microsoft.EventGrid/topics/readme.md
- Update the event grid name input paramtere to `name`
- Updated documentation & parameter file
[![EventGrid: Topics](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventgrid.topics.yml/badge.svg?branch=users%2Falsehr%2F561_eg_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventgrid.topics.yml)
> Update to latest

- arm/Microsoft.EventHub/namespaces/authorizationRules/deploy.bicep
- arm/Microsoft.EventHub/namespaces/authorizationRules/readme.md
- arm/Microsoft.EventHub/namespaces/deploy.bicep
- arm/Microsoft.EventHub/namespaces/disasterRecoveryConfigs/deploy.bicep
- arm/Microsoft.EventHub/namespaces/disasterRecoveryConfigs/readme.md
- arm/Microsoft.EventHub/namespaces/eventhubs/authorizationRules/deploy.bicep
- arm/Microsoft.EventHub/namespaces/eventhubs/authorizationRules/readme.md
- arm/Microsoft.EventHub/namespaces/eventhubs/consumergroups/deploy.bicep
- arm/Microsoft.EventHub/namespaces/eventhubs/consumergroups/readme.md
- arm/Microsoft.EventHub/namespaces/eventhubs/deploy.bicep
- arm/Microsoft.EventHub/namespaces/eventhubs/readme.md
- arm/Microsoft.EventHub/namespaces/readme.md
- Update EventHub to use `existing`
- Update outputs
- Update readme
[![EventHub: Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml/badge.svg?branch=users%2Falsehr%2F562_eh_existing)](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml)
> Update EventHub to use `existing`

- arm/Microsoft.MachineLearningServices/workspaces/.parameters/parameters.json
- arm/Microsoft.MachineLearningServices/workspaces/deploy.bicep
- arm/Microsoft.MachineLearningServices/workspaces/readme.md
- Update input parameter to `name`
- Aligned diagnostic settings 
- Added outputs
> Update input parameter to `name`

- arm/Microsoft.Sql/managedInstances/administrators/deploy.bicep
- arm/Microsoft.Sql/managedInstances/databases/backupLongTermRetentionPolicies/deploy.bicep
- arm/Microsoft.Sql/managedInstances/databases/backupLongTermRetentionPolicies/readme.md
- arm/Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies/deploy.bicep
- arm/Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies/readme.md
- arm/Microsoft.Sql/managedInstances/databases/deploy.bicep
- arm/Microsoft.Sql/managedInstances/encryptionProtector/deploy.bicep
- arm/Microsoft.Sql/managedInstances/keys/deploy.bicep
- arm/Microsoft.Sql/managedInstances/securityAlertPolicies/deploy.bicep
- arm/Microsoft.Sql/managedInstances/vulnerabilityAssessments/deploy.bicep
- arm/Microsoft.Sql/servers/databases/deploy.bicep
- arm/Microsoft.Sql/servers/firewallRules/deploy.bicep
- arm/Microsoft.Sql/servers/securityAlertPolicies/deploy.bicep
- Updated Microsoft.SQL to child-resource structure
> Updated Microsoft.SQL to child-resource structure

- arm/Microsoft.Sql/servers/.parameters/parameters.json
> Fixed incorrect token

- docs/wiki/Context.md
- docs/wiki/ContributionGuide.md
- docs/wiki/GettingStarted.md
- docs/wiki/Home.md
- docs/wiki/ModulesDesign.md
- docs/wiki/ParameterFileTokens.md
- docs/wiki/PipelinesDesign.md
- docs/wiki/PipelinesUsage.md
- docs/wiki/TestingDesign.md
- docs/wiki/TestingUsage.md
> Added scope section to wiki & fixed relative links

- arm/Microsoft.Automation/automationAccounts/deploy.bicep
- arm/Microsoft.Automation/automationAccounts/readme.md
- Caps change on the principalId output of Automation Account
> Minor fix for MI on AA

- arm/Microsoft.Web/connections/.parameters/parameters.json
- arm/Microsoft.Web/connections/deploy.bicep
- arm/Microsoft.Web/connections/readme.md
- arm/Microsoft.Web/hostingEnvironments/.parameters/parameters.json
- arm/Microsoft.Web/hostingEnvironments/deploy.bicep
- arm/Microsoft.Web/hostingEnvironments/readme.md
- arm/Microsoft.Web/sites/config/readme.md
- Update input parameter to use `name`
- Updated parameter files
- Update docs
[![Web: Connections](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.connections.yml/badge.svg?branch=users%2Falsehr%2F581_web_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.connections.yml)
[![Web: Hostingenvironments](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.hostingenvironments.yml/badge.svg?branch=users%2Falsehr%2F581_web_name)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.hostingenvironments.yml)
> Update ASE & connection input parameters to use `name`

- arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
- arm/Microsoft.Compute/virtualMachineScaleSets/readme.md
- arm/Microsoft.Compute/virtualMachines/deploy.bicep
- utilities/tools/Set-ModuleReadMe.ps1
- Removed temporal workaround from Module ReadMe Script
- Minor fixes to diverse `readme.md` & `deploy.bicep`
> Removed temporal workaround from Module ReadMe Script

- arm/Microsoft.ContainerInstance/containerGroups/.parameters/parameters.json
Fixing wrong image value
Ref: https://docs.microsoft.com/en-us/answers/questions/594663/the-image-39microsoftaci-helloworld39-in-container.html
[![ContainerInstance: Containergroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerinstance.containergroups.yml/badge.svg?branch=users%2Ferikag%2Faci)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerinstance.containergroups.yml)
> Fix Container Instances

- arm/Microsoft.Sql/servers/readme.md
- utilities/tools/Set-ModuleReadMe.ps1
- Add functionality to auto fill parameter usage for:
- Private Endpoints
- Role Assignments
- Tags
- Remove the code for "Resources" folder structure
> Update Set-ModuleReadMe script

- docs/wiki/GettingStarted.md
- Update the `Getting Started` section with an additional option as per the linked issue
> Update the `Getting Started` section

- arm/Microsoft.Network/networkWatchers/connectionMonitors/readme.md
- arm/Microsoft.Network/networkWatchers/readme.md
- Update the readMe to match the module
> Fix #582: connectionMonitor readme.md parameter example error #582

- arm/Microsoft.Insights/privateLinkScopes/deploy.bicep
- arm/Microsoft.Insights/privateLinkScopes/readme.md
- arm/Microsoft.Insights/privateLinkScopes/scopedResources/deploy.bicep
- Updated `privateLinkScopes` to `existing`
- Minor cleanup
> Updated `privateLinkScopes` to `existing`

- arm/Microsoft.Network/connections/readme.md
- arm/Microsoft.Network/trafficmanagerprofiles/readme.md
- arm/Microsoft.Web/connections/readme.md
- arm/Microsoft.Web/hostingEnvironments/readme.md
- arm/Microsoft.Web/serverfarms/readme.md
- arm/Microsoft.Web/sites/readme.md
Including a few leftovers from a previous PR
> Align plural in readme titles to be shown in the repo home readme

- docs/wiki/ModulesDesign.md
Attempt to be more explicit regarding the deployment names in Wiki
> Attempt to be more explicit regarding the deployment names in Wiki

- arm/Microsoft.Sql/managedInstances/.parameters/parameters.json
- arm/Microsoft.Sql/managedInstances/deploy.bicep
- arm/Microsoft.Sql/managedInstances/readme.md
[![Sql: ManagedInstances](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml/badge.svg?branch=users%2Fmast%2FMI-SQLMI)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml)
- Align MI on SQLMI
> Align MI on SQL MI

- arm/Microsoft.Sql/servers/.parameters/parameters.json
- arm/Microsoft.Sql/servers/deploy.bicep
- arm/Microsoft.Sql/servers/readme.md
[![Sql: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Fmast%2FMI-SQLsrv)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml)
- Align MI on SQL Servers
> Align MI on SQL Servers

- arm/Microsoft.Web/sites/.parameters/fa.parameters.json
- arm/Microsoft.Web/sites/.parameters/wa.parameters.json
- arm/Microsoft.Web/sites/deploy.bicep
- arm/Microsoft.Web/sites/readme.md
[![Web: Sites](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml/badge.svg?branch=users%2Fmast%2FMI-WebSite)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml)
- Align MI on Web Sites
> Align MI on Web Sites

- arm/Microsoft.ServiceBus/namespaces/.parameters/parameters.json
- arm/Microsoft.ServiceBus/namespaces/deploy.bicep
- arm/Microsoft.ServiceBus/namespaces/readme.md
[![ServiceBus: Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml/badge.svg?branch=users%2Fmast%2FMI-ServiceBusNamespace)](https://github.com/Azure/ResourceModules/actions/workflows/ms.servicebus.namespaces.yml)
- Align MI on Service Bus Namespace
> Align MI on Service Bus Namespace

- utilities/pipelines/dependencies/Microsoft.Compute/galleries/parameters/parameters.json
- utilities/pipelines/dependencies/Microsoft.Network/privateDnsZones/parameters/parameters.json
- Fix to dependency pipeline parameter files
> Fix to dependency pipeline parameter files

- arm/Microsoft.Logic/workflows/.parameters/parameters.json
- arm/Microsoft.Logic/workflows/deploy.bicep
- arm/Microsoft.Logic/workflows/readme.md
[![Logic: Workflows](https://github.com/Azure/ResourceModules/actions/workflows/ms.logic.workflows.yml/badge.svg?branch=users%2Fmast%2FMI-LogicApps)](https://github.com/Azure/ResourceModules/actions/workflows/ms.logic.workflows.yml)
- Align MI on Logic Apps
> Align MI on Logic Apps

- arm/Microsoft.Storage/storageAccounts/.parameters/parameters.json
- arm/Microsoft.Storage/storageAccounts/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/readme.md
[![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Fmast%2FMI-StorageAccount)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml)
- Align MI on Storage Account
> Align MI on Storage Account

- arm/Microsoft.RecoveryServices/vaults/.parameters/parameters.json
- arm/Microsoft.RecoveryServices/vaults/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/readme.md
[![RecoveryServices: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml/badge.svg?branch=users%2Fmast%2FMI-RSV)](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml)
- Align MI on Recovery Service Vaults
> Align MI on Recovery Service Vaults

- arm/Microsoft.Resources/deploymentScripts/.parameters/parameters.json
- arm/Microsoft.Resources/deploymentScripts/deploy.bicep
- arm/Microsoft.Resources/deploymentScripts/readme.md
[![Resources: DeploymentScripts](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.deploymentscripts.yml/badge.svg?branch=users%2Fmast%2FMI-DeploymentScripts)](https://github.com/Azure/ResourceModules/actions/workflows/ms.resources.deploymentscripts.yml)
- Align MI on DeploymentScripts
> Align MI on DeploymentScripts

- arm/Microsoft.ContainerInstance/containerGroups/.parameters/parameters.json
- arm/Microsoft.ContainerInstance/containerGroups/deploy.bicep
- arm/Microsoft.ContainerInstance/containerGroups/readme.md
[![ContainerInstance: ContainerGroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerinstance.containergroups.yml/badge.svg?branch=users%2Fmast%2FMI-ContainerInstance)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerinstance.containergroups.yml)
- Align MI on ContainerInstance
> Align MI on ContainerInstance

- arm/Microsoft.Compute/virtualMachines/.parameters/parameters.json
- arm/Microsoft.Compute/virtualMachines/deploy.bicep
- arm/Microsoft.Compute/virtualMachines/readme.md
[![Compute: VirtualMachines](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml/badge.svg?branch=users%2Fmast%2FMI-VM)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml)
- Align MI on VM
> Align MI on VM

- arm/Microsoft.ContainerRegistry/registries/.parameters/parameters.json
- arm/Microsoft.ContainerRegistry/registries/deploy.bicep
- arm/Microsoft.ContainerRegistry/registries/readme.md
[![ContainerRegistry: Registries](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml/badge.svg?branch=users%2Fmast%2FMI-ContinerRegistry)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml)
- Align MI on ContinerRegistry
> Align MI on ContinerRegistry

- docs/wiki/KnownIssues.md
- docs/wiki/PipelinesDesign.md
Remove references to `removal tags` from the the wiki
> Remove references to `removal tags` from the the wiki

- arm/Microsoft.EventHub/namespaces/.parameters/parameters.json
- arm/Microsoft.EventHub/namespaces/deploy.bicep
- arm/Microsoft.EventHub/namespaces/readme.md
[![EventHub: Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml/badge.svg?branch=users%2Fmast%2FMI-EventhubNamespace)](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml)
- Align MI on EvenHub Namespace
> Align MI on EvenHub Namespace

- arm/Microsoft.DataFactory/factories/.parameters/parameters.json
- arm/Microsoft.DataFactory/factories/deploy.bicep
- arm/Microsoft.DataFactory/factories/readme.md
[![DataFactory: Factories](https://github.com/Azure/ResourceModules/actions/workflows/ms.datafactory.factories.yml/badge.svg?branch=users%2Fmast%2FMI-DataFactory)](https://github.com/Azure/ResourceModules/actions/workflows/ms.datafactory.factories.yml)
- Align MI on Data Factory
> Align MI on Data Factory

- arm/Microsoft.ContainerService/managedClusters/.parameters/azure.parameters.json
- arm/Microsoft.ContainerService/managedClusters/.parameters/kubenet.parameters.json
- arm/Microsoft.ContainerService/managedClusters/deploy.bicep
- arm/Microsoft.ContainerService/managedClusters/readme.md
[![ContainerService: ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Fmast%2FMI-ContainerService)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml)
- Align MI on ContainerService
> Align MI on ContainerService

- arm/Microsoft.Compute/virtualMachineScaleSets/.parameters/linux.parameters.json
- arm/Microsoft.Compute/virtualMachineScaleSets/.parameters/windows.parameters.json
- arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
- arm/Microsoft.Compute/virtualMachineScaleSets/readme.md
[![Compute: VirtualMachineScaleSets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachinescalesets.yml/badge.svg?branch=users%2Fmast%2FMI-VMSS)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachinescalesets.yml)
- Align MI on VM scale set
> Align MI on VM scale set

- arm/Microsoft.Network/applicationGateways/.parameters/parameters.json
- arm/Microsoft.Network/applicationGateways/deploy.bicep
- arm/Microsoft.Network/applicationGateways/readme.md
[![Network: ApplicationGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationgateways.yml/badge.svg?branch=users%2Fmast%2FMI-NetworkApplicationGW)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationgateways.yml)
- Align MI on Network ApplicationGW
> Align MI on Network ApplicationGW

- arm/Microsoft.ContainerRegistry/registries/.parameters/parameters.json
- arm/Microsoft.ContainerService/managedClusters/.parameters/azure.parameters.json
- arm/Microsoft.ContainerService/managedClusters/.parameters/kubenet.parameters.json
- arm/Microsoft.DataFactory/factories/.parameters/parameters.json
- arm/Microsoft.Databricks/workspaces/.parameters/parameters.json
- arm/Microsoft.DesktopVirtualization/applicationgroups/.parameters/parameters.json
- arm/Microsoft.DesktopVirtualization/hostpools/.parameters/parameters.json
- arm/Microsoft.DesktopVirtualization/workspaces/.parameters/parameters.json
- arm/Microsoft.DocumentDB/databaseAccounts/.parameters/mongodb.parameters.json
- arm/Microsoft.DocumentDB/databaseAccounts/.parameters/plain.parameters.json
- arm/Microsoft.DocumentDB/databaseAccounts/.parameters/sqldb.parameters.json
- arm/Microsoft.EventGrid/topics/.parameters/parameters.json
- arm/Microsoft.EventHub/namespaces/.parameters/parameters.json
- arm/Microsoft.Insights/components/.parameters/parameters.json
- arm/Microsoft.Insights/diagnosticSettings/.parameters/parameters.json
- arm/Microsoft.Insights/privateLinkScopes/.parameters/parameters.json
- arm/Microsoft.Insights/scheduledQueryRules/.parameters/parameters.json
- arm/Microsoft.KeyVault/vaults/.parameters/parameters.json
- arm/Microsoft.Logic/workflows/.parameters/parameters.json
- arm/Microsoft.MachineLearningServices/workspaces/.parameters/parameters.json
- arm/Microsoft.Web/hostingEnvironments/.parameters/parameters.json
- arm/Microsoft.Web/sites/.parameters/fa.parameters.json
- arm/Microsoft.Web/sites/.parameters/wa.parameters.json
Updating LAW for the 2nd group of resources
> Update law 2nd step

- arm/Microsoft.Logic/workflows/.parameters/parameters.json
- arm/Microsoft.Logic/workflows/deploy.bicep
- arm/Microsoft.Logic/workflows/readme.md
- arm/Microsoft.MachineLearningServices/workspaces/.parameters/parameters.json
- arm/Microsoft.MachineLearningServices/workspaces/deploy.bicep
- arm/Microsoft.MachineLearningServices/workspaces/readme.md
[![MachineLearningServices: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml/badge.svg?branch=users%2Fmast%2FMI-MLServices)](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml)
- Align MI on MLServices
> Align MI on MLServices

- .github/workflows/platform.dependencies.yml
- arm/Microsoft.Authorization/policyDefinitions/deploy.bicep
- utilities/pipelines/dependencies/Microsoft.Compute/virtualMachines/parameters/parameters.json
- Removed redundant reference in dependency pipeline (moduleName) as it is not leveraged in the referenced composite action
- Added some whitespaces to policyDefinitions
- Fixed virtual machine dependency parameters
[![.Platform: Dependencies](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml/badge.svg?branch=users%2Falsehr%2F697_dependenciesCleanup)](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml)
> Depedency pipeline cleanup

- arm/Microsoft.VirtualMachineImages/imageTemplates/deploy.bicep
Aligning deployment names to naming convention for Microsoft.VirtualMachineImages resource provider
> Microsoft.VirtualMachineImages deployment names

- arm/Microsoft.Sql/managedInstances/databases/deploy.bicep
- arm/Microsoft.Sql/managedInstances/deploy.bicep
- arm/Microsoft.Sql/servers/deploy.bicep
Aligning deployment names to naming convention for Ms.Sql resource provider
> Align MS.Sql deployment names

- arm/Microsoft.Resources/resourceGroups/deploy.bicep
Aligning deployment names to naming convention for Microsoft.Resources resource provider
> Align Microsoft.Resources deployment names

- arm/Microsoft.MachineLearningServices/workspaces/deploy.bicep
Aligning deployment names to naming convention for Microsoft.MachineLearningServices resource provider
> Align Microsoft.MachineLearningServices deployment names

- arm/Microsoft.ManagedIdentity/userAssignedIdentities/deploy.bicep
Aligning deployment names to naming convention for Microsoft.ManagedIdentity resource provider
> Align Microsoft.ManagedIdentity deployment names

- arm/Microsoft.ManagedServices/registrationDefinitions/deploy.bicep
Aligning deployment names to naming convention for Microsoft.ManagedServices resource provider
> Align Microsoft.ManagedServices deployment names

- arm/Microsoft.Management/managementGroups/deploy.bicep
Aligning deployment names to naming convention for Microsoft.Management resource provider
> Align Microsoft.Management deployment names

- arm/Microsoft.HealthBot/healthBots/deploy.bicep
Aligning deployment names to naming convention for Microsoft.HealthBot resource provider
> Align Microsoft.HealthBot deployment names

- arm/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
- arm/Microsoft.DesktopVirtualization/hostpools/deploy.bicep
- arm/Microsoft.DesktopVirtualization/workspaces/deploy.bicep
Aligning deployment names to naming convention for Microsoft.DesktopVirtualization resource provider
> Align Microsoft.DesktopVirtualization deployment names

- arm/Microsoft.Databricks/workspaces/deploy.bicep
Aligning deployment names to naming convention for Microsoft.Databricks resource provider
> Align Microsoft.Databricks deployment names

- arm/Microsoft.ContainerService/managedClusters/deploy.bicep
Aligning deployment names to naming convention for Microsoft.ContainerService resource provider
> Align Microsoft.ContainerService deployment names

- arm/Microsoft.CognitiveServices/accounts/deploy.bicep
Aligning deployment names to naming convention for Microsoft.CognitiveServices resource provider
> Align Microsoft.CognitiveServices deployment names

- arm/Microsoft.AnalysisServices/servers/deploy.bicep
Aligning deployment names to naming convention for Microsoft.AnalysisServices resource provider
> Align Microsoft.AnalysisServices deployment names

- arm/Microsoft.Storage/storageAccounts/blobServices/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/queueServices/deploy.bicep
- arm/Microsoft.Storage/storageAccounts/tableServices/deploy.bicep
Aligning deployment names to naming convention for Ms.Storage resource provider
> Align Ms.Storage deployment names

- arm/Microsoft.Compute/availabilitySets/deploy.bicep
- arm/Microsoft.Compute/diskEncryptionSets/deploy.bicep
- arm/Microsoft.Compute/galleries/deploy.bicep
- arm/Microsoft.Compute/galleries/images/deploy.bicep
- arm/Microsoft.Compute/images/deploy.bicep
- arm/Microsoft.Compute/proximityPlacementGroups/deploy.bicep
- arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
- arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep
- arm/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface_publicIPAddress.bicep
- arm/Microsoft.Compute/virtualMachines/deploy.bicep
Aligning deployment names to naming convention for Microsoft.Compute resource provider
> Align Microsoft.Compute deployment names

- arm/Microsoft.ContainerRegistry/registries/deploy.bicep
- arm/Microsoft.ContainerService/managedClusters/deploy.bicep
Aligning deployment names to naming convention for Microsoft.ContainerRegistry resource provider
> Align Microsoft.ContainerRegistry deployment names

- arm/Microsoft.EventGrid/topics/deploy.bicep
Aligning deployment names to naming convention for Microsoft.EventGrid resource provider
> Align Microsoft.EventGrid deployment names

- arm/Microsoft.Insights/actionGroups/deploy.bicep
- arm/Microsoft.Insights/activityLogAlerts/deploy.bicep
- arm/Microsoft.Insights/components/deploy.bicep
- arm/Microsoft.Insights/metricAlerts/deploy.bicep
- arm/Microsoft.Insights/privateLinkScopes/deploy.bicep
- arm/Microsoft.Insights/scheduledQueryRules/deploy.bicep
Aligning deployment names to naming convention for Microsoft.Insights resource provider
> Align Microsoft.Insights deployment names

- utilities/pipelines/resourceRemoval/helper/Remove-Deployment.ps1
Updated the use dependency filter to work with just a resourceId
> Updated the use dependency filter to work with just a resourceId

- .github/workflows/platform.dependencies.yml
Update action path in dependency pipeline
> Update action path in dependency pipeline

- .azuredevops/modulePipelines/ms.containerregistry.registries.yml
- .github/workflows/ms.containerregistry.registries.yml
- arm/Microsoft.ContainerRegistry/registries/.parameters/min.parameters.json
- arm/Microsoft.ContainerRegistry/registries/.parameters/parameters.json
- Updated ACR name as previous was taken (and probably too generic)
- Added min parameter file too
- Added reference to both GH & ADO pipelines
[![ContainerRegistry: Registries](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml/badge.svg?branch=users%2Falsehr%2FcontainerReg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml)
> Updated ACR name + added min param file

- arm/Microsoft.Network/virtualNetworks/deploy.bicep
> Allow peering to target remoteVnet in different subscription

- arm/Microsoft.Network/virtualNetworks/deploy.bicep
- Fix indempotency bug of VNET deployment
[![Network: VirtualNetworks](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml/badge.svg?branch=users%2Falsehr%2F844_vnet)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml)
> VNET: Fixed indempotency bug with subnet deployment

- .github/workflows/ms.recoveryservices.vaults.yml
- arm/Microsoft.RecoveryServices/vaults/deploy.bicep
[![RecoveryServices: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml/badge.svg?branch=users%2Fmast%2FRSV-MIFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml) -> Though this could be lying! :D
Added extra condition on systemAssignedPrincipalId to check if there is principal ID in the identity property of the deployed resource. Currently it seems flaky from the API if this is returned or not. So seems like a backend issue.
> Fix Recovery Services Vault MI Issue

- arm/Microsoft.ApiManagement/service/deploy.bicep
- arm/Microsoft.Automation/automationAccounts/deploy.bicep
- arm/Microsoft.CognitiveServices/accounts/deploy.bicep
- arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
- arm/Microsoft.Compute/virtualMachines/deploy.bicep
- arm/Microsoft.ContainerInstance/containerGroups/deploy.bicep
- arm/Microsoft.ContainerRegistry/registries/deploy.bicep
- arm/Microsoft.ContainerService/managedClusters/deploy.bicep
- arm/Microsoft.DataFactory/factories/deploy.bicep
- arm/Microsoft.DocumentDB/databaseAccounts/deploy.bicep
- arm/Microsoft.EventHub/namespaces/deploy.bicep
- arm/Microsoft.Logic/workflows/deploy.bicep
- arm/Microsoft.ServiceBus/namespaces/deploy.bicep
- arm/Microsoft.Sql/managedInstances/deploy.bicep
- arm/Microsoft.Sql/servers/deploy.bicep
- arm/Microsoft.Web/sites/deploy.bicep
Aligned outputs according to the fix that was implemented for Storage Account and Recovery Services Vaults.
> Align MI outputs

- .azuredevops/modulePipelines/ms.web.hostingenvironments.yml
> web.hostingenvironment to defaultJobTimeoutInMinutes: 360

- utilities/pipelines/resourceValidation/Test-TemplateWithParameterFile.ps1
- Detailed error output for Test-AzDeployment
- Added success output
> Updated error output for Test-AzDeployment

- arm/Microsoft.Compute/images/.parameters/parameters.json
- arm/Microsoft.VirtualMachineImages/imageTemplates/.parameters/parameters.json
Fixed prerequisites for compute gallery pipeline to work.
[![Compute: Images](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.images.yml/badge.svg?branch=users%2Ferikag%2Fvmimage)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.images.yml)
> Fix Compute Images

- arm/Microsoft.RecoveryServices/vaults/.parameters/parameters.json
- Removed unused param from parameter file
[![RecoveryServices: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml/badge.svg?branch=users%2Falsehr%2FrsvCleanup)](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml)
> RSV: Removed unused param from parameter file

- arm/Microsoft.Network/applicationGateways/deploy.bicep
- Added unition for optional param
> Added union for optional param

- utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/7.virtualHubConnection.parameters.json
Fixing dependency resource for vhub to be tokenized.
> tokenize vhub dependency

- arm/Microsoft.Compute/galleries/images/deploy.bicep
> Added fix for galleries module failure

- arm/Microsoft.Network/virtualHubs/.parameters/min.parameters.json
- arm/Microsoft.Network/virtualHubs/.parameters/parameters.json
Moved vHub reference to a non-existing vWan to not interfere with the vWan pipeline
> Fixed vHub ref

- docs/wiki/Home.md
Completed the title in wiki home.
> Incomplete title on wiki home

- .azuredevops/modulePipelines/ms.compute.disks.yml
Added missing ADO pipeline for disks
> Added missing ADO pipeline for disks

- .azuredevops/modulePipelines/ms.network.firewallpolicies.yml
Fix publishing template for firewall policies in ADO
> Fix publishing template for firewall policies in ADO

- .github/workflows/platform.dependencies.yml
- arm/Microsoft.Compute/availabilitySets/.parameters/min.parameters.json
- arm/Microsoft.Compute/availabilitySets/.parameters/parameters.json
- arm/Microsoft.Insights/components/version.json
- arm/Microsoft.KeyVault/vaults/version.json
- arm/Microsoft.MachineLearningServices/workspaces/version.json
- arm/Microsoft.Network/routeTables/version.json
- arm/Microsoft.OperationalInsights/workspaces/version.json
- arm/Microsoft.Resources/resourceGroups/version.json
- arm/Microsoft.Storage/storageAccounts/version.json
- utilities/pipelines/dependencies/Microsoft.Compute/proximityPlacementGroups/parameters/parameters.json
- Undo changes not intended for this repo
> Undo changes not intended for this repo

- arm/Microsoft.OperationalInsights/workspaces/deploy.bicep
- arm/Microsoft.OperationalInsights/workspaces/readme.md
> Fixed incorrect description

- .azuredevops/pipelineTemplates/jobs.publishModule.yml
Based on an issue raised by Eliza via mail. 
There is a copy/paste mistake in the ADO publishing template, causing an issue when attempting to resolve a template path when using json templates.
For testing:
- Created a new branch of this branch (users/mast/publishingfixADOjsonValidation)
- Converted whole repo to be ARM/Json
- Only running publishing on the following pipelines
- It successfully runs the pipelines
[![Build Status](https://dev.azure.com/servicescode/infra-as-code-source/_apis/build/status/CARML-Modules/AnalysisServices%20-%20Servers?branchName=users%2Fmast%2FpublishingfixADOjsonValidation)](https://dev.azure.com/servicescode/infra-as-code-source/_build/latest?definitionId=2156&branchName=users%2Fmast%2FpublishingfixADOjsonValidation)
[![Build …
> Bugfix for publishing json templates using ADO

- docs/wiki/ModulesUsage.md
- The TF example wasn't working with outputs
- Aligned TF & ACR deployments
- Both the TF & ACR examples were incomplete
- Added bicepconfig.json
> Updated TS example

- docs/wiki/Home.md
Adding empty md files and alternative TOC to be replaced section by section
> Wiki restructuring - empty side by side toc

- arm/Microsoft.Compute/virtualMachines/deploy.bicep
As the default behavior of accelerated networking is enabled in the UI, I set it to true + fixed the logic for changing it.
> Fix accelerated networking on VM

- .azuredevops/modulePipelines/ms.analysisservices.servers.yml
- .github/workflows/ms.analysisservices.servers.yml
- arm/Microsoft.AnalysisServices/servers/.parameters/max.parameters.json
Microsoft.AnalysisServices-Servers-Max param file
> Microsoft.AnalysisServices-Servers-Max param file

- docs/wiki/The library - Module design.md
- docs/wiki/The library - Module usage.md
- docs/wiki/The library.md
Move from old content + check internal links
> Wiki restructure - The library

- .azuredevops/modulePipelines/ms.apimanagement.service.yml
- .github/workflows/ms.apimanagement.service.yml
- arm/Microsoft.ApiManagement/service/.parameters/min.parameters.json
- settings.json
Microsoft.ApiManagement-service Min Param File Added
[![ApiManagement: Service](https://github.com/SaumilkumarShah/ResourceModules/actions/workflows/ms.apimanagement.service.yml/badge.svg?branch=users%2Fsaumil%2FMicrosoft.ApiManagement-service-fixes)](https://github.com/SaumilkumarShah/ResourceModules/actions/workflows/ms.apimanagement.service.yml)
> Microsoft.ApiManagement-service Min Param File Added

- arm/Microsoft.ContainerRegistry/registries/.parameters/parameters.json
Added private endpoint deployment to container registry
[![ContainerRegistry: Registries](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml/badge.svg?branch=users%2Falsehr%2FregistryEndpoint)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml)
> Added private endpoint deployment to container registry

- arm/Microsoft.ContainerService/managedClusters/deploy.bicep
- arm/Microsoft.ContainerService/managedClusters/readme.md
added some properties
[![ContainerService: ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml)
> Adding new properties to AKS

- arm/Microsoft.ServiceFabric/clusters/deploy.bicep
- arm/Microsoft.ServiceFabric/clusters/readme.md
- Aligned lock API versions across modules to latest that can be fetched via the cmdlet: `2017-04-01`
> Aligned lock API versions across modules

- arm/Microsoft.Network/virtualNetworks/readme.md
- docs/wiki/The library - Module usage.md
- Added example for VNET subnet parameter  
> VNET: Added example for VNET subnet parameter  

- docs/wiki/The library - Module usage.md
- Updated deployment examples for modules/templates
> Updated deployment examples for modules/templates

- arm/Microsoft.EventHub/namespaces/.parameters/parameters.json
- arm/Microsoft.EventHub/namespaces/deploy.bicep
- Fixed an incorrect default value for event hub deployments 
- Updated test
[![EventHub: Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml/badge.svg?branch=users%2Falsehr%2FehFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml)
> Fixed rights ref for event hub

- arm/Microsoft.CognitiveServices/accounts/deploy.bicep
- arm/Microsoft.CognitiveServices/accounts/readme.md
- Added additional parameters
- Regenerated docs
[![CognitiveServices: Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml/badge.svg?branch=users%2Falsehr%2F468_cognitiveProperties)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml)
> Cognitive Services: Added additional parameters

- arm/Microsoft.KeyVault/vaults/deploy.bicep
- arm/Microsoft.KeyVault/vaults/readme.md
Added comments for better separation;
Added publicNetworkAccess parameter;
Added additional log setting for diagnostic settings;
Corrected usage of diagnosticSettingsName;
> Updated KeyVault module

- arm/Microsoft.Insights/components/deploy.bicep
- arm/Microsoft.Insights/components/readme.md
Add RetentionInDays and SamplingPercentage
> Update application insights module

- arm/Microsoft.ContainerService/managedClusters/deploy.bicep
- arm/Microsoft.ContainerService/managedClusters/readme.md
- Updated AKS API version
[![ContainerService: ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Falsehr%2FaksAPI)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml)
> AKS: Updated api version

- arm/Microsoft.Web/serverfarms/.parameters/parameters.json
- arm/Microsoft.Web/serverfarms/deploy.bicep
- arm/Microsoft.Web/serverfarms/readme.md
Add diagnostic settings to App Service Plan
> Add diagnostic settings to App Service Plan

- docs/wiki/Getting started - Setup environment.md
just set the correct name to the description
> Update Getting started - Setup environment.md

- arm/Microsoft.Network/virtualNetworks/deploy.bicep
Fixed incorrect name of diagnostic settings resource.
> [VNET] Fixed incorrect resource name

- bicepconfig.json
- docs/wiki/The CI environment - Bicep configuration file.md
- docs/wiki/The CI environment.md
Added `bicepconfig.json` to disable location warning
> Added `bicepconfig.json` to disable location warning

- .github/workflows/platform.dependencies.yml
Removing parameter set retrieval from dependencies pipeline (not working)
Closes #1297
| Pipeline |
| - |
| [![.Platform: Dependencies](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml/badge.svg?branch=users%2Ferikag%2Ffix-dep-pipeline)](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml) |
> Fix dependency pipeline

- arm/Microsoft.Compute/virtualMachines/readme.md
- arm/Microsoft.Web/serverfarms/readme.md
Bulk regeneration of all module readmes. found 2 updates to fix failing static validation step for vms and serverfarms
| Pipeline |
| - |
| |
> all readmes regenerated

- arm/Microsoft.Compute/virtualMachines/.parameters/linux.min.parameters.json
- arm/Microsoft.Compute/virtualMachines/.parameters/linux.parameters.json
- arm/Microsoft.Compute/virtualMachines/.parameters/windows.min.parameters.json
- arm/Microsoft.Compute/virtualMachines/.parameters/windows.parameters.json
- Updated SKU to work with accelerated notworking (pipeline failure)
| Pipeline |
| - |
|[![Compute: VirtualMachines](https://github.com/Azure/ResourceModules/workflows/Compute:%20VirtualMachines/badge.svg?branch=users%2Falsehr%2FvmSKU)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml) |
> [VM] Updated SKU

- utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
Closes #1315 and #1126 
- Updating general removal sequence to consider 
- Removing private endpoint resources before the actual target resource. 
- Removing `'Microsoft.OperationsManagement/solutions'` before `'Microsoft.OperationalInsights/workspaces/linkedServices'` and before any target resource on which those are applied
Tested for all modules applying private endpoints and solutions
| Pipeline |
| - |
| [![ContainerRegistry: Registries](https://github.com/Azure/ResourceModules/workflows/ContainerRegistry:%20Registries/badge.svg?branch=users%2Ferikag%2F1126)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml) |
| [![KeyVault: …
> Updating general removal sequence (fixing PE removal)

- README.md
Fix home tooling section wiki and status badge links.
| Pipeline |
| - |
| |
> Fix home tooling section

- arm/Microsoft.ContainerService/managedClusters/deploy.bicep
- arm/Microsoft.KubernetesConfiguration/extensions/.parameters/min.parameters.json
- arm/Microsoft.KubernetesConfiguration/extensions/.parameters/parameters.json
- arm/Microsoft.KubernetesConfiguration/extensions/deploy.bicep
- arm/Microsoft.KubernetesConfiguration/extensions/readme.md
- arm/Microsoft.KubernetesConfiguration/fluxConfigurations/.parameters/min.parameters.json
- Changed the min parameter files to succeed build. 
- Removed one property, which is now set by logic (if version is provided)
- fixed position of AKS SKU
[![KubernetesConfiguration: Extensions](https://github.com/Azure/ResourceModules/actions/workflows/ms.kubernetesconfiguration.extensions.yml/badge.svg?branch=users%2Frahalan%2FFixFlux)](https://github.com/Azure/ResourceModules/actions/workflows/ms.kubernetesconfiguration.extensions.yml)
[![KubernetesConfiguration: FluxConfigurations](https://github.com/Azure/ResourceModules/actions/workflows/ms.kubernetesconfiguration.fluxconfigurations.yml/badge.svg?branch=users%2Frahalan%2FFixFlux)](https://github.com/Azure/ResourceModules/actions/workflows/ms.kubernetesconfiguration.fluxconfigurations.yml)
Please delete options that are not …
> Fix Flux extension failure on pipeline runs

- arm/Microsoft.Network/virtualNetworks/.parameters/parameters.json
- arm/Microsoft.Network/virtualNetworks/deploy.bicep
- arm/Microsoft.Network/virtualNetworks/subnets/.bicep/nested_rbac.bicep
- arm/Microsoft.Network/virtualNetworks/subnets/deploy.bicep
- arm/Microsoft.Network/virtualNetworks/subnets/readme.md
Adding RBAC to subnets
| Pipeline |
| - |
|[![Network: VirtualNetworks](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml/badge.svg?branch=Azure-main)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml) |
> add subnet rbac

- .azuredevops/platformPipelines/platform.dependencies.yml
- .github/workflows/platform.dependencies.yml
- utilities/pipelines/dependencies/Microsoft.Web/sites/parameters/parameters.json
- Added function app deployment to dependency pipeline
| Pipeline |
| - |
| [![.Platform: Dependencies](https://github.com/Azure/ResourceModules/workflows/.Platform:%20Dependencies/badge.svg?branch=users%2Falsehr%2F1329_appServiceMitigation)](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml) |
| Azure DevOps [link](https://dev.azure.com/servicescode/infra-as-code-source/_build/results?buildId=275925&view=results) |
> Added function app to prevent serverfarm auto-removal

- arm/Microsoft.Storage/storageAccounts/.parameters/parameters.json
- arm/Microsoft.Storage/storageAccounts/readme.md
- Added IP test
| Pipeline |
| - |
| [![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/workflows/Storage:%20StorageAccounts/badge.svg?branch=users%2Falsehr%2FextendedTests)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml)|
> Storage: Added IP test

- arm/Microsoft.Network/virtualNetworkGateways/.parameters/expressRoute.parameters.json
- arm/Microsoft.Network/virtualNetworkGateways/deploy.bicep
- arm/Microsoft.Network/virtualNetworkGateways/readme.md
Small suggestion how to get rid of some of the variables
[![Network: VirtualNetworkGateways](https://github.com/Azure/ResourceModules/workflows/Network:%20VirtualNetworkGateways/badge.svg?branch=users%2Fmsanzdelrio%2Fvngw-ip-fix_sugg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworkgateways.yml)
> VNET Gateway: Small suggested changes to reduce amount of variables

- arm/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
Compare with #1242 (for VMs)
| Pipeline |
| - |
| |
> VMSS add Condition to EncryptionAtHost

- arm/Microsoft.RecoveryServices/vaults/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/readme.md
Updating RSV API Version to the latest, also updating README as well. 
| Pipeline |
| - |
|[![Build Status](https://dev.azure.com/seseichtMSFT/CARLM-SeSeicht/_apis/build/status/RecoveryServices%20-%20Vaults?branchName=main)](https://dev.azure.com/seseichtMSFT/CARLM-SeSeicht/_build/latest?definitionId=311&branchName=main) |
> update Recovery Services Vault API to latest

- .azuredevops/modulePipelines/ms.resources.deploymentscripts.yml
parameter paths were not correct in yaml according to files
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/seseichtMSFT/CARLM-SeSeicht/_apis/build/status/Resources%20-%20DeploymentScripts?branchName=main)](https://dev.azure.com/seseichtMSFT/CARLM-SeSeicht/_build/latest?definitionId=312&branchName=main)|
> [Modules] update parameter paths of Deployment Scripts

- utilities/pipelines/resourceRemoval/helper/Invoke-ResourcePostRemoval.ps1
- Implemented purge for AppConfiguration
| Pipeline |
| - |
|  [![AppConfiguration: ConfigurationStores](https://github.com/Azure/ResourceModules/actions/workflows/ms.appconfiguration.configurationstores.yml/badge.svg?branch=users%2Falsehr%2FappConfigPurge)](https://github.com/Azure/ResourceModules/actions/workflows/ms.appconfiguration.configurationstores.yml) |
> [Testing] Implemented purge for AppConfiguration

- .azuredevops/platformPipelines/platform.dependencies.yml
- Updated conditions for ADO dependency pipeline
- Moved conditions to compile-time conditions (which fixes a bug of the VHD condition)
- Removed redundant conditions
cc: @SeSeicht 
| Pipeline |
| - |
| [Flags disabled](https://dev.azure.com/servicescode/infra-as-code-source/_build/results?buildId=281634&view=results) |
| [Flags enabled](https://dev.azure.com/servicescode/infra-as-code-source/_build/results?buildId=281635&view=results) |
> [Pipeline] Updated conditions for ADO dependency pipeline

- .azuredevops/platformPipelines/platform.updateReadMe.yml
- .azuredevops/platformPipelines/platform.wiki-sync.yml
Updates some references to the variables file that was moved to the root.
| Pipeline |
| - |
| |
> Updated references to the moved global variables file

- arm/Microsoft.RecoveryServices/vaults/protectionContainers/protectedItems/deploy.bicep
- arm/Microsoft.RecoveryServices/vaults/protectionContainers/protectedItems/readme.md
Added . to multiple parameters to fix failed Pester tests. 
| Pipeline |
| - |
| |
> Updated parameters description to fix failed Pester tests

- utilities/pipelines/dependencies/Microsoft.DesktopVirtualization/hostpools/parameters/parameters.json
Replaced `validationEnviroment` -> `validationEnvironment`
| Pipeline |
| - |
| [![.Platform: Dependencies](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml/badge.svg?branch=users%2Fmast%2FdepAVDBugfix)](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml) |
> [Bug] Corrected AVD Host pool parameter for dependency pipeline

- utilities/pipelines/dependencies/Microsoft.RecoveryServices/vaults/parameters/parameters.json
Added `"principalType": "ServicePrincipal` to RSV param.
| Pipeline |
| - |
| Coming! |
> [Bug] Added principalType to RSV param

- arm/Microsoft.Storage/storageAccounts/readme.md
Minor update to the readme example for networkAcls . Changed from subnetId to Id. 
| Pipeline |
| - |
| |
> [Modules] Storage Account minor update to param example in networkAcls.

- arm/Microsoft.ContainerRegistry/registries/deploy.bicep
> Applied all default values as per  NIST 800 
| Pipeline |
| - |
| |
> [Modules] Container registry updated default value

- arm/Microsoft.ContainerRegistry/registries/deploy.bicep
- arm/Microsoft.ContainerRegistry/registries/readme.md
Reverting default encryptionStatus to disabled. Needs to be looked into more thoroughly
Updating container registry readme file missing in latest PR
| Pipeline |
| - |
| [![ContainerRegistry: Registries](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml/badge.svg?branch=users%2Ferikag%2Ffix-containerReg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml) |
> [Modules] Revert encryption default value and update container registry readme

- arm/Microsoft.Authorization/locks/deploy.bicep
- arm/Microsoft.Authorization/locks/resourceGroup/deploy.bicep
- arm/Microsoft.Authorization/locks/resourceGroup/readme.md
- arm/Microsoft.Authorization/locks/subscription/deploy.bicep
- arm/Microsoft.Authorization/locks/subscription/readme.md
Fixing scope for lock outputs
| Pipeline |
| - |
| [![Authorization: Locks](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.locks.yml/badge.svg?branch=users%2Ferikag%2Ffix-locks)](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.locks.yml) |
> [Modules] Fix locks output scope

- utilities/tools/Format-Release.ps1
- utilities/tools/Get-FormattedGitHubRelease.ps1
- Added a `Format-Release` function we can use to reduce the effort when summarizing all updates for a new release.
> [Utilities] Added Format-Release function

- docs/wiki/Contribution guide - Contribution flow.md
- docs/wiki/_Sidebar.md
- Adding missing link to sidebar for newly added page
- Updating PR instructions contribution flow
| Pipeline |
| - |
| |
> [Wiki] Sidebar and contribution flow update

- docs/wiki/Contribution guide - Contribution flow.md
> [Wiki] Contribution flow remove duplicate

- .github/workflows/platform.dependencies.yml
- utilities/pipelines/dependencies/Microsoft.Compute/diskEncryptionSets/parameters/parameters.json
- Updated 2 parameters
| Pipeline |
| - |
| [![.Platform: Dependencies](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml/badge.svg?branch=users%2Falsehr%2FdependencyFix)](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml) |
> [Fixes] Fixed DiskEncryption Dependency Parameters

- modules/Microsoft.Compute/virtualMachines/.bicep/nested_networkInterface.bicep
- modules/Microsoft.Compute/virtualMachines/.test/linux.autmg.parameters.json
- modules/Microsoft.Compute/virtualMachines/.test/linux.min.parameters.json
- modules/Microsoft.Compute/virtualMachines/.test/linux.parameters.json
- modules/Microsoft.Compute/virtualMachines/.test/windows.autmg.parameters.json
- modules/Microsoft.Compute/virtualMachines/.test/windows.min.parameters.json
- modules/Microsoft.Compute/virtualMachines/.test/windows.parameters.json
- modules/Microsoft.Compute/virtualMachines/readme.md
- modules/Microsoft.Network/networkInterfaces/.test/min.parameters.json
- modules/Microsoft.Network/networkInterfaces/.test/parameters.json
- modules/Microsoft.Network/networkInterfaces/deploy.bicep
- modules/Microsoft.Network/networkInterfaces/readme.md
- Updated subnetID to subnetResourceId for consistency
> Follow-up to #1677 
| Pipeline |
| - |
| [![Compute: VirtualMachines](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml/badge.svg?branch=users%2Falsehr%2FnicPropertyName)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml) |
| [![Network: NetworkInterfaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkinterfaces.yml/badge.svg?branch=users%2Falsehr%2FnicPropertyName)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkinterfaces.yml) |
> [Modules] NIC: Updated subnetID to subnetResourceId for consistency

- docs/wiki/Solution creation.md
- Updated template-orchestrated solution examples
- Moved parameters into module deployments
- Simplified references
> [Wiki] Updated template-orchestrated solution examples

- modules/Microsoft.Compute/virtualMachines/readme.md
- modules/Microsoft.Network/networkInterfaces/deploy.bicep
- modules/Microsoft.Network/networkInterfaces/readme.md
closes #1718 
- Updated nic module API version and documentation.
- Updated VM documentation for the new nic api version
| Pipeline |
| - |
| [![Network: NetworkInterfaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkinterfaces.yml/badge.svg?branch=users%2Fahmad%2FnicUpdates)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkinterfaces.yml)|
|[![Compute: VirtualMachines](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml/badge.svg?branch=users%2Fahmad%2FnicUpdates)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml)|
Please delete options that are not …
> [Modules] Updated Network Interface module API Version

- .github/workflows/platform.dependencies.yml
- utilities/pipelines/dependencies/Microsoft.Compute/virtualMachines/parameters/parameters.json
- Fixing bug in VM parameters causing VM job in dependencies pipeline to fail
- Updating OS version 
| Pipeline |
| - |
| [![.Platform: Dependencies](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml/badge.svg?branch=users%2Ferikag%2Ffix-dependencies)](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml) unrelated error with disk encryption set |
> [Fixes] Dependencies pipeline VM

- modules/Microsoft.Storage/storageAccounts/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Storage/storageAccounts/.test/parameters.json
- modules/Microsoft.Storage/storageAccounts/blobServices/containers/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Storage/storageAccounts/blobServices/containers/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies/readme.md
- modules/Microsoft.Storage/storageAccounts/blobServices/containers/readme.md
- modules/Microsoft.Storage/storageAccounts/blobServices/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/blobServices/readme.md
- modules/Microsoft.Storage/storageAccounts/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/fileServices/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/fileServices/readme.md
- modules/Microsoft.Storage/storageAccounts/fileServices/shares/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/fileServices/shares/readme.md
- modules/Microsoft.Storage/storageAccounts/managementPolicies/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/managementPolicies/readme.md
- modules/Microsoft.Storage/storageAccounts/queueServices/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/queueServices/queues/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Storage/storageAccounts/queueServices/queues/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/queueServices/queues/readme.md
- modules/Microsoft.Storage/storageAccounts/queueServices/readme.md
- modules/Microsoft.Storage/storageAccounts/readme.md
- modules/Microsoft.Storage/storageAccounts/tableServices/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/tableServices/readme.md
- modules/Microsoft.Storage/storageAccounts/tableServices/tables/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/tableServices/tables/readme.md
Closes #1732 
Updating all versions to the latest documented by ARR 2021-09-01
| Pipeline |
| - |
| [![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Ferikag%2Ftest-storage-acl)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) |
> [Modules] Update Microsoft.Storage modules API version

- .github/workflows/ms.aad.domainservices.yml
- Fixed a typo for the AAD Azure DevOps pipeline
> [Fixes] ADO pipeline typo fix

- utilities/tools/Clear-ManagementGroupDeployment.ps1
- Adjusted the implementation to split chunks
> [Utility] Small update to management group deployments removal script to better handle small number of deployments

- docs/wiki/Getting started - Scenario 2 Onboard module library and CI environment.md
- global.variables.yml
- settings.json
- utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
> Restored CARML Settings

- modules/Microsoft.Network/applicationGateways/.test/parameters.json
- modules/Microsoft.Network/applicationGateways/readme.md
Fixes #1741 
Fixes the network application gateway module as recent properties of one of the parameters is now mandatory
| Pipeline |
| - |
|[![Network: ApplicationGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationgateways.yml/badge.svg?branch=users%2Fahmad%2FappGwFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationgateways.yml) |
> [Modules] Update the Application Gateway test parameter files to support mandatory properties after an API version update

- modules/Microsoft.ContainerService/managedClusters/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/readme.md
added more Log types
| Pipeline |
| - |
| [![ContainerService: ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=1154-add-pip-to-azure-fw-and-for-lb-check-for-others)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml)
> [modules] Adding more log types to AKS

- modules/Microsoft.KeyVault/vaults/.test/min.parameters.json
- modules/Microsoft.KeyVault/vaults/deploy.bicep
- modules/Microsoft.KeyVault/vaults/readme.md
- modules/Microsoft.KeyVault/vaults/version.json
Closes #1756 #1458 
| Pipeline |
| - |
| [![KeyVault: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=users%2Ferikag%2F1756-kv)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml) |
> [Modules] Remove autogenerated unique name from KV

- utilities/pipelines/dependencies/constructs/StoreVhdToStorage/deploy.bicep
- Fixed subscription ID reference in dependency construct
> [Fixes] Fixed subscription ID reference in dependency construct

- .github/actions/templates/getModuleTestFiles/action.yml
- .github/actions/templates/getWorkflowInput/action.yml
- .github/actions/templates/publishModule/action.yml
- .github/actions/templates/setEnvironmentVariables/action.yml
- .github/actions/templates/validateModuleDeployment/action.yml
- .github/actions/templates/validateModulePester/action.yml
- .github/workflows/ms.analysisservices.servers.yml
- .github/workflows/ms.apimanagement.service.yml
- .github/workflows/ms.web.serverfarms.yml
- Small working fixes 
- Replaced double quotation with single quotation where applicable
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2Fpipelineformat)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
> [Fixes] Small working fixes and updates to quotation

- modules/Microsoft.AppConfiguration/configurationStores/readme.md
- modules/Microsoft.Automation/automationAccounts/readme.md
- modules/Microsoft.Batch/batchAccounts/readme.md
- modules/Microsoft.Cache/redis/readme.md
- modules/Microsoft.CognitiveServices/accounts/readme.md
- modules/Microsoft.ContainerRegistry/registries/readme.md
- modules/Microsoft.DataFactory/factories/managedVirtualNetwork/managedPrivateEndpoints/readme.md
- modules/Microsoft.DataFactory/factories/readme.md
- modules/Microsoft.EventGrid/topics/readme.md
- modules/Microsoft.EventHub/namespaces/readme.md
- modules/Microsoft.Insights/privateLinkScopes/readme.md
- modules/Microsoft.KeyVault/vaults/readme.md
- modules/Microsoft.Logic/workflows/readme.md
- modules/Microsoft.MachineLearningServices/workspaces/readme.md
- modules/Microsoft.RecoveryServices/vaults/readme.md
- modules/Microsoft.ServiceBus/namespaces/readme.md
- modules/Microsoft.SignalRService/webPubSub/readme.md
- modules/Microsoft.Sql/servers/readme.md
- modules/Microsoft.Storage/storageAccounts/readme.md
- modules/Microsoft.Synapse/privateLinkHubs/readme.md
- modules/Microsoft.Synapse/workspaces/readme.md
- modules/Microsoft.Web/sites/readme.md
- modules/Microsoft.Web/staticSites/readme.md
- utilities/tools/moduleReadMeSource/resourceUsage-privateEndpoints.md
Closes #1802 
This PR updates the primary readme section for referencing a private endpoint parameter usage. After that regenerated all documentations to ensure we update them with the guidance fix.
See issue for more details.
| Pipeline |
| - |
|[![AppConfiguration: ConfigurationStores](https://github.com/Azure/ResourceModules/actions/workflows/ms.appconfiguration.configurationstores.yml/badge.svg?branch=users%2Fahmad%2FbugFix_privateDnsZoneResourceIds)](https://github.com/Azure/ResourceModules/actions/workflows/ms.appconfiguration.configurationstores.yml) |
|[![Automation: AutomationAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.automation.automationaccounts.yml/badge …
> [Bug Fix] Corrected Private Endpoint Parameter Usage documentation

- modules/Microsoft.Network/networkWatchers/readme.md
The task would be to scan over each of the following policies and make sure, that the module is per default complying to them.\built-in-policies\policyDefinitions\Network\NetworkWatcher_Enabled_Audit.json
| Pipeline |
| - |
| |
- Update to documentation
> [Modules] Updated network watcher resource group

- docs/wiki/Getting started - Scenario 2 Onboard module library and CI environment.md
- modules/Microsoft.CognitiveServices/accounts/.test/encr.parameters.json
- modules/Microsoft.CognitiveServices/accounts/readme.md
- Updated MSI ref
- Added missing docs
- Fixed docs ref
| Pipeline |
| - |
| [![CognitiveServices: Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml/badge.svg?branch=users%2Falsehr%2FcognServ_fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml) |
> [Fixes] CognitiveServices: Updated MSI ref & docs

- modules/Microsoft.Sql/servers/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Sql/servers/databases/deploy.bicep
- modules/Microsoft.Sql/servers/databases/readme.md
- modules/Microsoft.Sql/servers/deploy.bicep
- modules/Microsoft.Sql/servers/firewallRules/deploy.bicep
- modules/Microsoft.Sql/servers/firewallRules/readme.md
- modules/Microsoft.Sql/servers/readme.md
- modules/Microsoft.Sql/servers/securityAlertPolicies/deploy.bicep
- modules/Microsoft.Sql/servers/securityAlertPolicies/readme.md
- modules/Microsoft.Sql/servers/vulnerabilityAssessments/deploy.bicep
- modules/Microsoft.Sql/servers/vulnerabilityAssessments/readme.md
Closes #1856 
Update API version to latest documented
| Pipeline |
| - |
| [![Sql: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Ferikag%2Fsql)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml) |
> [Modules] SQL server API version update

- modules/Microsoft.Synapse/workspaces/readme.md
Closes #1853 
Updating readme causing the static validation job to fail
| Pipeline |
| - |
| [![Synapse: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml/badge.svg?branch=users%2Ferikag%2Fsynapse)](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml) |
> [Modules] Regenerating Synapse Workspaces module readme

- modules/Microsoft.Logic/workflows/readme.md
- Fixed Logic App Readme
| Pipeline |
| - |
| [![Logic: Workflows](https://github.com/Azure/ResourceModules/actions/workflows/ms.logic.workflows.yml/badge.svg?branch=users%2Falsehr%2FlogicAppReadme)](https://github.com/Azure/ResourceModules/actions/workflows/ms.logic.workflows.yml) |
> [Fixes] Fixed Logic App Readme

- modules/Microsoft.ContainerRegistry/registries/.test/parameters.json
- modules/Microsoft.ContainerRegistry/registries/readme.md
- Updated ACR name to bypass 'stuck' Azure resource
| Pipeline |
| - |
| [![ContainerRegistry: Registries](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml/badge.svg?branch=users%2Falsehr%2Facrname)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerregistry.registries.yml) |
> [Modules] Updated ACR name to bypass 'stuck' Azure resource

- modules/Microsoft.ContainerInstance/containerGroups/deploy.bicep
- modules/Microsoft.ContainerInstance/containerGroups/readme.md
- Updated container instance API version
| Pipeline |
| - |
| [![ContainerInstance: ContainerGroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerinstance.containergroups.yml/badge.svg?branch=users%2Falsehr%2FconInFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerinstance.containergroups.yml) |
> [Modules] Updated container instance API version

- modules/Microsoft.Sql/managedInstances/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Sql/managedInstances/.test/min.parameters.json
- modules/Microsoft.Sql/managedInstances/.test/parameters.json
- modules/Microsoft.Sql/managedInstances/administrators/deploy.bicep
- modules/Microsoft.Sql/managedInstances/administrators/readme.md
- modules/Microsoft.Sql/managedInstances/databases/backupLongTermRetentionPolicies/deploy.bicep
- modules/Microsoft.Sql/managedInstances/databases/backupLongTermRetentionPolicies/readme.md
- modules/Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies/deploy.bicep
- modules/Microsoft.Sql/managedInstances/databases/backupShortTermRetentionPolicies/readme.md
- modules/Microsoft.Sql/managedInstances/databases/deploy.bicep
- modules/Microsoft.Sql/managedInstances/databases/readme.md
- modules/Microsoft.Sql/managedInstances/deploy.bicep
- modules/Microsoft.Sql/managedInstances/encryptionProtector/deploy.bicep
- modules/Microsoft.Sql/managedInstances/encryptionProtector/readme.md
- modules/Microsoft.Sql/managedInstances/keys/deploy.bicep
- modules/Microsoft.Sql/managedInstances/keys/readme.md
- modules/Microsoft.Sql/managedInstances/readme.md
- modules/Microsoft.Sql/managedInstances/securityAlertPolicies/deploy.bicep
- modules/Microsoft.Sql/managedInstances/securityAlertPolicies/readme.md
- modules/Microsoft.Sql/managedInstances/vulnerabilityAssessments/deploy.bicep
- modules/Microsoft.Sql/managedInstances/vulnerabilityAssessments/readme.md
- utilities/pipelines/dependencies/Microsoft.Network/virtualNetworks/parameters/6.sqlmi.parameters.json
Closes #1858
| Pipeline |
| - |
| [![Sql: ManagedInstances](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml/badge.svg?branch=users%2Ferikag%2Fsqlmi)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml) |
> [Modules] SQLMI API version update

- modules/Microsoft.Sql/servers/.test/parameters.json
- modules/Microsoft.Sql/servers/.test/pe.parameters.json
- modules/Microsoft.Sql/servers/deploy.bicep
- modules/Microsoft.Sql/servers/readme.md
- modules/Microsoft.Sql/servers/version.json
- modules/Microsoft.Sql/servers/virtualNetworkRules/deploy.bicep
- modules/Microsoft.Sql/servers/virtualNetworkRules/readme.md
- modules/Microsoft.Sql/servers/virtualNetworkRules/version.json
Adding virtualNetworkRule child
Updating networking to disable public network access by default if pe is set and network rules are not set
Adding pe test file
Adding privateDNSResourceIds to test files
| Pipeline |
| - |
| [![Sql: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Ferikag%2F1895-sql-dns)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml) |
> [Modules] Configure privateDnsZoneGroups on sqlServer

- modules/Microsoft.RecoveryServices/vaults/.test/parameters.json
- modules/Microsoft.RecoveryServices/vaults/readme.md
Adding privateDNSResourceIds to configure privateDnsZoneGroups on RSV
Aligning tab size
| Pipeline |
| - |
| [![RecoveryServices: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml/badge.svg?branch=users%2Ferikag%2F1893-rsv-dns)](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml) |
> [Modules] Configure privateDnsZoneGroups on RSV

- modules/Microsoft.Insights/privateLinkScopes/.test/min.parameters.json
- modules/Microsoft.Insights/privateLinkScopes/.test/parameters.json
- modules/Microsoft.Insights/privateLinkScopes/readme.md
Configure privateDnsZoneGroups on privateLinkScopes
Add min parameter file
| Pipeline |
| - |
| [![Insights: PrivateLinkScopes](https://github.com/Azure/ResourceModules/actions/workflows/ms.insights.privatelinkscopes.yml/badge.svg?branch=users%2Ferikag%2F1969-monitor-dns)](https://github.com/Azure/ResourceModules/actions/workflows/ms.insights.privatelinkscopes.yml) |
> [Modules] Configure privateDnsZoneGroups on privateLinkScopes

- modules/Microsoft.Synapse/privateLinkHubs/.test/min.parameters.json
- modules/Microsoft.Synapse/privateLinkHubs/.test/parameters.json
- modules/Microsoft.Synapse/privateLinkHubs/readme.md
Configure privateDnsZoneGroups on main test file
Update resource naming to use namePrefix
| Pipeline |
| - |
| [![Synapse: PrivateLinkHubs](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.privatelinkhubs.yml/badge.svg?branch=users%2Ferikag%2F1971-synapse-dns)](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.privatelinkhubs.yml) |
> [Modules] Configure privateDnsZoneGroups on Synapse privateLinkHubs

- modules/Microsoft.Cache/redis/.test/min.parameters.json
- modules/Microsoft.Cache/redis/.test/parameters.json
- modules/Microsoft.Cache/redis/readme.md
Adding privateDNSResourceIds to main test file
| Pipeline |
| - |
| [![Cache: Redis](https://github.com/Azure/ResourceModules/actions/workflows/ms.cache.redis.yml/badge.svg?branch=users%2Ferikag%2F1901-redis-dns)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cache.redis.yml) |
> [Modules] Configure privateDnsZoneGroups on redisCache

- .github/workflows/ms.powerbidedicated.capacities.yml
Fixed bug in GitHub Actions workflow for Microsoft.PowerBiDedicated/capacities
| Pipeline |
| - |
| |
> [Fixes] Updated PowerBIDedicated workflow name in env vars

- modules/Microsoft.Web/staticSites/.test/parameters.json
- modules/Microsoft.Web/staticSites/deploy.bicep
- modules/Microsoft.Web/staticSites/readme.md
Add privateDnsZoneGroups to tests using private endpoints
| Pipeline |
| - |
| [![Web: StaticSites](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.staticsites.yml/badge.svg?branch=users%2Ferikag%2F2006-staticsites-dns)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.staticsites.yml) |
> [Modules] Configure privateDnsZoneGroups on web staticSites

- modules/Microsoft.Web/sites/.test/fa.parameters.json
- modules/Microsoft.Web/sites/.test/wa.parameters.json
- modules/Microsoft.Web/sites/readme.md
Add privateDnsZoneGroups to tests using private endpoints
| Pipeline |
| - |
| [![Web: Sites](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml/badge.svg?branch=users%2Ferikag%2F2004-sites-dns)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml) |
> [Modules] Configure privateDnsZoneGroups on web sites

- .github/workflows/ms.powerbidedicated.capacities.yml
- Align GH workflow to latest
| Pipeline |
| - |
| [![PowerBiDedicated: Capacities](https://github.com/Azure/ResourceModules/actions/workflows/ms.powerbidedicated.capacities.yml/badge.svg?branch=users%2Ferikag%2F2020-fix-powerbi)](https://github.com/Azure/ResourceModules/actions/workflows/ms.powerbidedicated.capacities.yml) |
> [Fixes] Fix failing PowerBIDedicated Capacities workflow

- .github/actions/templates/validateModuleDeployment/action.yml
- .github/workflows/platform.dependencies.yml
- utilities/pipelines/dependencies/constructs/StoreVhdToStorage/deploymentScripts/Copy-VhdToStorageAccount.ps1
- Small fix for dependency pipeline & VHD build in particular
| Pipeline |
| - |
| [![.Platform: Dependencies](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml/badge.svg?branch=users%2Falsehr%2FdependencyVHD)](https://github.com/Azure/ResourceModules/actions/workflows/platform.dependencies.yml) |
> [Fixes] Fix failing dependencies pipeline on VHD creation

- docs/wiki/Known issues.md
Document known issue with DES redeployment in dependencies pipeline 
| Pipeline |
| - |
| |
> [Wiki] Document known issue with DES redeployment in dependencies pipeline

- docs/wiki/Known issues.md
Add `Limited job execution time` section to `Known Issues`
| Pipeline |
| - |
| |
> [Wiki] Add `Limited job execution time` section to `Known Issues`

- ps-rule.yaml
> [Hackathon] Topic 6 - Create ps-rule.yaml

- .github/workflows/ms.resources.resourcegroups.yml
- ps-rule.yaml
> [Hackathon] Token replacement for the resource group module

- .github/workflows/ms.network.virtualnetworks.yml
- modules/Microsoft.Network/virtualNetworks/.test/vnet-ps-rule.yaml
- ps-rule.yaml
> Please include a summary of the change and which issue is fixed. 
[Hackathon] PSRule addition for VNet resource 
| Pipeline |
| - |
| |
> [Hackathon] PSRule addition for VNet resource 

- .github/workflows/ms.network.virtualnetworks.yml
- .ps-rule/dep-suppress.Rule.yaml
- modules/Microsoft.Network/virtualNetworks/.test/vnet-ps-rule.yaml
Added suppression group for dependency resources
| Pipeline |
| - |
| |
> [Hackathon] Added suppression group for dependency resources

- .github/workflows/ms.keyvault.vaults.yml
- .github/workflows/ms.network.virtualnetworks.yml
- .github/workflows/ms.resources.resourcegroups.yml
- modules/Microsoft.Network/virtualNetworks/.test/vnet-ps-rule.yaml
.github\workflows\ms.network.virtualnetworks.yml updated to print output in csv format
modules\Microsoft.Network\virtualNetworks\.test\vnet-ps-rule.yaml updated to suppress summary and outcome (fail)
> [Hackaton] Psrule output on csv format with detailed results

- .github/workflows/ms.network.virtualnetworks.yml
- modules/Microsoft.Network/virtualNetworks/.test/vnet-ps-rule.yaml
- utilities/pipelines/PSRuleValidation/Set-PSRuleOutput.ps1
Updated vnetwork workflow and psrule output script
> [Hackaton] Added PSRule Output to job summary

- .github/actions/templates/validateModulePSRule/action.yml
- .github/workflows/ms.network.virtualnetworks.yml
- ps-rule.yaml
| Pipeline |
| - |
| |
- [x ] New feature (non-breaking change which adds functionality)
> [Hackaton] Hack/topic6 virtual network PSrule on GitHub Action

- .github/actions/templates/validateModulePSRule/action.yml
- .github/workflows/ms.keyvault.vaults.yml
- .github/workflows/ms.network.virtualnetworks.yml
- .github/workflows/ms.resources.resourcegroups.yml
- ps-rule.yaml
- utilities/pipelines/PSRuleValidation/Set-PSRuleOutput.ps1
| Pipeline |
| - |
| |
- [X ] New feature (non-breaking change which adds functionality)
> [hackaton]: Hack/topic6 fabmas/psrule test updated RG, KV, VNET

- .ps-rule/min-suppress.Rule.yaml
- ps-rule.yaml
> [Hackathon]  Suppress rules where not required

- .azuredevops/pipelineTemplates/jobs.publishModule.yml
- .github/actions/templates/publishModule/action.yml
- docs/wiki/Getting started - Scenario 1 Consume library.md
- docs/wiki/Solution creation.md
- settings.yml
- utilities/pipelines/resourcePublish/Publish-ModuleToBicepRegistry.ps1
1. Enable anonymous access on the current CARML repo. @segraef 
2. Introduce `bicepRegistryPublic` switch and adjust code (add `bicepRegistryPublic` in wiki and all yml pipelines). @ArielRam99
3. Create an automated way (script) to get current versions and put it on a Wiki page.
1. Crawl it with `az acr repository list`. @arnoldna
2. Get latest versions of all modules.
3. Optional: (Remove child modules)
4. Place script in `utilities/tools/`.
5. Create a list or all parent modules with URIs as output and put it on the markdown page.
6. Adjust publish modules script to support latest. @segraef @arnoldna 
```
az acr repository list --name adpsxxazacrx001
az acr repository show --name adpsxxazacrx001 --image bicep/modules/microsoft.storage.storageaccounts:04
az acr repository show-tags …
```
> [Hackathon] Public Bicep Registry implementation

- .azuredevops/pipelineTemplates/jobs.validateModulePSRule.yml
- .azuredevops/pipelineTemplates/stages.module.yml
> [Hackathon] Added psrule to ado pipelines

- .github/actions/templates/publishModule/action.yml
| Pipeline |
| - |
| [![KeyVault: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=hack%2Ftopic4-judechen1)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml) |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status/Modules/KeyVault%20-%20Vaults?repoName=Azure%2FResourceModules&branchName=hack%2Ftopic4-judechen1)](https://dev.azure.com/carml/CARML/_build/latest?definitionId=46&repoName=Azure%2FRe …
> fixed typo.

- modules/Microsoft.Consumption/budgets/readme.md
The minor missing newline causes the module static validation to fail
| Pipeline |
| - |
| [![Consumption: Budgets](https://github.com/Azure/ResourceModules/actions/workflows/ms.consumption.budgets.yml/badge.svg?branch=users%2Ferikag%2F2140-fix-budgets)](https://github.com/Azure/ResourceModules/actions/workflows/ms.consumption.budgets.yml) |
> [Fixes] Consumption Budget readme update

- modules/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/readme.md
Updated readme so the test will not fail
| Pipeline |
| - |
| |
> fix readme

- modules/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/readme.md
Removed TODO placeholder
Aligned header to plural form
| Pipeline |
| - |
| [![Network: ApplicationGatewayWebApplicationFirewallPolicies](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationgatewaywebapplicationfirewallpolicies.yml/badge.svg?branch=users%2Ferikag%2Fcleanup-todo)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationgatewaywebapplicationfirewallpolicies.yml) |
> [Fixes] Update WAF readme

- modules/Microsoft.KeyVault/vaults/.test/common/deploy.test.bicep
- modules/Microsoft.KeyVault/vaults/.test/pe/deploy.test.bicep
- modules/Microsoft.KeyVault/vaults/readme.md
Add tags to Microsoft.KeyVault\vaults common test
Can be used as a reference for similar issues tracked in #2191
| Pipeline |
| - |
| [![KeyVault: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=users%2Ferikag%2F2192-kv-tags)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml) |
> [Modules] Add tags to `Microsoft.KeyVault\vaults` common test

- modules/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/agentPools/readme.md
- modules/Microsoft.ContainerService/managedClusters/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/readme.md
- modules/Microsoft.KubernetesConfiguration/extensions/.test/common/dependencies.bicep
- modules/Microsoft.KubernetesConfiguration/extensions/.test/min/dependencies.bicep
- modules/Microsoft.KubernetesConfiguration/extensions/deploy.bicep
- modules/Microsoft.KubernetesConfiguration/fluxConfigurations/.test/common/dependencies.bicep
- modules/Microsoft.KubernetesConfiguration/fluxConfigurations/.test/min/dependencies.bicep
- modules/Microsoft.KubernetesConfiguration/fluxConfigurations/deploy.bicep
Update API version and regenerate readmes to fix pipeline failure on static validation.
| Pipeline |
| - |
| [![ContainerService: ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Ferikag%2F2197-aks-api)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml) |
> [Modules] Update AKS API version

- modules/Microsoft.DataFactory/factories/readme.md
Regenerating DataFactory factory readme file causing its module pipeline to fail on static validation
| Pipeline |
| - |
| [![DataFactory: Factories](https://github.com/Azure/ResourceModules/actions/workflows/ms.datafactory.factories.yml/badge.svg?branch=users%2Ferikag%2F2210-fix-datafactory)](https://github.com/Azure/ResourceModules/actions/workflows/ms.datafactory.factories.yml) |
> [Fixes] Regenerating DataFactory factory readme file

- .azuredevops/modulePipelines/ms.network.dnsresolvers.yml
- .github/workflows/ms.network.dnsresolvers.yml
- modules/Microsoft.Network/dnsResolvers/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Network/dnsResolvers/.test/common/dependencies.bicep
- modules/Microsoft.Network/dnsResolvers/.test/common/deploy.test.bicep
- modules/Microsoft.Network/dnsResolvers/deploy.bicep
- modules/Microsoft.Network/dnsResolvers/readme.md
- modules/Microsoft.Network/dnsResolvers/version.json
Added new modules for Microsoft.Network/DNSResolvers, added with new dependency approach for Virtual Network/Subnet Requirements.
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status/Modules/Network%20-%20DNS%20Resolvers?branchName=users%2Fcsidebotham%2F2199-feature-request-create-new-module-for-private-dns-resolver-service)](https://dev.azure.com/carml/CARML/_build/latest?definitionId=116&branchName=users%2Fcsidebotham%2F2199-feature-request-create-new-module-for-private-dns-resolver-service)|
> [Modules] New module DNS Private Resolvers with new dependency approach

- modules/Microsoft.Sql/servers/.test/common/dependencies.bicep
- modules/Microsoft.Sql/servers/.test/pe/dependencies.bicep
Fixing Sql Server failing pipeline on deployment validation
| Pipeline |
| - |
| [![Sql: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Ferikag%2F2222-fix-sql)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml) |
> [Fixes] Update Sql Server PrivateDNSZone dependency name

- modules/Microsoft.ManagedIdentity/userAssignedIdentities/.test/common/deploy.test.bicep
- modules/Microsoft.ManagedIdentity/userAssignedIdentities/readme.md
Add tags to Microsoft.ManagedIdentity\userAssignedIdentities common test
Fixes #2208 
| Pipeline |
| - |
| [![ManagedIdentity: UserAssignedIdentities](https://github.com/MrRoundRobin/AzureResourceModules/actions/workflows/ms.managedidentity.userassignedidentities.yml/badge.svg?branch=mi_test_tags)](https://github.com/MrRoundRobin/AzureResourceModules/actions/workflows/ms.managedidentity.userassignedidentities.yml) |
> [Modules] Add tags to Microsoft.ManagedIdentity\userAssignedIdentities common test

- modules/Microsoft.Network/loadBalancers/inboundNatRules/deploy.bicep
- Addressed warning of Bicep resource ref
| Pipeline |
| - |
| [![Network: LoadBalancers](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.loadbalancers.yml/badge.svg?branch=users%2Falsehr%2FlbRefUpdate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.loadbalancers.yml) |
> [Fixes] Addressed warning of Bicep resource ref

- modules/Microsoft.Web/serverfarms/.test/common/deploy.test.bicep
- modules/Microsoft.Web/serverfarms/readme.md
fixes #2193 
| Pipeline |
| - |
| [![Web: Serverfarms](https://github.com/MrRoundRobin/AzureResourceModules/actions/workflows/ms.web.serverfarms.yml/badge.svg?branch=web_test_tags)](https://github.com/MrRoundRobin/AzureResourceModules/actions/workflows/ms.web.serverfarms.yml) |
> [Modules] Add tags to Microsoft.web\serverfarms common test

- docs/wiki/Known issues.md
- modules/Microsoft.Synapse/workspaces/readme.md
Closes #2032
Bicep v0.11.1 should solve the issue (tested locally)
Waiting for the update to be installed on MS hosted runners. 
Update 22/10/2022: Bicep v0.11.1 available on MS hosted runners. Pipeline ran successfully.
- Updated readme file
- Removed bug from known issues
| Pipeline |
| - |
| [![Synapse: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml/badge.svg?branch=users%2Ferikag%2Fsynapse-v011)](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml) |
> [Fixes] Fix failing Synapse Workspaces

- modules/Microsoft.KeyVault/vaults/.test/common/deploy.test.bicep
- modules/Microsoft.KeyVault/vaults/.test/min/deploy.test.bicep
- modules/Microsoft.KeyVault/vaults/readme.md
- Changed resource names to account for conflicts
| Pipeline |
| - |
| [![KeyVault: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=users%2Falsehr%2F2277_kvltName)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml) |
> [Modules] KeyVault: Changed resource names to account for conflicts

- modules/Microsoft.Compute/proximityPlacementGroups/.test/common/dependencies.bicep
- modules/Microsoft.Compute/proximityPlacementGroups/.test/min/deploy.test.bicep
- modules/Microsoft.Compute/proximityPlacementGroups/deploy.bicep
- modules/Microsoft.Compute/proximityPlacementGroups/readme.md
- Updated PPG API Version
- Added 'min' test case
| Pipeline |
| - |
| [![Compute: ProximityPlacementGroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.proximityplacementgroups.yml/badge.svg?branch=users%2Falsehr%2FppgAPI)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.proximityplacementgroups.yml) |
> [Modules] Updated PPG API Version

- .github/workflows/platform.assignPrToAuthor.yml
- .github/workflows/platform.linkcheck.yml
Update version of external actions in platform pipelines
- `.Platform: Broken Links Check`: new version leverages output env files to fix deprecated `set-output` warning.
- `.Platform: Assign Pull Request to Author`: new version updates action to use `Node.js 16` and gets rid of deprecated `Node.js 12` warning.
| Pipeline |
| - |
| |
> [Fixes] Update version of platform pipelines external actions

- modules/Microsoft.Compute/images/.test/common/dependencies.bicep
- modules/Microsoft.Compute/images/.test/common/deploy.test.bicep
- modules/Microsoft.Compute/images/deploy.bicep
- modules/Microsoft.Compute/images/readme.md
- Updated Compute Image API Version
| Pipeline |
| - |
| [![Compute: Images](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.images.yml/badge.svg?branch=users%2Falsehr%2FcomputeImageAPIUpdate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.images.yml) |
> [Modules] Updated Compute Image API Version

- docs/wiki/Fetching latest changes - Scenario 1 Consume library.md
- docs/wiki/Fetching latest changes - Scenario 2 Module library and CI environment.md
> [Wiki] Update Fetch latest updates section and fix broken links

- modules/Microsoft.Web/sites/readme.md
- Fixed incorrect parameter usage example for `appSettingsKeyValuePairs`
> [Fixes] Fixed incorrect parameter usage example

- modules/Microsoft.Authorization/policyExemptions/managementGroup/readme.md
- modules/Microsoft.Authorization/policyExemptions/resourceGroup/readme.md
- modules/Microsoft.Authorization/policyExemptions/subscription/readme.md
- modules/Microsoft.EventHub/namespaces/eventhubs/readme.md
- modules/Microsoft.Resources/tags/resourceGroups/readme.md
- modules/Microsoft.Resources/tags/subscriptions/readme.md
- modules/Microsoft.ServiceBus/namespaces/queues/readme.md
- modules/Microsoft.ServiceBus/namespaces/topics/readme.md
- Updated ReadMes based on latest main
> [Modules] Updated ReadMes based on latest main

- modules/Microsoft.ApiManagement/service/deploy.bicep
- modules/Microsoft.EventHub/namespaces/deploy.bicep
- modules/Microsoft.EventHub/namespaces/eventHubs/deploy.bicep
- Fixed incorrect child module references
| Pipeline |
| - |
| [![EventHub: Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml/badge.svg?branch=users%2Falsehr%2FmoduleRefFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml) |
> [Fixes] Fixed incorrect child module references

- modules/Microsoft.Network/networkWatchers/.test/common/dependencies.bicep
| Pipeline |
| - |
| [![Network: NetworkWatchers](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkwatchers.yml/badge.svg?branch=users%2Ferikag%2Fnw-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkwatchers.yml) |
> [Fixes] Fix Network Watcher dependency ubuntu VM offer update

- modules/Microsoft.Sql/servers/.test/common/dependencies.bicep
- modules/Microsoft.Sql/servers/.test/common/deploy.test.bicep
- modules/Microsoft.Sql/servers/databases/deploy.bicep
- modules/Microsoft.Sql/servers/databases/readme.md
- modules/Microsoft.Sql/servers/deploy.bicep
- modules/Microsoft.Sql/servers/elasticPools/deploy.bicep
- modules/Microsoft.Sql/servers/elasticPools/readme.md
- modules/Microsoft.Sql/servers/elasticPools/version.json
- modules/Microsoft.Sql/servers/readme.md
- Added Elastic Pool support to SQL Server
- Updated test case
| Pipeline |
| - |
| [![Sql: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Falsehr%2F2348_elasticPool)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml) |
> [Modules] Added Elastic Pool support to SQL Server

- .github/workflows/platform.linter.yml
- README.md
limit PR trigger to main branch
add manual trigger
update file name for consistency with other platform pipelines
| Pipeline |
| - |
| |
> [Fixes] Update Linter pipeline filename and trigger

- modules/Microsoft.Network/natGateways/.test/common/deploy.test.bicep
- modules/Microsoft.PowerBIDedicated/capacities/deploy.bicep
- modules/Microsoft.PowerBIDedicated/capacities/readme.md
- PowerBiDedicated: Capacities - Added missing telemetry to
- Network NAT Gateway - Removed excess syntax
| Pipeline |
| - |
| [![PowerBiDedicated: Capacities](https://github.com/Azure/ResourceModules/actions/workflows/ms.powerbidedicated.capacities.yml/badge.svg?branch=users%2Falsehr%2F0811pipelineFixes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.powerbidedicated.capacities.yml) |
| [![Network: NatGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.natgateways.yml/badge.svg?branch=users%2Falsehr%2F0811pipelineFixes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.natgateways.yml) |
Please delete options that are not …
> [Fixes] Fixed failing pipelines

- modules/Microsoft.Authorization/roleAssignments/.test/mg.min/deploy.test.bicep
- modules/Microsoft.Authorization/roleAssignments/.test/rg.min/deploy.test.bicep
- modules/Microsoft.Authorization/roleAssignments/.test/sub.min/deploy.test.bicep
- modules/Microsoft.Authorization/roleAssignments/readme.md
- Fixes Role Assignment module tests
| Pipeline |
| - |
| [![Authorization: RoleAssignments](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.roleassignments.yml/badge.svg?branch=users%2Falsehr%2FauthorizationFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.roleassignments.yml) |
> [Fixes] Fixes Role Assignment module tests

- .azuredevops/pipelineTemplates/jobs.getModuleTestFiles.yml
- docs/wiki/Solution creation.md
- docs/wiki/The library - Module usage.md
- utilities/pipelines/resourceDeployment/New-TemplateDeployment.ps1
- utilities/pipelines/resourceRemoval/Initialize-DeploymentRemoval.ps1
- utilities/pipelines/resourceRemoval/helper/Get-ResourceIdsAsFormattedObjectList.ps1
- utilities/pipelines/staticValidation/module.tests.ps1
- utilities/tools/Test-ModuleLocally.ps1
- Updated deployment & usage examples
- Removed another location where we still had the original parameters.json support
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status/Modules/AnalysisServices%20-%20Servers?branchName=users%2Falsehr%2FparameterRefCleanup)](https://dev.azure.com/carml/CARML/_build/latest?definitionId=2&branchName=users%2Falsehr%2FparameterRefCleanup) |
> [Wiki] Updated deployment & usage examples & further cleanup

- .azuredevops/modulePipelines/ms.network.privatelinkservices.yml
> [Fixes] Privatelink ADO pipeline name fix

- .github/workflows/platform.assignIssueToProject.yml
Project URL changed to to new project type. 
| Pipeline |
| - |
| https://github.com/Azure/ResourceModules/actions/runs/3673953209|
> Update project URL

- .github/workflows/platform.assignIssueToProject.yml
change code to updated logic to add issues to new projects
> [Platform] Change code to updated logic to add issues to new projects

- .github/workflows/platform.assignIssueToProject.yml
> fixing variable reference

- .github/workflows/platform.assignIssueToProject.yml
Use the newly created token with the correct permissions
> use new token for assigning issues

- utilities/tools/AzureDevOps/Register-AzureDevOpsPipeline.ps1
- Improve deployment example for `Register-AzureDevOpsPipeline` utility
> [Documention] Improve deployment example for `Register-AzureDevOpsPipeline` utility

- modules/Microsoft.DocumentDB/databaseAccounts/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/.test/gremlindb/deploy.test.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/.test/mongodb/deploy.test.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/.test/plain/deploy.test.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/.test/sqldb/deploy.test.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/deploy.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/gremlinDatabases/deploy.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/gremlinDatabases/graphs/deploy.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/gremlinDatabases/graphs/readme.md
- modules/Microsoft.DocumentDB/databaseAccounts/gremlinDatabases/readme.md
- modules/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections/deploy.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections/readme.md
- modules/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/deploy.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/readme.md
- modules/Microsoft.DocumentDB/databaseAccounts/readme.md
- modules/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/deploy.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/readme.md
- modules/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/deploy.bicep
- modules/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/readme.md
- utilities/src/apiSpecsList.json
This PR resolves #2481 and updates API versions of modules under `Microsoft.DocumentDB/databaseAccounts` to fix failing pester tests.
| Pipeline |
| - |
| [![DocumentDB: DatabaseAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml/badge.svg?branch=users%2Fkrbar%2F2481-documentDbApiVersions)](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml) |
>  [Modules] Updated API versions for Microsoft.DocumentDB/databaseAccounts

- .azuredevops/platformPipelines/platform.apiSpecs.yml
- .github/workflows/platform.apiSpecs.yml
- utilities/src/apiSpecsList.json
- utilities/tools/platform/Set-ApiSpecsFile.ps1
- Updated to latest AzureAPICrawler module version
- Now combines both the 'Azure API Specs' repository API versions & those returned by the `Get-AzResourceProvider` cmdlet to get the most complete picture
| Pipeline |
| - |
| [![.Platform: Update API Specs file](https://github.com/Azure/ResourceModules/actions/workflows/platform.apiSpecs.yml/badge.svg?branch=users%2Falsehr%2F2518_apiSpecs)](https://github.com/Azure/ResourceModules/actions/workflows/platform.apiSpecs.yml) |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status/Platform/.Platform%20-%20Update%20API%20Specs%20file?branchName=users%2Falsehr%2F2518_apiSpecs)](https://dev.azure.com/carml/CARML/_build/latest?definit …
> [Pipelines] Updated to latest AzureAPICrawler module version

- .github/workflows/platform.apiSpecs.yml
Update scheduled job to only run on branch  'main/master'
| Pipeline | |
| - | - |
| [![.Platform: Update API Specs file](https://github.com/Azure/ResourceModules/actions/workflows/platform.apiSpecs.yml/badge.svg?branch=users%2Falsehr%2F2517_schedulebranch)](https://github.com/Azure/ResourceModules/actions/workflows/platform.apiSpecs.yml) | Was skipped as expected |
> [Fixes] Update scheduled job to only run on branch  'main/master'

- modules/Microsoft.Network/virtualNetworks/.test/vnetPeering/deploy.test.bicep
- modules/Microsoft.Network/virtualNetworks/readme.md
- Fixed VNET Peering test
| Pipeline |
| - |
| [![Network: VirtualNetworks](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml/badge.svg?branch=users%2Falsehr%2FvnetFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml) |
> [Fixes] Fixed VNET Peering test

- modules/Microsoft.RecoveryServices/vaults/deploy.bicep
- modules/Microsoft.RecoveryServices/vaults/readme.md
Updating readme file and publicNetworkAccess default values following PR #2488 to fix failing deployment
| Pipeline |
| - |
| [![RecoveryServices: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml/badge.svg?branch=users%2Fcsidebotham%2Frsv-readmefix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.recoveryservices.vaults.yml)|
> [Modules]: Microsoft.RecoveryServices - Param and Readme fix failing pipeline

- modules/Microsoft.MachineLearningServices/workspaces/deploy.bicep
- modules/Microsoft.MachineLearningServices/workspaces/readme.md
Fixing failing static validation
| Pipeline |
| - |
| [![MachineLearningServices: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml/badge.svg?branch=users%2Ferikag%2F2485-fix-ml)](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml) |
> [Fixes] Update ML workspaces parameter description and readme

- modules/Microsoft.Compute/galleries/images/readme.md
Fixing failing static validation
Adding min test
| Pipeline |
| - |
| [![Compute: Galleries](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.galleries.yml/badge.svg?branch=users%2Ferikag%2F2533-fix-galleries)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.galleries.yml) |
> [Modules] Update galleries readme and add min test

- modules/Microsoft.Web/staticSites/readme.md
Fixing failing static validation
| Pipeline |
| - |
| [![Web: StaticSites](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.staticsites.yml/badge.svg?branch=users%2Ferikag%2Ffix-web-static)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.staticsites.yml) |
> [Fixes] Web Staticsites readme update

- modules/Microsoft.Compute/galleries/.test/min/deploy.test.bicep
- modules/Microsoft.Compute/galleries/readme.md
| Pipeline |
| - |
| [![Compute: Galleries](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.galleries.yml/badge.svg?branch=users%2Ferikag%2Fmin-gallery)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.galleries.yml) |
> [Modules] Add min test to compute galleries

- modules/Microsoft.MachineLearningServices/workspaces/.test/common/deploy.test.bicep
- modules/Microsoft.MachineLearningServices/workspaces/computes/deploy.bicep
- modules/Microsoft.MachineLearningServices/workspaces/computes/readme.md
- modules/Microsoft.MachineLearningServices/workspaces/deploy.bicep
- modules/Microsoft.MachineLearningServices/workspaces/readme.md
Closes #2548 
- Fix a bug related to the wrong `sku` referenced in the SKU parameter. 
- Updated API version to `2022-10-01`
| Pipeline |
| - |
| [![MachineLearningServices: Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml/badge.svg?branch=users%2Fahmad%2F2548_mlFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.machinelearningservices.workspaces.yml)|
> [Modules] Fix Machine Learning Workspaces SKU Type and update API version to "2022-10-01"

- modules/Microsoft.Network/virtualHubs/readme.md
Fix for the VHUB Pipeline.
| Pipeline |
| - |
|[![Network: VirtualHubs](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualhubs.yml/badge.svg?branch=users%2Fahmad%2Ffix_vhub_pipeline)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualhubs.yml) |
> Fix Virtual Hubs Pipeline

- modules/Microsoft.Compute/disks/.test/common/deploy.test.bicep
- modules/Microsoft.Compute/disks/.test/image/deploy.test.bicep
- modules/Microsoft.Compute/disks/.test/import/deploy.test.bicep
- modules/Microsoft.Compute/disks/.test/min/deploy.test.bicep
- modules/Microsoft.Compute/images/.test/common/deploy.test.bicep
- modules/Microsoft.Network/azureFirewalls/.test/hub/deploy.test.bicep
- modules/Microsoft.Network/azureFirewalls/.test/min/deploy.test.bicep
- modules/Microsoft.Resources/resourceGroups/.test/common/deploy.test.bicep
- Fixed typos in `deploy.test.bicep` parameter description
> [Fixed] Fixed typos in `deploy.test.bicep` parameter description

- docs/wiki/The library - Module design.md
Linking to existing code examples
| Pipeline |
| - |
| |
> [Fixes] Update link to code examples in module design Wiki

- utilities/pipelines/resourcePublish/Get-ModulesMissingFromPrivateBicepRegistry.ps1
- utilities/pipelines/resourcePublish/Get-ModulesMissingFromTemplateSpecsRG.ps1
- utilities/pipelines/resourcePublish/Get-ModulesMissingFromUniversalArtifactsFeed.ps1
- Added missing 'ErrorAction'
- Fixed incorrect array count validation
- Aligned naming
Successfully validated that it doesn't fail on missing ACR & correctly creates a new one once necessary
| Pipeline |
| - |
| [![AnalysisServices: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2FpublishTest)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
> [Fixes] Several small fixes for the Publishing logic

- modules/Microsoft.DesktopVirtualization/scalingplans/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.DesktopVirtualization/scalingplans/deploy.bicep
- modules/Microsoft.DesktopVirtualization/scalingplans/readme.md
Closes #2583 
Closes #2536 
Update the API version for AVD Scaling Plans to latest deployable API version `2022-04-01-preview`. Other APIs like [2022-09-09](https://learn.microsoft.com/en-us/azure/templates/microsoft.desktopvirtualization/2022-09-09/scalingplans?pivots=deployment-language-bicep) and [2022-10-14-preview](https://learn.microsoft.com/en-us/azure/templates/microsoft.desktopvirtualization/2022-10-14-preview/scalingplans?pivots=deployment-language-bicep) cause issues where the RP is not available in the region we are using for testing. Create an issue #2587 to keep track of the use case.
| Pipeline |
| - |
|[![DesktopVirtualization: Scalingplans](https://github.com/Azure/ResourceModules/actions/workflows/ms.desktopvirtualization.scalingplans.yml/badge.svg?branch=users%2Fahmad%2F …
> [Modules] Update AVD Scaling Plans API Version

- README.md
Remove duplicated status badges for linter and broken links platform pipelines
| Pipeline |
| - |
| |
> [Fixes] Remove duplicated status badges from home page

- modules/Microsoft.KeyVault/vaults/accessPolicies/deploy.bicep
- modules/Microsoft.KeyVault/vaults/accessPolicies/readme.md
- modules/Microsoft.KeyVault/vaults/deploy.bicep
- modules/Microsoft.KeyVault/vaults/keys/deploy.bicep
- modules/Microsoft.KeyVault/vaults/keys/readme.md
- modules/Microsoft.KeyVault/vaults/readme.md
- modules/Microsoft.KeyVault/vaults/secrets/deploy.bicep
- modules/Microsoft.KeyVault/vaults/secrets/readme.md
This PR updates the outdated api version for the keyvault modules, so that the validation tests will pass again.
See #2621
| Pipeline |
| - |
| [![KeyVault: Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=users%2Ff_blix%2Fupdatekvapiversions)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml) |
> [Modules] Update KeyVault API Versions

- modules/Microsoft.ApiManagement/service/deploy.bicep
- modules/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
- modules/Microsoft.Network/natGateways/deploy.bicep
- modules/Microsoft.PolicyInsights/remediations/managementGroup/deploy.bicep
- modules/Microsoft.PolicyInsights/remediations/resourceGroup/deploy.bicep
- modules/Microsoft.PolicyInsights/remediations/subscription/deploy.bicep
- modules/Microsoft.Sql/servers/databases/deploy.bicep
- modules/Microsoft.Sql/servers/databases/readme.md
- modules/Microsoft.Sql/servers/deploy.bicep
Remove json function where not needed and added comment when needed
| Pipeline |
| - |
| [![Sql: Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Ferikag%2Fjson-remove)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml) |
| [![ApiManagement: Service](https://github.com/Azure/ResourceModules/actions/workflows/ms.apimanagement.service.yml/badge.svg?branch=users%2Ferikag%2Fjson-remove)](https://github.com/Azure/ResourceModules/actions/workflows/ms.apimanagement.service.yml) |
| [![Network: NatGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.natgateways.yml/badge.svg?branch=user …
> [Fixes] Remove json function from modules not requiring it

- modules/Microsoft.Compute/virtualMachines/readme.md
- modules/Microsoft.Network/azureFirewalls/readme.md
- modules/Microsoft.Network/bastionHosts/readme.md
- modules/Microsoft.Network/natGateways/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Network/natGateways/deploy.bicep
- modules/Microsoft.Network/natGateways/readme.md
- modules/Microsoft.Network/natGateways/version.json
- modules/Microsoft.Network/publicIPAddresses/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Network/publicIPAddresses/deploy.bicep
- modules/Microsoft.Network/publicIPAddresses/readme.md
- modules/Microsoft.Network/virtualNetworkGateways/readme.md
Uplift PIP API version
Regenerate readme files for all modules cross referencing pip
Update NAT gateway to cross reference pip
| Pipeline |
| - |
| [![Network: NatGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.natgateways.yml/badge.svg?branch=users%2Ferikag%2Fpip-api-update)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.natgateways.yml) |
| [![Network: PublicIpAddresses](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.publicipaddresses.yml/badge.svg?branch=users%2Ferikag%2Fpip-api-update)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.publicipaddresses.yml) |
Please delete options that are …
> [Modules] Update PIP API version and modules cross referencing it

- modules/Microsoft.ContainerService/managedClusters/.test/min/deploy.test.bicep
- modules/Microsoft.ContainerService/managedClusters/readme.md
Added min test to managedClusters.
| Pipeline |
| - |
| [![ContainerService: ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Fmast%2FmanageClusterMinTest)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml) |
> [Modules] Added min test to managedClusters

- .azuredevops/modulePipelines/ms.healthcareapis.workspaces.yml
- .azuredevops/modulePipelines/ms.security.azuresecuritycenter.yml
GH counterpart covered by #2637 
| Pipeline |
| - |
| |
> [Fixes] Align ADO module pipeline input parameters

- modules/Microsoft.Network/applicationGateways/deploy.bicep
- modules/Microsoft.Network/applicationGateways/readme.md
Added 2 option a to sslPolicyMinProtocolVersion paramater
Added 2 options for sslPolicyName
Added 1 option for sslPolicyType
Updated API version
Solves #2699
| Pipeline |
| - |
| |
> [Modules] Adding parameter options to application gateway

- modules/Microsoft.Network/loadBalancers/backendAddressPools/deploy.bicep
- modules/Microsoft.Network/loadBalancers/backendAddressPools/readme.md
- modules/Microsoft.Network/loadBalancers/deploy.bicep
- modules/Microsoft.Network/loadBalancers/inboundNatRules/deploy.bicep
- modules/Microsoft.Network/loadBalancers/inboundNatRules/readme.md
- modules/Microsoft.Network/loadBalancers/readme.md
Closes #2716
Updated Azure Load Balancer to the latest API version
| Pipeline |
| - |
|[![Network - LoadBalancers](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.loadbalancers.yml/badge.svg?branch=users%2Fahmad%2F2716_fixApi_LB)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.loadbalancers.yml) |
> [Modules] Updated Azure Load Balancer Module to the latest API version (2022-07-01)

- modules/Microsoft.Network/applicationSecurityGroups/deploy.bicep
- modules/Microsoft.Network/applicationSecurityGroups/readme.md
Closes #2715 
Updated ASG to the latest API version
| Pipeline |
| - |
|[![Network - ApplicationSecurityGroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationsecuritygroups.yml/badge.svg?branch=users%2Fahmad%2F2715_fixApi_ASG)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationsecuritygroups.yml) |
> [Modules] Updated Application Security Groups Module to the latest API version (2022-07-01)

- modules/Microsoft.Network/publicIPPrefixes/deploy.bicep
- modules/Microsoft.Network/publicIPPrefixes/readme.md
Closes #2706
Updated public IP prefix module API version
| Pipeline |
| - |
|[![Network - PublicIpPrefixes](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.publicipprefixes.yml/badge.svg?branch=users%2Fahmad%2F2706_apiFix_pipPrefix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.publicipprefixes.yml) |
> [Modules] Updated Public IP Prefix Module to the latest API Version (2022-07-01)

- modules/Microsoft.Network/azureFirewalls/deploy.bicep
- modules/Microsoft.Network/azureFirewalls/readme.md
Closes #2710 
Updated Azure Firewall module to latest API version
| Pipeline |
| - |
| [![Network - AzureFirewalls](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.azurefirewalls.yml/badge.svg?branch=users%2Fahmad%2F2710_apiFix_AzFW)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.azurefirewalls.yml)|
> [Modules] Updated Azure Firewall Module to the latest API Version (2022-07-01)

- modules/Microsoft.Network/firewallPolicies/.test/common/deploy.test.bicep
- modules/Microsoft.Network/firewallPolicies/deploy.bicep
- modules/Microsoft.Network/firewallPolicies/readme.md
- modules/Microsoft.Network/firewallPolicies/ruleCollectionGroups/deploy.bicep
- modules/Microsoft.Network/firewallPolicies/ruleCollectionGroups/readme.md
Closes #2712 
Updated firewall policies API to latest version 
| Pipeline |
| - |
|[![Network - FirewallPolicies](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.firewallpolicies.yml/badge.svg?branch=users%2Fahmad%2F2712_apiFix_fWpolicies)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.firewallpolicies.yml) |
> [Modules] Updated Firewall Policies Module to the latest API Version (2022-07-01)

- modules/Microsoft.Network/privateEndpoints/deploy.bicep
- modules/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/deploy.bicep
- modules/Microsoft.Network/privateEndpoints/privateDnsZoneGroups/readme.md
- modules/Microsoft.Network/privateEndpoints/readme.md
Closes #2707 
Updated PE module to the latest version
| Pipeline |
| - |
|[![Network - PrivateEndpoints](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.privateendpoints.yml/badge.svg?branch=users%2Fahmad%2F2707_fixApi_PE)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.privateendpoints.yml) |
> [Modules] Updated Private Endpoints Module to the latest API Version (2022-07-01)

- modules/Microsoft.Network/networkInterfaces/deploy.bicep
- modules/Microsoft.Network/networkInterfaces/readme.md
Closes #2713 
Updated the NIC module to the latest API version
| Pipeline |
| - |
| [![Network - NetworkInterfaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkinterfaces.yml/badge.svg?branch=users%2Fahmad%2F2713_fixApi_NIC)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networkinterfaces.yml)|
> [Modules] Updated Network Interface Module to the latest API version (2022-07-01)

- modules/Microsoft.Network/virtualNetworks/.test/common/deploy.test.bicep
- modules/Microsoft.Network/virtualNetworks/deploy.bicep
- modules/Microsoft.Network/virtualNetworks/readme.md
- modules/Microsoft.Network/virtualNetworks/subnets/deploy.bicep
- modules/Microsoft.Network/virtualNetworks/subnets/readme.md
- modules/Microsoft.Network/virtualNetworks/virtualNetworkPeerings/deploy.bicep
- modules/Microsoft.Network/virtualNetworks/virtualNetworkPeerings/readme.md
Closes #2785 
Updated Virtual Network Module to the latest API Version (2022-07-01)
| Pipeline |
| - |
|[![Network - VirtualNetworks](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml/badge.svg?branch=users%2Fahmad%2F2785_apiFix_vnet)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworks.yml) |
> [Modules] Updated Virtual Network Module to the latest API Version (2022-07-01)

- modules/Microsoft.Network/virtualWans/deploy.bicep
- modules/Microsoft.Network/virtualWans/readme.md
Closes #2783 
[Modules] Updated Virtual WAN Module to the latest API Version (2022-07-01)
| Pipeline |
| - |
| [![Network - VirtualWans](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualwans.yml/badge.svg?branch=users%2Fahmad%2F2783_apiFix_vWan)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualwans.yml)|
> [Modules] Updated Virtual WAN Module to the latest API Version (2022-07-01)

- modules/Microsoft.Network/expressRouteCircuits/.test/common/deploy.test.bicep
- modules/Microsoft.Network/expressRouteCircuits/deploy.bicep
- modules/Microsoft.Network/expressRouteCircuits/readme.md
Closes #2781 
[Modules] Updated Express Route Circuit Module to latest API Version (2022-07-01)
| Pipeline |
| - |
|[![Network - ExpressRouteCircuits](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.expressroutecircuits.yml/badge.svg?branch=users%2Fahmad%2F2781_apiFix_er)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.expressroutecircuits.yml) |
> [Modules] Updated Express Route Circuit Module to latest API Version (2022-07-01)

- modules/Microsoft.Network/connections/.test/vnet2vnet/deploy.test.bicep
- modules/Microsoft.Network/connections/deploy.bicep
- modules/Microsoft.Network/connections/readme.md
Closes #2704 
[Modules] Connections Module to latest API Version (2022-07-01)
| Pipeline |
| - |
|[![Network - Connections](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.connections.yml/badge.svg?branch=users%2Fahmad%2F2704_apiFi_connec)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.connections.yml) |
> [Modules] Connections Module to latest API Version (2022-07-01)

- modules/Microsoft.Network/networkSecurityGroups/deploy.bicep
- modules/Microsoft.Network/networkSecurityGroups/readme.md
- modules/Microsoft.Network/networkSecurityGroups/securityRules/deploy.bicep
- modules/Microsoft.Network/networkSecurityGroups/securityRules/readme.md
Closes #2778 
[Modules] Updated Network Security Group Module to latest API Version (2022-07-01)
| Pipeline |
| - |
| [![Network - NetworkSecurityGroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networksecuritygroups.yml/badge.svg?branch=users%2Fahmad%2F2778_apiFix_nsg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.networksecuritygroups.yml)|
> [Modules] Updated Network Security Group Module to latest API Version (2022-07-01)

- modules/Microsoft.Network/localNetworkGateways/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Network/localNetworkGateways/deploy.bicep
- modules/Microsoft.Network/localNetworkGateways/readme.md
Closes #2701 
[Modules] Updated Local Network Gateway Module to the latest API Version (2022-07-01)
| Pipeline |
| - |
|[![Network - LocalNetworkGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.localnetworkgateways.yml/badge.svg?branch=users%2Fahmad%2F2701_apiFi_lng)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.localnetworkgateways.yml) |
> [Modules] Updated Local Network Gateway Module to the latest API Version (2022-07-01)

- modules/Microsoft.Network/ddosProtectionPlans/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Network/ddosProtectionPlans/deploy.bicep
- modules/Microsoft.Network/ddosProtectionPlans/readme.md
Closes #2698 
[Modules] Updated DDoS Protection Plan Module to the latest API Version (2022-07-01)
| Pipeline |
| - |
| [![Network - DdosProtectionPlans](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.ddosprotectionplans.yml/badge.svg?branch=users%2Fahmad%2F2698_apiFi_ddos)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.ddosprotectionplans.yml)
> [Modules] Updated DDoS Protection Plan Module to the latest API Version (2022-07-01)

- modules/Microsoft.Network/ipGroups/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Network/ipGroups/deploy.bicep
- modules/Microsoft.Network/ipGroups/readme.md
Closes #2700 
[Modules] Updated IP Groups Module to the latest API Version (2022-07-01)
| Pipeline |
| - |
| [![Network - IpGroups](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.ipgroups.yml/badge.svg?branch=users%2Fahmad%2F2700_apiFi_ip)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.ipgroups.yml)|
> [Modules] Updated IP Groups Module to the latest API Version (2022-07-01)

- .github/workflows/platform.ManageIssueForFailingPipelines.yml
Due to a renaming, the exclusion filter needed to be adapted. See #2796 
| Pipeline |
| - |
| |
> [Fixes] fix filter for excluded workflows in manage issue pipeline

- modules/Microsoft.Automation/automationAccounts/readme.md
- modules/Microsoft.Batch/batchAccounts/readme.md
- modules/Microsoft.Cache/redis/readme.md
- modules/Microsoft.CognitiveServices/accounts/readme.md
- modules/Microsoft.Compute/virtualMachines/readme.md
- modules/Microsoft.ContainerRegistry/registries/readme.md
- modules/Microsoft.ContainerService/managedClusters/readme.md
- modules/Microsoft.DataFactory/factories/readme.md
- modules/Microsoft.EventGrid/domains/readme.md
- modules/Microsoft.EventGrid/topics/readme.md
- modules/Microsoft.EventHub/namespaces/readme.md
- modules/Microsoft.Insights/privateLinkScopes/readme.md
- modules/Microsoft.KeyVault/vaults/readme.md
- modules/Microsoft.KubernetesConfiguration/extensions/readme.md
- modules/Microsoft.MachineLearningServices/workspaces/readme.md
- modules/Microsoft.Purview/accounts/readme.md
- modules/Microsoft.RecoveryServices/vaults/readme.md
- modules/Microsoft.ServiceBus/namespaces/readme.md
- modules/Microsoft.SignalRService/signalR/readme.md
- modules/Microsoft.SignalRService/webPubSub/readme.md
- modules/Microsoft.Sql/servers/readme.md
- modules/Microsoft.Storage/storageAccounts/readme.md
- modules/Microsoft.Synapse/privateLinkHubs/readme.md
- modules/Microsoft.Synapse/workspaces/readme.md
- modules/Microsoft.Web/sites/readme.md
- modules/Microsoft.Web/sites/slots/readme.md
- modules/Microsoft.Web/staticSites/readme.md
- utilities/tools/Set-ModuleReadMe.ps1
- Updated regex to remove only top-level dependsOn statements
- Fix for the new condition for when it should be adding examples into the readme
- Refreshed all readme's
| Pipeline |
| - |
| [![AnalysisServices - Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml/badge.svg?branch=users%2Falsehr%2F2688_depends)](https://github.com/Azure/ResourceModules/actions/workflows/ms.analysisservices.servers.yml) |
| [![Compute - VirtualMachines](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml/badge.svg?branch=users%2Falsehr%2F2688_depends)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtual …
> [Utilities] Updated regex to remove only top-level dependsOn statements

- modules/Microsoft.Network/vpnSites/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Network/vpnSites/.test/common/deploy.test.bicep
- modules/Microsoft.Network/vpnSites/deploy.bicep
- modules/Microsoft.Network/vpnSites/readme.md
Closes #2709 
Updated VPN Sites to latest module
| Pipeline |
| - |
|[![Network - VPN Sites](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.vpnsites.yml/badge.svg?branch=users%2Fahmad%2F2709_apiFix_vpnSites)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.vpnsites.yml) |
> [Modules] Updated VPN Sites Module to the latest API Version (2022-07-01)

- modules/Microsoft.DesktopVirtualization/applicationgroups/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.DesktopVirtualization/applicationgroups/.test/common/dependencies.bicep
- modules/Microsoft.DesktopVirtualization/applicationgroups/.test/common/deploy.test.bicep
- modules/Microsoft.DesktopVirtualization/applicationgroups/.test/min/dependencies.bicep
- modules/Microsoft.DesktopVirtualization/applicationgroups/applications/deploy.bicep
- modules/Microsoft.DesktopVirtualization/applicationgroups/applications/readme.md
- modules/Microsoft.DesktopVirtualization/applicationgroups/deploy.bicep
- modules/Microsoft.DesktopVirtualization/applicationgroups/readme.md
- modules/Microsoft.DesktopVirtualization/scalingplans/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.DesktopVirtualization/scalingplans/deploy.bicep
- modules/Microsoft.DesktopVirtualization/scalingplans/readme.md
- modules/Microsoft.DesktopVirtualization/workspaces/.test/common/dependencies.bicep
Closes #2705 
Update to latest non preview all modules under Microsoft.DesktopVirtualization RP
No new property added from change log, although some may have been available already before and missing from the modules. 
Opening a new issue to investigate how to add msix properties to appGroup/applications
| Pipeline |
| - |
| [![DesktopVirtualization - Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.desktopvirtualization.workspaces.yml/badge.svg?branch=users%2Ferikag%2Fappgroup-api)](https://github.com/Azure/ResourceModules/actions/workflows/ms.desktopvirtualization.workspaces.yml) |
| [![DesktopVirtualization - …
> [Modules] Update Microsoft.DesktopVirtualization RP modules API version

- modules/Microsoft.Network/vpnGateways/connections/deploy.bicep
- modules/Microsoft.Network/vpnGateways/connections/readme.md
- modules/Microsoft.Network/vpnGateways/deploy.bicep
- modules/Microsoft.Network/vpnGateways/natRules/deploy.bicep
- modules/Microsoft.Network/vpnGateways/natRules/readme.md
- modules/Microsoft.Network/vpnGateways/readme.md
Closes #2714 
Updated VPN GW Module to latest API version
| Pipeline |
| - |
| [![Network - VPNGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.vpngateways.yml/badge.svg?branch=users%2Fahmad%2F2714_apiFix_vpnGW)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.vpngateways.yml)|
> [Modules] Updated VPN Gateway Module to the latest API Version (2022-07-01)

- modules/Microsoft.Synapse/workspaces/.bicep/nested_cmkRbac.bicep
- modules/Microsoft.Synapse/workspaces/.test/common/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/common/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwsai/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwsai/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwuai/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/encrwuai/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/managedvnet/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/managedvnet/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/.test/min/dependencies.bicep
- modules/Microsoft.Synapse/workspaces/.test/min/deploy.test.bicep
- modules/Microsoft.Synapse/workspaces/deploy.bicep
- modules/Microsoft.Synapse/workspaces/keys/deploy.bicep
- modules/Microsoft.Synapse/workspaces/readme.md
Updated Synapse Workspace module to the latest API version.
| Pipeline |
| - |
| [![Synapse - Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml/badge.svg?branch=users%2Fkrbar%2F2708-synapse-workspaces-api-versions)](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml) |
> [Modules] Updated Synapse Workspace module to the latest API version

- .azuredevops/modulePipelines/ms.web.hostingenvironments.yml
This PR resolves #2834 and increases Azure DevOps pipeline timeout for `Microsoft.Web/hostingEnvironments` module as this resource takes multiple hours to deploy.
| Pipeline |
| - |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status/Modules/Web%20-%20HostingEnvironments?branchName=main)](https://dev.azure.com/carml/CARML/_build/latest?definitionId=95&branchName=main) |
> [CI Environment] Increased Azure DevOps timeout for Microsoft.Web/hostingEnvironments

- .azuredevops/modulePipelines/ms.app.containerapps.yml
- .azuredevops/modulePipelines/ms.app.managedenvironments.yml
- .github/workflows/ms.app.containerapps.yml
- .github/workflows/ms.app.managedenvironments.yml
- modules/Microsoft.App/containerApps/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.App/containerApps/.test/common/dependencies.bicep
- modules/Microsoft.App/containerApps/.test/common/deploy.test.bicep
- modules/Microsoft.App/containerApps/.test/min/dependencies.bicep
- modules/Microsoft.App/containerApps/.test/min/deploy.test.bicep
- modules/Microsoft.App/containerApps/deploy.bicep
- modules/Microsoft.App/containerApps/readme.md
- modules/Microsoft.App/containerApps/version.json
- modules/Microsoft.App/managedEnvironments/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.App/managedEnvironments/.test/common/dependencies.bicep
- modules/Microsoft.App/managedEnvironments/.test/common/deploy.test.bicep
- modules/Microsoft.App/managedEnvironments/.test/min/dependencies.bicep
- modules/Microsoft.App/managedEnvironments/.test/min/deploy.test.bicep
- modules/Microsoft.App/managedEnvironments/deploy.bicep
- modules/Microsoft.App/managedEnvironments/readme.md
- settings.yml
I have added new module for Microsoft.App managedEnvironments for Container Apps: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/managedenvironments?pivots=deployment-language-bicep
Managed Environments module is under Container Apps and it acts as a secure boundary around groups of container apps. Container Apps in the same environment are deployed in the same virtual network and write logs to the same Log Analytics workspace.
| Pipeline |
| - |
| [![Container Apps - Managed Environments](https://github.com/shaban-khan/ResourceModules/actions/workflows/ms.app.managedenvironments.yml/badge.svg?branch=main)](https://github.com/shaban-khan/ResourceModules/actions/workflows/ms.app.managedenvironments.yml) |
> [Modules] New module Microsoft.App managedEnvironments for Container Apps

- modules/Microsoft.Storage/storageAccounts/blobServices/deploy.bicep
- modules/Microsoft.Storage/storageAccounts/blobServices/readme.md
> Naming suggestion covering diagnostic settings with default naming

- modules/Microsoft.Network/virtualNetworkGateways/.test/vpn/deploy.test.bicep
- modules/Microsoft.Network/virtualNetworkGateways/deploy.bicep
- modules/Microsoft.Network/virtualNetworkGateways/readme.md
Closes #2347 
Updated the VNET Gateway Module with more SKUs and Generation parameter
| Pipeline |
| - |
|[![Network - VirtualNetworkGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworkgateways.yml/badge.svg?branch=users%2Fahmad%2F2347_vnetGw)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualnetworkgateways.yml) |
> [Modules] Updated SKU options and added generation parameter for VNET Gateways

- modules/Microsoft.Sql/servers/.test/secondary/dependencies.bicep
- modules/Microsoft.Sql/servers/.test/secondary/deploy.test.bicep
- modules/Microsoft.Sql/servers/databases/deploy.bicep
- modules/Microsoft.Sql/servers/databases/readme.md
- modules/Microsoft.Sql/servers/deploy.bicep
- modules/Microsoft.Sql/servers/readme.md
Adds support for createMode on microsoft.sql/servers/databases allowing replicas or restores of databases to be created.
| Pipeline |
| - |
| |
> [Modules] Added support for createMode

- modules/Microsoft.SignalRService/signalR/.test/common/deploy.test.bicep
- modules/Microsoft.SignalRService/signalR/readme.md
- modules/Microsoft.SignalRService/webPubSub/.test/common/deploy.test.bicep
- modules/Microsoft.SignalRService/webPubSub/readme.md
Closes #2957 
Closes #2975 
| Pipeline |
| - |
| [![SignalRService - WebPubSub](https://github.com/Azure/ResourceModules/actions/workflows/ms.signalrservice.webpubsub.yml/badge.svg?branch=users%2Ferikag%2Fpsrule-tags-signalr)](https://github.com/Azure/ResourceModules/actions/workflows/ms.signalrservice.webpubsub.yml) |
| [![SignalRService - SignalR](https://github.com/Azure/ResourceModules/actions/workflows/ms.signalrservice.signalr.yml/badge.svg?branch=users%2Ferikag%2Fpsrule-tags-signalr)](https://github.com/Azure/ResourceModules/actions/workflows/ms.signalrservice.signalr.yml) |
> [Fixes] Update tags signalRService RP

- modules/Microsoft.NetApp/netAppAccounts/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.NetApp/netAppAccounts/capacityPools/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.NetApp/netAppAccounts/capacityPools/deploy.bicep
- modules/Microsoft.NetApp/netAppAccounts/capacityPools/readme.md
- modules/Microsoft.NetApp/netAppAccounts/capacityPools/volumes/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.NetApp/netAppAccounts/capacityPools/volumes/deploy.bicep
- modules/Microsoft.NetApp/netAppAccounts/capacityPools/volumes/readme.md
- modules/Microsoft.NetApp/netAppAccounts/deploy.bicep
- modules/Microsoft.NetApp/netAppAccounts/readme.md
Closes #2982 
| Pipeline |
| - |
| [![NetApp - NetAppAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.netapp.netappaccounts.yml/badge.svg?branch=users%2Ferikag%2Fnetapp-api)](https://github.com/Azure/ResourceModules/actions/workflows/ms.netapp.netappaccounts.yml) |
> [Modules] Update Azure NetApp Files API version

- README.md
Closes #3000
Added disclaimer/guidance on which version of the code to leverage. 
> [Wiki] Added disclaimer/guidance on which version of the code to leverage

- modules/Microsoft.Compute/availabilitySets/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Compute/availabilitySets/deploy.bicep
- modules/Microsoft.Compute/availabilitySets/readme.md
Closes #3022 
Updated API Version
| Pipeline |
| - |
| [![Compute - AvailabilitySets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.availabilitysets.yml/badge.svg?branch=users%2Fahmad%2F3022_as)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.availabilitysets.yml)|
> [Modules] Updated Availability Sets Module to Latest API Version (2022-11-01)

- modules/Microsoft.Compute/virtualMachineScaleSets/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.Compute/virtualMachineScaleSets/deploy.bicep
- modules/Microsoft.Compute/virtualMachineScaleSets/extensions/deploy.bicep
- modules/Microsoft.Compute/virtualMachineScaleSets/extensions/readme.md
- modules/Microsoft.Compute/virtualMachineScaleSets/readme.md
Closes #3021 
| Pipeline |
| - |
|[![Compute - VirtualMachineScaleSets](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachinescalesets.yml/badge.svg?branch=users%2Fahmad%2F3021_vmss)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachinescalesets.yml) |
> [Modules] Updated VMSS Module to the latest API Version (2022-11-01)

- modules/Microsoft.ContainerService/managedClusters/.bicep/nested_roleAssignments.bicep
- modules/Microsoft.ContainerService/managedClusters/.test/azure/dependencies.bicep
- modules/Microsoft.ContainerService/managedClusters/.test/azure/deploy.test.bicep
- modules/Microsoft.ContainerService/managedClusters/.test/kubenet/dependencies.bicep
- modules/Microsoft.ContainerService/managedClusters/.test/kubenet/deploy.test.bicep
- modules/Microsoft.ContainerService/managedClusters/.test/min/deploy.test.bicep
- modules/Microsoft.ContainerService/managedClusters/agentPools/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/agentPools/readme.md
- modules/Microsoft.ContainerService/managedClusters/deploy.bicep
- modules/Microsoft.ContainerService/managedClusters/readme.md
This PR resolves #3023 
| Pipeline |
| - |
| [![ContainerService - ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Fkrbar%2F3023-aks-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml) |
> [Modules] Updated AKS Module to the latest API Version

- modules/Microsoft.Sql/servers/.test/secondary/deploy.test.bicep
- modules/Microsoft.Sql/servers/encryptionProtector/readme.md
- modules/Microsoft.Sql/servers/readme.md
Closes #3073 
| Pipeline |
| - |
| [![Sql - Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Ferikag%2Fsql-readme)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml) |
> [Fixes] Sql servers readme update

- .ps-rule/na-suppress.Rule.yaml
- modules/Microsoft.Purview/accounts/.test/common/deploy.test.bicep
- modules/Microsoft.Purview/accounts/readme.md
Closes #3085 
| Pipeline |
| - |
| [![Purview - Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.purview.accounts.yml/badge.svg?branch=users%2Ferikag%2Fpsrule-tags-update)](https://github.com/Azure/ResourceModules/actions/workflows/ms.purview.accounts.yml) |
| [![.Platform: Library PSRule pre-flight validation](https://github.com/Azure/ResourceModules/actions/workflows/platform.librarycheck.psrule.yml/badge.svg?branch=users%2Ferikag%2Fpsrule-tags-update)](https://github.com/Azure/ResourceModules/actions/workflows/platform.librarycheck.psrule.yml) |
> [CI Environment] PSRule fix tags suppression group and add tags to purview

- modules/Microsoft.Synapse/workspaces/deploy.bicep
- modules/Microsoft.Synapse/workspaces/readme.md
added a parameter to the synapse workspace to add GIT configuration
https://github.com/Azure/ResourceModules/issues/3092
- [v] I'm sure there are no other open Pull Requests for the same update/change
- [?] My corresponding pipelines / checks run clean and green without any errors or warnings
- [v] My code follows the style guidelines of this project
- [v] I have commented my code, particularly in hard-to-understand areas
- [v] I have made corresponding changes to the documentation (readme)
- [v] I did format my code
> [Modules] SynapseWorkspaces add workspaceRepositoryConfiguration property

- .azuredevops/modulePipelines/ms.digitaltwins.digitaltwinsinstances.yml
- .github/workflows/ms.digitaltwins.digitaltwinsinstances.yml
- modules/Microsoft.DigitalTwins/digitalTwinsInstances/endpoints-eventGrid/readme.md
- modules/Microsoft.DigitalTwins/digitalTwinsInstances/endpoints-eventHub/readme.md
- modules/Microsoft.DigitalTwins/digitalTwinsInstances/endpoints-serviceBus/readme.md
- modules/Microsoft.DigitalTwins/digitalTwinsInstances/readme.md
- Updated ReadMe's of Digital Twins module
| Pipeline |
| - |
| [![DigitalTwins - DigitalTwinsInstances](https://github.com/Azure/ResourceModules/actions/workflows/ms.digitaltwins.digitaltwinsinstances.yml/badge.svg?branch=users%2Falsehr%2FdigitalTwinReadME)](https://github.com/Azure/ResourceModules/actions/workflows/ms.digitaltwins.digitaltwinsinstances.yml) |
> [Fixes] Updated ReadMe's of Digital Twins module

- .github/ISSUE_TEMPLATE/question_feedback.yml
Closes #3063 
| Pipeline |
| - |
| |
> [CI Environment] Add template for question issue

- .github/ISSUE_TEMPLATE/config.yml
Closes #3061 
| Pipeline |
| - |
| |
> [CI Environment] Enforce opening issues through template

- modules/Microsoft.Compute/virtualMachines/deploy.bicep
- modules/Microsoft.Compute/virtualMachines/extensions/deploy.bicep
- modules/Microsoft.Compute/virtualMachines/extensions/readme.md
> [Modules] Add tags on VM extensions. Fixes #3115

- modules/Microsoft.Compute/virtualMachines/.test/linux/deploy.test.bicep
- modules/Microsoft.Compute/virtualMachines/.test/windows/deploy.test.bicep
- modules/Microsoft.Compute/virtualMachines/extensions/readme.md
- modules/Microsoft.Compute/virtualMachines/readme.md
Closes #3127 
Closes #3123 
| Pipeline |
| - |
| [![Compute - VirtualMachines](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml/badge.svg?branch=users%2Ferikag%2Fvm-tags-update)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml) |
> [Modules] Fix readme and add tags to VM extension examples

- modules/Microsoft.ManagedIdentity/userAssignedIdentities/deploy.bicep
- modules/Microsoft.ManagedIdentity/userAssignedIdentities/readme.md
Fixes #3113  - adds output param.
| Pipeline |
| - |
| |
> [Modules] Update User Managed Identity module to output Client ID (Application ID)

- README.md
- docs/wiki/Home.md
- docs/wiki/The CI environment - Troubleshooting.md
- Added guidelines to troubleshoot outdated Bicep versions
> [Wiki] Added guidelines to troubleshoot outdated Bicep versions

- .github/workflows/platform.linter.yml
- Renamed linter pipline to show it is optional
> [CI Environment] Renamed linter pipline to show it is optional

- modules/Network/privateLinkServices/.bicep/nested_roleAssignments.bicep
- modules/Network/privateLinkServices/.test/common/dependencies.bicep
- modules/Network/privateLinkServices/.test/common/main.test.bicep
- modules/Network/privateLinkServices/.test/min/dependencies.bicep
- modules/Network/privateLinkServices/.test/min/main.test.bicep
- modules/Network/privateLinkServices/README.md
- modules/Network/privateLinkServices/main.bicep
PR resolves #3170 and updated module to the newest API version.
| Pipeline |
| - |
| [![Network - PrivateLinkServices](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.privatelinkservices.yml/badge.svg?branch=users%2Fkrbar%2F3170-privatelinkservices)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.privatelinkservices.yml) |
> [Modules] Updated Private Link Services module to the newest API

- modules/Network/applicationGatewayWebApplicationFirewallPolicies/.test/common/main.test.bicep
- modules/Network/applicationGatewayWebApplicationFirewallPolicies/README.md
- modules/Network/applicationGatewayWebApplicationFirewallPolicies/main.bicep
PR closes #3174 and updates module to the newest API versions
| Pipeline |
| - |
| [![Network - ApplicationGatewayWebApplicationFirewallPolicies](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationgatewaywebapplicationfirewallpolicies.yml/badge.svg?branch=users%2Fkrbar%2F3174-applicationgatewaywebapplicationfirewallpolicies)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.applicationgatewaywebapplicationfirewallpolicies.yml) |
> [Modules] Updated ApplicationGateway WAF Policies Module to latest API 

- modules/Network/bastionHosts/.bicep/nested_roleAssignments.bicep
- modules/Network/bastionHosts/.test/common/dependencies.bicep
- modules/Network/bastionHosts/.test/common/main.test.bicep
- modules/Network/bastionHosts/.test/custompip/dependencies.bicep
- modules/Network/bastionHosts/.test/custompip/main.test.bicep
- modules/Network/bastionHosts/.test/min/dependencies.bicep
- modules/Network/bastionHosts/.test/min/main.test.bicep
- modules/Network/bastionHosts/README.md
- modules/Network/bastionHosts/main.bicep
PR resolves #3181, updates module to the latest API version and adds parameter `enableKerberos`
| Pipeline |
| - |
| [![Network - BastionHosts](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.bastionhosts.yml/badge.svg?branch=users%2Fkrbar%2F3181-bastionhosts)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.bastionhosts.yml) |
> [Modules] Updated Bastion Hosts to latest API and added new parameter

- modules/DocumentDB/databaseAccounts/.bicep/nested_roleAssignments.bicep
- modules/DocumentDB/databaseAccounts/.test/gremlindb/dependencies.bicep
- modules/DocumentDB/databaseAccounts/.test/mongodb/dependencies.bicep
- modules/DocumentDB/databaseAccounts/.test/plain/dependencies.bicep
- modules/DocumentDB/databaseAccounts/.test/sqldb/dependencies.bicep
- modules/DocumentDB/databaseAccounts/README.md
- modules/DocumentDB/databaseAccounts/gremlinDatabases/README.md
- modules/DocumentDB/databaseAccounts/gremlinDatabases/graphs/README.md
- modules/DocumentDB/databaseAccounts/gremlinDatabases/graphs/main.bicep
- modules/DocumentDB/databaseAccounts/gremlinDatabases/main.bicep
- modules/DocumentDB/databaseAccounts/main.bicep
- modules/DocumentDB/databaseAccounts/mongodbDatabases/README.md
- modules/DocumentDB/databaseAccounts/mongodbDatabases/collections/README.md
- modules/DocumentDB/databaseAccounts/mongodbDatabases/collections/main.bicep
- modules/DocumentDB/databaseAccounts/mongodbDatabases/main.bicep
- modules/DocumentDB/databaseAccounts/sqlDatabases/README.md
- modules/DocumentDB/databaseAccounts/sqlDatabases/containers/README.md
- modules/DocumentDB/databaseAccounts/sqlDatabases/containers/main.bicep
- modules/DocumentDB/databaseAccounts/sqlDatabases/main.bicep
PR resolves #3177 and updates the DocumentDB module (and child modules) to the newest API versions
| Pipeline |
| - |
| [![DocumentDB - DatabaseAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml/badge.svg?branch=users%2Fkrbar%2F3177-documentdb)](https://github.com/Azure/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml) |
> [Modules] Updated the DocumentDB to the newest API

- modules/synapse/workspaces/.test/common/main.test.bicep
- modules/synapse/workspaces/README.md
- modules/synapse/workspaces/main.bicep
Add missing diagnostic logs for Synapse workspace
[![Synapse - Workspaces](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.synapse.workspaces.yml/badge.svg?branch=fix%2Fsynpase-diag)](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.synapse.workspaces.yml)
> Update Synapse Diagnostic Logs

- docs/wiki/Getting started - Prerequisites.md
- docs/wiki/Getting started.md
- docs/wiki/Home.md
- docs/wiki/_Sidebar.md
- Added prerequisites section to wiki
> [Wiki] Added prerequisites section

- modules/app/container-apps/README.md
- modules/app/container-apps/main.bicep
- modules/db-for-my-sql/flexible-servers/README.md
- modules/db-for-my-sql/flexible-servers/main.bicep
- modules/db-for-postgre-sql/flexible-servers/README.md
- modules/db-for-postgre-sql/flexible-servers/main.bicep
- modules/synapse/workspaces/keys/README.md
- modules/synapse/workspaces/keys/main.bicep
Set param enableDefaultTelemetry bool = true in all modules and tests
close #3327 
| Pipeline |
| - |
|[![DbForPostgreSQL - FlexibleServers](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml) |
|[![DbForMySQL - FlexibleServers](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbformysql.flexibleservers.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbformysql.flexibleservers.yml)|
|[![Synapse - Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml/badge.svg)](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml)| …
> [Modules] fixed telemetry default value

- docs/wiki/Getting started - Scenario 1 Consume library.md
> Command for key vault module deployment(sample guideline) was not correct hence updated the same
| Pipeline |
| - |
| |
> [Wiki] Update Getting started - Scenario 1 Consume library.md

- docs/wiki/Getting started - Scenario 1 Consume library.md
updated key-vault from keyvault
Document was referring KeyVault hence changed to key-vault as per new repo structure
key-vault
| Pipeline |
| - |
| |
> Update Getting started - Scenario 1 Consume library.md

- modules/network/service-endpoint-policies/.test/common/dependencies.bicep
- modules/network/service-endpoint-policies/.test/common/main.test.bicep
- modules/network/service-endpoint-policies/.test/min/main.test.bicep
- modules/network/service-endpoint-policies/README.md
- modules/network/service-endpoint-policies/main.bicep
- Added support for dependencies for the common test scenario
- Updated syntax
| Pipeline |
| - |
|[![Network - ServiceEndpointPolicies](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.serviceendpointpolicies.yml/badge.svg?branch=users%2Fahmad%2FserviceEndpointPolicy)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.serviceendpointpolicies.yml) |
> [Modules] Updated Service Endpoints Policy Module - Follow up

- modules/relay/namespaces/.test/common/main.test.bicep
- modules/relay/namespaces/.test/main.test.bicep
- modules/relay/namespaces/.test/min/main.test.bicep
- modules/relay/namespaces/.test/pe/main.test.bicep
Updated the Relay namespace module:
- Added namePrefix parameter
- Added new test file aligning with the new changes.
| Pipeline |
| - |
|[![Relay - Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.relay.namespaces.yml/badge.svg?branch=users%2Fahmad%2FrelayFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.relay.namespaces.yml) |
> [Modules] Updated Relay Namespace Module to align with new Bicep Test file changes

- modules/data-protection/backup-vaults/.bicep/nested_roleAssignments.bicep
- modules/data-protection/backup-vaults/.test/common/main.test.bicep
- modules/data-protection/backup-vaults/README.md
- modules/data-protection/backup-vaults/backup-policies/README.md
- modules/data-protection/backup-vaults/backup-policies/main.bicep
- modules/data-protection/backup-vaults/main.bicep
Closes #3363 
Updated API version and added new property
| Pipeline |
| - |
|[![DataProtection - BackupVaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.dataprotection.backupvaults.yml/badge.svg?branch=users%2Fahmad%2F3363_backupVaults)](https://github.com/Azure/ResourceModules/actions/workflows/ms.dataprotection.backupvaults.yml) |
> [Modules] Updated Data Protection Backup Vaults Module API Version

- modules/db-for-my-sql/flexible-servers/README.md
- modules/db-for-my-sql/flexible-servers/databases/README.md
- modules/db-for-my-sql/flexible-servers/firewall-rules/README.md
Azure Resource Reference doc now includes latest used api versions
Closes #3395 
| Pipeline |
| - |
| [![DbForMySQL - FlexibleServers](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbformysql.flexibleservers.yml/badge.svg?branch=users%2Ferikag%2Fdbformysql-readme)](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbformysql.flexibleservers.yml) |
> [Fixes] DBforMySQL flexibleServers Readme update

- modules/sql/managed-instances/.test/common/dependencies.bicep
- modules/sql/managed-instances/.test/common/main.test.bicep
Closes #3366 
| Pipeline |
| - |
| [![Sql - ManagedInstances](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml/badge.svg?branch=users%2Ferikag%2Fsqlmi-cmk)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml) |
> [Modules] SqlMi - Enable purge protection on cmk dep kv

- modules/network/virtual-hubs/hub-route-tables/README.md
- modules/network/virtual-hubs/hub-virtual-network-connections/README.md
Regenerate vhub readmes
Fixes pipeline failure
| Pipeline |
| - |
| [![Network - VirtualHubs](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualhubs.yml/badge.svg?branch=users%2Ferikag%2Freadme-vhub)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.virtualhubs.yml) |
> [Fixes] Virtual Hubs readme regen

- docs/wiki/Solution creation.md
- docs/wiki/The context - CARML CI environment.md
- docs/wiki/The context - Logical layers and personas.md
- Update 'context' section to latest
> [Wiki] Update 'context' section to latest

- utilities/tools/ConvertTo-ARMTemplate.ps1
Updated utilty to NOT remove the module name, description, etc.
Result test files:
```JSON
{
"$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#",
"contentVersion": "1.0.0.0",
"metadata": {},
"parameters": {
"resourceGroupName": {
"type": "string",
"defaultValue": "[format('ms.analysisservices.servers-{0}-rg', parameters('serviceShort'))]",
"maxLength": 90,
"metadata": {
"description": "Optional. The name of the resource group to deploy for testing purposes."
}
},
(...)
}
```
Result template files:
```JSON
{
"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
"contentVersion": "1.0.0.0",
"metadata": {
"name": "Analysis Services Servers",
"description": "This module deploys an Analysis Services …
```
> [Utilities] Updated Bicep to ARM conversion script

- docs/wiki/Getting started - Get module cross-references.md
- docs/wiki/Getting started - Scenario 1 Consume library.md
- docs/wiki/Getting started - Scenario 2 Onboard module library and CI environment.md
- utilities/tools/Get-CrossReferencedModuleList.ps1
- Updated 'Getting Started' sections (& utilities) to latest
> [Wiki] Updated 'Getting Started' sections (& utilities) to latest

- docs/wiki/Solution creation.md
- Updated 'solution creation' to latest
> [Wiki] Updated 'solution creation' to latest

- docs/wiki/Fetching latest changes - Scenario 1 Consume library.md
- docs/wiki/Fetching latest changes - Scenario 2 Module library and CI environment.md
- Updated 'Fetching changes' to latest version
> [Wiki] Updated 'Fetching changes' to latest version

- docs/wiki/Known issues.md
- Updated 'known issues' to latest
> [Wiki] Updated 'known issues' to latest

- modules/synapse/workspaces/main.bicep
- modules/synapse/workspaces/main.json
- Small fix of the CMK interface to address a warning
| Pipeline |
| - |
| [![Synapse - Workspaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml/badge.svg?branch=users%2Falsehr%2FsynapseWarning)](https://github.com/Azure/ResourceModules/actions/workflows/ms.synapse.workspaces.yml) |
> [Modules] Updated Synapse CMK interface

- modules/storage/storage-accounts/blob-services/containers/immutability-policies/main.json
- modules/storage/storage-accounts/blob-services/containers/main.json
- modules/storage/storage-accounts/blob-services/main.json
- modules/storage/storage-accounts/file-services/main.json
- modules/storage/storage-accounts/file-services/shares/main.json
- modules/storage/storage-accounts/local-users/main.json
- modules/storage/storage-accounts/main.json
- modules/storage/storage-accounts/management-policies/main.json
- modules/storage/storage-accounts/queue-services/main.json
- modules/storage/storage-accounts/queue-services/queues/main.json
- modules/storage/storage-accounts/table-services/main.json
- modules/storage/storage-accounts/table-services/tables/main.json
Closes #3552 
| Pipeline |
| - |
| [![Storage - StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Ferikag%2Fstorage-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml) |
> [Fixes] Update storage account main.json

- modules/db-for-my-sql/flexible-servers/databases/main.json
- modules/db-for-my-sql/flexible-servers/firewall-rules/main.json
- modules/db-for-my-sql/flexible-servers/main.json
- modules/db-for-postgre-sql/flexible-servers/README.md
- modules/db-for-postgre-sql/flexible-servers/configurations/README.md
- modules/db-for-postgre-sql/flexible-servers/configurations/main.json
- modules/db-for-postgre-sql/flexible-servers/databases/README.md
- modules/db-for-postgre-sql/flexible-servers/databases/main.json
- modules/db-for-postgre-sql/flexible-servers/firewall-rules/README.md
- modules/db-for-postgre-sql/flexible-servers/firewall-rules/main.json
- modules/db-for-postgre-sql/flexible-servers/main.json
DB for postgreSQL regenerate readmes and json files
| Pipeline |
| - |
| [![DbForPostgreSQL - FlexibleServers](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml/badge.svg?branch=users%2Ferikag%2Fdbfor-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.dbforpostgresql.flexibleservers.yml) |
> [Fixes] DB for postgreSQL regenerate readmes and json files

- .azuredevops/modulePipelines/ms.network.expressroutegateways.yml
- .github/workflows/ms.network.expressroutegateways.yml
ExpressRouteGateway - Update pipeline name to align with naming convention now automatically tested by Pester
| Pipeline |
| - |
| |
> [Fixes] ExpressRouteGateway - Update pipeline name to align with naming convention

- .azuredevops/modulePipelines/ms.compute.virtualmachines.yml
- .github/workflows/ms.compute.virtualmachines.yml
- modules/compute/virtual-machines/README.md
- modules/compute/virtual-machines/extensions/main.json
- modules/compute/virtual-machines/main.bicep
- modules/compute/virtual-machines/main.json
Closes #3541 
| Pipeline |
| - |
| [![Compute - VirtualMachines](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml/badge.svg?branch=users%2Ferikag%2Fvm-fix&event=fork)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml) |
> [Fixes] VM - Update cross reference to updated rsv module

- .github/workflows/ms.network.expressroutegateways.yml
- utilities/tools/helper/Get-SpecsAlignedResourceName.ps1
Closes #3515 
Update get core function
Fixes expressroutegateways validation pipeline
| Pipeline |
| - |
| [![Network - ExpressRouteGateways](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.expressroutegateways.yml/badge.svg?branch=users%2Ferikag%2Fexpgateway-fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.expressroutegateways.yml) |
> [Fixes] Update get core function

- modules/network/azure-firewalls/.test/addpip/dependencies.bicep
- modules/network/azure-firewalls/.test/addpip/main.test.bicep
- modules/network/azure-firewalls/README.md
- modules/network/azure-firewalls/main.bicep
- modules/network/azure-firewalls/main.json
> Based on PR #3338 
Fixes #3305 
Adds the newer 'Basic' SKU for Azure Firewall and it's accompanying Management Public IP logic.
| Pipeline |
| - |
| [![Network - AzureFirewalls](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.azurefirewalls.yml/badge.svg?branch=users%2Falsehr%2FDanoThom_azure-firewall-basic-sku)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.azurefirewalls.yml) |
> [Modules] Azure Firewall - Added 'Basic' SKU support

- docs/wiki/Getting started - Prerequisites.md
> [Wiki] Fix 'av bicep version' typo

- modules/cdn/profile/README.md
- modules/cdn/profile/main.bicep
- modules/cdn/profile/main.json
Closes #3712 
Bicep Parameters for Front Door modules was missing correct values.
> [Modules] Allowed missing Front Door SKUs

- modules/sql/server/.test/common/main.test.bicep
- Bug fix for the SQL server test for maintenance where the location was hardcoded to west europe.
| Pipeline |
| - |
|[![Sql - Servers](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml/badge.svg?branch=users%2Fahmad%2FsqlMIupdate)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.servers.yml) |
> [Modules] Update SQL Server test to support dynamic location parameter for Maintenance Configuration

- modules/document-db/database-account/README.md
- modules/document-db/database-account/mongodb-database/README.md
- modules/network/virtual-network/README.md
- modules/operational-insights/workspace/README.md
- Fixed diverse in-readme references to child-modules that still used the classic folder naming scheme
| Pipeline |
| - |
| [![.Platform: Broken Links Check](https://github.com/Azure/ResourceModules/actions/workflows/platform.linkcheck.yml/badge.svg?branch=users%2Falsehr%2F3874_branchFix)](https://github.com/Azure/ResourceModules/actions/workflows/platform.linkcheck.yml) |
> Fixed diverse references

- docs/wiki/Getting started - Scenario 2 Onboard module library and CI environment.md
- docs/wiki/The CI environment - Publishing.md
Updated Guidelines around publishing
> [Wiki] Updated Guidelines around publishing

- modules/data-protection/backup-vault/.bicep/nested_roleAssignments.bicep
- modules/data-protection/backup-vault/README.md
- modules/data-protection/backup-vault/backup-policy/README.md
- modules/data-protection/backup-vault/backup-policy/main.bicep
- modules/data-protection/backup-vault/backup-policy/main.json
- modules/data-protection/backup-vault/main.bicep
- modules/data-protection/backup-vault/main.json
- Updated Data-Protection Vault API version
| Pipeline |
| - |
| [![DataProtection - BackupVaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.dataprotection.backupvaults.yml/badge.svg?branch=users%2Falsehr%2Frsv_api)](https://github.com/Azure/ResourceModules/actions/workflows/ms.dataprotection.backupvaults.yml) |
> [Modules] Updated Data-Protection Vault API version

- docs/wiki/Known issues.md
- modules/managed-services/registration-definition/.test/common/main.test.bicep
- modules/managed-services/registration-definition/.test/rg/main.test.bicep
- modules/managed-services/registration-definition/README.md
Added 'Known Issue' for Lighthouse
> [Modules] Added 'Known Issue' for Lighthouse

- modules/management/management-group/.test/main.test.bicep
- Fixed incorrect target scope for `/.test/main.test.bicep` template. This did not yet raise attention as we've not build compiling the file (something I'm doing now across the board)
> [Fixes] ManagementGroup: Fixed test template target scope

- modules/policy-insights/remediation/.test/main.test.bicep
- Policy-Insights: Fixed possible scope for test cases
- This is in alignment with e.g., the authorization namespace tests
| Pipeline |
| - |
| [![PolicyInsights - Remediations](https://github.com/Azure/ResourceModules/actions/workflows/ms.policyinsights.remediations.yml/badge.svg?branch=users%2Falsehr%2FpolicyInsightsTests)](https://github.com/Azure/ResourceModules/actions/workflows/ms.policyinsights.remediations.yml) |
> [Fixes] Policy-Insights: Fixed possible scope for test cases

- modules/authorization/lock/.test/common/main.test.bicep
- modules/authorization/lock/.test/main.test.bicep
- Lock: Removed unused test parameter
[![Authorization - Locks](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.locks.yml/badge.svg?branch=users%2Falsehr%2FlockUnusedTestParam)](https://github.com/Azure/ResourceModules/actions/workflows/ms.authorization.locks.yml)
> [Fixes] Lock: Removed unused test parameter

- modules/container-service/managed-cluster/README.md
- modules/container-service/managed-cluster/agent-pool/README.md
- modules/healthcare-apis/workspace/README.md
- modules/healthcare-apis/workspace/dicomservice/README.md
- modules/healthcare-apis/workspace/fhirservice/README.md
- modules/healthcare-apis/workspace/iotconnector/README.md
- modules/healthcare-apis/workspace/iotconnector/fhirdestination/README.md
- modules/insights/action-group/README.md
Readme updates for updated resource type url ref
| Pipeline |
| - |
| |
> [Fixes] Readme updates for updated resource type url ref

- .ps-rule/min-suppress.Rule.yaml
- modules/network/public-ip-address/README.md
- modules/network/public-ip-address/main.bicep
- modules/network/public-ip-address/main.json
This PR solve then issues described in the Issue #3997 as follows:
- Added supression of the rule Azure.PublicIP.AvailabilityZone for min tests.
- Set default value for skuName to Standard.
Closes #3997
| Pipeline |
| - |
|[![Network - PublicIpAddresses](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.publicipaddresses.yml/badge.svg?branch=users%2Felbatane%2Fpsrulepublicip)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.publicipaddresses.yml) |
> [PSRule] Public Ip addresses

- .azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
- .github/actions/templates/validateModuleDeployment/action.yml
- .github/actions/templates/validateModulePester/action.yml
- modules/key-vault/vault/README.md
- modules/web/site/slot/README.md
- utilities/pipelines/sharedScripts/Get-LocallyReferencedFileList.ps1
- utilities/tools/Get-CrossReferencedModuleList.ps1
- Updated reference resolution to simplified AVM approach
- Regenerated all docs to ensure nothing is lost
| Pipeline |
| - |
| [![CognitiveServices - Accounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml/badge.svg?branch=users%2Falsehr%2FreferencesScript)](https://github.com/Azure/ResourceModules/actions/workflows/ms.cognitiveservices.accounts.yml) |
| [![Build Status](https://dev.azure.com/carml/CARML/_apis/build/status%2FModules%2FKeyVault%20-%20Vaults?branchName=users%2Falsehr%2FreferencesScript)](https://dev.azure.com/carml/CARML/_build/latest?definitionId=46&branchName=users%2Falsehr%2FreferencesScript) |
> [CI Environment] Updated reference resolution to simplified AVM approach

- modules/key-vault/vault/README.md
- modules/key-vault/vault/access-policy/main.json
- modules/key-vault/vault/key/main.json
- modules/key-vault/vault/secret/main.json
Hot fix for Key Vault module pipeline failure.
| Pipeline |
| - |
| [![KeyVault - Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=users%2Fahmad%2FKV_hotfix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml)|
> [Modules] Updated Key Vault Module Readme

- modules/web/site/.bicep/nested_roleAssignments.bicep
- modules/web/site/.test/webAppCommon/main.test.bicep
- modules/web/site/README.md
- modules/web/site/basic-publishing-credentials-policy/README.md
- modules/web/site/basic-publishing-credentials-policy/main.bicep
- modules/web/site/basic-publishing-credentials-policy/main.json
- modules/web/site/config--appsettings/README.md
- modules/web/site/config--appsettings/main.bicep
- modules/web/site/config--appsettings/main.json
- modules/web/site/config--authsettingsv2/README.md
- modules/web/site/config--authsettingsv2/main.bicep
- modules/web/site/config--authsettingsv2/main.json
- modules/web/site/hybrid-connection-namespace/relay/README.md
- modules/web/site/hybrid-connection-namespace/relay/main.bicep
- modules/web/site/hybrid-connection-namespace/relay/main.json
- modules/web/site/main.bicep
- modules/web/site/main.json
- modules/web/site/slot/.bicep/nested_roleAssignments.bicep
- modules/web/site/slot/README.md
- modules/web/site/slot/config--appsettings/README.md
- modules/web/site/slot/config--appsettings/main.bicep
- modules/web/site/slot/config--appsettings/main.json
- modules/web/site/slot/config--authsettingsv2/README.md
- modules/web/site/slot/config--authsettingsv2/main.bicep
- modules/web/site/slot/config--authsettingsv2/main.json
- modules/web/site/slot/hybrid-connection-namespace/relay/README.md
- modules/web/site/slot/hybrid-connection-namespace/relay/main.bicep
- modules/web/site/slot/hybrid-connection-namespace/relay/main.json
- modules/web/site/slot/main.bicep
- modules/web/site/slot/main.json
- Co-authored with @chris5287 
- Updated Web Sites parent module to support Public Network Access Parameter.
- Uplifted API version to latest documented `2022-09-01`
- Added additional parameters and test cases to validate them.
- scmSiteAlsoStopped
- vnetContentShareEnabled
- vnetImagePullEnabled
- vnetRouteAllEnabled
- publicNetworkAccess
- Removed comments from the module bicep files to align with all other CARML modules.
- Updated API versions for other components used in the modules.
- Regenerated all readmes
- Regenerated all JSON files.
| Pipeline |
| - |
| [![Web - Sites](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml/badge.svg?branch=users%2Fahmad%2F4024_WebSites)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.sites.yml)|
> [Modules] Updated Web Sites API Version to '2022-09-01' and added new parameters

- modules/container-service/managed-cluster/main.bicep
Fix the outputs for `azureKeyvaultSecretsProvider` which has a typo in the parameter 
| Pipeline |
| - |
| |
> Fix AKS Key Vault Outputs

- modules/container-service/managed-cluster/.test/azure/dependencies.bicep
- modules/container-service/managed-cluster/.test/azure/main.test.bicep
- modules/container-service/managed-cluster/README.md
- modules/container-service/managed-cluster/agent-pool/main.json
- modules/container-service/managed-cluster/main.bicep
- modules/container-service/managed-cluster/main.json
Closes #4031 
- Updated bug on the output for the Key Vault Secrets Provider. Collab with @coolhome
- Added additional test cases on the `Azure` test scenario to cover additional parameters
| Pipeline |
| - |
|[![ContainerService - ManagedClusters](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml/badge.svg?branch=users%2Fahmad%2FAKS_Fix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.containerservice.managedclusters.yml) |
> [Modules] Fixed AKS Key Vault Secrets Provider Output and added additional test parameters

- modules/key-vault/vault/README.md
- modules/sql/managed-instance/README.md
- modules/sql/server/README.md
- utilities/tools/Get-CrossReferencedModuleList.ps1
- utilities/tools/Set-ModuleReadMe.ps1
- Fixed issue where Keyvault-Keys resource lead to a Hashtable object reference 'keys' not being resolved
- Fixed issue with ReferenceResolution where remote references (i.e., registry) were not considered
- Re-ran all readme generation scripts
| Pipeline |
| - |
| [![Compute - VirtualMachines](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml/badge.svg?branch=users%2Falsehr%2FreadMeFixAVM)](https://github.com/Azure/ResourceModules/actions/workflows/ms.compute.virtualmachines.yml) |
| [![KeyVault - Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=users%2Falsehr%2FreadMeFixAVM)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml) |
> [Fixes] Fixed small issues of readme generation script

- modules/network/virtual-network/subnet/README.md
<details>
<summary>Issues that this PR fixes</summary>
Fixes #3007 
</details>
| Pipeline |
| - |
| |
> Parameter Usage: Service endpoints fix 

- modules/event-hub/namespace/.bicep/nested_roleAssignments.bicep
- modules/event-hub/namespace/.test/common/main.test.bicep
- modules/event-hub/namespace/.test/pe/main.test.bicep
- modules/event-hub/namespace/README.md
- modules/event-hub/namespace/authorization-rule/README.md
- modules/event-hub/namespace/authorization-rule/main.bicep
- modules/event-hub/namespace/authorization-rule/main.json
- modules/event-hub/namespace/disaster-recovery-config/README.md
- modules/event-hub/namespace/disaster-recovery-config/main.bicep
- modules/event-hub/namespace/disaster-recovery-config/main.json
- modules/event-hub/namespace/eventhub/.bicep/nested_roleAssignments.bicep
- modules/event-hub/namespace/eventhub/README.md
- modules/event-hub/namespace/eventhub/authorization-rule/README.md
- modules/event-hub/namespace/eventhub/authorization-rule/main.bicep
- modules/event-hub/namespace/eventhub/authorization-rule/main.json
- modules/event-hub/namespace/eventhub/consumergroup/README.md
- modules/event-hub/namespace/eventhub/consumergroup/main.bicep
- modules/event-hub/namespace/eventhub/consumergroup/main.json
- modules/event-hub/namespace/eventhub/main.bicep
- modules/event-hub/namespace/eventhub/main.json
- modules/event-hub/namespace/main.bicep
- modules/event-hub/namespace/main.json
- modules/event-hub/namespace/network-rule-set/README.md
- modules/event-hub/namespace/network-rule-set/main.bicep
- modules/event-hub/namespace/network-rule-set/main.json
- Updated to the latest documented API version for Event Hub (2022-10-01-preview)
- Added additional test cases parameters to the 'common' and 'pe' test case for more coverage.
- Validated idempotency for the 'common' test case.
- Added support for retention
- Updated JSON files
- Reduced code duplication in the event hub child module by using the `union()` function to combine properties when required.
| Pipeline |
| - |
| [![EventHub - Namespaces](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml/badge.svg?branch=users%2Fahmad%2Fupdate_eventHub)](https://github.com/Azure/ResourceModules/actions/workflows/ms.eventhub.namespaces.yml)|
> [Modules] Uplift the Event Hub Module API Version, add support for Retention and additional test cases

- modules/db-for-postgre-sql/flexible-server/main.bicep
When redeploying `modules/db-for-postgres/flexible-server/main.bicep` that has 3 configurations will produce a failed deployment most of the time. Each run has a possibility of at least one configuration failure with the following message: Setting batchSize(1) gave me 100% successful redeployments out of 10 deployments.
I imagine the MySql database is similar.
```json
{
"code": "DeploymentFailed",
"target": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Resources/deployments/<redacted>",
"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
"details": [
{
"code": "ResourceDeploymentFailure",
"target": …
```
> [Modules] Update the PostgreSQL - Configurations child module deployment to be sequential

- .azuredevops/modulePipelines/ms.databricks.accessconnectors.yml
- .github/workflows/ms.databricks.accessconnectors.yml
- modules/databricks/access-connector/.bicep/nested_roleAssignments.bicep
- modules/databricks/access-connector/.test/common/dependencies.bicep
- modules/databricks/access-connector/.test/common/main.test.bicep
- modules/databricks/access-connector/.test/min/main.test.bicep
- modules/databricks/access-connector/README.md
- modules/databricks/access-connector/main.bicep
- modules/databricks/access-connector/main.json
- modules/databricks/access-connector/version.json
Created a new module for Databricks Access Connectors using the latest documented APIs (https://learn.microsoft.com/en-us/azure/templates/microsoft.databricks/workspaces?pivots=deployment-language-bicep)
- Generated RBAC list
- Added test cases `common` and `min`
- Generated Readme
- Generated JSON
| Pipeline |
| - |
|[![Databricks - Access Connectors](https://github.com/ahmadabdalla/ResourceModules/actions/workflows/ms.databricks.accessconnectors.yml/badge.svg?branch=main)](https://github.com/ahmadabdalla/ResourceModules/actions/workflows/ms.databricks.accessconnectors.yml) |
**NOTE**: Pipeline is failing on publishing stage due to name BR conflict
> [Modules] New Module - Databricks Access Connectors

- modules/key-vault/vault/access-policy/README.md
- modules/key-vault/vault/key/README.md
- modules/key-vault/vault/secret/README.md
- modules/kubernetes-configuration/extension/README.md
- modules/kubernetes-configuration/flux-configuration/README.md
- modules/logic/workflow/README.md
- modules/machine-learning-services/workspace/README.md
- modules/machine-learning-services/workspace/compute/README.md
- modules/machine-learning-services/workspace/compute/main.bicep
- modules/machine-learning-services/workspace/compute/main.json
- modules/machine-learning-services/workspace/main.json
- modules/maintenance/maintenance-configuration/README.md
- modules/managed-services/registration-definition/README.md
- modules/management/management-group/README.md
- modules/network/azure-firewall/README.md
- modules/network/bastion-host/README.md
- modules/network/connection/README.md
- modules/network/dns-resolver/README.md
- modules/network/load-balancer/README.md
- modules/network/network-interface/README.md
- modules/network/network-manager/README.md
- modules/network/network-manager/main.bicep
- modules/network/private-dns-zone/txt/README.md
- modules/network/private-endpoint/README.md
Moved and removed diverse custom readme notes as preparation for AVM
>  [AVM] Updated Readme's to support AVM transition - Part (-3) 

- modules/network/network-manager/README.md
- modules/network/network-manager/connectivity-configuration/main.json
- modules/network/network-manager/main.json
- modules/network/network-manager/network-group/main.json
- modules/network/network-manager/network-group/static-member/main.json
- modules/network/network-manager/scope-connection/main.json
- modules/network/network-manager/security-admin-configuration/main.json
- modules/network/network-manager/security-admin-configuration/rule-collection/main.json
- modules/network/network-manager/security-admin-configuration/rule-collection/rule/main.json
> [Modules] Updated Network Manager JSON Files and Readmes

- utilities/pipelines/staticValidation/helper/helper.psm1
- Made metadata removal ready for UDT by adding a case handling for whether the resources in the compiled template of of type array or hashtable
| Pipeline |
| - |
| [![KeyVault - Vaults](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml/badge.svg?branch=users%2Falsehr%2FremoveMetaUpdateForUDT)](https://github.com/Azure/ResourceModules/actions/workflows/ms.keyvault.vaults.yml) |
> [Utilities] Made metadata removal ready for UDT

- modules/sql/managed-instance/.bicep/nested_roleAssignments.bicep
- modules/sql/managed-instance/README.md
- modules/sql/managed-instance/administrator/README.md
- modules/sql/managed-instance/administrator/main.bicep
- modules/sql/managed-instance/administrator/main.json
- modules/sql/managed-instance/database/README.md
- modules/sql/managed-instance/database/backup-long-term-retention-policy/README.md
- modules/sql/managed-instance/database/backup-long-term-retention-policy/main.bicep
- modules/sql/managed-instance/database/backup-long-term-retention-policy/main.json
- modules/sql/managed-instance/database/backup-short-term-retention-policy/README.md
- modules/sql/managed-instance/database/backup-short-term-retention-policy/main.bicep
- modules/sql/managed-instance/database/backup-short-term-retention-policy/main.json
- modules/sql/managed-instance/database/main.bicep
- modules/sql/managed-instance/database/main.json
- modules/sql/managed-instance/encryption-protector/README.md
- modules/sql/managed-instance/encryption-protector/main.bicep
- modules/sql/managed-instance/encryption-protector/main.json
- modules/sql/managed-instance/key/README.md
- modules/sql/managed-instance/key/main.bicep
- modules/sql/managed-instance/key/main.json
- modules/sql/managed-instance/main.bicep
- modules/sql/managed-instance/main.json
- modules/sql/managed-instance/security-alert-policy/README.md
- modules/sql/managed-instance/security-alert-policy/main.bicep
- modules/sql/managed-instance/security-alert-policy/main.json
- modules/sql/managed-instance/vulnerability-assessment/.bicep/nested_storageRoleAssignment.bicep
- modules/sql/managed-instance/vulnerability-assessment/README.md
- modules/sql/managed-instance/vulnerability-assessment/main.bicep
- modules/sql/managed-instance/vulnerability-assessment/main.json
Closes #4095 
| Pipeline |
| - |
| [![Sql - ManagedInstances](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml/badge.svg?branch=users%2Fahmad%2FAPI_BugFixes_SQLMI)](https://github.com/Azure/ResourceModules/actions/workflows/ms.sql.managedinstances.yml)|
> [Modules] Updated SQL Managed Instance module API Version

- modules/web/serverfarm/README.md
- modules/web/serverfarm/main.bicep
- modules/web/serverfarm/main.json
| Pipeline |
| - |
|[![Web - Serverfarms](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.serverfarms.yml/badge.svg?branch=users%2Fahmad%2Fasp_uplift_hotfix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.web.serverfarms.yml) |
> [Modules] Hotfix for the App Service Plan module to fix the conditional parameter description

- modules/network/dns-forwarding-ruleset/MOVED-TO-AVM.md
- modules/network/dns-forwarding-ruleset/README.md
- modules/network/dns-resolver/MOVED-TO-AVM.md
- modules/network/dns-resolver/README.md
- modules/network/dns-zone/MOVED-TO-AVM.md
- modules/network/dns-zone/README.md
- modules/network/private-dns-zone/MOVED-TO-AVM.md
- modules/network/private-dns-zone/README.md
| Pipeline |
| - |
| [![Network - DNS Forwarding Rulesets](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.dnsforwardingrulesets.yml/badge.svg?branch=usrs%2Fcsidebotham%2Fcs-avm-module-notes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.dnsforwardingrulesets.yml)  |
| [![Network - PrivateDnsZones](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.privatednszones.yml/badge.svg?branch=usrs%2Fcsidebotham%2Fcs-avm-module-notes)](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.privatednszones.yml) |
| [![Network - DNS Resolvers](https://github.com/Azure/ResourceModules/actions/workflows/ms.network.dnsresolvers.yml/badge.svg?branch=usrs%2Fcsidebotham%2Fcs-avm-module-notes)](https://github.com/Azure/Resource …
> [Modules] Updating Moved-to-avm.md on Migrated Modules

- modules/batch/batch-account/MOVED-TO-AVM.md
- modules/batch/batch-account/README.md
- modules/cognitive-services/account/MOVED-TO-AVM.md
- modules/cognitive-services/account/README.md
- modules/insights/action-group/MOVED-TO-AVM.md
- modules/insights/action-group/README.md
- modules/network/network-interface/MOVED-TO-AVM.md
- modules/network/network-interface/README.md
Added additional `MOVED-TO-AVM.md` files for ported modules
> Added MOVED-TO-AVM files

- modules/network/load-balancer/MOVED-TO-AVM.MD
- modules/network/load-balancer/README.md
Migrated Load Balancing module to AVM - closes issue #4044 
- [ X] Update to documentation
- [X ] I have made corresponding changes to the documentation (readme)
> Moved module to AVM - closes #4044

- modules/web/site/README.md
- modules/web/site/main.bicep
- modules/web/site/main.json
- modules/web/site/slot/README.md
- modules/web/site/slot/basic-publishing-credentials-policy/README.md
- modules/web/site/slot/basic-publishing-credentials-policy/main.bicep
- modules/web/site/slot/basic-publishing-credentials-policy/main.json
- modules/web/site/slot/basic-publishing-credentials-policy/version.json
- modules/web/site/slot/main.bicep
- modules/web/site/slot/main.json
- modules/web/site/tests/e2e/webAppCommon/main.test.bicep
New module for `Microsoft.Web/sites/slots/basicPublishingCredentialsPolicies`
[![Web - Sites](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.web.sites.yml/badge.svg?branch=feature%2Fweb-uplift)](https://github.com/TY-Consulting/ResourceModules/actions/workflows/ms.web.sites.yml)
> [Modules] New Child Module for Microsoft.Web/sites/slots/basicPublishingCredentialsPolicies

- modules/operations-management/solution/MOVED-TO-AVM.md
- modules/operations-management/solution/README.md
Added `MOVED-TO-AVM.md` files for `operations-management/solution` module as it has been merged into AVM, see https://github.com/Azure/bicep-registry-modules/pull/610
This PR resolves #4059.
> Added MOVED-TO-AVM.md  for `operations-management/solution` module

- modules/search/search-service/shared-private-link-resource/version.json
- modules/search/search-service/version.json
Fixes an outdated version.json file schema in the Search Services module.
| Pipeline |
| - |
| [![Search - SearchServices](https://github.com/Azure/ResourceModules/actions/workflows/ms.search.searchservices.yml/badge.svg?branch=users%2Fkrbar%2FversionSchemaFix)](https://github.com/Azure/ResourceModules/actions/workflows/ms.search.searchservices.yml) |
> [Modules] Search Service - fixed outdated version file schema

- modules/analysis-services/server/main.bicep
- modules/analysis-services/server/main.json
Updated missing module for role assignments
| Pipeline |
| - |
| |
> [Fixed] Updated missing module for role assignments

- modules/network/express-route-gateway/MOVED-TO-AVM.MD
- modules/network/express-route-gateway/README.md
Migrated module to AVM resolves #4265
> [Modules] Added Moved-to-Avm file to ExpressRouteGW

- modules/network/express-route-circuit/MOVED-TO-AVM.MD
- modules/network/express-route-circuit/README.md
Migrated module to AVM. Resolves #4264
> [Modules] Added Moved-to-Avm file to ExpressRoute Circuit

- modules/network/express-route-circuit/README.md
- modules/network/express-route-gateway/README.md
Fixes on 2 Network modules with outdated readmes
> [Fixes] Fixes on 2 Network modules with outdated readmes

- modules/event-grid/domain/MOVED-TO-AVM.md
- modules/event-grid/domain/README.md
- modules/event-grid/system-topic/MOVED-TO-AVM.md
- modules/event-grid/system-topic/README.md
- modules/event-grid/topic/MOVED-TO-AVM.md
- modules/event-grid/topic/README.md
Added MovedToAVM to modules missing it
> [Fixes] Added MovedToAVM to modules missing it

- modules/network/network-security-group/MOVED-TO-AVM.md
- modules/network/network-security-group/README.md
- modules/network/network-security-group/security-rule/main.json
Added Moved to AVM note for the NSG Module
-->
| Pipeline |
| - |
| |
> [Modules] NSG - Added Moved to AVM Note

- modules/web/serverfarm/MOVED-TO-AVM.md
- modules/web/serverfarm/README.md
> [Modules] Added MOVED-TO-AVM.md to Web-Serverfarm module

- modules/resources/resource-group/MOVED-TO-AVM.md
- modules/resources/resource-group/README.md
Added AVM disclaimer
Closes #4430
> [Modules] Added AVM disclaimer

- modules/insights/private-link-scope/README.md
- modules/insights/private-link-scope/main.bicep
- modules/insights/private-link-scope/main.json
- modules/insights/private-link-scope/scoped-resource/main.json
- modules/insights/private-link-scope/tests/e2e/defaults/main.test.bicep
- modules/insights/private-link-scope/tests/e2e/max/main.test.bicep
- modules/insights/private-link-scope/tests/e2e/waf-aligned/main.test.bicep
Requested upgrade for AMPLS in issue #4035.
Upgraded the API version of the AMPLS resource and added the required properties. Also, added two UDTs to make parameters input for the user easier. This is a breaking change because it introduced new properties that are required in the newer version.
> [Modules] Updates to the Azure Monitor Private Link Service (AMPLS) Module

- modules/network/application-security-group/MOVED-TO-AVM.md
- modules/network/application-security-group/README.md
- modules/network/connection/MOVED-TO-AVM.md
- modules/network/connection/README.md
- modules/network/ddos-protection-plan/MOVED-TO-AVM.md
- modules/network/ddos-protection-plan/README.md
- modules/network/express-route-circuit/MOVED-TO-AVM copy.md
- modules/network/express-route-gateway/MOVED-TO-AVM copy.md
- modules/network/load-balancer/MOVED-TO-AVM copy.md
- modules/network/nat-gateway/MOVED-TO-AVM.md
- modules/network/nat-gateway/README.md
- modules/network/route-table/MOVED-TO-AVM.md
- modules/network/route-table/README.md
- modules/network/virtual-network/MOVED-TO-AVM.md
- modules/network/virtual-network/README.md
- modules/network/vpn-gateway/MOVED-TO-AVM.md
- modules/network/vpn-gateway/README.md
- modules/network/vpn-site/MOVED-TO-AVM.md
- modules/network/vpn-site/README.md
- modules/resource-graph/query/MOVED-TO-AVM.md
- modules/resource-graph/query/README.md
- modules/resources/deployment-script/MOVED-TO-AVM.md
- modules/resources/deployment-script/README.md
- modules/web/static-site/MOVED-TO-AVM.md
- modules/web/static-site/README.md
- Added missing `Moved-to-AVM.md`
> [Modules] Added missing `Moved-to-AVM.md`

- modules/web/site/MOVED-TO-AVM.md
- modules/web/site/README.md
Added `MOVED-TO-AVM.md` files for:
- `web/site`
- PR: https://github.com/Azure/bicep-registry-modules/pull/779
- resolves #4438
> Added MOVED-TO-AVM

- modules/container-registry/registry/MOVED-TO-AVM.md
- modules/container-registry/registry/README.md
- `container-registry/registry`
- PR: https://github.com/Azure/bicep-registry-modules/pull/816
- resolves #4456
> Added MOVED-TO-AVM.md for `container-registry/registry`

- modules/analysis-services/server/MOVED-TO-AVM.md
- modules/analysis-services/server/README.md
- modules/cache/redis/MOVED-TO-AVM.md
- modules/cache/redis/README.md
- modules/compute/disk/MOVED-TO-AVM.md
- modules/compute/disk/README.md
- modules/compute/image/MOVED-TO-AVM.md
- modules/compute/image/README.md
- modules/consumption/budget/MOVED-TO-AVM.md
- modules/consumption/budget/README.md
- modules/data-protection/backup-vault/MOVED-TO-AVM.md
- modules/data-protection/backup-vault/README.md
- modules/databricks/access-connector/MOVED-TO-AVM.md
- modules/databricks/access-connector/README.md
- modules/databricks/workspace/MOVED-TO-AVM.md
- modules/databricks/workspace/README.md
- modules/db-for-my-sql/flexible-server/MOVED-TO-AVM.md
- modules/db-for-my-sql/flexible-server/README.md
- modules/health-bot/health-bot/MOVED-TO-AVM.md
- modules/health-bot/health-bot/README.md
- modules/net-app/net-app-account/MOVED-TO-AVM.md
- modules/net-app/net-app-account/README.md
- `module`
- PR: https://github.com/Azure/bicep-registry-modules/pull/790
- resolves #4398 
- `module`
- PR: https://github.com/Azure/bicep-registry-modules/pull/791
- resolves #4464  
- `module`
- PR: https://github.com/Azure/bicep-registry-modules/pull/792
- resolves #4402 
- `module`
- PR: https://github.com/Azure/bicep-registry-modules/pull/793
- resolves #4399
- `module`
- PR: https://github.com/Azure/bicep-registry-modules/pull/794
- resolves #4406  
- `module`
- PR: https://github.com/Azure/bicep-registry-modules/pull/795
- resolves #4400  
- `module`
- PR: https://github.com/Azure/bicep-registry-modules/pull/796
- resolves #4407 
- `module`
- PR: https://github.com/Azure/bicep-registry-modules/pull/797
- resolves #4405 
- …
> Moved to AVM

- modules/network/local-network-gateway/MOVED-TO-AVM.md
- modules/network/local-network-gateway/README.md
- modules/network/virtual-network-gateway/MOVED-TO-AVM.md
- modules/network/virtual-network-gateway/README.md
added the Moved-to-AVM.md files to the Local-Network-GW & Virtual-Network-GW modules
Readme.md updated as well
> [Modules] moved to AVM: local-network-gateway and virtual-network-gateway

- modules/desktop-virtualization/application-group/application/main.json
- modules/desktop-virtualization/application-group/main.json
- modules/desktop-virtualization/host-pool/main.json
- modules/desktop-virtualization/scaling-plan/MOVED-TO-AVM.md
- modules/desktop-virtualization/scaling-plan/README.md
- modules/desktop-virtualization/scaling-plan/main.json
- modules/desktop-virtualization/workspace/main.json
Moved to AVM. Updated readme.
Issue: https://github.com/Azure/ResourceModules/issues/4474
https://github.com/Azure/bicep-registry-modules/pull/830
> Scaling Plan MOVED-TO-AVM.md

- modules/desktop-virtualization/application-group/MOVED-TO-AVM.md
- modules/desktop-virtualization/application-group/README.md
- modules/desktop-virtualization/application-group/application/main.json
- modules/desktop-virtualization/application-group/main.json
- modules/desktop-virtualization/host-pool/main.json
- modules/desktop-virtualization/scaling-plan/main.json
- modules/desktop-virtualization/workspace/main.json
Moved to AVM. Updated Readme. 
Issue: https://github.com/Azure/ResourceModules/issues/4476
https://github.com/Azure/bicep-registry-modules/pull/832
> Application group MOVED-TO-AVM.md

- modules/desktop-virtualization/application-group/application/main.json
- modules/desktop-virtualization/application-group/main.json
- modules/desktop-virtualization/host-pool/main.json
- modules/desktop-virtualization/scaling-plan/main.json
- modules/desktop-virtualization/workspace/MOVED-TO-AVM.md
- modules/desktop-virtualization/workspace/README.md
- modules/desktop-virtualization/workspace/main.json
Moved to AVM. Updated readme.
Issue: https://github.com/Azure/ResourceModules/issues/4476
https://github.com/Azure/bicep-registry-modules/pull/836
> Workspace MOVED-TO-AVM.md

- modules/desktop-virtualization/application-group/application/main.json
- modules/desktop-virtualization/application-group/main.json
- modules/desktop-virtualization/host-pool/MOVED-TO-AVM.md
- modules/desktop-virtualization/host-pool/README.md
- modules/desktop-virtualization/host-pool/main.json
- modules/desktop-virtualization/scaling-plan/MOVED-TO-AVM.md
- modules/desktop-virtualization/scaling-plan/README.md
- modules/desktop-virtualization/scaling-plan/main.json
- modules/desktop-virtualization/workspace/main.json
Moved to AVM. Updated readme.
Issue: https://github.com/Azure/ResourceModules/issues/4475
https://github.com/Azure/bicep-registry-modules/pull/831
> Host pool update readme

- modules/network/virtual-hub/MOVED-TO-AVM.md
- modules/network/virtual-hub/README.md
- modules/network/virtual-wan/MOVED-TO-AVM.md
- modules/network/virtual-wan/README.md
Contributes to https://github.com/Azure/ResourceModules/issues/4020
Migrated virtual-hub and virtual-wan from CARML to AVM
- [ X] I'm sure there are no other open Pull Requests for the same update/change
- [X ] I have made corresponding changes to the documentation (readme)
> Moved from CARML to AVM

- modules/machine-learning-services/workspace/MOVED-TO-AVM.md
- modules/machine-learning-services/workspace/README.md
- `management/management-group`
- PR: https://github.com/Azure/bicep-registry-modules/pull/1055
- resolves #4458
> Added MOVED-TO-AVM.md for the Machine Learning Workspace

- modules/purview/account/MOVED-TO-AVM.md
- modules/purview/account/README.md
- `management/management-group`
- PR: https://github.com/Azure/bicep-registry-modules/pull/1053
- resolves #4460
> Added MOVED-TO-AVM.md for the purview account

- utilities/tools/Get-RoleAssignmentList.ps1
Refactor role assignment filtering in Get-RoleAssignmentList.ps1
OpenAI:
```
PS /Azure/ResourceModules/utilities/tools> Get-RoleAssignmentList -ProviderNamespace 'Microsoft.CognitiveServices' -ResourceType 'account' | select -ExpandProperty bicepFormat 
'Azure AI Developer': subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '64702f94-c441-49e6-a78b-ef80e0188fee')
'Azure AI Enterprise Network Connection Approver': subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b556d68e-0be0-4f35-a333-ad7ee1ce17ea')
'Cognitive Services Contributor': subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '25fbc0a9-bd7c-42a3-aa1a-3b75d497ee68')
'Cognitive Services Custom Vision Contributor': subscriptionResourceId('Microsoft.Authorization/roleDefinitions', …
```
> Refactor role assignment filtering in Get-RoleAssignmentList.ps1
